### ISSUE TITLE
The Sentry logo on the readme file is broken.

### ISSUE THREAD

**Issue by Alexgmin** [getsentry/sentry-laravel#101]
![image](https://user-images.githubusercontent.com/8340441/29364228-149afd7c-8293-11e7-82df-efacc469eed6.png)
Image link: https://sentry.io/_static/getsentry/images/branding/png/sentry-horizontal-black.png

**Comment by stayallive** [comment]
You are 100% correct, currently working on updating the docs that will also fix this, thanks creating an issue for it 👍
