### ISSUE TITLE
Why does Sentry not show issue details, but only it's name under Overview?

### ISSUE THREAD

**Issue by thomasmoors** [getsentry/sentry-laravel#106]
'm not sure if this is a server config question, but I will try it here because of the sentry tag.

I have set up Sentry myself using the Docker install guide. Everything seems to work fine except for issues that say:

Sorry, the events for this issue could not be found.

This could be due to a handful of reasons:

The events are still processing and are on their way The events have been deleted There is an internal systems error or active issue Retry
Screenshot of Missing info
https://i.stack.imgur.com/Vk21B.png

I have no clue why the debug information is missing, but I really would like to know how to fix it. Googling does not help me any further.

https://stackoverflow.com/questions/46605183/why-does-sentry-not-show-issue-details-but-only-its-name-under-overview

**Comment by stayallive** [comment]
Hey @thomasmoors!

I cannot help much since this has nothing to do with the Laravel integration but I would look if the Sentry worker is running on your server, it looks like it has not processed the event yet. If you are still encounter issues when everything seems to be running try the Sentry forums.

**Comment by thomasmoors** [comment]
@stayallive I'm sorry, I however am already helped a lot by knowing that I can probably find the reason with the Worker not running as it should. Thanks!

**Comment by stayallive** [comment]
@thomasmoors no problem, hope you get it working!
