### ISSUE TITLE
Question: Google Cloud Platform hosting - exec()

### ISSUE THREAD

**Issue by coreation** [getsentry/sentry-laravel#108]
Hi there,

when releasing sentry on GCP I caught an error in the PHP error log file stating that exec is not supported by the platform by default and it seems that there's no way of working around it. 

Is there a way to use the sentry package and still get a code version added to the sentry log based on the sha1 of a the version of the code?

**Comment by stayallive** [comment]
I think your best bet is to somehow add the SHA1 hash of the commit in an environment variable. And read it from there, I don't know how deployments work so I am not sure if I can help you with a specific code example. But something like this in `config/sentry.php` should work:

```php
<?php
return array(
    'dsn' => env('SENTRY_DSN'),

    // capture release as git sha
    'release' => env('SENTRY_SHA'),

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => true,

    // Capture default user context
    'user_context' => true,
);
```

Let me know.

**Comment by coreation** [comment]
hey @stayallive , that seems like a way forward, I've set the release now to env('app.version'), but I think if we add a post-script everything something gets pushed to master which refreshes the SHA1 in the environment file, that would work. It indeed depends on how we deploy, but I think that workflow works in multiple approaches, including ours. Thanks!

**Comment by stayallive** [comment]
That would certainly work. Unfortunatly there is no 1-way for every case :)
