### ISSUE TITLE
Config name conflict with /rydurham/Sentinel

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry-laravel#112]
"I am having issues with installation to Laravel 5.2. I am currently using github.com/rydurham/Sentinel/ for authentication which has the same config name as your package and also I believe you use the same facade name, but I have not got that far to find out if the below issue was fixed? getsentry/sentry-laravel#24" -@warmwhisky

@stayallive could you take a look?

**Comment by stayallive** [comment]
@warmwhiskey I noticed we fixed it but never documented it. I created a PR to explain how to get around this and hop this helps. If you have any questions or things are not clear let me know!

See: https://github.com/getsentry/sentry-laravel/blob/3688402ec28eab5e7333d1bdcb8c3cdbca1ad922/README.md#resolve-name-conflicts-with-packages-also-called-sentry

**Comment by stayallive** [comment]
@warmwhisky I noticed we fixed it but never documented it. I created a PR to explain how to get around this and hop this helps. If you have any questions or things are not clear let me know!

See: https://github.com/getsentry/sentry-laravel/blob/3688402ec28eab5e7333d1bdcb8c3cdbca1ad922/README.md#resolve-name-conflicts-with-packages-also-called-sentry

**Comment by warmwhisky** [comment]
Hey thanks for the help so far!

I have an issue now when I publish the new config file using this
`php artisan config:publish sentry/sentry-laravel`

It says 
`Command "config:publish" is not defined. `

**Comment by stayallive** [comment]
Ah my bad, this should be `vendor:publish` 😄

**Comment by warmwhisky** [comment]
Oh man I did try that too but got the following error :/
```
[37;41m  [Symfony\Component\Console\Exception\RuntimeException]  [39;49m
[37;41m  Too many arguments, expected arguments "command".       [39;49m
```

**Comment by stayallive** [comment]
Sorry about that, not around a computer to check the commands first... while I get to working on improving that part...

That command should basicly copy this: https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/SentryLaravel/config.php file over to your config folder with the name `sentry-laravel.php` assuming you followed the instructions linked above.

So if you create the `config/sentry-laravel.php` file yourself and copy pasta the contents of https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/SentryLaravel/config.php in you should be good to go and the config/vendor publish command can be skipped :)

**Comment by warmwhisky** [comment]
Ok thanks I will do that. 

Maybe I need to completely uninstall and then go through the entire process again? I am not sure that if trying to install without the conflict steps above and then applying the steps above cause an issue, if that makes sense??

**Comment by stayallive** [comment]
No you should be fine. Reinstalling won't change anything. 

The package does need to be installed before the conflict resolutions steps can be implemented otherwise some classes it uses cannot be found yet since the only thing it does is extend classes found in the package so the name `sentry` can be overriden to `sentry-laravel`.

**Comment by warmwhisky** [comment]
Eish. I got past this, but now I have found another issue with the Sentry package I have installed. I forced an error by misnaming a variable. The error was reported in the laravel.log but the very next stack was Sentry related.

Here is the error
`[2017-11-23 11:53:04] local.ERROR: BadMethodCallException: Method [captureException] is not supported by Sentry or no User has been set on Sentry to access shortcut method. in E:\NetBeansProjects\Ngwenya-Catalogue\vendor\cartalyst\sentry\src\Cartalyst\Sentry\Sentry.php:731`

**Comment by stayallive** [comment]
Yes ofcourse, that was an oversight. I realised we supply this example code.

```php
public function report(Exception $exception)
{
    if (app()->bound('sentry') && $this->shouldReport($exception)) {
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

There and anywhere else you are referencing Sentry (this sentry) like `app('sentry')`, those references needs to be updated to `app('sentry-laravel')`.

So in the example above:

```php
public function report(Exception $exception)
{
    if (app()->bound('sentry-laravel') && $this->shouldReport($exception)) {
        app('sentry-laravel')->captureException($exception);
    }

    parent::report($exception);
}
```

Does that fix this issue?

**Comment by warmwhisky** [comment]
Thank you! I have it working now.

I really appreciate your help with enabling me to use both sentry packages.

**Comment by warmwhisky** [comment]
I just tried this with a Laravel 5.5 installation, but it didn't work. Is that because of 5.5 auto discovery?

I added the required to config/app.php but I'm not sure that works with auto discovery?

My error is...
`Call to undefined method Raven_Client::check() (View: /home/username/public_html/app/resources/views/includes/header.blade.php)`

**Comment by warmwhisky** [comment]
Ahhh. Sorry I missed that from doing my 5.2 version yesterday!

Thanks again!

**Comment by stayallive** [comment]
No problem, thanks for letting me know the documentation was (mostly) correct!

If you have other issues, feel free to open a new issue for them :)
