### ISSUE TITLE
Incorrect User Context ID Sporadically

### ISSUE THREAD

**Issue by jconroy** [getsentry/sentry-laravel#115]
Hi All,

Just a follow up to https://github.com/getsentry/sentry-laravel/pull/81#issuecomment-349934854

I'm seeing a weird issue where the user context set on a few of our issues/events in sentry.io are incorrect.

I've had a really good dig into our code and I've also contacted Sentry via email to see if it could be anything on their end. The response I got was 

> Looking at the payload - those IDs are definitely getting sent so this seems like it's either related to the PHP SDK or something with how you are setting the user context.....doing a quick search I didn't see any open issues that would explain this behavior but if you wanted to open one on GitHub...

So I am a bit confused about whether the issue is on our end or not. 

**Background / Context**

For the most part everything is working - that is - the user id / context is correct 90% of the time. Every now and again the ID is set to the wrong user which has never had the error.

To demonstrate - our app queues up 9 jobs (using standard Laravel/Lumen behavior) if we have an error present in all 9 jobs an issue/error is logged in Sentry with the user ID. Every now again the user id assigned to the error for the last job is incorrect.  This is an example spreadsheet to try and demonstrate more visually. https://docs.google.com/spreadsheets/d/1jv7ptxqsw5c9KXzw-65Lcw6g8m-FzT0g0ap_U-ENdEg/edit?usp=sharing

We also see it random for other events - but the spreadsheet and queues give a better visual representation to show the ID's work most of the time.

**Package Versions**

* "laravel/lumen-framework": "5.3.*",
* "sentry/sentry-laravel": "^0.7.0"

**Code**

The code we use to ensure a context is set looks like

```
		if ( app()->bound( 'sentry' ) ) {
			$sentry = app( 'sentry' );
			// Add user context
			$sentry->user_context( [
				'id' => $this->store->customer_id,
			] );
		}
```

Which is just based on the docs/examples we have available.

Any help/pointers would be very useful. Thanks

**Comment by stayallive** [comment]
It is really hard to debug this from here but I want to try and give you some places to look if that's okay because I am not convinced yet this is an SDK error, especially since this occurs in the Queue and not in a normal web request which can be possibly be funky with the SDK trying to resolve an user ID itself.

- The code to ensure a user context
        - Is that code being run before or after your app get's a chance to do anything else
        - have you tried echoing this out with the job data and looking at the queue logs to ensure the correct user is in the store, just to be 100% sure the store has the correct customer id.
 - In your spreadsheet, are other jobs that are not failing also running through there?

And maybe the most important question since this could be a cause, are you manually calling `captureException` or is it submitted through the Laravel error handler as per the docs?

**Comment by jconroy** [comment]
Hi @stayallive 

> hard to debug this from here

Yep totally understand that and really appreciate the response. I'm just reaching the end of what I can think to try. Especially because the support team confirmed that "Looking at the payload - those IDs are definitely getting sent"

> I am not convinced yet this is an SDK error

Yeah I'm not 100% sure it is - but I'm confused because we were told the IDs are definitely getting sent. I'm assuming because we sent through the IDs we were expecting that is the correct ID's were sent/received.

---

To answer some of your questions.

> Is that code being run before or after your job get's a chance to do anything else?

We set the context user id as part of our `__construct` method when each Job is created (using the code I posted previously)

> Have you tried echoing this out with the job data and looking at the queue logs to ensure the correct user is in the store, just to be 100% sure the store has the correct customer id?

We haven't echoed it out but some store data is captured in sentry and we can see the store data on the issue/event does not match the user id context displayed. That's how we picked up there was an issue. In a batch of 9 jobs for a specific user the first 8 seem to work fine then the last one job displays an incorrect ID. I'll see if we can add some additional logging to the event handler.

> Are you using Auth::login

Not at this point in time. We perform Auth on the initial request and then to make sure the correct context is being sent we specifically set it using the code posted previously. There isn't anything else which happens with Auth.

> In your spreadsheet, are other jobs that are not failing also running through there?

That spreadsheet only includes failed jobs - roughly batches of 9 for a user.

> are you manually calling captureException or is it submitted through the Laravel error handler as per the docs?

We just use

```
	public function report( Exception $e ) {
		// Send errors/exceptions through to Sentry
		if ( $this->shouldReport( $e ) ) {
			app( 'sentry' )->captureException( $e );
		}
		parent::report( $e );
	}
```

In `App\Exceptions\Handler.php`

**Comment by stayallive** [comment]
Hmm this all sounds perfectly fine and normal... there is one thing I am not sure of and that is using the `__construct` which also can cause issues in your web request error reporting. Could you try to move the (or all) logic that the job itself needs to `handle()` and only use the `__construct()` for setting the data your job needs.

Like: https://laravel.com/docs/5.3/queues#class-structure

If you use `__construct` to set the user ID you are also setting the ID when queuing the job which could explain weird user id's from web requests... however we are dealing with the opposit. But just to rule it out :) 

Also you could update to the sentry-laravel 0.8.0 version just for the heck of it, don't think there would be anything related in there but it's worth a shot.

And just to make sure, what queue driver are you using? Not Iron.io right?

**Comment by jconroy** [comment]
> Could you try to move the (or all) logic that the job itself needs to handle() and only use the __construct() for setting the data your job needs.

> Also you could update to the sentry-laravel 0.8.0 version just for the heck of it

Ok I'll see if its possible / what we can do

> And just to make sure, what queue driver are you using? Not Iron.io right?

We're just using Redis

**Comment by stayallive** [comment]
I have not head back from you and since than have not found other users dealing with the same issue, if you are still seeing it please reopen the issue with more information so we can investigate further.
