### ISSUE TITLE
package owner sentry not redirecting to getsentry anymore

### ISSUE THREAD

**Issue by altf4rocks** [getsentry/sentry-laravel#116]
sentry/sentry-laravel is no longer redirecting to getsentry/sentry-laravel package when trying to install.
You may want to update the readme.

**Comment by dcramer** [comment]
I must have overlooked a PR where we changed behavior here (or this is working as expected). The package name is 'sentry/sentry-laravel', while the repository name is 'getsentry/sentry-laravel'.

**Comment by stayallive** [comment]
You mean using https://github.com/sentry/sentry-laravel to go to this repository? AFAIK this has never worked, it has always been `sentry/sentry-laravel` on packagist and `getsentry/sentry-laravel` here.

- https://packagist.org/packages/sentry/sentry
- https://packagist.org/packages/sentry/sentry-laravel

Are you adding the git repository yourself in the composer.json?

**Comment by altf4rocks** [comment]
Maybe i added it manually in my composer.json, that was like more than a year, but it was working and I am doing composer update around once per week. The repository is in my vendor directory in local and was online too (it was installed through composer install), but when trying to composer update yesterday in my online version it broke my project because it couldnt find sentry/sentry-laravel anymore.

**Comment by altf4rocks** [comment]
Well I have just tried to install it locally from a fresh composer.json and it worked. I will have to try online again and see if it work again, maybe it was just a temporary glitch in the matrix. Ill keep you posted if the glitch persist, thanks !

**Comment by stayallive** [comment]
Thanks, will close this for now (hoping it was just a glitch) otherwise feel free to reopen 👍
