### ISSUE TITLE
everything related to old owner is not working anymore

### ISSUE THREAD

**Issue by altf4rocks** [getsentry/sentry-laravel#117]
For example
sentry/sentry in the composer.json points to a 404

**Comment by dcramer** [comment]
Dupe of #116

**Comment by dcramer** [comment]
To be clear, there is no 'old owner'.

https://packagist.org/packages/sentry/sentry

The packages are 'sentry' on packagist, and the repo owner is 'getsentry'. This hasn't changed AFAIK, and has been this way a long time.
