### ISSUE TITLE
Consider automatically attaching user credentials

### ISSUE THREAD

**Issue by dwightwatson** [getsentry/sentry-laravel#118]
I think it might be worthwhile automatically configuring this for developers using this package. 

The grand majority of developers are going to be using Laravel's built-in authentication functionality so adding support will be beneficial to most people. In addition I don't think most developers are aware of this functionality provided by Sentry so they just gloss over it in the docs.

Laravel can be configured to username or email authentication and it's easy to get this stuff out of it. At the very least I think it should be fine to report the user's primary key and identifier (username/email). If a developer did want to send additional user information *then* they could opt to configure this feature manually.

Would you be open to automatically attaching the active user to error reports with this package?

**Comment by stayallive** [comment]
Hey @dwightwatson,

Thanks for your suggestion, this is actually already a feature. This is where the `user_context` key is for in the configuration. See here the code that add's the user's primary key to a Sentry event:

https://github.com/getsentry/sentry-laravel/blob/a978c2110c4d49660b0de2a18800de4ea4e08acc/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php#L112-L116

**Comment by dwightwatson** [comment]
Ah - gotcha. Looks like I have an older copy of the configuration file before this functionality was added, just re-published and it's good to go. Thanks for getting back to me.
