### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by straube** [getsentry/sentry-laravel#119]
Laravel 5.6 introduces the idea of [logging channels](https://laravel.com/docs/5.6/logging). It would be nice if Sentry implements that new feature.

**Comment by antoniopaisfernandes** [comment]
There's even a problem with ```bindLogger``` implementation for 5.6 with the usage of ```getMonolog``` method that does not exist.

**Comment by freekmurze** [comment]
Is the current version of the package able to send exceptions correctly to sentry (when installed in a L5.6 app)?

**Comment by m1guelpf** [comment]
@freekmurze Yes

**Comment by patrickbrouwers** [comment]
Submitted a PR for a sentry log channel: https://github.com/getsentry/sentry-laravel/pull/122

**Comment by stayallive** [comment]
I'll close this since 5.6 is supported and PR #122 is dealing with adding the log channel 👍
