### ISSUE TITLE
Schedule for the next release 

### ISSUE THREAD

**Issue by fntneves** [getsentry/sentry-laravel#120]
Hi,

Thank you for providing this package to the community.

I am getting an issue related to the commit https://github.com/getsentry/sentry-laravel/commit/bb8efcbb1c0a5c6510e7afb3c8a82a2f0603896a that conflicts with a package I developed, which replaces the event dispatcher (but respects the contract).

Is there any release date for the new version that includes fixes like this?

**Comment by stayallive** [comment]
Hey @fntneves I see we never released an version containing that fix since we need to split out Laravel 4 support first for that to happen (since v4 does not have those contracts, see #107). Let me get on that. I have no fixed date though, soon-ish 😉

**Comment by fntneves** [comment]
Hi @stayallive, thank you for your reply!
I understand, let me know if you need help to make this happen 😉 
Thank you !

**Comment by sebastiaanluca** [comment]
Hey, any ETA on this? :) Master branch contains some useful fixes and a PR for Laravel 5.6 log channels we are currently using (through the fork).

**Comment by stayallive** [comment]
@sebastiaanluca Yes, planning is this week. 

The "wait" is for sentry-php which needs a few looks on some fixes, we're getting there!
