### ISSUE TITLE
Test command failing with custom provider name

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [getsentry/sentry-laravel#124]
When registering in Laravel 4.2 applications there is a common name collision between catalyst/sentry and sentry/laravel.

Quite easy to solve with some custom classes in the application:

`app/lib/MyApp/Support/config/sentry-laravel.php`
```
<?php
return [
    'dsn' => '',
    // capture release as git sha
    'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),
    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => true,
    // Capture default user context
    'user_context' => true,
];
```

`app/lib/MyApp/Support/SentryFacade.php`
```
<?php

namespace MyApp\Support;

use Illuminate\Support\Facades\Facade;

class SentryFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'sentry-laravel';
    }
}
```

`app/lib/MyApp/Support/SentryLaravelServiceProvider.php`
```
<?php

namespace MyApp\Support;

use Sentry\SentryLaravel\SentryLaravel;
use Sentry\SentryLaravel\SentryLaravelEventHandler;
use Illuminate\Support\ServiceProvider;

class SentryLaravelServiceProvider extends ServiceProvider
{
    /**
     * Indicates if loading of the provider is deferred.
     *
     * @var bool
     */
    protected $defer = false;
    
    /**
     * Bootstrap the application events.
     *
     * @return void
     */
    public function boot()
    {
        $app = $this->app;
        // Laravel 4.x compatibility
        if (version_compare($app::VERSION, '5.0') < 0) {
            $this->package('sentry/sentry-laravel', 'sentry-laravel', __DIR__);
            
            $app->error(function (\Exception $e) use ($app) {
                $app['sentry-laravel']->captureException($e);
            });
            
            $app->fatal(function ($e) use ($app) {
                $app['sentry-laravel']->captureException($e);
            });
            
            $this->bindEvents($app);
        } else {
            // the default configuration file
            $this->publishes(array(
                __DIR__ . '/config.php' => config_path('sentry-laravel.php'),
            ), 'config');
            $this->bindEvents($app);
        }
        
        if ($this->app->runningInConsole()) {
            $this->registerArtisanCommands();
        }
    }
    
    /**
     * Register the artisan commands.
     */
    protected function registerArtisanCommands()
    {
        $this->commands(array(
            'Sentry\SentryLaravel\SentryTestCommand',
        ));
    }
    
    /**
     * Bind to the Laravel event dispatcher to log events.
     *
     * @param $app
     */
    protected function bindEvents($app)
    {
        $config = $app['config']->get('sentry-laravel::sentry-laravel');

        $handler = new SentryLaravelEventHandler($app['sentry-laravel'], $config);

        $handler->subscribe($app->events);

        // In Laravel >=5.3 we can get the user context from the auth events
        if (version_compare($app::VERSION, '5.3') >= 0) {
            if (isset($config['user_context']) && $config['user_context'] !== false) {
                $handler->subscribeAuthEvents($app->events);
            }
        }
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('sentry-laravel', function ($app) {
            
            // sentry::config is Laravel 4.x
            $config = $app['config']->get('sentry-laravel::sentry-laravel');
            // Make sure we don't crash when we did not publish the config file
            if (is_null($config)) {
                $config = [];
            }
            $client = SentryLaravel::getClient(array_merge(array(
                'environment' => $app->environment(),
                'prefixes' => array(base_path()),
                'app_path' => app_path(),
                'excluded_app_paths' => array(base_path() . '/vendor'),
            ), $config));
            // bind user context if available
            try {
                if ($app['auth']->check()) {
                    $user = $app['auth']->user();
                    $client->user_context(array(
                        'id' => $user->getAuthIdentifier(),
                    ));
                }
            } catch (\Exception $e) {
                error_log(sprintf('sentry.breadcrumbs error=%s', $e->getMessage()));
            }
            return $client;
        });
    }
    
    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return array('sentry-laravel');
    }
}
```

This is easier to solve in Laravel 5 as all the instances of the package have been changed to use a static property on the service provider `public static $abstract = 'sentry';` which you can change in the `app.php` providers array with a key, e.g `'sentry-laravel' => '\Path\To\Sentry\Provider'`.

However i've spotted when running the `php artisan sentry::test` command there is an instance of the package string still being used:

![image](https://user-images.githubusercontent.com/1327332/36149311-2b3f1948-10b7-11e8-89a5-37c489c58177.png)

`$client = app('sentry');` from `SentryTestCommand` may need to look at the service provider to see what name it has been configured with, otherwise the incorrect provider's instance can be returned from the app container as above `$client == Cartalyst\Sentry\Sentry`

**Comment by Caffe1neAdd1ct** [comment]
I can submit a pull request for this one, however would like some advice on the best way to check the configured alias for the service provider. I'm doubtful this would work:
```
$client = app(\Sentry\SentryLaravel\SentryLaravelServiceProvider::$abstract); 
```

**Comment by stayallive** [comment]
Hmm yes you have a valid point here that I think is hard to solve... since we would know the name of your own service provider to resolve it correctly which we cannot know before we know the prefix... quite the problem.

I am not sure if we can solve this without also allowing you to register the test command and set the custom prefix there too like we do with the service provider.

I would say that (unfortunatly) the easiest way is to copy the test command to your own application and change the prefix there in what you made it to be.

If someone finds a better solutions I am all ears ofcourse!

**Comment by Caffe1neAdd1ct** [comment]
Exactly what I have already done :+1: 

Would it be possible to accept an optional constructor argument for setting this via an extending class calling parent? May not be possible or appropriate as already extending `Command` 

Alternatively read a protected property with the package name inside which can be changed on the extending child class?

Would save copying the entire handle() function across to the child class which would potentially become outdated.

**Comment by stayallive** [comment]
It seems I dropped the ball on this issue, sorry about that 😟 

I hope you have found a workable workaround for this issue!

Since we are no longer supporting Laravel 4 (and Cartalyst Sentry only works for Laravel 4) I am going to close this issue.
