### ISSUE TITLE
No config file is created with command

### ISSUE THREAD

**Issue by joveice** [getsentry/sentry-laravel#126]
Hello, when I do this command
```
php artisan vendor:publish --provider="Sentry\SentryLaravel\SentryLaravelServiceProvider"
```
No config file is created and I get this message of publish complete. vendor:publish does not display anything related to sentry.

I'm using L56 and Sentry 1.8.3

**Comment by joveice** [comment]
Ah, the guide on the webpage says you should do this:
```
composer require "sentry/sentry"
```

but this ones says 
```
composer require sentry/sentry-laravel
```
this one worked. So update your guide on the page?

**Comment by stayallive** [comment]
Hey @joveice on which webpage are you seeing the guide?

**Comment by joveice** [comment]
https://sentry.io/<team>/<project>/getting-started/php-laravel/

**Comment by stayallive** [comment]
Thanks! I am going to dig in why a little bit of the generic php guide is prepended to this, however the Laravel 5.x instructions are right below it with the correct composer commands.

**Comment by stayallive** [comment]
A PR is submitted (getsentry/sentry-php#570) to fix this, will soon be resolved.

**Comment by luizguilhermefr** [comment]
Happening on 1.0.0-beta2 with Laravel 5.4.36

**Comment by stayallive** [comment]
@luizguilhermefr Laravel 5.4 does not auto configure your serviceproviders. Make sure you added the service provider to your `config/app.php` as per the docs: https://docs.sentry.io/platforms/php/laravel/. If that doesn't work please open a new issue.

**Comment by luizguilhermefr** [comment]
Yes, shame on me. I was on automatic mode thinking on 5.5+.
