### ISSUE TITLE
Missing server, project and keys

### ISSUE THREAD

**Issue by njxqlus** [getsentry/sentry-laravel#127]
Hello! 
Problem: Sentry doesn't work without any errors
Environment: Laravel 5.6.15, Sentry ^0.8.0, Docker
Steps: install sentry, add SENTRY_DSN to .env and add to error handler
```php
public function report(Exception $exception)
{
    if (app()->bound('sentry') && $this->shouldReport($exception)) {
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

Nothing happens, errors don't occur in dashboard.
I tried to `php artisan senty:test` and receive next:
```
[sentry] ERROR: Missing configuration for server
[sentry] ERROR: Missing configuration for public_key
[sentry] ERROR: Missing configuration for secret_key
[sentry] Client configuration:
-> server:
-> project: 1
-> public_key:
-> secret_key:
```

**Comment by stayallive** [comment]
Did you publish the configuration with the following command?

```php
php artisan vendor:publish --provider="Sentry\SentryLaravel\SentryLaravelServiceProvider"
```

There should be a `sentry.php` file in your config folder.

If there is, can the issue be config caching?

Try to run the following before the test command.

```bash
php artisan config:clear
```

**Comment by njxqlus** [comment]
@stayallive oh, sorry, it's real config cache issue, now `sentry:test` working. But error handler (report methpd)  still doesn't do anything

**Comment by stayallive** [comment]
If the test works the handler should also work unless the exception is marked as "do not report" (`$this->shouldReport($exception)`), is it an exception that is not caught and/or marked as "do not report"?

Laravel also excludes a few itself:

https://github.com/laravel/framework/blob/d36ae2327475f5bb352f1ef62f993a7f28627880/src/Illuminate/Foundation/Exceptions/Handler.php#L56-L64

**Comment by njxqlus** [comment]
@stayallive no, I have `Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException`.
`$doNotReport` is empty

**Comment by stayallive** [comment]
As you can see Laravel excludes that one by default (or well, it excludes any `HttpException` which `NotFoundHttpException` is based on: https://github.com/laravel/framework/blob/d36ae2327475f5bb352f1ef62f993a7f28627880/src/Illuminate/Foundation/Exceptions/Handler.php#L59

So it is excluded from being reported, you can override `$internalDontReport` in your handler if you do not want that or remove the ` && $this->shouldReport($exception)` to simply log _all_ exceptions (but this can be quite noisy). https://github.com/laravel/framework/blob/d36ae2327475f5bb352f1ef62f993a7f28627880/src/Illuminate/Foundation/Exceptions/Handler.php#L56

**Comment by njxqlus** [comment]
@stayallive thx for the answer.
Overwriting `$internalDontReport` don't help, but removing `&& $this->shouldReport($exception)` works like a charm, THX!

**Comment by andreshg112** [comment]
Same here, even config:clear doesn't work. I already have set the SENTRY_LARAVEL_DSN.

**Comment by stayallive** [comment]
The error about missing the private key is correct, since I just noticed the CLI tester was not updated since the public keys are deprecated.

@andreshg112 have you tested if regular events are coming through?

(meanwhile I'm updating the tester command to not require the private key)

**Comment by andreshg112** [comment]
No errors now. Thank you, @stayallive!
![image](https://user-images.githubusercontent.com/15859884/42885401-6f143abc-8a66-11e8-895e-dfb04cad8e01.png)
