### ISSUE TITLE
Uploaded files missing from body / POST json

### ISSUE THREAD

**Issue by garygreen** [getsentry/sentry-laravel#131]
When you upload a file and an error is reported to Sentry, it doesn't include information about the uploaded file.

![image](https://user-images.githubusercontent.com/1702638/39398051-14c36f88-4b00-11e8-95f6-4137b9e84be2.png)

Would it be an idea to attach some 'meta' data about the file that was uploaded, at least?

Something like:

```json
"pdf": {
    "type": "file",
    "valid": true,
    "size": 1024
}
```

**Comment by Braunson** [comment]
@stayallive This may be something better suited to add via middleware that add's scope to the report. If files are set in the request, apply details to the request about them.

**Comment by stayallive** [comment]
Bit late to mention this, but this has been solved in the PHP SDK and looks something like this:

![image](https://user-images.githubusercontent.com/1090754/117259613-83644200-ae4e-11eb-9fba-5d5223d00368.png)

So it should happen now, but it is dependant on how large the request body was if it tries to do this (https://github.com/getsentry/sentry-php/blob/1b4acb089c63246d1a6f074e4b5ebcfe80be2057/src/Integration/RequestIntegration.php#L198-L205).

So you might need to tweak this configuration option: https://docs.sentry.io/platforms/php/configuration/options/#max-request-body-size
