### ISSUE TITLE
Setting the user IP (with trusted proxies)

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-laravel#133]
As reported in getsentry/sentry-php#585, when using trusted proxies (since Laravel 5.5) the Sentry SDK possibly doesn't get the right user IP address (not tested in Laravel but is the case in Symfony). We should retrieve this info from the framework.

**Comment by georgeboot** [comment]
As a workaround, I created a `SentryServiceProvider.php` in which I added the following code:

```php
use Sentry\Laravel\Facade as Sentry;
use Sentry\State\Scope;

Sentry::configureScope(function (Scope $scope) use ($userScope): void {
    $scope->setUser([
        'id' => auth()->id(),
        'email' => auth()->user()->email ?? null
        'ip_address' => request()->ip(),
    ]);
});

**Comment by tillkruss** [comment]
Or just put it in your `AuthServiceProvider`.

**Comment by tillkruss** [comment]
A slightly more elegant solution:

```php
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        \Illuminate\Auth\Events\Authenticated::class => [
            \App\Listeners\Auth\Authenticated::class,
        ],
    ];
}
```

```php
<?php

namespace App\Listeners\Auth;

use Sentry\State\Scope;
use Sentry\Laravel\Facade as Sentry;

use Illuminate\Http\Request;

class Authenticated
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function handle($event)
    {
        $user = $this->request->user();

        Sentry::configureScope(function (Scope $scope) use ($user) {
            $scope->setUser([
                'id' => $user->getAuthIdentifier(),  // TODO: Already set by Sentry
                'email' => $user->email,
                'username' => $user->name,
            ]);
        });
    }
}
```

**Comment by shiny** [comment]
When the latest Laravel Framework running on php-fpm which in a docker container, the ip address info is noneffective like 172.23.0.8.

**Comment by shiny** [comment]
My solution:

app/Exceptions/Handler.php
```php
    /**
     * Report or log an exception.
     *
     * @param  \Exception  $exception
     * @return void
     */
    public function report(Exception $exception)
    {
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            \Sentry\configureScope(function (\Sentry\State\Scope $scope) {
                $scope->setUser([
                    'ip_address' => request()->ip()
                ]);
            });
            app('sentry')
                ->captureException($exception);
        }
    
        parent::report($exception);
    }
```

**Comment by adam1010** [comment]
Is this on the roadmap?  I use the `configureScope` technique and it works most of the time, but many requests still show my load balancer's IP address on Sentry. (So the user context has not been set before Sentry triggers the event)

In the base `sentry-php` repo they're defaulting to the `REMOTE_ADDR` if the user context hasn't been set:  
https://github.com/getsentry/sentry-php/blob/master/src/Integration/RequestIntegration.php#L103

Since the `sentry-php` repo is responsible for passing in that `request` object, we could easily overwrite `REMOTE_ADDR` using `Request::ip()` so that it's correct when the user context isn't set.

**Comment by markkimsal** [comment]
There doesn't seem to be any internal laravel events earlier than authorized user.

The solutions presented here all use the ServiceProvider feature of Laravel.  Why not just do it in `LaravelSentryServiceProvider::configure()` where the user ID is set?

It seems like Sentry considers the IP to be a property of the user and not of the event/log.  But, I can't envision a log or crash where I would not want to see the IP reported.  So I would suggest uncoupling the IP from any sort of user events.

```php
            $client = SentryLaravel::getClient(array_merge(array(  // ....
            // ...
            /// ));
            if ($app->bound('request')) {
                 /** @var \Illuminate\Http\Request $request */
                 $request = $app->make('request');
                 $client->user_context([
                       'ip_address' => $request->ip(),
                 ]);
            }
```

**Comment by adam1010** [comment]
When is `$app->bound('sentry')` equal to `false`? The example code would cause the IP for the user to not be set when `false` which would then cause line 101 (https://github.com/getsentry/sentry-php/blob/master/src/Integration/RequestIntegration.php#L101)  to default it to `REMOTE_ADDR`

Is there a guaranteed way to make sure that sentry is bound so that we don't just skip initializing the user? If not, it seems the solution is to pass in the Event with `REMOTE_ADDR` set to `Request::ip()`  on line 76 in that same file.

**Comment by adam1010** [comment]
Has there been any movement here? I'm getting wildly inaccurate "unique user" metrics from Sentry because the load balancer has a fixed IP address so most traffic shows as having that same IP

**Comment by adam1010** [comment]
This seems to fix the issue:   In my `AppServiceProvider.php`

```php
  public function register(){
    if(app()->bound('sentry')){
      app('sentry')->getClient()->getOptions()
        ->setBeforeSendCallback(function(Event $e){
          $e->setRequest(array_merge($e->getRequest(), ['url' => request()->fullUrl()]));
          $e->getUserContext()->setIpAddress(request->ip());
          return $e;
        });
    }
```

**Comment by stayallive** [comment]
So did anyone try the changes I proposed in #419 already to see if that solves the issue? 😄

**Comment by stayallive** [comment]
I think we can finally close this, sorry it took so long.

But we have release [2.4.0](https://github.com/getsentry/sentry-laravel/releases/tag/2.4.0) with the required changes to read the IP from the Laravel request on which trusted proxies work.

Please open up a new issue if with 2.4.0 this problem still persists.
