### ISSUE TITLE
SentryLaravelEventHandler does not use \Illuminate\Contracts\Events\Dispatcher

### ISSUE THREAD

**Issue by srottem** [getsentry/sentry-laravel#134]
I want to work with the sentry/sentry-laravel package and the fntneves/laravel-transactional-events, however the latter provides a different event dispatcher implementation than the default laravel \Illuminate\Events\Dispatcher so the two packages are incompatible.

If the SentryLaravelEventHandler::subscribe and SentryLaravelEventHandler::subscribeAuthEvents methods accepted the \Illuminate\Contracts\Events\Dispatcher contract instead of the \Illuminate\Events\Dispatcher implementation I believe these packages would be compatible.

Is there any chance this could be changed?

**Comment by stayallive** [comment]
Hey @srottem are you already on 0.9.0? 

This version included a change to depend on the contract instead of the implementation for this exact reason (see #107).

**Comment by srottem** [comment]
Doh.  I was on 0.8.0 - apologies.

**Comment by stayallive** [comment]
No problem ofcourse, it was only released a few days ago 😎 glad that fixes it for you 👌
