### ISSUE TITLE
Documentation page references incorrect env property SENTRY_DSN

### ISSUE THREAD

**Issue by opetgether** [getsentry/sentry-laravel#135]
The documentation page https://docs.sentry.io/clients/php/integrations/laravel/ instructs you to use the .env value SENTRY_DSN but the 0.9 config file expects SENTRY_LARAVEL_DSN.

Having SENTRY_DSN set in .env on my local environment still worked correctly but when running on a staging environment, issues weren't visible in my dashboard, but an error ID was generated.

**Comment by stayallive** [comment]
Setting `SENTRY_DSN` should still work since the PHP package should read that out correctly from the env variables (unless you use config caching), but yes that should be updated, will close this issue when it's done.

**Comment by opetgether** [comment]
Ah yes that's the difference. The remote staging environment caches its config. Error IDs were still being generated though and the user feedback form was showing up ( app()->bound('sentry') && !empty(Sentry::getLastEventID()) were true) so it was behaving as if it was configured correctly. 

I think the config change needs to be highlighted or or a warning shown if SENTRY_LARAVEL_DSN isn't set. In the case where you're on 0.8, upgrade to 0.9 and test locally without cached config files everything will work. You deploy to a cached config environment, no errors are shown and sentry seems to work but issues aren't submitted correctly. It could take a long time to realise that the config isn't correct.

**Comment by stayallive** [comment]
Yes 100%, the doc change will be merged and probably live tomorrow, so this should not happen anymore.

Thanks for keeping me sharp 👍

**Comment by stayallive** [comment]
Docs are updated and live, thanks again 😄
