### ISSUE TITLE
Errors not showing up in Sentry

### ISSUE THREAD

**Issue by patackett** [getsentry/sentry-laravel#137]
I am running laravel 5.5 and just went through the installation process to add Sentry integration.  I tested successfully with the cli but errors in my laravel app are not showing up in Sentry.  Not sure how to troubleshoot so any help would be appreciated.

**Comment by dhritimanrick** [comment]
same here

**Comment by stayallive** [comment]
Can you confirm you added Sentry reporting to app/Exceptions/Handler.php:

```php
public function report(Exception $exception)
{
    if (app()->bound('sentry') && $this->shouldReport($exception)) {
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

If this is not present not errors are transmitted.

Also make sure `config/sentry.php` contains the correct DSN and or reference to a variable in you `.env` file and you ran `php artisan config:cache` again if you are using config caching (or just `php artisan config:clear` to be sure).

**Comment by html5maker** [comment]
same for me, laravel 5.2, php 7.1
*works only with php 5.6...

**Comment by patackett** [comment]
@stayallive, I did make the changes to handler.php and I did run config:clear.  What can we do to troubleshoot the problem?

**Comment by stayallive** [comment]
Hey @patackett & @html5maker, thanks for all the information!

I would try the following change to get some debugging information:

```diff
public function report(Exception $exception)
{
    if (app()->bound('sentry') && $this->shouldReport($exception)) {
+       app('log')->debug('Submitting exception to Sentry!');
-       app('sentry')->captureException($exception);
+       $eventId = app('sentry')->captureException($exception);
+       app('log')->debug('Submitted exception to Sentry with id:' . $eventId);
+       app('log')->debug('Possible send error: ' . app('sentry')->_lasterror);
    }

    parent::report($exception);
}
```

This way there should be a log entry in the Laravel log if Sentry was called to capture an exception with some debugging information.

@patackett on what PHP version are you? 

And are you (both) using sentry.io or self-hosted?

**Comment by patackett** [comment]
I am running php 7.0

I made the changes to the handler.php file and there was no entry written to the log file.  Perhaps I am unclear on even how to test this.  I created an error in the application by using an invalid table name in a query within one of my controllers.  When i go to that page, laravel throws an error message and the laravel error does appear in my log file, but it doesn't appear that the sentry exception handler is being executed.

**Comment by stayallive** [comment]
If that piece of code is not running and showing logs there are 2 things that could be at play.

Either you (mistakingly) added the exception to https://github.com/laravel/laravel/blob/5.5/app/Exceptions/Handler.php#L10-L17 (or one of it's parent classes).

But that is probably unlikely given the kind of exception you are trying to catch... 

So that would mean `app()->bound('sentry')` is untrue, so there are a few ways why that would be, however the command is working (which also resolved sentry from the container) so I a bit lost tbh...

It could be `composer install` or `composer update` is erroring so it never correctly auto-discovers and registers the package. You can check the output to make sure it discovers the Sentry package (output should look something like this: https://f.bouma.me/v/93V4Ul02MFYCj7yHlxkA).

Can you reproduce this in a clean 5.5 install and put that up somehwere on github so I can check your implementation out and try to find where it chokes?

**Comment by patackett** [comment]
I checked the handler and the dontReport array is empty.  I am not following your comment that the command is working.  I added a line of code to log a message before the check of app()->bound('sentry') and got nothing.  This tells me the report function is not even being called.

**Comment by patackett** [comment]
I did some searching and found some others who had handler issues and found this

https://laracasts.com/discuss/channels/laravel/exception-handler-not-recognized

When I added the sentry report code to Illuminate\Foundation\Exceptions\Handler::class it is now working.  I don't know if this is the right way to do it but it does seem to work.

**Comment by stayallive** [comment]
Very interesting, so what are you seeing in `bootstrap/app.php`?

If you are seeing:

```php
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    Illuminate\Foundation\Exceptions\Handler::class
);
```

You can change it to:

```php
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class // Do change this to the correct namespace for you app
);
```

**Comment by patackett** [comment]
I have gone back and forth between the two options in bootstrap/app.php and it doesn't change the outcome.  Even if I use App\Exceptions\Handler::class, the sentry reporting only works if it is in  Illuminate\Foundation\Exceptions\Handler::class

**Comment by stayallive** [comment]
I would suggest to take this to the Laracasts forum since this is not an issue with the Sentry Laravel integration but with your Laravel installation somehow not using the correct exception handler... hopefully people there can figure out what is going wrong!

**Comment by alirezamirsepassi** [comment]
Check whether domain sentry.io is reachable from your servers or not. In my case, the error was not showing up in the sentry because my country was blocked to access sentry.io
