### ISSUE TITLE
Support for Sentry environment

### ISSUE THREAD

**Issue by kevinreynolds** [getsentry/sentry-laravel#138]
Wondering whether this package support passing environment?
https://docs.sentry.io/learn/environments/

**Comment by stayallive** [comment]
Yes it definitly does.

You can do it while setting context with the `->setRelease($release)` method on the client:

https://github.com/getsentry/sentry-laravel#adding-context

Or you can for example change your AppServiceProvider's register method too:

```php
    /**
     * Register any application services.
     */
    public function register(): void
    {
        // Set the release for Sentry
        app()->resolving('sentry', function (Raven_Client $sentry) {
            $sentry->setRelease(config('app.version'));
        });
    }
```

**Comment by bluec** [comment]
I believe this package already sends the `APP_ENV` from your `.env` as the environment. If you want to send the release / version that can be configured within `config/sentry.php` as per commented out example in that file.

**Comment by stayallive** [comment]
Yes it does indeed. Sorry totally misread this question... 

You can however override it from a service provider if you want to.

It's implemented here:

https://github.com/getsentry/sentry-laravel/blob/39e918a8f2c9d06c7408d275095e36ad4258886d/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php#L81
