### ISSUE TITLE
Error use logger for Sentry

### ISSUE THREAD

**Issue by Smolevich** [getsentry/sentry-laravel#143]
I add this rows in `config/logging.php` 
```
'channels' => [
    // ...
    'sentry' => [
        'driver' => 'sentry',
        'level'  => error,
        'bubble' => true,
    ],
],
```
 But if i try to use ```Log::channel('sentry')->error('Message', [])```, i catch Exception with message `Driver [sentry] is not supported.` Version of laravel: 5.6.26

**Comment by stayallive** [comment]
Make sure you are using version `0.9.x` of the `sentry/sentry-laravel` package.

**Comment by Smolevich** [comment]
I use version `0.9.0`

**Comment by stayallive** [comment]
Did `php artisan package:discover` also output `Discovered Package: sentry/sentry-laravel`?

Also make sure you are not doing the Log in a serviceprovider's register/boot method since the Sentry service provider might not have booted and registered the logging driver yet.

**Comment by Smolevich** [comment]
command `php artisan package:discover` not shows sentry package. I call method of Log in standart http controller

**Comment by Smolevich** [comment]
I remove `config/sentry.php` and run command `php artisan vendor:publish --provider="Sentry\SentryLaravel\SentryLaravelServiceProvider"`. It is helps me
