### ISSUE TITLE
Missing browser context

### ISSUE THREAD

**Issue by RobinOng** [getsentry/sentry-laravel#147]
Hey, I am wondering if there is a way to add browser context. Currently it will always be Unknown Browser:
<img width="824" alt="screen shot 2018-08-12 at 2 52 22 am" src="https://user-images.githubusercontent.com/22089936/43994116-ce9fe562-9dda-11e8-8607-f63bd6a90245.png">

I dug into the code and tried to add 'browser' into `Raven_Context`, then modify `capture()` in `RavenClient`, this works.

**Comment by stayallive** [comment]
A solution is being dicussed in https://github.com/getsentry/sentry/issues/8555.

And if any changes on the PHP client side is required, we'll implement it in the base SDK.

**Comment by andreshg112** [comment]
Same here!
