### ISSUE TITLE
How could I mark logs from different channels ?

### ISSUE THREAD

**Issue by smknstd** [getsentry/sentry-laravel#151]
I use different logging channels in my laravel app. I log them all in sentry but it seems I'm unable to filter them then. Does anybody using channels ? Do you think adding a "tag" would help, and how could I do that ?

thanx

**Comment by stayallive** [comment]
I am not sure what you mean, log channels are the outputs so you can write to multiple channels for example Sentry and a log file... not sure where or how you want to filter them 😄 Can you explain a bit more what you are trying to achieve?

Also as a gentle reminder, Sentry is _not_ an [logging service](https://sentry.io/vs/logging/) so you might not be able to achieve what you want.

**Comment by smknstd** [comment]
Hi @stayallive, thanx for answering ! I'm using logging channel as introduced in laravel recently: https://laravel.com/docs/5.6/logging#writing-to-specific-channels

Being able to log errors from specific parts of an application in different places has great value

```
Log::channel('stripe')->error('Payment refused');
...
Log::channel('emailing')->error('Sending email failed');
```

When in sentry I would like to keep that channel information at least and ideally being able to filter errors based on that criteria. What do you think ?

**Comment by stayallive** [comment]
Hey, this is cool, did not think about adding some config name, simple enough 👍 

If you wan't and have the time I'd be happy to accept a PR to update the docs on this 😄

**Comment by smknstd** [comment]
https://github.com/getsentry/sentry-laravel/pull/152

**Comment by stayallive** [comment]
Thanks!
