### ISSUE TITLE
add support to report all PHP 7+ Error type

### ISSUE THREAD

**Issue by michaelnguyen547** [getsentry/sentry-laravel#155]
PHP has new Error class for all internal PHP errors. The Error class implements Throwable interface. 

[PHP 7+ Throwable](http://php.net/manual/en/class.throwable.php)

At the moment, Sentry only report Exception (which is part of Throwable), it does not report Error (which is another part of Throwable).

**Comment by stayallive** [comment]
How are they not supported? What are you running into?

![image](https://user-images.githubusercontent.com/1090754/46570978-402b5500-c96d-11e8-9711-f8e4395e3a4c.png)

You might want to double check you are using the latest version of this package (0.10.x).
