### ISSUE TITLE
New DNS errors

### ISSUE THREAD

**Issue by Tbaile** [getsentry/sentry-laravel#158]
Hello everyone, 
there's a catch in the new DSN given by Sentry, the component signals it as invalid and no further action will be done.
Someone have already a workaround for it?

**Comment by stayallive** [comment]
Hey @Tbaile, my guess is that you are on an older version of the SDK that does not accept a DSN without the private key... try updating to `0.10.x` of this library, that should fix it.

**Comment by Tbaile** [comment]
Already tried, currently I'm working with sentry/sentry 1.9.0 and sentry/sentry-laravel 0.10.0.
The system avoids the error using the old DSN with the secret in it.
Some suggestion where to start debugging the whole thing so I can give a hand?

**Comment by stayallive** [comment]
You are a bit behind then 👍 

> https://github.com/getsentry/sentry-php/releases/tag/1.9.1

So updating to sentry-php of at least 1.9.1 should fix it!

**Comment by Tbaile** [comment]
Damn, I really feel dumb now. The issue was in the .lock that "magically" kept all the time the 1.9.0. 
Sorry and thank you for the help! 😄

**Comment by stayallive** [comment]
Ah! Happens to the best of us 👍 glad you found it!
