### ISSUE TITLE
How to "fix" reported IP when using a proxy?

### ISSUE THREAD

**Issue by cviebrock** [getsentry/sentry-laravel#16]
Our site uses not only haproxy on the server side, but we're behind Cloudflare as well.  As a result, all of our exceptions that are caught by Sentry are reporting "user = ip:127.0.0.1" under Tags, and "IP Address	127.0.0.1" under User.

We do set an "X-Forwarded-For" header with the correct IP address (left-most entry in a comma-delimited list), but I'm trying to figure out how to override the value that is automatically reported.

To make things "worse", this is for a Laravel 4.2 application.  `Request::ip()` handles the X-Forwarded-For parsing, so I've tried the following in _app/start/global.php_:

```php
App::error(function (Exception $exception, $code) {
	// Add context to Sentry

	$ip = Request::ip();
	Sentry::tags_context(array(
		'user' => 'ip:' . $ip
	));

	Log::error($exception);
});
```

But Sentry adds the following to the error report:

```
There was 1 error encountered while processing this event
Discarded invalid value for parameter 'tags'
{
  "name": "tags",
  "value": [
    "user",
    "ip:123.123.123.123"
  ]
}
```

Any suggestions on how to fix this?

**Comment by dcramer** [comment]
Where is Sentry::tags_context coming from?

Regarding IP, you just need to bind user_context with ip = '...'

**Comment by cviebrock** [comment]
`Sentry::tags_context(...)` was just me using the facade instead of `app('sentry')->tags_context(...)`.

As for your other suggestion, I tried:

```php
app('sentry')->user_context(array(
	'ip' => $ip
));
```

The resulting report looks like this: 

![screenshot 2016-05-24 22 26 25](https://cloud.githubusercontent.com/assets/166810/15527333/13235d5e-21ff-11e6-9dc6-08769432028d.png)

Is there no way to completely overwrite those 127.0.0.1s?

**Comment by dcramer** [comment]
Sorry, my mistake. It's ip_address

Will take a look at the tags issue as well

**Comment by cviebrock** [comment]
No problem ... thanks!

**Comment by TadiNate** [comment]
Yes I needed your support for the following error
SiteLock Incident ID 480000780398715067-367604567268918497
Your IP Address 197.156.86.150
Proxy IP 107.154.147.229
Proxy ID 10480
Server IP N/A
Error Code 16
Error Name Security error (code 16)
Error Description This request was blocked by the security rules
Incident Time
