### ISSUE TITLE
Undefined class constant 'VERSION'

### ISSUE THREAD

**Issue by RafaelGSS** [getsentry/sentry-laravel#160]
Hello everyone.

I have an application running 

`
"require": {
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.7.*",
        "sentry/sentry-laravel": "^0.10.0",
    }`

But when i gonna test the sentry with command:

`php artisan sentry:test`

I receive the error

> In SentryLaravelServiceProvider.php line 107:
                                      
> Undefined class constant 'VERSION' 

I follow the tutorial:
https://docs.sentry.io/clients/php/integrations/laravel/#lumen-5-x

**Comment by RafaelGSS** [comment]
Just change the Service Provider Name in bootstrap/app.php 
to
$app->register('Sentry\SentryLaravel\SentryLumenServiceProvider');

**Comment by stayallive** [comment]
That service provider name is the exact one mentioned in the docs?

https://docs.sentry.io/clients/php/integrations/laravel/#lumen-5-x

Or am I missing somewhere, where the incorrect serviceprovider is used?

**Comment by stayallive** [comment]
Ah perfect :) Thanks for letting me know 👍
