### ISSUE TITLE
Setup issue: error when running php artisan

### ISSUE THREAD

**Issue by rizkysyazuli** [getsentry/sentry-laravel#161]
Saw an error when running the `php artisan` command.

    php artisan vendor:publish --provider="Sentry\SentryLaravel\SentryLaravelServiceProvider"

It says:

```
[LogicException]
The command defined in "Sentry\SentryLaravel\SentryTestCommand" cannot have an empty name.
```

I'm using Laravel 5.0.x

**Comment by stayallive** [comment]
Hey @rizkysyazuli, sorry for the trouble!

0.10.1 was just released which fixes the error :)
