### ISSUE TITLE
Add a public function to add/alter top level contexts.

### ISSUE THREAD

**Issue by bartabel** [getsentry/sentry-laravel#162]
I would like to be able to set the "browser", "device" and "os" contexts in the sentry reports. Right now we have functions to add the "user", "tags" and "extra" contexts but no other contexts.

I used to set the other contexts in app/Exceptions/Handler when calling captureException. But we have now switched to using Laravel 5.6+ log channels so I can no longer modify the data at that point.

**Comment by stayallive** [comment]
There is an PR open to implement this in the extra context: getsentry/sentry-php#690
