### ISSUE TITLE
Class sentry does not exist

### ISSUE THREAD

**Issue by quantumwebco** [getsentry/sentry-laravel#164]
I took over a laravel project and it has this package installed and it just seems to break everything. I have removed all references I can find to Sentry in the code but whenever I run composer update I just get
```PHP Fatal error:  Uncaught ReflectionException: Class sentry does not exist in ...\app\vendor\laravel\framework\src\Illuminate\Container\Container.php:734```

How can I just get rid of this package so I can actually use composer etc again??

**Comment by stayallive** [comment]
I am curious when this started breaking? Is this new or was this always the case? If it's a bug in the library it would be great if we can resolve it... or were you in the process of removing it and did it start throwing errors?

----

`composer update --no-scripts` and afterwards `composer update` should work again.

Assuming you remove `sentry/sentry` from your composer.json and have removed every `app('sentry')` or `Sentry::` calls from your code.

If that doesn't help try removing `bootstrap/autoload.php` and the `bootstrap/cache` folder.

I think this is some weird caching by composer and or the autoloader.

If all the above is not working, sentry is still being resolved from the container by the code probably...

**Comment by quantumwebco** [comment]
Sorry, this was my bad. I think it had a lot to do with the php version I was using on command line. Forogt I was running 7.2cli but 5.6 for apache.

Fixed it by removing all references from providers in config.app and in particular the Handler ```app('sentry')->captureException($exception);```

Reverted back to php 5.6cli, was running 7.2cli and laravel 5.4, derp :s

Ran composer update

Added references back n to config.app and Handler class.
