### ISSUE TITLE
30 seconds timeout error exception in php-http\client-common\src\Plugin\RetryPlugin

### ISSUE THREAD

**Issue by yoyosan** [getsentry/sentry-laravel#181]
Packages info:
```
laravel/framework v5.7.19
sentry/sentry                         2.0.0-beta1
sentry/sentry-laravel                 1.0.0-beta2
php-http/client-common 1.9.0
```

and I get this error:

```
[Fri Jan 18 14:39:18 2019] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in
C:\Users\yoyosan\Work\abonati\vendor\php-http\client-common\src\Plugin\RetryPlugin.php on line 121
```

I've tried :
* to use the DSN URI in the browser and it works fine.
* to send one test message using the command line:

```
php artisan sentry:test
[sentry] Client DSN discovered!
[sentry] Generating test event
[sentry] Sending test event
[sentry] Event sent: blablablabla
```

Nothing is sent.

**Comment by ste93cry** [comment]
Can you try setting the `retry_options` configuration option to something lower than the default value (which btw is too much high and we should change it)? I don't know why but I believe that for some reason you get an error and Httplug tries to send the event again and again up to the specified amount of times, however the PHP timeout comes first

**Comment by yoyosan** [comment]
![image](https://user-images.githubusercontent.com/32405/51399786-72914480-1b4f-11e9-81a4-519197b406be.png)

Increased to 20(as you can see above) and I get the same error. There's no error in my laravel app logs.

**Comment by yoyosan** [comment]
I found the problem.

The following error is thrown: `[object] (Http\\Client\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

That's because I'm using Windows to develop, therefore I had to:
* download the latest CA certificates from https://curl.haxx.se/docs/caextract.html
* point to it in `php.ini`, `curl.cainfo = "C:\path\to\cacert.pem"`
