### ISSUE TITLE
Add setUser() instructions to README

### ISSUE THREAD

**Issue by futzlarson** [getsentry/sentry-laravel#182]
The [Sentry docs](https://docs.sentry.io/enriching-error-data/context/?platform=php#capturing-the-user) for capturing the user include PHP but not Laravel so this:

```
configureScope(function (Scope $scope): void {
    $scope->setUser(['email' => 'john.doe@example.com']);
});

```
Had me very confused. For Laravel the first line needs to be:

`app('sentry')->configureScope(function (Scope $scope): void {`

It would be helpful to include this right in the README. Something like this:

```
        use Sentry\State\Scope;
        use function Sentry\configureScope;

        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->configureScope(function (Scope $scope): void {
                $user = auth()->user();

                if ($user) {
                    $scope->setUser([
                        'id' => $user->id,
                        'email' => $user->email,
                        'plan' => $user->plan
                    ]);
                }
            });
            app('sentry')->captureException($exception);
        }
```

I'll also be suggesting they add it to the [installation page](https://docs.sentry.io/platforms/php/laravel/#laravel-5x).

**Comment by stayallive** [comment]
```php
use function Sentry\configureScope;

configureScope(function (Scope $scope): void {
  $scope->setUser(['email' => 'john.doe@example.com']);
});
```

This should work even in the Laravel integration right @HazAT? Or are we doing something funky? But yes either way we should add documentation for this! Thanks for opening an issue for that!

**Comment by futzlarson** [comment]
Definitely didn't work for me and I had the correct `use` statements. I [posted this on r/laravel](https://www.reddit.com/r/laravel/comments/ahrd6e/capturing_user_in_sentry/) because it wasn't working. [This comment](https://www.reddit.com/r/laravel/comments/ahrd6e/capturing_user_in_sentry/eehke4x/) may explain why?

A note about configuring releases in the config would also be helpful. Thanks for responding!

**Comment by futzlarson** [comment]
@TLMNicolas I check `auth()->user()` before adding user information. Wouldn't that suffice, or does it need to be `auth()->check()`? I've never been sure which one to use.

That SO post is over two years old so I figured it no longer applied.

I did have `use Sentry\State\Scope` as well, just didn't include. I updated my original post.

**Comment by futzlarson** [comment]
For what it's worth, I'm on 5.6.

Rearranging middleware - at least at this stage of my Laravel understanding - seems risky. Like it's in a specific order for a reason, right?

Side question: Is there any different between `if (auth()->user())` and `if (auth()->check())`?

I did get it working. This issue is merely to suggest some updates to the README to make it easier for newcomers because that threw me for an unnecessary loop. A note about configuring releases (in the config, commented out by default) would also be nice. Really anything in the Sentry Getting Started progress bar:

<img src="https://user-images.githubusercontent.com/1168673/51694227-56b5f480-1fce-11e9-8a58-268bf4ce692e.png" width="200">

**Comment by ppalmeida** [comment]
I'm not sure if I should just comment it here or add a new issue. Because my problem is not about `setUser` exactly but using `configureScope`. But since they are very similar as I saw here, I will post my problem here first.

The code I'm doing here is an Artisan command. I want to catch an Exception (so the command still running after that), but I want to send all exceptions to Sentry log service. 

This is how my code looks like:
```
// First, I import Sentry dependencies...
use Sentry\State\Scope;
use function Sentry\captureException;
use function Sentry\configureScope;

// .... then, later in my code, there is the try/catch block:
try {
      // a few things here...
      
} catch (\Exception $e) {
    // create some extra values to help my debugging flow:
    // Obs: $schedule is a variable previously created in the script:
    configureScope(function (Scope $scope) use($schedule) {
        $scope->setExtra('player1', $schedule->player1->name);
        $scope->setExtra('player2', $schedule->player2->name);
        $scope->setExtra('tournament_event_id', $schedule->event->id);
    });

    // send the exception to Sentry: 
    app('sentry')->captureException($e);
}
```

Running that, I get this error:

```
Call to undefined function Sentry\configureScope()
```
I try to install the default Sentry SDK, but it conflicts with the one Sentry-Laravel is using:
```
composer require sentry/sentry:2.0.0-beta1 php-http/curl-client guzzlehttp/psr7
Using version ^1.7 for php-http/curl-client
Using version ^1.5 for guzzlehttp/psr7
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sentry/sentry-laravel 0.11.0 requires sentry/sentry ^1.9.0 -> satisfiable by sentry/sentry[1.x-dev].
    - sentry/sentry-laravel 0.11.0 requires sentry/sentry ^1.9.0 -> satisfiable by sentry/sentry[1.x-dev].
    - sentry/sentry-laravel 0.11.0 requires sentry/sentry ^1.9.0 -> satisfiable by sentry/sentry[1.x-dev].
    - Can only install one of: sentry/sentry[2.0.0-beta1, 1.x-dev].
    - Installation request for sentry/sentry 2.0.0-beta1 -> satisfiable by sentry/sentry[2.0.0-beta1].
    - Installation request for sentry/sentry-laravel ^0.11.0 -> satisfiable by sentry/sentry-laravel[0.11.0].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by futzlarson** [comment]
I would say a new issue. Mine is just about updating the README. Best to keep it separate.

**Comment by stayallive** [comment]
The 1.0.0 version of the Laravel integration is now released.

Installation instructions are here: [docs.sentry.io/platforms/php/laravel](https://docs.sentry.io/platforms/php/laravel/)

This also includes instructions for adding user context: https://docs.sentry.io/platforms/php/laravel/#user-context

If it's still unclear please open a new issue so we can address that in the documentation!

**Comment by fh32000** [comment]
Work for me 

```
   public function report(Throwable $exception)
    {
        if (!App::environment('local') && $this->shouldReport($exception) && app()->bound('sentry')) {
            if ($user = request()->user()) {
                \Sentry\configureScope(function (\Sentry\State\Scope $scope) use ($user) {
                    $scope->setUser([
                            'id' => $user->id,
                            'name' => $user->full_name,
                            'email' => $user->email,
                            'phone' => $user->phone,
                            'userable_type' => $user->userable_type
                        ]
                    );
                });
            }
            app('sentry')->captureException($exception);
        }
        parent::report($exception);
    }
```

**Comment by chrillep** [comment]
> The 1.0.0 version of the Laravel integration is now released.
> 
> Installation instructions are here: [docs.sentry.io/platforms/php/laravel](https://docs.sentry.io/platforms/php/laravel/)
> 
> This also includes instructions for adding user context: https://docs.sentry.io/platforms/php/laravel/#user-context
> 
> If it's still unclear please open a new issue so we can address that in the documentation!

https://docs.sentry.io/platforms/php/guides/laravel/enriching-events/identify-user/
docs are stil not telling you where to add it (which file..)

**Comment by stayallive** [comment]
There are a few ways you can do this, and it's up to you which you choose.

However we provide an example with a middleware: https://docs.sentry.io/platforms/php/guides/laravel/usage/#user-context

I must admit that that should be mentioned on the Identify Users page though, I'll look into improving that!
