### ISSUE TITLE
"Missing event handler:loghandler" on Laravel 5.2 clean installation.

### ISSUE THREAD

**Issue by mspivak** [getsentry/sentry-laravel#186]
This is happening on Laravel 5.2, clean install.

`RuntimeException: Missing event handler:loghandler ... on line 104`

I was able to work around locally by adding `return;` right before the exception (src/Sentry/Laravel/EventHandler.php:104).

I saw that the mentioned exception is added on beta3. Downgrading to beta2 produces a memory exhaust right there, I'm guessing thats what the exception is for.

**Comment by stayallive** [comment]
I am a bit puzzled on how `handler:loghandler` ended up in the event handler tbh... did you add anything else or custom or did something to register the event handler yourself?

**Comment by mspivak** [comment]
I was working on a different, pretty big L5.2 project, with custom log handlers and got that exception. To isolate the issue and ensure it was a `laravel-sentry` related issue, I created a clean install through `composer create-project --prefer-dist laravel/laravel blog "5.2.*"` and then proceeded with the `laravel-sentry` installation instructions. 

Also, please note that there is a missing space on https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/EventHandler.php#L104. The `$method` var is actually set to `"log"`, not `"loghandler"`.


>

**Comment by stayallive** [comment]
Yep I found it right after I placed a comment here, sorry about that.

Should be fixed by #187
