### ISSUE TITLE
transChoice method is deprecated in Symfony 4.2

### ISSUE THREAD

**Issue by prodigymike** [getsentry/sentry-laravel#188]
Hello,

I wanted to add this here to provide heads up/help someone else since I was able to fix this issue (hopefully correctly).

I recently upgraded from sentry-laravel 0.7.0 to 1.0.0-beta3 as per the integration guide. All appeared to work well since updating until visiting a inner blade page that makes use thujohn/twitter's ago method (\Thujohn\Twitter\Facades\Twitter::ago($user->updated_at)). This page was now heavily broken as some HTML tags weren't closed (since the exception was thrown) as well as the updated_at data being missing. It appears the deprecation is being treated as an exception (see references below).

Upon removing "sentry/sentry-laravel": "1.0.0-beta3" from composer.json things work correctly. 0.7.0 also previously worked correctly. 

**My fix:**
Instead of downgrading symfony/translation as per reference 1, I was able to correct this by adding "\Symfony\Component\Translation\Translator::transChoice," to the $dontReport array within app/Exceptions/Handler.php. I'm hoping this won't cause any other funny business within the application.

**Full error:**
User Deprecated: The "Symfony\Component\Translation\Translator::transChoice()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%count%" parameter.

**References:**
https://github.com/briannesbitt/Carbon/issues/1548
https://github.com/symfony/symfony/issues/29607

**Comment by stayallive** [comment]
This sounds like when you when removed `sentry-laravel:1.0.0-beta3` you also downgraded the Symfony translation package? I'm not sure Sentry does anything different since `0.7.x` in this regard.

Sentry should never interrupt the request, ever. It looks like the Laravel error handler is the culprit here converting the notice to an exception (which is in the end also captured by Sentry).

However, I will keep this open so we can investigate and see if we can replicate the behaviour.

**Comment by prodigymike** [comment]
Hey @stayallive,

To clarify a bit, I didn't have to downgrade to `sentry-laravel:0.7.0` and I'm still using `sentry-laravel:1.0.0-beta3`.

I've run a `composer show -i` and it appears that `symfony/translation` is still at `v4.2.3`. I believe when `sentry-laravel:0.7.0` was in use my app may have been using `symfony/translation:4.1.x` at the time.

I hope this helps and thanks a lot for your time/attention. Please let me know if I can help further.

**Comment by jiriko** [comment]
+1 same problem.  

> "\Symfony\Component\Translation\Translator::transChoice," to the $dontReport array
seems to solve the reporting issue but won't solve the rendering issue if you want to add user context earlier in the request in a middleware

**Comment by stayallive** [comment]
I have installed a clean Laravel 5.7 to test this issue and followed the installation instructions: https://docs.sentry.io/platforms/php/laravel/#laravel-5x (made no changes to any config).

I tested the following route:
```php
Route::get('/', function () {
    @trigger_error(sprintf('The "%s()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%%count%%" parameter.', __METHOD__), E_USER_DEPRECATED);

    return view('welcome');
});
```

And in that view used (made sure translations package is 4.2.x):
```blade
{{ now()->diffForHumans() }}
```

And couldn't trigger the deprecation to show up as ErrorException or being sent to Sentry.

The following worked immediately (as expected):
```php
Route::get('/', function () {
    throw new Exception('Pizza!');

    return view('welcome');
});
```

Hope you can possibly provide some more info or configuration that could trigger this exception. 

Are you using the log channels? Did you make any changes in the `config/sentry.php` file? Did you make other changes to the Laravel error handler? Are you setting user context somewhere?

**Comment by jiriko** [comment]
try adding a user context to sentry earlier in the request before the trigger_error

**Comment by stayallive** [comment]
What is the PHP version you are running on? 

And do you have a stacktrace for the error?

**Comment by jiriko** [comment]
try adding a user context to sentry earlier in the request before the trigger_error

PHP 7.2.0
laravel/framework  v5.7.24
sentry/sentry       2.0.0-beta1                     
sentry/sentry-laravel    1.0.0-beta3

```
public function report(Exception $exception)
    {
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
                      app('sentry')->captureException($exception);
          }

        parent::report($exception);
    }
```

```
class SentryContext
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
    * @return mixed
     */
    public function handle($request, Closure $next)
   {

            app('sentry')->getCurrent()->configureScope(function (Scope $scope): void {
                $scope->setUser(['email' => 'foo@gmail.com']);
           });


       return $next($request);
   }
}
```

**Comment by stayallive** [comment]
@jiriko thanks for all the info! I'm getting somewhere with this 👍

**Comment by stayallive** [comment]
@jiriko can you upgrade to the latest beta versions and see if it's still there?

sentry/sentry-laravel 1.0.0-beta4 (which should install sentry/sentry 2.0.0-beta2)

**Comment by jiriko** [comment]
@stayallive awesome! you're my hero. Ta

**Comment by stayallive** [comment]
@jiriko yes, that's expected. Sentry is logging exceptions and errors (a deprecation is triggered by `trigger_error`). You can disable that by adding the following in your `config/sentry.php`:

```php
    'error_types' => E_ALL & ~E_USER_DEPRECATED,
```

This means send everyting except deprecation notices.

**Comment by jiriko** [comment]
@stayallive perfect! thank you so much

**Comment by stayallive** [comment]
No problem, going to close this issue since was already fixed.

If you are still having issues make sure you are on `1.0.0-beta4` or higher!

If you don't want deprecated notices being sent to Sentry read: https://github.com/getsentry/sentry-laravel/issues/188#issuecomment-463612747
