### ISSUE TITLE
Support for Laravel 5.1

### ISSUE THREAD

**Issue by eaponiente** [getsentry/sentry-laravel#192]
Do you still support 5.1? 

I am getting this error on 
Laravel 5.1 
PHP 7.3

```
Installation request for sentry/sentry-laravel 1.0.0-beta5 -> satisfiable by sentry/sentry-laravel[1.0.0-beta5] 
```

**Comment by stayallive** [comment]
Hey @eaponiente, yes we do. But I'm missing part of the error there should be a few lines below that "Installation request" which will explain what the actual error is.

But is sounds similar to another issue: https://github.com/getsentry/sentry-laravel/issues/191#issuecomment-465291233

You can try to run the following and that might already fix it (without knowing the actual error):

```
composer require "sentry/sentry:2.0.0-beta2@dev" "sentry/sentry-laravel:1.0.0-beta5@dev" php-http/curl-client guzzlehttp/psr7
```

**Comment by stayallive** [comment]
The 1.0.0 version of the Laravel integration is now released.

Installation instructions are here: https://docs.sentry.io/platforms/php/laravel/

And they should no longer require any stability changes and work on 5.1 just fine :)

Please re-open / open a new issue if you keep having troubles!
