### ISSUE TITLE
How to filter out exceptions ?

### ISSUE THREAD

**Issue by realtebo** [getsentry/sentry-laravel#208]
I've the problem that this useless exceptions is consuming  my free sentry plan

>ErrorException
> User Deprecated: The "Symfony\Component\HttpFoundation\Request::setTrustedHeaderName()" method is deprecated since Symfony 3.3 and will be removed in 4.0. Use the $trustedHeaderSet argument of the Request::setTrustedProxies() method instead.

Could you kindly point how / where to filter out this exception?

I already have E_USER_DEPRECATED reporting disabled, so I've NO idea of what's happening here...

```
    public function report(Exception $exception)
    {
       if (app()->bound('sentry') && $this->shouldReport($exception)){
            
            app('sentry')->captureException($exception);
        }
    
        parent::report($exception);
    }
    
```

I also discovered I cannot Log::debug($exception) inside this function, it not works (simply, no error and no logs, why ?)

**Comment by stayallive** [comment]
Hey @realtebo,

How did you disable `E_USER_DEPRECATED`? The way to do it is adding the following key to your `config/sentry.php`.

```php
    'error_types' => E_ALL ^ E_USER_DEPRECATED,
```

---

`Log::debug($exception)` is not reporting to Sentry, that's correct. It's not supposed to (since Sentry is not a logging platform and `Log::debug` is normally used for all kind of messages not needing to be sent to Sentry), if you want to sent an exception you are catching yourself to Sentry you can do something like this:

```php
try {
   theCodeThatIsThrowingAnException();
} catch (\Exception $e) {
    // Log::debug($e);

    // I added the app()->bound() call to make sure Sentry is enabled/registered (so it doesn't crash in development)
    if (app()->bound('sentry')) {
        app('sentry')->captureException($e);
    }
}
```

Let me know if that answers your questions!

**Comment by realtebo** [comment]
Sorry, I explained not so well.... I was trying to log to file, but it was not working.

**Comment by realtebo** [comment]
I'll check the configuration

```
'error_types' => E_ALL ^ E_USER_DEPRECATED,
```

**Comment by realtebo** [comment]
Hey ! Look at this: https://github.com/getsentry/sentry-php/releases/tag/2.0.1 

Please, update your project dependency so we can have this free :)

**Comment by stayallive** [comment]
@realtebo you might need to run `composer update` still, 2.0.1 should be automatically installed.

You can check by running `composer show sentry/sentry` in the directory of your project, it should read:

```
# composer show sentry/sentry          
name     : sentry/sentry
descrip. : A PHP SDK for Sentry (http://sentry.io)
keywords : crash-reporting, crash-reports, error-handler, error-monitoring, log, logging, sentry
versions : * 2.0.1
// ... cut away the rest of the output
```

This will solve the issue.

**Comment by realtebo** [comment]
Fixed, thanks !
