### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: mb_convert_encoding()

### ISSUE THREAD

**Issue by darkgoldblade01** [getsentry/sentry-laravel#21]
We are getting this error reported in sentry once per hour, and it appears to be extending from the Raven lib. Are there any other reports of this/is there a fix for it? We are using PHP7.0 and nginx.

    Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: mb_convert_encoding(): Unable to detect character encoding in /[folder_route]/vendor/sentry/sentry/lib/Raven/ReprSerializer.php:41
    Stack trace:
    #0 /[folder_route]/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(36): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_convert_enco...', '/[folder_route]...', 41, Array)
    #1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'mb_convert_enco...', '/[folder_route]...', 41, Array)
    #2 /[folder_route]/vendor/sentry/sentry/lib/Raven/ReprSerializer.php(41): mb_convert_encoding('\xFF\xF3@\xC4\x00\x14\x00J\xB0\x0FO\x10\x00Bt...', 'UTF-8', 'auto')
    #3 /[folder_route]/vendor/sentry/sentry/lib/Raven/Serializer.php(45): Raven_ReprSerializer->serializeValue('\xFF\xF3@\xC4\x00\x14\x00J\xB0\x0FO\x10\x00Bt...')
    #4 /[folder_route]/vendor/sentry/sentry/lib/Raven/Serializer.php(40)
    #0 vendor/sentry/sentry/lib/Raven/ReprSerializer.php(41): null

**Comment by dcramer** [comment]
@darkgoldblade01 i thought we addressed this -- can you confirm version of the SDK?

**Comment by darkgoldblade01** [comment]
Latest, just installed on our server using composer require to get the latest version. There are random hours where we don't get the report, but that is maybe once per day, otherwise it is hourly.

<img width="327" alt="screen shot 2016-06-23 at 11 30 48 am" src="https://cloud.githubusercontent.com/assets/9066551/16315165/ffe5b13a-3935-11e6-8c75-8e7b37ba2a6a.png">

**Comment by darkgoldblade01** [comment]
<img width="896" alt="screen shot 2016-06-23 at 11 34 22 am copy" src="https://cloud.githubusercontent.com/assets/9066551/16315487/5c778256-3937-11e6-8244-913be09a27e0.png">

**Comment by darkgoldblade01** [comment]
<img width="896" alt="screen shot 2016-06-23 at 11 34 22 am copy" src="https://cloud.githubusercontent.com/assets/9066551/16315562/a1a7424e-3937-11e6-80db-5f9c3e9e04b8.png">

**Comment by darkgoldblade01** [comment]
<img width="915" alt="screen shot 2016-06-23 at 11 44 05 am copy" src="https://cloud.githubusercontent.com/assets/9066551/16315692/294ad788-3938-11e6-87f2-88ba0af158fa.png">
(I figured out how to block it out properly 😄)

**Comment by dcramer** [comment]
Ah looks like we havent released this fix. Could you try dev-master?

**Comment by darkgoldblade01** [comment]
Awesome, you can close this issue then. I will let you know if we run into the issue still.

**Comment by dcramer** [comment]
Will push out 0.22.0 shortly
