### ISSUE TITLE
Double entry with different level - only from view

### ISSUE THREAD

**Issue by arxeiss** [getsentry/sentry-laravel#210]
I just updated Sentry from **0.10** to **1.0** on my Laravel project, which still is on version 5.7.
However, sometimes it is acting weird and put double entries into Sentry. Here is example:

**HomeController**:
```php
public function index()
{
    throw new \Exception("Error Processing Request", 1);
}
```
When I visit homepage, it send my exception into Sentry and shows **only once** with level **Error**.

Error level: **Error** - Exception
in \app\Http\Controllers\HomeController.php
Error Processing Request

If I put there something like this and visit homepage not logged in
```php
public function index()
{
    $a = \Auth::user()->tst;
}
```
It produce two errors into Sentry, both with level **Info**.
Error level: Info - ErrorException
in \app\Http\Controllers\HomeController.php
Trying to get property of non-object

---

When I have my view like below and visit any page not being logged in, it log twice with different levels
**layout.blade.php**:
```blade
var a = @json(Auth::user()->tst)
```
Error level: **Info** - ErrorException
in \storage\framework\views\37f5806917ac9107d4ad865b4c5dfb9772471201.php
Notice: Trying to get property of non-object

Error level: **Fatal** - ErrorException
in \storage\framework\views\37f5806917ac9107d4ad865b4c5dfb9772471201.php
Trying to get property of non-object (View: D:\www\SunPrihlasky\resources\views\layouts\app.blade.php)

It is good to mention, that in my Laravel log folder are all those errors logged just once and always with level **Error**. 

Is there something what I'm missing? I deleted all code to set up more data like user, tags etc and it does still the same. I tried to checkout older commit, downgrade packages back to 0.10 and it was logging errors from view only once. When I checkout back to master and upgraded to 1.0 it does this weird behaviour again.

**Comment by arxeiss** [comment]
Just discovered. If I do not "Add Sentry reporting to App/Exceptions/Handler.php:" nor use "Laravel 5.6 log channels", it shouldn't be logging anything. But it does and then it occurs in Sentry just once.

**Comment by stayallive** [comment]
@arxeiss there could be a few thing at play here.

First to make sure we are talking about the same thing, calling `$object->property_that_does_not_exist` creates a PHP Notice (or error of level notice). This is different from an Exception which can be caught, notices are not capturable (only suppressible by using the `@` operator).

So what happens when a notice is thrown, it will be caught by the `error_handler` once by Laravel and once by Sentry. Sentry sends errors directly to sentry.io if it's within the configured error level (which by default it is). Laravel will log this notice to a log file (or channel).

So if you are using both a log channel and Sentry a notice will be duplicated because Sentry / Laravel don't know if either handled the error (notice).

Important to keep in mind that the snippet you add to the Laravel exception handler class only captures Exceptions (so no errors and therefore notices).

If you want to truly disable Sentry sending errors keep the DSN set to `null`.

Does the above answer your questions?

**Comment by arxeiss** [comment]
Thank you for detailed answer. Yes I know, that E_NOTICE is not an exception. But yes, Laravel convert it into Exception. And this is the problem.

Because sometimes I have code like this
```php
try{
    ...
}catch(SomeException $e){
    \Illuminate\Support\Facades\Log::warning($e);
}
```
And I have default channel `stack` with `daily` and `sentry`. So if this SomeExceptions happen, then I have info in my local file and Sentry as well.

But because of this, also Exception created from E_NOTICE is logged into `stack`. So those error will occur in Sentry twice.

So is there some way, how to disable Sentry to register `error_handler`, because Laravel will do too? Otherwise I don't know how to deal with this. To be able use `\Illuminate\Support\Facades\Log` to log into local file and Sentry, but do not log E_NOTICE etc into Sentry twice.

Thank you

**Comment by stayallive** [comment]
Ah I think I misunderstood what you wanted to achieve there. Sorry about that.

Disabling the error handler is actually pretty doable by adding the following to `config/sentry.php`:

```
   'error_types' => E_ALL ^ E_NOTICE, // Add what you want to ignore or set it to `0` to disable error reporting at all.
```

**Comment by arxeiss** [comment]
Sorry, I really explained it badly, as I thought the origin of this issue is totally different. Now I updated config and it works! Thank you

Now I found it is also in documentation, but before I wasn't able. Don't understand it

Thank you for your patient.

**Comment by stayallive** [comment]
No problem, happy you got it resolved. Thanks for the update!

**Comment by arxeiss** [comment]
Just to clear this up.
I set config to `'error_types' => E_ERROR`, set memory_limit to 10M and loads much more data. Sentry SDK and Laravel logged issue into Sentry. Then I tried the same with max_execution_time and also everything appear twice. When I set `'error_types' => 0` then it was there just once.

So you can disable it totally (not deeply tested).
And I think you have mistake in documentation (when I finally found the option): https://docs.sentry.io/platforms/php/default-integrations/#errorlistenerintegration
You write you reserve 10 MB, but you actually do just 10kB.
