### ISSUE TITLE
File Permission issue

### ISSUE THREAD

**Issue by wtbloom** [getsentry/sentry-laravel#216]
I'm having an issue with any version above 0.11.0 where I'm suddenly getting a bunch of ErrorExceptions logged to Sentry similar to 

fopen(storage/framework/cache/data/c7/47/c7477d641690dffc017a5ec645a45b8f5b274907): failed to open stream: No such file or director

as well as:

filesize(): stat failed for storage/framework/cache/data/a8/f8/a8f8f1dee46f6fafdd752d10a3f666b7e4f9368c

Any version 0.11.0 or lower doesn't have this issue, additionally nothing else has changed in the code / on the server.  I've tried every variation of config:clear and cache:clear I can think of.

**Comment by stayallive** [comment]
@wtbloom I assume you got it fixed. Looks like it was a permission error on your cache directory Sentry surfaced. This does not look like an issue with Sentry but Sentry reporting about an issue in your environment.

**Comment by vsaraswat95** [comment]
@wtbloom
If you dont mind can you please share
What was causing this error ?
I am also getting lot of these errors in sentry
