### ISSUE TITLE
The option "user_context" does not exist

### ISSUE THREAD

**Issue by MattRogowski** [getsentry/sentry-laravel#218]
Hi,

I've seen other issues about this, and they say to remove `'user_context' => false,` from `config/sentry.php`, but mine doesn't have this, it's just the default config after publishing the package.

The only reference I can find in actual code to `user_context` in the entire codebase is inside `vendor/monolog/monolog/src/Monolog/Handler/RavenHandler.php`

I'm not sure what I need to do to fix this?

**Comment by stayallive** [comment]
Are you using the `RavenHandler`? It is just part of monolog so if you are not actively doing something it being there should not matter.

Have you tried clearing your config cache (`php artisan cache:clear`)?

Also make sure you did not accidentally overwritten your `config/sentry.php` with an older version and `user_context` now is there. Or you are setting `user_context` in your own code somewhere.

**Comment by MattRogowski** [comment]
I'm not sure what handler it would be using other than the default, my config file is just this:

```<?php

return array(
    'dsn' => env('SENTRY_LARAVEL_DSN'),

    // capture release as git sha
    // 'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),

    'breadcrumbs' => [

        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => true,

    ],
);
```

I can't run `php artisan cache:clear` as it outputs the same error:

`In OptionsResolver.php line 747:
The option "user_context" does not exist.`

The only code matches in the project are inside the monolog package itself:

![image](https://user-images.githubusercontent.com/545339/54765212-02f01200-4bf1-11e9-9273-901585fc6fe7.png)

**Comment by stayallive** [comment]
Try and remove the config cache file yourself (context: https://github.com/getsentry/sentry-laravel/issues/185#issuecomment-468732050).

Run `rm bootstrap/cache/config.php` from your project root.

After that it should be fixed.

Those files are "just" part of the Monolog package and are not even touching the `user_context` configuration just the method, and that is not what's being complained about.

**Comment by MattRogowski** [comment]
Ah, that fixed it, thank you. I was trying to find where the cached config actually was and missed your comment in the other ticket.

Thank you for helping so quickly.

**Comment by stayallive** [comment]
No problem! Glad it's resolved.
