### ISSUE TITLE
Error in documentation for user context middleware

### ISSUE THREAD

**Issue by teeli** [getsentry/sentry-laravel#219]
Not sure where to report documentation issues, but this is regarding https://docs.sentry.io/platforms/php/laravel/#user-context

Looks like there's an error. At least with Laravel 5.5, `configureScope` function is not working like this:

```php
Sentry\configureScope(...)
```

You need to add a backslash in front of Sentry, like this:

```php
\Sentry\configureScope(...)
```

Minor detail, but it took me a while to figure it out.

**Comment by stayallive** [comment]
Jep, good point. Looks like we forgot the include for it. Sorry about that!

A PR was created to fix that 👍 getsentry/sentry-docs#863
