### ISSUE TITLE
Log artisan command, arguments and options

### ISSUE THREAD

**Issue by cweiske** [getsentry/sentry-laravel#223]
When an artisan command line call crashes, I currently do not see the command and its arguments and options in Sentry.

It would be nice if those information would be passed to sentry.

(This is with sentry-laravel 0.9.0, but I did not find anything in the changelog that indicates this feature is implemented in the current version.)

**Comment by stayallive** [comment]
@cweiske, sorry for the late response, however, `1.x` does add a tag to indicate the command that is running and I have a PR open that should add the command input as a breadcrumb (#232). 

You could re-implement that yourself by listening to the `CommandStarting` event and pushing a breacrumb like #232 does (although you need to adapt that example to work for the `1.x` PHP SDK) or upgrade to Sentry Laravel `>=1.0` which wil eventually include #232.

**Comment by cweiske** [comment]
Thank you!
