### ISSUE TITLE
Custom options in `sentry.php` throws errors

### ISSUE THREAD

**Issue by antoniopaisfernandes** [getsentry/sentry-laravel#225]
Hi there,

I'm trying to make a concept with Sentry both using PHP's version and Javascript's.

Using Laravel, I would like to have a configuration option so that, in blade, the javascript script tag would only be rendered if the configuration was set.

sentry.php config:
```php
return [
    'dsn' => env('SENTRY_DSN'),

    // capture release as git sha
    'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),

    'breadcrumbs' => [
        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => true,
    ],

    // use the correct environment context data
    'environment' => env('APP_ENV', 'production'),

    // Javascript
    'javascript' => env('SENTRY_JAVASCRIPT_ENABLE'),
];
```

This way, I would have a partial:
```
@if(config('sentry.javascript'))
    // render JS sentry
@endif
```

but I cannot:
```
In OptionsResolver.php line 747:

  The option "javascript" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "context_lines", "defa
  ult_integrations", "dsn", "enable_compression", "environment", "error_types", "excluded_exceptions", "http_proxy", "in_app_exclude", "integrations", "logger", "max_bre
  adcrumbs", "max_value_length", "prefixes", "project_root", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags".
```

Is there any way I can achieve that without having a new config file?

Best regards

**Comment by stayallive** [comment]
Currently there is no way 😞 

Our options are very strict and we have no good way to filter out custom user options. I'm trying to see if we can get it to work by whitelisting option keys so user configuration can still live in the same file. But for now you'll need to define your own options in another config file (`config('app.sentry.javascript')`) for example).

**Comment by antoniopaisfernandes** [comment]
Thank you for the quick reply.

Will do.

**Comment by stayallive** [comment]
I have discussed this internally and checked to see if there was anything we can/should do to allow custom options added to the `sentry.php` config file but have decided not too to prevent needing to maintain whitelist or any other complex logic to only pass on supported options.

`sentry.php` config file options are all passed directly to the Sentry SDK unless they are Laravel integration specific options (than we strip them out).

If you need custom options for your own integrations you can add those options to your `app.php` config or maybe even better to your `services.php` file and add a `sentry` key there.
