### ISSUE TITLE
Exceptions doesn't reach Sentry

### ISSUE THREAD

**Issue by jurios** [getsentry/sentry-laravel#229]
Hello there,

I am integrating Sentry in a Laravel project which I am working on. When I throw an exception in a local environment, everything is working as expected. However, the exceptions doesn't reach Sentry (sentry.io) when I throw the same one in production.

Looking to the logs, I can see the exception handler calling to the sentry library. Following the instructions in #137 I added some logs messages in the exception handler (where I call to Sentry) and I can see in the logs the ID returned by `captureException($exception);`. But, as I said, anything arrives to Sentry.

Sadly, I don't know where start to debug as I can't see anything unexpected in the logs so I am not sure if it is a php / server configuration problem, composer libraries problem (may I have forgotten upload some `vendor/` files in the deployment process ?) or Sentry / authentication problem.

Any help would be appreciated,

Cheers.

**Comment by ste93cry** [comment]
> I can see in the logs the ID returned by `captureException($exception);`

Since the ID is generated client-side (and imho this is broken design, but it's out of topic for this discussion), saying that getting it back means that the event has been sent is unfortunately wrong in most of the cases (it depends really on the transport used and on a few other things like for example if the event was skipped due to the `before_send` option)

Since we already had a few cases like this one, please check that in your `php.ini` that the path of the `curl.cainfo` setting is correctly pointing to a CA bundle file. No error is thrown in this case (not our fault since we don't implement the HTTP client ourselves), so everything seems to work well when it isn't

**Comment by jurios** [comment]
Hi @ste93cry ,

Thanks for your answer. I checked `curl.cainfo` and I realized that it has empty value in the configuration. The thing is `curl.cainfo` is empty in my local environment too but in this case it is working. Is this parameter mandatory in order to let Sentry work?

Thanks.

**Comment by ste93cry** [comment]
No it's not, it depends on whether the server you're sending events to is protected by SSL or not. If it is and the HTTP client is configured to check the certificate, not having such option configured means that cURL cannot find the list of root certificates to validate the one used by the server and will refuse to connect. Anyway having such `php.ini` option configured is not a bad idea in general, so I strongly suggest to set it. Let me know if this solves the issue, otherwise we have to dive deep to understand why it doesn't work

**Comment by jurios** [comment]
Hi @ste93cry ,

when you say `the server you're sending events to is protected by SSL or not`, do you mean Sentry? In this case, is Sentry protected by SSL? (I guess it is, right?) . Then you say `and the HTTP client is configured to check the certificate`. How can I check  that configuration? (I am using the default http client used by Sentry as I installed the Sentry SDK).

Thanks for your suggestion. I take it into account. 😃 

Unfortunately, in this case I am not the owner of the production server. Thus, I can't change the `php.ini` easily. IMHO, as I am using in both environments the same HTTP client, same http client configuration (the default one) and same `curl.cainfo` configuration value but, is only working in local, looks like this is not the problem (not 100% sure, of course). Do you agree with me?

Thanks.

**Comment by ste93cry** [comment]
>when you say the server you're sending events to is protected by SSL or not, do you mean Sentry? In this case, is Sentry protected by SSL? (I guess it is, right?)

[Sentry.io](https://sentry.io) is protected by SSL, if you host it yourself (on-premise) it may not, this is what I meant

>Then you say and the HTTP client is configured to check the certificate. How can I check that configuration?

This is really a configuration of cURL and not of our library. If you didn't set the HTTP client explicitly through the `ClientBuilder`, then SSL check should be enabled by default

>Unfortunately, in this case I am not the owner of the production server. Thus, I can't change the php.ini easily

There is no really need to update the `php.ini` (even if imho it's the best way to do it). You can just use `ini_set` or pass the absolute path to your own instance of the HTTP client that you will then set using the client builder. Something like this (I coded it blindly, I'm not sure it works) should do what I'm saying:

```php
use Http\Client\Curl\Client as HttpCurlClient;
use Sentry\ClientBuilder;
use Sentry\State\Hub;

$client = ClientBuilder::create(['dsn' => '...'])
    ->setHttpClient(new HttpCurlClient(null, null, ['CURLOPT_CAINFO' => '/path/to/ca-bundle.crt']))
    ->getClient();

Hub::getCurrent()->bindClient($client);
```

>[...] looks like this is not the problem (not 100% sure, of course). Do you agree with me?

It seems so, I would just try to be sure to set the option as explained above (if coding requires too much effort then trying to set it with `ini_set`). At least we can exclude that reason with a reasonable safety. If it doesn't work then I would not know what's happening and you will have to dig deeper in your code and in the library by debugging yourself

**Comment by jurios** [comment]
Hi there,

ok, I'll take it a look. In case I find out the problem I'll leave a comment here. Meanwhile, I think we can close the issue.

Thank you!

**Comment by the-great-tao** [comment]
Hello,

My local and production environments are on the same host with these configuration:
- PHP 7.4.3
- Laravel 5.8.18
- Composer sentry/sentry (2.1.0)
- Composer sentry/sentry-laravel (1.0.2)

I'm facing this issue too. My local environment works really well with sentry.io but exceptions on production environment does not.

Both use same codes, same sentry's configuration, only these differences in .env:

```
< APP_ENV=production
---
> APP_ENV=local
4,5c4,5
< APP_DEBUG=false
< APP_URL=https://prod.***hidden***.com
---
> APP_DEBUG=true
> APP_URL=https://dev.***hidden***.com
```

When I run sentry:test command, it works and shows exception on sentry.io. Other application exceptions are not capture by sentry.

Please help, thank you!

**Comment by the-great-tao** [comment]
Hello,

My local and production environments are on the same host with these configuration:
- PHP 7.4.3
- Laravel 5.8.18
- Composer sentry/sentry (2.1.0)
- Composer sentry/sentry-laravel (1.0.2)

I'm facing this issue too. My local environment works really well with sentry.io but exceptions on production environment does not.

Both use same codes, same sentry's configuration, only these differences in .env:

```
2c2
< APP_ENV=production
---
> APP_ENV=local
4,5c4,5
< APP_DEBUG=false
< APP_URL=https://prod.***hidden***.com
---
> APP_DEBUG=true
> APP_URL=https://dev.***hidden***.com
```

When I run sentry:test command, it works and shows exception on sentry.io. Other application exceptions are not capture by sentry.

Please help, thank you!

**Comment by the-great-tao** [comment]
OK I found the problem: I'm using Laravel Nova, it overrides app/Exception/Handler with its own NovaExceptionHandler. This blocks exceptions flying to Sentry.

Thanks!
