### ISSUE TITLE
Exceptions not showing up in self-hosted sentry whilst on production environment

### ISSUE THREAD

**Issue by dblencowe** [getsentry/sentry-laravel#23]
I'm 100% sure this is something to do with this server but I've been running around all morning trying to figure out what it could be.

I'm running a laravel 5.2 app which is meant to send errors to a Sentry instance I host. It works in the development environment (currently using valet) and JS reporting works in both environments.

In the production environment exceptions aren't shown in Sentry. There is also no mention of Sentry in the Exception stacktrace (although I'm not sure there is meant to be).

The production server is running PHP7 through [Serverpilot](http://serverpilot.io).

Currently loaded PHP modules:

> php7.0-sp -m
> [PHP Modules]
> bcmath
> bz2
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> gettext
> gmp
> hash
> iconv
> imap
> intl
> json
> ldap
> libxml
> mbstring
> mcrypt
> mysqli
> mysqlnd
> odbc
> openssl
> pcntl
> pcre
> PDO
> pdo_dblib
> pdo_mysql
> PDO_ODBC
> pdo_pgsql
> pdo_sqlite
> pgsql
> Phar
> posix
> readline
> Reflection
> session
> shmop
> SimpleXML
> snmp
> soap
> sockets
> SPL
> sqlite3
> standard
> tidy
> tokenizer
> xml
> xmlreader
> xmlrpc
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib
> 
> [Zend Modules]
> Zend OPcache

Composer.json:
> {
>     "name": "laravel/laravel",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "type": "project",
>     "require": {
>         "php": ">=5.5.9",
>         "laravel/framework": "5.2.*",
>         "laravel/cashier": "^6.0",
>         "sentry/sentry-laravel": "^0.3.0",
>         "guzzlehttp/guzzle": "^6.2"
>     },
>     "require-dev": {
>         "fzaninotto/faker": "~1.4",
>         "mockery/mockery": "0.9.*",
>         "phpunit/phpunit": "~4.0",
>         "symfony/css-selector": "2.8.*|3.0.*",
>         "symfony/dom-crawler": "2.8.*|3.0.*"
>     },
>     "autoload": {
>         "classmap": [
>             "database"
>         ],
>         "psr-4": {
>             "App\\": "app/"
>         }
>     },
>     "autoload-dev": {
>         "classmap": [
>             "tests/TestCase.php"
>         ]
>     },
>     "scripts": {
>         "post-root-package-install": [
>             "php -r \"copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "php artisan key:generate"
>         ],
>         "post-install-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postInstall",
>             "php artisan optimize"
>         ],
>         "post-update-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postUpdate",
>             "php artisan optimize"
>         ]
>     },
>     "config": {
>         "preferred-install": "dist"
>     }
> }

composer7.0-sp show | grep "sentry" output

> sentry/sentry                         0.22.0  A PHP client for Sentry (http://getsentry.com)
> sentry/sentry-laravel                 0.3.0   Laravel integration for Sentry (http://getsentry.com)

**Comment by stayallive** [comment]
You could use `php artisan tinker` on the server to check if `app()->bound('sentry');` to see if Sentry is loaded and try to send a message from there using `app('sentry')->captureException(new Exception('Hello from artisan tinker!'));`, if still no message is sent I would try to figure out if the DSN is even loaded from the `.env` file or your DSN is correct (empty or `null` DSN means Sentry won't be able to sent any events).

**Comment by dblencowe** [comment]
Thanks @stayallive, I've never seen the Tinker command before. Sentry was loaded, but after running some tests it seems that my server doesn't seem to be able to send the events over HTTPS, which is weird as HTTPS works fine for the JS libs.

I'm guessing it's a missing SSL library somewhere which isn't a Sentry problem. I'll close the issue but update it if I find out what lib is missing.
