### ISSUE TITLE
ErrorExceptions are sent avoiding handler.

### ISSUE THREAD

**Issue by stasgar** [getsentry/sentry-laravel#234]
Hello. I've set my error handler to send sentry reports with additional checks:
```php
if ({my additional checks} && app()->bound('sentry') && $this->shouldReport($exception)) {
    app('sentry')->captureException($exception);
}
```

But the problem is that `ErrorException` exceptions are still being sent to my cdn and i dont want them to. Is that intentional behaviour or am i missing something? Thanks.

**Comment by stayallive** [comment]
Hey @stasgar an `ErrorException` indicates a "error" like a notice or warning.

These do not go through the error handler but are captured directly by Sentry.

You can configure this behaviour using the `error_types` configuration option: https://docs.sentry.io/platforms/php/#error_types

**Comment by stasgar** [comment]
Hmm. Okay, thanks for the explanation :+1:
