### ISSUE TITLE
[sentry] Could not discover DSN! Check your config or .env file

### ISSUE THREAD

**Issue by JeffBeltran** [getsentry/sentry-laravel#235]
Hello, i'm trying to figure out why i can't get my dev server to post to sentry. when i try the `php artisan sentry:test` command i get `[sentry] Could not discover DSN! Check your config or .env file`

This works fine locally, but when im on the server i get the above. I even tried putting my DSN directly into the config file (rule out env file issues) but that didn't make a difference. Do you have any other suggestions on why this could be occurring?

Details: 
Laravel 5.8
sentry-laravel 1.0.2

If you need more info please let me know.

Thanks

**Comment by JeffBeltran** [comment]
in the process of debugging this it started to work... i really have no idea what changed but i'll close this to remove the noise.

**Comment by stayallive** [comment]
Take a look at config caching, this was most likely the cause :)

**Comment by JeffBeltran** [comment]
yeah that was the first thing i did but didn't seem to fix it... oh well working as intended. Thanks for the reply though

**Comment by Vinayak-k160** [comment]
> Take a look at config caching, this was most likely the cause :)
> 
> Glad you got it working though!

👍👍
Most of the times I forgot
