### ISSUE TITLE
The option "in_app_exclude" does not exist

### ISSUE THREAD

**Issue by Deifinger** [getsentry/sentry-laravel#237]
I've catch exception which was mantioned in title. Version 1.0.2

![35196cb342](https://user-images.githubusercontent.com/6638145/57366986-d0927800-7190-11e9-8b8c-230077d4fc71.jpg)

Issue happens in OptionsResolver, because 'in_app_exclude' option was passed into ClientBuilder in ServiceProvider

![2446c2796b](https://user-images.githubusercontent.com/6638145/57367426-a097a480-7191-11e9-994e-20fd0453462e.jpg)

But you don't have it in default options in Options.php

![0059f61d5f](https://user-images.githubusercontent.com/6638145/57367654-16037500-7192-11e9-939a-3b6a1965e867.jpg)

**Comment by stayallive** [comment]
You might be on an older or even beta version of our sdk.

Can you make sure you only require `sentry/sentry-laravel` with version `^1.0` or similair constraint? No other Sentry packages should be required.

If that doesn't work it would help if you could paste your composer.json file so we can investigate!

**Comment by Deifinger** [comment]
I have reinstalled my packages and have next version of dependencies:
  - Installing sentry/sentry (2.0.0-beta1)
  - Installing sentry/sdk (2.0.1)
  - Installing sentry/sentry-laravel (1.0.2): Loading from cache

My `composer.json`:
   ```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "ext-json": "^1.6",
        "anhskohbo/no-captcha": "^3.0",
        "doctrine/dbal": "^2.9",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "hamburgscleanest/laravel-guzzle-throttle": "^3.1",
        "intervention/image": "^2.4",
        "jgrossi/corcel": "^2.7",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "mikey179/vfsstream": "^1.6",
        "orangehill/iseed": "^2.6",
        "php-http/curl-client": "^1.7",
        "sentry/sentry-laravel": "^1.0",
        "spatie/laravel-image-optimizer": "^1.4",
        "watson/sitemap": "^2.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0",
        "roave/security-advisories": "dev-master"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by stayallive** [comment]
Hey @Deifinger it is very weird it installs `2.0.0-beta1` of `sentry/sentry`.

Could you try to run `composer update` to see if you get `2.0.1` of `sentry/sentry` (which is at the time of writing the latest version)? (if you have changed your `composer.json` you should first run `composer install` to have composer re-read your `composer.json` file).

---

If I copy your `composer.json` in an empty directory and run `composer install` I get the correct versions installed:
```
  - Installing sentry/sentry (2.0.1)
  - Installing sentry/sdk (2.0.2)
  - Installing sentry/sentry-laravel (1.0.2)
```

**Comment by Deifinger** [comment]
Hey @stayallive 
Update was fixed the problem. Seems like I had some troubles in composer.lock or I updated your package without dependencies. Thanks a lot

**Comment by stayallive** [comment]
Great to hear you got it fixed! 👍
