### ISSUE TITLE
Missing errors since update

### ISSUE THREAD

**Issue by Nuranto** [getsentry/sentry-laravel#242]
I recently updated to Laravel 5.8, and sentry-laravel (from ^0.10.0 to ^1.0).
Since then, Sentry is missing many errors where I get a blank page with "Something went wrong" with a log in laravel.log, but nothing on sentry.

Am I missing something ?

**Comment by stayallive** [comment]
Do any errors show up in Sentry or is Sentry not sending anything?

In case only some are missing, could you share your `composer.json` & `config/sentry.php` (with the DSN removed) and a example of an error that is not being caught so we can try to reproduce.

**Comment by Nuranto** [comment]
Ok, I just figured out my Exception handler has been reinitialized. I have to find why, but that's not an issue of sentry after all !
Thanks for you help @stayallive

**Comment by stayallive** [comment]
@Nuranto ah okay great!

If you do find an issue after all please don't hesitate to re-open or open a new issue 😄
