### ISSUE TITLE
ErrorException appears with level info

### ISSUE THREAD

**Issue by smknstd** [getsentry/sentry-laravel#245]
Can you help me understand why a "notice" ends up as an ErrorException with level "info" in my sentry dashboard ?

![sentry-notice](https://user-images.githubusercontent.com/2412608/60077086-6d9d7600-9729-11e9-8884-c56f0329a2e2.png)

I asked for a minimum logging level in my `config/logging.php` :

```
        'sentry' => [
            'driver' => 'sentry',
            'level' => 'warning'
        ],
```

versions:
sentry/sdk                            2.0.3
sentry/sentry                         2.1.0
sentry/sentry-laravel                 1.0.2

**Comment by stayallive** [comment]
Hey @smknstd, I can help understand :)

A `ErrorException` is create by the Sentry SDK when an PHP error is generated (errors are different from Exceptions).

When you register our SDK we inject a few handlers to catch any errors that occur and also any uncaught/fatal Exceptions.

You added Sentry as a logging driver, however this will not prevent the SDK for listening for errors and uncaught/fatal Exceptions.

If you want to configure the which or if errors are caught you can set the following config key in your `sentry.php`:

```php
    'error_types' => E_ALL ^ E_NOTICE,
```

As an example the above excludes only errors with the level notice. You can see all types [here](https://www.php.net/manual/en/errorfunc.constants.php).

**Comment by smknstd** [comment]
Thanks a lot for your explanation, 100% clear! 

It might be usefull to update documentation with config key `error_types` :)

**Comment by stayallive** [comment]
@smknstd where would you have expected to see it?

It's here: https://docs.sentry.io/platforms/php/#error_types

**Comment by smknstd** [comment]
@stayallive ok

It might be usefull to mention that you can add those php options directly in `sentry.php` in https://docs.sentry.io/platforms/php/laravel

What do you think ?

**Comment by beNjiox** [comment]
Hey,

Out of curiosity, is there any way to setup Sentry so that it tracks those errors as something else than with info level ? I believe previous versions of the SDK allowed us to do that (with a configurable map), but I can't find how to do that now.

Thanks!
