### ISSUE TITLE
Sending exception from tinker

### ISSUE THREAD

**Issue by nanaya** [getsentry/sentry-laravel#250]
Calling `app('sentry')->captureException(new \Exception('test'));` from tinker console doesn't seem to do anything. What am I missing? Exact same line works when called from controller.

1. start tinker (`php artisan tinker`)
2. create a test report `app('sentry')->captureException(new \Exception('test'));`
3. it returns event id
4. check sentry
5. no report

As from controller

1. add to one of the controller action
2. access the page
3. check sentry
4. the test report is there

PHP: 7.2.18
Laravel: 5.5.34
sentry-laravel: 1.0.2

(For the context, I've been trying to upgrade to new SDK but I needed to create a separate client for some functionalities and I've been trying to figure out how to do it with new SDK as the documentation barely have any mention of using client separate from the global one)

**Comment by nanaya** [comment]
So it looks like it's using async http which never triggers for tinker...? Is there no way to try things out?

**Comment by SCIF** [comment]
Hi @nanaya , 

Why do you use Sentry directly? It works for me to use hinting of `ExceptionHandler`, rather than Sentry itself.

**Comment by nanaya** [comment]
One is to report unexpected data followed by ignoring it so client doesn't see any errors (thus not using global exception handler), the other is to report errors to different project because it's handled by different people.

**Comment by SCIF** [comment]
@nanaya , I cannot see any issues of using `ExceptionHandler::report()`. It doesn't render an exception but log it to files and/or to Sentry.

**Comment by SCIF** [comment]
It's up to you but I really like it's behaviour — in dev env you don't need to report Sentry and just show exception handling page and handler works great for that.

**Comment by nanaya** [comment]
I'm not sure what you're suggesting here and how it's related to the original issue. Or are you saying I shouldn't bother trying out using sentry (figure out how the tag, etc works) from tinker manually?

**Comment by SCIF** [comment]
Just I think hinting of `Hub` to services is worse than using `ExceptionHandler`.
However the issue is reproduced by me and looks weird for me.

**Comment by stayallive** [comment]
Unfortunately there is a reasons this is happening. I won;t go into great detail since it's a really long story and there is much work being done in the base sdk to resolve this.

But events are only sent once the request/execution finishes. That's why events are not sent immediately.

If you want to "flush" the queue you can force it by calling `\Sentry\Laravel\Integration::flushEvents();` (see also #228 which is related).

**Comment by nanaya** [comment]
Thanks, it's fine as long there's a way to actually send the events.
