### ISSUE TITLE
Missing Issues

### ISSUE THREAD

**Issue by Nuranto** [getsentry/sentry-laravel#252]
Hello,

Sometimes, in production (so without xdebug... since I first thought it was related to #244), I have errors that does'nt show in sentry.
However, I have my trace in laravel.log...

I don't know how to reproduce easily... But even if I refresh the error page multiple times, I have a different sentry error ID, but nothing on my sentry's backoffice.

I would say it is 10%-ish of the errors....

Here is an error number if it can help : 7c9b5648f71a478eb6bece088b4f1e18

I don't think the error is relevant here, but here it is just in case : 
<pre>
[2019-07-07 07:40:42] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'toto' (SQL: select * from `tata` left join `toto` on .... left join `toto` on.... {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'toto' ... at /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'toto' at /opt/****/shared/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'toto' at /opt/****/shared/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)
[stacktrace]
#0 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select`...', Array, Object(Closure))
#1 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select ...', Array, Object(Closure))
#2 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2124): Illuminate\\Database\\Connection->select('select...', Array, true)
#3 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2112): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2598): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2113): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(505): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /opt/****/releases/1.0.0-RC22/app/Http/Controllers/....php(186): Illuminate\\Database\\Eloquent\\Builder->get()
#9 [internal function]: App\\Http\\Controllers\\...->index(Object(Illuminate\\Http\\Request), 'chat-et-chaton....')
#10 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#12 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\...), 'index')
#13 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#14 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#15 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /opt/****/shared/vendor/spatie/laravel-cookie-consent/src/CookieConsentMiddleware.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Spatie\\CookieConsent\\CookieConsentMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /opt/****/shared/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationViewPath->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /opt/****/shared/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationRedirectFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /opt/****/shared/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LocaleSessionRedirect->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /opt/****/releases/1.0.0-RC22/app/Http/Middleware/...php(99): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\...->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /opt/****/shared/vendor/jacobbennett/laravel-http2serverpush/src/Middleware/AddHttp2ServerPush.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): JacobBennett\\Http2ServerPush\\Middleware\\AddHttp2ServerPush->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /opt/****/shared/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#55 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#56 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#57 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#58 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#59 /opt/****/shared/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /opt/****/releases/1.0.0-RC22/app/Http/Middleware/PjaxMiddleware.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\PjaxMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /opt/****/shared/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#78 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#81 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#82 /opt/****/shared/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#83 /opt/****/releases/1.0.0-RC22/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#84 {main}

</pre>

PHP 7.3.6
Laravel v5.8.27 
sentry/sdk                             2.0.3   
sentry/sentry                          2.1.1    
sentry/sentry-laravel                  1.0.2

**Comment by stayallive** [comment]
@Nuranto do you have `sql_bindings` enabled in your settings and are doing a few queries in that specific request leading up to the error? 

It is possible the request is getting too big for Sentry (assuming you are using sentry.io) and is being dropped (unfortunately silently otherwise we might get stuck in a loop).

There is currently an issue in the SDK with gzip not being enabled correctly causing some requests to fail. We are looking into that trying to improve the situation.

For now you could try and disable the `sql_binding` which should drop a considerable amount of data of the request. We're still trying to figure out the best way to make sure events never exceed the limit.

**Comment by Nuranto** [comment]
@stayallive Yes, I had sql_bindings ON. Just disabled it. I will update if I still got the issue despite that change.

Thanks a lot.

**Comment by Nuranto** [comment]
Hello @stayallive 

Just got the issue with `sql_bindings` to false. 

The error was not DB-related : ``` Route [contact] not defined.```

Error ID: 53be6fc19d6a4e5b8d2bab304727166b  (sentry.io)

**Comment by stayallive** [comment]
Sorry but now I am a bit confused... the error was not db related but without the bindings disabled it did show up in Sentry now?

**Comment by Nuranto** [comment]
Hello. No, some error still no show up in sentry. Got another one yesterday evening.
I have `'sql_bindings' => false,`.

**Comment by Nuranto** [comment]
Just happened again : 

```
[2019-08-13 11:15:33] production.ERROR: Call to a member function getDisplayName() on null
```

Error displayed to the user : 5b3f8ee7df1a4673984da038c1fa333a

But no alert, and bug not found on sentry.io 

My sentry conf is still the same : 
```
<?php

return array(
    'dsn' => env('SENTRY_LARAVEL_DSN'),

    // capture release as git sha
    //'release' => trim(exec('git log --pretty="%h" -n1 HEAD')),

    // Capture bindings on SQL queries
    'breadcrumbs' => [

        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => false,

    ],

);
```

**Comment by stayallive** [comment]
We have done a lot in the past few weeks to hopefully fix this (in particular we now correctly compress requests so they are a lot smaller).

I would love to hear from you if `1.3` of the Laravel integration and `2.2` of the base SDK (automatically installed with the Laravel integration) works better now!

**Comment by patrickschmidt** [comment]
Hi,

I experience the same issue.
This happens if we use the integration via Log Channels as described here: https://docs.sentry.io/platforms/php/laravel/#log-channels

If we integrate sentry by modifying the \App\Exceptions\Handler as described here:
https://docs.sentry.io/platforms/php/laravel/#laravel-5x--6x

everything is sent to sentry.

Maybe this helps debugging.
Cheers,
Patrick

**Comment by stayallive** [comment]
@patrickschmidt The log channel issue might be caused by the `level` configuration option defaulting to something higher causing some events to not be sent, not really sure, feel free to open up a issue if you feel like this is a bug with examples of issues sent/not sent when using log channels vs. the exception handler.

This is a pretty old issue and I have not heard back from anyone here that the problems are still there using the latest version of the SDK. I'm going to close this issue for now. Feel free to open up a new issue of the problem persists so we can restart the investigation.

**Comment by Nuranto** [comment]
just for info, i did not had this issue for a long time now. And I still produce stupid errors from time to time. So I think it is solved indeed :)

**Comment by stayallive** [comment]
Happy to hear that @Nuranto and thanks for reporting back 👍 

As mentioned, please do open up a new issue if there is any smell of a regression or missed issues (or any other unexpected behaviour)!
