### ISSUE TITLE
HTTP/PSR Exception

### ISSUE THREAD

**Issue by CameronSumpter** [getsentry/sentry-laravel#255]
I recently updated from 0.11.0 to 1.1.0, going from Lumen 5.8.0 to 5.8.11 at the same time. Now, whenever Sentry is registered, the following two errors appear for all API calls:

```
Fatal error: Declaration of Http\Client\Common\PluginClient::sendRequest(Psr\Http\Message\RequestInterface $request) must be compatible with Http\Client\HttpClient::sendRequest(Psr\Http\Message\RequestInterface $request): Psr\Http\Message\ResponseInterface in ...\vendor\php-http\client-common\src\PluginClient.php on line 20
```

```
Fatal error: Uncaught TypeError: Argument 2 passed to Sentry\Transport\HttpTransport::__construct() must implement interface Http\Client\HttpAsyncClient, instance of Http\Client\Common\PluginClient given, called in ...\vendor\sentry\sentry\src\ClientBuilder.php on line 342 and defined in ...\vendor\sentry\sentry\src\Transport\HttpTransport.php on line 48
```

Other related packages include:
```
"guzzlehttp/psr7": "^1.6"
"php-http/curl-client": "^2.0"
"php-http/guzzle6-adapter": "^2.0.1"
"php-http/httplug": "2.0.0 as 1.1.0"
```

This happens for me both in a development environment (Windows / PHP 7.3.5) and in staging (Ubuntu / PHP 7.3.7). I’ve looked through the call stack and have been unable to identify anything in my project or configuration that would be causing this.

**Comment by stayallive** [comment]
@CameronSumpter can you explain a bit about having httplug `2.0.0 as 1.1.0` that sounds like the culprit here to be honest...

**Comment by CameronSumpter** [comment]
It was! I had tried different dependency versions before opening the issue, and that had been in there to satisfy `"mailgun/mailgun-php": "^2.8.1"`. I had not been aware that they have a 3.0.0-beta1 available with newer dependencies that don't conflict with the newer Sentry package; updating it too seems to have sorted it all out. Thanks, @stayallive!

**Comment by stayallive** [comment]
Sentry should also work with httplug 1.0 (but the curl-client & guzzle adapter must also be the 1.x variant then) although mixed results are had with that :)

Glad it's resolved!
