### ISSUE TITLE
Sentry laravel 5.5 stopped reporting

### ISSUE THREAD

**Issue by ramimohammad** [getsentry/sentry-laravel#256]
Hi all ,

I need help in this matter please ,

Sentry laravel 5.5 stopped reporting after changing the dsn in .env file , also after rollback to the previous dsn not reporting at all. I've followed these instructions https://docs.sentry.io/platforms/php/laravel/?_ga=2.92211865.264668699.1563990557-913758905.1562777069 , what's the problem ? 

Best regards

**Comment by stayallive** [comment]
The only thing you changed is the DSN? Nothing else? No version changes?

How did you set the DSN in your config? And how does your `config/sentry.php` look?

**Comment by ramimohammad** [comment]
# resolved by clearing cache : 
sudo php artisan config:clear
sudo php artisan cache:clear
sudo php artisan route:clear

**Comment by stayallive** [comment]
Okay I did not even think about it. But yes, always try `php artisan config:clear` after changing your `.env` file. Glad you got is solved!

**Comment by ramimohammad** [comment]
Thanks a lot :)

‫في الثلاثاء، 30 يوليو 2019 في 10:43 م تمت كتابة ما يلي بواسطة ‪Alex
Bouma‬‏ <‪notifications@github.com‬‏>:‬
