### ISSUE TITLE
Provide proper release notes / upgrade guide

### ISSUE THREAD

**Issue by hackel** [getsentry/sentry-laravel#260]
Trying to upgrade to 1.1 from the old 0.11 is a nightmare because you don't provide any documentation.  I finally found #185 which contains a link to this [upgrade guide](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md) for the parent sentry-php library which, while helpful, is still woefully inadequate.

Specifically, the following options I was using just say "Removed" in the upgrade document with no information about their replacements:

    user_context
    trust_x_forwarded_proto
    install_default_breadcrumb_handlers

Apparently `user_context` is now called `send_default_pii`, but I still have no idea about the others.  Has the default behaviour changed?  Who knows!  There should be a single place to see all of this information when it is such a major upgrade like this.  It's very frustrating to say the least.  Especially because `user_context` was previously in the *default* config!

Yes, I can hunt through the code and revision history of each project to figure all this out for myself, but come on, help us out here...

**Comment by hackel** [comment]
I extracted all the default options in v1.1 in case this is helpful to anyone:
```php
'attach_stacktrace'       => false,
'before_breadcrumb'       => function (Sentry\Breadcrumb $breadcrumb): ?Sentry\Breadcrumb {
    return $breadcrumb;
},
'before_send'             => function (Sentry\Event $event): ?Sentry\Event {
    return $event;
},
'breadcrumbs'             => [
    'sql_bindings' => false,
],
'capture_silenced_errors' => false,
'class_serializers'       => [],
'context_lines'           => 5,
'default_integrations'    => true,
'dsn'                     => $_SERVER['SENTRY_DSN'] ?? null,
'enable_compression'      => true,
'environment'             => app()->environment(),
'error_types'             => E_ALL,
'excluded_exceptions'     => [],
'http_proxy'              => null,
'in_app_exclude'          => [base_path('vendor')],
'integrations'            => [new Sentry\Laravel\Integration],
'logger'                  => 'php',
'max_breadcrumbs'         => 100,
'max_request_body_size'   => 'medium',
'max_value_length'        => 1024,
'prefixes'                => [base_path()],
'project_root'            => base_path(),
'release'                 => $_SERVER['SENTRY_RELEASE'] ?? null,
'sample_rate'             => 1,
'send_attempts'           => 3,
'send_default_pii'        => false,
'server_name'             => gethostname(),
'tags'                    => [],
```

**Comment by reenekt** [comment]
`user_context` was renamed to `send_default_pii` in this [commit](https://github.com/getsentry/sentry-laravel/commit/8fac7c263cc1ba6a3b44d3db56c34f635ecbbefc#diff-8d63ad0f7f7c0c833ab13b1f198ad664c79228277bf38eeab1b2782448542512L60-R61)

`trust_x_forwarded_proto` and `install_default_breadcrumb_handlers` were removed.  
`trust_x_forwarded_proto` removed in https://github.com/getsentry/sentry-php/pull/599 (see also [this issue](https://github.com/getsentry/sentry-php/pull/592#issuecomment-386541303)).  
I don't know exactly why `install_default_breadcrumb_handlers` was deleted, but I suppose [this issue](https://github.com/getsentry/sentry-php/issues/321) maybe the reason.

**Comment by stayallive** [comment]
Here you can find the default (and below it all the options and their allowed values) for the 3.3 version of the PHP SDK which the 2.x release of the Laravel SDK uses:

https://github.com/getsentry/sentry-php/blob/3bb122f9fc2bc43a4646e37db79eaf115b35b047/src/Options.php#L699-L732

We agree the upgrade docs are... lacking. But we have tried to document all the current options as best as we can here: https://docs.sentry.io/platforms/php/guides/laravel/configuration/.

If you are unable to find what you are looking for and/or having trouble migrating over, please open up an issue with the current config and version you are using so we can help you out with the correct config options for the newer SDK's if needed.
