### ISSUE TITLE
ocramius/package-versions

### ISSUE THREAD

**Issue by fpcimmino** [getsentry/sentry-laravel#262]
Hi,
I tried to install sentry repository to lumen and receive this error:

Package operations: 1 install, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.5.0): Downloading (100%)
Plugin installation failed, rolling back
  - Removing ocramius/package-versions (1.5.0)

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Could not delete /var/www/my-project/vendor/ocramius/package-versions:

Do you help me?

Thanks

**Comment by stayallive** [comment]
I am not a 100% sure why this is happening but might have something todo with that package dropping 7.2 support (which you might have had locally but not on your server).

See this issue for details: https://github.com/getsentry/sentry-php/issues/850

And here is the most likely solution: https://github.com/getsentry/sentry-php/issues/850#issuecomment-514856622

**Comment by stayallive** [comment]
Because I have not heard back I am going to assume my directions were sufficient and the problem was solved, closing this issue, feel free to reopen or open a new one if there are still unsolved issues.
