### ISSUE TITLE
Your configuration files are not serializable

### ISSUE THREAD

**Issue by InstanceOfMichael** [getsentry/sentry-laravel#266]
config/sentry.php

```php
<?php

use Sentry\Event;

return [

    'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),

    'before_send' => function (Event $event): ?Event {
        // literally anything
        return $event;
     },
];
```

```shell
php artisan config:cache
```
![Screenshot from 2019-08-23 11-24-53](https://user-images.githubusercontent.com/4094542/63603969-ae363600-c598-11e9-8600-ade36c8fb0d2.png)

**Comment by stayallive** [comment]
Yes, that is because you are using a closure in your configuration file which is not allowed :)

This is a Laravel limitation (and a good one because serializing closures is a hack).

You can circumvent this by doing the following:

```php
<?php

namespace App\Exceptions;

use Sentry\Event;

class Sentry
{
    public static function before(Event $event): ?Event
    {
        // literally anything

        return $event;
    }
}
```

Which you can set in your configuration like:

```php
<?php
return [

    'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),

    'before_send' => [App\Exceptions\Sentry::class, 'before'],

];
```

This works because we allow PHP [callables](https://www.php.net/manual/en/language.types.callable.php) to be passed for all callbacks.

**Comment by stayallive** [comment]
Because I have not heard back I am going to assume my directions were sufficient and the problem was solved, closing this issue, feel free to reopen or open a new one if there are still unsolved issues.

**Comment by atta1234** [comment]
> Yes, that is because you are using a closure in your configuration file which is not allowed :)
> 
> This is a Laravel limitation (and a good one because serializing closures is a hack).
> 
> You can get around this limitation by doing the following:
> 
> ```
> <?php
> 
> namespace App\Exceptions;
> 
> use Sentry\Event;
> 
> class Sentry
> {
>     public static function before(Event $event): ?Event
>     {
>         // literally anything
> 
>         return $event;
>     }
> }
> ```
> 
> Which you can set in your configuration like:
> 
> ```
> <?php
> 
> return [
> 
>     'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),
> 
>     'before_send' => [App\Exceptions\Sentry::class, 'before'],
> 
> ];
> ```
> 
> This works because we allow PHP [callables](https://www.php.net/manual/en/language.types.callable.php) to be passed for all callbacks.

doing the following on which file?

**Comment by mfn** [comment]
> doing the following on which file?

`config/sentry.php`

It's not explicitly documented as the config options are passed through directly to Sentry. So when you read something like https://docs.sentry.io/platforms/php/#tagging-events , it's basically the content of `config/sentry.php` passed internally to this init.

**Comment by atta1234** [comment]
> > doing the following on which file?
> 
> `config/sentry.php`
> 
> It's not explicitly documented as the config options are passed through directly to Sentry. So when you read something like https://docs.sentry.io/platforms/php/#tagging-events , it's basically the content of `config/sentry.php` passed internally to this init.

i don't have that file in config folder

**Comment by mfn** [comment]
Seems to me you didn't follow the installation guide then, see e.g. https://sentry.io/for/laravel/

Especially the last step ("create the sentry configuration")
