### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by mdzhokanov** [getsentry/sentry-laravel#270]
**Last version of Sentry does not support Lumen.**

STEPS TO REPRODUCE:
1) Created a clean Lumen 5.5 project, as described here - https://lumen.laravel.com/docs/5.5
2) Integrate Sentry-laravel, as described here - https://docs.sentry.io/clients/php/integrations/
3) execute "php artisan sentry:test"

RESULT: 
"**Class 'Sentry\SentryLaravel\SentryLumenServiceProvider' not found**"

**Comment by stayallive** [comment]
This is correct, I see we never updated the docs... thanks for letting me know!

Instead of:

```php
$app->register('Sentry\SentryLaravel\SentryLumenServiceProvider');
```

You would need to use:

```php
$app->register('Sentry\SentryLaravel\SentryLaravelServiceProvider');
```

I will update the docs shortly!

**Comment by mdzhokanov** [comment]
Thanks for the quick reply! I changed the service provider, but now I get following error:
```
In OptionsResolver.php line 796:

  The options "level", "user_context" do not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "b
  efore_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enabl
  e_compression", "environment", "error_types", "excluded_exceptions", "http_proxy", "in_app_exclude", "integrations"
  , "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "project_root", "release",
  "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags".
```

**Comment by stayallive** [comment]
It looks like you upgraded from 0.x to 1.x of the Laravel integration which uses the all new PHP SDK 2.0 underneath! This changed some options and configurations.

I would suggest you grab a clean sentry.php config file from here: https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php

And add you changes on top of that. Current options are listed in the error message you showed and a list is available here: https://docs.sentry.io/error-reporting/configuration/?platform=php

And I also suggest you check out the upgrade guide for the base SDK in case you do anything with the Sentry SDK directly: https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md

**Comment by mdzhokanov** [comment]
Awesome! Thank you!

**Comment by stayallive** [comment]
So I just noticed you were looking at the old documentation :)

This is why the instruction were wrong, I'm sorry I didn't catch that.

You should be looking at: https://docs.sentry.io/platforms/php/laravel/

There is a big warning on top of the page where you were looking (https://docs.sentry.io/clients/php/integrations/) to indicate this :)

![image](https://user-images.githubusercontent.com/1090754/64080819-5ca84c80-ccf8-11e9-80be-e702c8517c15.png)

**Comment by pynner** [comment]
AHh I got baited by the same depreciated client, reason why I didn't see the notice is because you can jump right to the section from googling Lumen Sentry

**Comment by stayallive** [comment]
Ah dang, I'm seeing this too, I'm checking internally if we can prevent this / make the banner sticky / remove them from Google or something to prevent this 😄

**Comment by yordadev** [comment]
> 
> 
> This is correct, I see we never updated the docs... thanks for letting me know!
> 
> Instead of:
> 
> ```
> $app->register('Sentry\SentryLaravel\SentryLumenServiceProvider');
> ```
> 
> You would need to use:
> 
> ```
> $app->register('Sentry\Laravel\ServiceProvider');
> ```
> 
> I will update the docs shortly! (I will leave this issue open until the docs are updated)

Came across this issue, documentation still not updated. However, thank you for this reply for fix.

https://docs.sentry.io/clients/php/integrations/#lumen-5-x

Cheers.

**Comment by stayallive** [comment]
@yordadev it is, please read my comment: https://github.com/getsentry/sentry-laravel/issues/270#issuecomment-526943051

You are looking at the old docs. They will not be updated, the current docs show the right instructions.
