### ISSUE TITLE
Setting custom options in config/sentry.php throws an error

### ISSUE THREAD

**Issue by carestad** [getsentry/sentry-laravel#277]
Trying to set what I would assume is considered an unsupported config option in the `config/sentry.php` config file throws an error and makes all `artisan` commands unusable:

```
In OptionsResolver.php line 796:
                                                                                                                                                                                             
  The option "frontend" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "def  
  ault_integrations", "dsn", "enable_compression", "environment", "error_types", "excluded_exceptions", "http_proxy", "in_app_exclude", "integrations", "logger", "max_breadcrumbs", "max_r  
  equest_body_size", "max_value_length", "prefixes", "project_root", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags".
```

I have separate projects for the frontend and backend and have set a `sentry.frontend.dsn` key for this previously, due to the error I created a separate `config/sentry-frontend.php` file for this now.

Would it be possible to consider accepting non-standard options in the config file somehow though?

**Comment by stayallive** [comment]
Hey @carestad this feature request is tracked here: https://github.com/getsentry/sentry-laravel/issues/225#issuecomment-479464560
