### ISSUE TITLE
Issue with Laravel 4

### ISSUE THREAD

**Issue by Claymm** [getsentry/sentry-laravel#28]
Hi,

On my Laravel 4.2 app I have defined within my `app/start/global.php` file the following:

``` php
App::error(function(Exception $exception, $code) {
    Log::error($exception);
    ...
    if ( ! App::environment('local')) {
        switch ($code) {
            case 403:
                return Response::view('errors.403', [], 403);
            case 404:
                return Response::view('errors.404', [], 404);
            case 500:
                return Response::view('errors.500', [], 500);
            default:
                return Response::view('errors.default', [], $code);
        }
    }
});
```

but the problem is that the following code within `src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php` is not capturing the Exception:

``` php
$app->error(function (\Exception $e) use ($app) {
    $app['sentry']->captureException($e);
});
```

I guess it's because `$app->error(function (\Exception $e)` is actually similar to `App::error(function(Exception $exception, $code) {` and that my bit is overriding your bit?

Any workaround?

**Comment by Claymm** [comment]
My workaround so far:
```php
App::error(function(Exception $exception, $code) {
    Log::error($exception);

    app('sentry')->captureException($e);

    ...
    if ( ! App::environment('local')) {
        switch ($code) {
            case 403:
                return Response::view('errors.403', [], 403);
            case 404:
                return Response::view('errors.404', [], 404);
            case 500:
                return Response::view('errors.500', [], 500);
            default:
                return Response::view('errors.default', [], $code);
        }
    }
});
```

**Comment by stayallive** [comment]
I think this is because you are defining your App::error callback before Sentry's (or the other way around) and since you always return something handlers after that are not called (as for all Laravel events I believe).

**Comment by stayallive** [comment]
@Claymm did you manage to get it to work?

**Comment by stayallive** [comment]
Closing this because I assume by now a solution was found by now.

Feel free to reopen if that's not the case!
