### ISSUE TITLE
When is the data sent to Sentry?

### ISSUE THREAD

**Issue by JeremyHutchings** [getsentry/sentry-laravel#29]
Hi,

We're on php-fpm so fastcgi_finish_request() works properly in Laravel's [Terminal Middleware](https://laravel.com/docs/5.3/middleware#terminable-middleware) (there seems to be an issue with it, unless it's php-fpm).

Anyway ...... I was wondering is the call to Sentry taking (or planning to take) advantage of Terminal Middleware? So the processing and sending of the error data isn't blocking the response.

Thanks.

**Comment by dcramer** [comment]
We dont do anything special around it, so generally its sent immediately. The PHP SDK has an experimental async option, but it doesnt properly handle all errors at the moment so its not enabled by default.
