### ISSUE TITLE
How to send meta with the new 1.* version ?

### ISSUE THREAD

**Issue by fico7489** [getsentry/sentry-laravel#291]
With the 0.* version I used this : 

	\Sentry::captureMessage($ex->getMessage(), ['order_id'], [
		'level' => "error",
		'tags' => [
			'service' => 'queue',
		]
	]);

but now I see that captureMessage() take first param string error message, second severity level

**Comment by fico7489** [comment]
I found

	\Sentry::configureScope(function (Scope $scope) use ($meta) {
		$scope->setExtras($meta);
	});

	\Sentry::captureException($throwable);

**Comment by stayallive** [comment]
For future reference, the Laravel SDK exposed the full PHP SDK so everything here also applies for Laravel.

> https://docs.sentry.io/enriching-error-data/context/?platform=php
