### ISSUE TITLE
Why are all logs level "error"?

### ISSUE THREAD

**Issue by markkimsal** [getsentry/sentry-laravel#292]
```
    $ctx = ['exception'=>new \Exception('test exception')];
    \Log::debug("Debug thing", $ctx);
    \Log::warning("Warn thing", $ctx);
    \Log::critical("Critical thing", $ctx);
    \Log::error("Error thing", $ctx);
    \Log::alert("Alert thing", $ctx);
    throw new \Exception('test exception');
```

All of these show up as level = "error" because they all contain a key "exception" in the context array.

```
        if (isset($record['context']['exception']) && $record['context']['exception'] instanceof \Throwable) { 
            $this->hub->captureException($record['context']['exception']);
        } else {
            $this->hub->captureMessage($record['formatted'], $this->getLogLevel($record['level'])); 
        }
```

Why don't we always set the log level in the `SentryHandler::write() addEventPreprocessor`?

```
    if (!empty($record['level']) {
        $event->setLevel( $this->getLogLevel($record['level']));
    }
````

This way, if I specifically call Log::notice()  it will show up in sentry with level = "notice" and not level  = "error".  Uncaught exceptions will always have level = "error" because laravel's base Exception Handler class calls $logger->error() in the base report() method.

The context key `"exception"` can be used to decide if an event should be rendered as an exception, but since logs and exceptions come in the same way, it shouldn't be the only key used to determine the event's Severity.

**Comment by stayallive** [comment]
I'm sorry this was ignored for a long time... but this looks like we finally got a fix for it 👍 

Because of grouping though to see the effect you'd need something like this:

```php
    \Log::debug("Debug thing", ['exception' => new \Exception('Debug exception')]);
    \Log::warning("Warn thing", ['exception' => new \Exception('Warn exception')]);
    \Log::critical("Critical thing", ['exception' => new \Exception('Critical exception')]);
    \Log::error("Error thing", ['exception' => new \Exception('Error exception')]);
    \Log::alert("Alert thing", ['exception' => new \Exception('Alert exception')]);
```

This is because otherwise Sentry server will group all exception in 1 entry and uses the highest severity level or maybe the latest not entirely sure.

Fix in #505 pending release.
