### ISSUE TITLE
PHP 5.3 Compatible last tag 0.8.1 contains incompatible usage

### ISSUE THREAD

**Issue by umutkirgoz** [getsentry/sentry-laravel#293]
**static::$...** and **$this** cannot be used  in closures in PHP 5.3.
In 0.8.1 tag which was the latest PHP 5.3 compatible version, register method of **SentryLaravelServiceProvider** contains invalid usage :

```php
$this->app->singleton(static::$abstract, function ($app) {   
       $user_config = $app[static::$abstract . '.config'];
            ........................
});
```

**Comment by andrey-helldar** [comment]
PHP 5.3? Really? In 2020, when will PHP 8 be released in November?

**Comment by umutkirgoz** [comment]
Because, sometimes it's not easy to change 20 years old code base...

**Comment by stayallive** [comment]
@umutkirgoz I'm sorry this took so long but you are correct, this sneaked in and is of course not PHP 5.3 compatible. I've just tagged `0.8.2` which should address that oversight. Thanks you for your report and patience.
