### ISSUE TITLE
Docs could have a "queue" section

### ISSUE THREAD

**Issue by smknstd** [getsentry/sentry-laravel#298]
Maybe, [docs](https://docs.sentry.io/platforms/php/laravel/) could have a section to confirm behaviour when queued job fails.

I think, it's not 100% clear if I need to use https://laravel.com/docs/6.x/queues#failed-job-events or not, and a simple doc section could help

**Comment by stayallive** [comment]
There is not much to tell really and I'm not sure it will help or add more confusion adding a queue section to the docs.

Sentry captures exceptions that occur, anywhere, in your application. So if a queue failed because of an unhandled exception Sentry will report that. The same goes for when a web request to your app fails with an unhandled exception.

What do you think adding to the docs would have helped in your case?

**Comment by smknstd** [comment]
I am pretty sure this statement could help others as well:

> Sentry captures exceptions that occur, anywhere, in your application. So if a queue failed because of an unhandled exception Sentry will report that.

I was not sure so I started to lose some time searching and found some confusing stuff like https://github.com/getsentry/sentry-laravel/pull/153

**Comment by smknstd** [comment]
PS: I did not try to point you to "$tries" option. I was wondering if I would need

```
    public function boot()
    {
        Queue::failing(function (JobFailed $event) {
            Log::channel('sentry')->error("...",[]);
        });
    }
```

**Comment by smknstd** [comment]
> If for example your job tries 3 times and fails all 3 times Sentry will have 3 errors reported (they ofcourse can all 3 be the same).

Ok but this seems true only if a `failed()` method is not defined in the job (https://laravel.com/docs/6.x/queues#cleaning-up-after-failed-jobs): 

```
    /**
     * The job failed to process.
     *
     * @param  Exception  $exception
     * @return void
     */
    public function failed(Exception $exception)
    {
        // Send user notification of failure, etc...
    }
```

If there is one, docs say that : 

> The Exception that caused the job to fail will be passed to the failed method

And I understand it implicitly as "the exception is catched and will not be thrown", so if nothing done in that method I'm pretty sure nothing will be sent to Sentry.

I think mentioning this in the docs would also help !

**Comment by stayallive** [comment]
Ah, this is very good feedback, I can understand why this might be a tricky thing to figure out.

Just to have it here and collect my thoughts before adding it to the docs:

When you have a `failed` method on your Queue job (https://laravel.com/docs/6.x/queues#cleaning-up-after-failed-jobs) that `failed` method acts a a `catch` and you can do work in there to cleanup after something goes wrong or possibly log something like sending the exception to Sentry so you know something went wrong.

I'll probably rewrite this a bit with some examples, I have already started a big "cleanup" in the docs (getsentry/sentry-docs#1380) and will make sure to add the information above too!

**Comment by stayallive** [comment]
@smknstd I've added the section as discussed, could you let me know if this would have helped you? 

https://github.com/getsentry/sentry-docs/pull/1380/commits/3fd0e12d8d8dd7e491ed74b0bfad382b2b2084fe

**Comment by stayallive** [comment]
This is now live 🎊

**Comment by smknstd** [comment]
good job !
