### ISSUE TITLE
Should this package register with Monolog instead

### ISSUE THREAD

**Issue by dwightwatson** [getsentry/sentry-laravel#3]
The docs currently indicate that we should capture the exception with Sentry in the `report()` method of our app's exception handler. However, this means that every exception is being reported, even those in the `$dontReport` array.

To get around this, you would need to first check that the exception should be reported.

```
    public function report(Exception $e)
    {
        if ($this->shouldReport($e)) {
            Sentry::captureException($e);
        }

        return parent::report($e);
    }
```

Perhaps instead, this package should register the Raven client with Laravel's Monolog instance. That way when the parent `report()` method is called, Laravel will only report the exception to Sentry if the exception is to be reported.

**Comment by dcramer** [comment]
@dwightwatson the lack of monolog usage is intentional as Laravel's implementation does not correctly pass exceptions. We're very adamant about *not* using logging anymore, as it ends up in poor user experiences.
