### ISSUE TITLE
Get user data in sentry 

### ISSUE THREAD

**Issue by adnanmayo** [getsentry/sentry-laravel#30]
Hello, 
I want to send a Auth::user() in sentry dashboard. i want to know error which user caused the error. is there a way around?

**Comment by stayallive** [comment]
Hey @adnanmayo,

Please read the readme, it is explained there how to do that: https://github.com/getsentry/sentry-laravel#adding-context

**Comment by adnanmayo** [comment]
@stayallive thanks for your response.

`    public function report(Exception $e)
    {
        if ($this->shouldReport($e)) {
            if (app()->bound('sentry')) {
                $sentry = app('sentry');
                if (auth()->check()) {
                    $sentry->user_context([
                        "user_id" => \Auth::id(),
                        "email" => \Auth::user()->email
                    ]);
                }
                else {
                    $sentry->user_context(['id' => null]);
                }
                $sentry->tags_context([]);
            }
            app('sentry')->captureException($e);
        }
        parent::report($e);
    }`

i am trying i this way, if i am wrong can you please guide me how i can achieve this.  Can you please also tell what is `$sentry->tags_context([...]);`

**Comment by stayallive** [comment]
@adnanmayo That should also work.

Tags context sets the value of tags, you can for example add the php version as a tag or the route action and so forth. You can read more about the configuration options in the `sentry-php` docs: https://docs.sentry.io/hosted/clients/php/config/#available-settings

**Comment by adnanmayo** [comment]
@stayallive thanks. Stayalive 👍
