### ISSUE TITLE
"release" option ignored when using logging channels

### ISSUE THREAD

**Issue by pehbehbeh** [getsentry/sentry-laravel#300]
We use Sentry via logging channel and want to set a release like so:

```
<?php

return [

    // ...

    'channels' => [

        // ...

        'sentry' => [
            'driver' => 'sentry',
            'release' => 'some-version',
            'environment' => env('SENTRY_ENVIRONMENT', env('APP_ENV')),
        ],
    ],

];
```

This setting is ignored. Events in Sentry do not have a release attached.  Is this a bug or should this work? Maybe the version needs to be set [somewhere around here](https://github.com/getsentry/sentry-laravel/blob/ba97b57e7e5a558a8f19399791263209b2ff2889/src/Sentry/Laravel/LogChannel.php#L18)?

**Comment by pehbehbeh** [comment]
The `SentryHandler` already has a `setRelease` method which is never used. Maybe just add the following in the `LogChannel` class?

```
$handler->setRelease($config['release']);
```

**Comment by stayallive** [comment]
Did you try setting the release from `config/sentry.php`?

**Comment by pehbehbeh** [comment]
Ah, my bad. I somehow missed the `sentry.php` config thought we only have a `logging.php` config when using via Logging Channel. It works now.

Thanks for the quick response!

**Comment by stayallive** [comment]
Yeah, you should use `config/sentry.php` to configure the Sentry client.

The log channel is merely a passthrough to the Sentry client not a stand-alone thing, so that's why configuration options there won't take effect 👍
