### ISSUE TITLE
Incorrect breadcrumb type

### ISSUE THREAD

**Issue by TheLevti** [getsentry/sentry-laravel#302]
The `commandStartingHandler`, `queueJobProcessingHandler`, `messageLoggedHandler` and `queryExecutedHandler` use the User breadcrumb type, which does not make a sense, because none of those are related to a user. Especially in a cli environment.

### Current behavior

![Screenshot from 2019-11-17 19-43-28](https://user-images.githubusercontent.com/7612582/69012193-6e9ea080-0973-11ea-867d-b25b9a90a75f.png)

All logs and all other type of laravel framework events that are handled by this package use the user breadcrumb type by default.

### Expected behavior

![Screenshot from 2019-11-17 19-45-30](https://user-images.githubusercontent.com/7612582/69012207-883fe800-0973-11ea-9636-c2f434016008.png)

Default breadcrumb type should be the default type. If someone wants to add a breadcrumb that is related to a user, use the sentry facade or service directly or extend the event handler to add additional functionality.

**Comment by stayallive** [comment]
I’d be happy accepting a PR fixing this if you’re up for that?

**Comment by TheLevti** [comment]
One question, where should I write the issue about missing highlighting of the FATAL level?

I mean we have some orange highlighting for warnings, red for error, but the most severe level looks like default. :)

**Comment by stayallive** [comment]
Let me check with the team what types are supported in the UI and what they are supposed to mean to the user. I think “user” level events might mean something else depending on who you ask. I’ll get back to you with that!

**Comment by stayallive** [comment]
@TheLevti just a quick follow up, are you on `1.4.x` or `1.5.x` of `sentry/sentry-laravel`?

**Comment by stayallive** [comment]
Can you let me know a bit more what code you used to generate those breadcrumbs since I thought #296 was supposed to fix this issue actually.

**Comment by TheLevti** [comment]
It was fixed. 1.5 I am using. The correct breadcrumb level is sent to sentry. Even the css classes are applied (fatal), but there is no styling for it. Its more of a frontend issue.

**Comment by TheLevti** [comment]
The problem is not the SDK side. The problem is that the frontend has no styling for the FATAL breadcrumb level.

**Comment by TheLevti** [comment]
```php

Route::get('/debug-sentry', function () {
    Log::debug('Debug log {debug_context}', ['debug_context' => 1]);
    Log::info('Info log {debug_context}', ['debug_context' => 2]);
    Log::notice('Notice log {debug_context}', ['debug_context' => 3]);
    Log::warning('Warning log {debug_context}', ['debug_context' => 4]);
    Log::error('Error log {debug_context}', ['debug_context' => 5]);
    Log::critical('Critical log {debug_context}', ['debug_context' => 6]);
    Log::alert('Alert log {debug_context}', ['debug_context' => 7]);
    Log::emergency('Emergency log {debug_context}', ['debug_context' => 8]);

    throw new Exception('My first Sentry error!');
});
```

Is what I used for my example.

**Comment by TheLevti** [comment]
If you inspect with the browser the elements, you can see that critical, alert and emergency correctly got the `crumb-fatal` css class assigned. I inspected the CSS file, but no style is defined for this level.

**Comment by TheLevti** [comment]
Any news on this? Pull request for this issue is already provided.
