### ISSUE TITLE
Required package "sentry/sentry" is not installed

### ISSUE THREAD

**Issue by flavazelli** [getsentry/sentry-laravel#304]
Lumen 6.0
PHP 7.2
"sentry/sentry-laravel": "1.5.0"

Required package "sentry/sentry" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files

The only way to fix it is to re-run composer install

**Comment by stayallive** [comment]
If I read this correctly you already fixed it, but this issue should also nog longer be present in theory after all your dependencies are up-to-date: https://github.com/getsentry/sentry-laravel/issues/274#issuecomment-554062007

**Comment by stayallive** [comment]
Closing this issue because it is quite old and it has been a long time since there was any activity, if there is still a problem please open a new issue.

**Comment by Ovski4** [comment]
For anyone still getting this issue, I was able to fix it by upgrading composer from version `2.0.2` to `2.0.12`.
