### ISSUE TITLE
Hide Sensitive Data

### ISSUE THREAD

**Issue by Arkanius** [getsentry/sentry-laravel#305]
Hello. I read at the docs that is there a way to hide [sensitive data](https://docs.sentry.io/data-management/sensitive-data/).

I tried to figure out at the docs of this package how to use the methods mentioned at the sentry docs and I didn't find anything.

Does anyone know how can I do this?

**Comment by stayallive** [comment]
By default the configuration option `send_default_pii` (`false` by default) does not add any more data than can be found in your stacktraces as explained on that page: https://docs.sentry.io/error-reporting/configuration/?platform=php#send-default-pii.

The other method mentioned is the `before_send` option which is explained [here](https://docs.sentry.io/platforms/php/#filter-events--custom-logic) and can be added to your `sentry.php` config file like this:

```php
    'before_send' => function (Sentry\Event $event): ?Sentry\Event {
        return $event;
    },
```

The `before_send` accepts any callable so you could create a custom class which has a static method in case you don't want any closures in your config file:

```php
    'before_send' => [App\Exceptions\Sentry::class, 'beforeSend'],
```

Does that answer your question a bit?

**Comment by Arkanius** [comment]
Oh, yes! I'll try this out. Thanks for the help!
