### ISSUE TITLE
When logging manually, "additionnal data" is not displayed anymore

### ISSUE THREAD

**Issue by smknstd** [getsentry/sentry-laravel#310]
When logging manually, 

```
        Log::error('manual_error',[
            "context_key" => "value",
        ]);
```

context is not displayed anymore as "additionnal data" with sdk 1.5

![Screenshot_2019-12-03  2019-12-03 15 45 24  laravel ERROR manual_error { context_key value }](https://user-images.githubusercontent.com/2412608/70061687-0263a400-15e5-11ea-9173-dc52d0479dcd.png)

What I had with sdk 0.10

![Screenshot_2019-12-03  2019-12-03 15 21 49  laravel ERROR mon erreur { a_string value , an_array_with_limited_size ](https://user-images.githubusercontent.com/2412608/70061709-10192980-15e5-11ea-97b5-468e93adb19e.png)

**Comment by stayallive** [comment]
This was indeed changed, if you want the info back in the additional data (`extra`) you can do the following:

```php
Log::error('manual_error', [
    'extra' => [
        'context_key' => 'value',
    ],
]);
```

Reference: https://github.com/getsentry/sentry-laravel/blob/11a7de5342dabccbaaa45e4363596c000aab1e04/src/Sentry/Laravel/SentryHandler.php#L154-L159

**Comment by smknstd** [comment]
Thanks for your answer! Doesn't sound like good news to me though.
