### ISSUE TITLE
Log channel does not work from Tinker

### ISSUE THREAD

**Issue by carestad** [getsentry/sentry-laravel#311]
I was trying to figure out if my Sentry log channel was working today, and just wanted to test it real quick in tinker, but nothing was ever logged. It was first when I put it in application code and went to a test URL that it actually ended up in Sentry.

Is there some sort of limitation to the log channel handler that it won't run from console commands? Any way of bypassing this?

Edit: my channel config:

```php
(...)
        'sentry' => [
            'driver' => 'sentry',
            'level' => 'debug',
        ],
(...)
```

And I tried running `Log::channel('sentry')->critical('Foo');`

**Comment by stayallive** [comment]
Hey @carestad maybe you already figure it out after you exited Tinker (with `exit` not with ctrl+c), but the events will only send after ending the execution ends.

I explained it in a bit more detail here (including a "manual" force send): https://github.com/getsentry/sentry-laravel/issues/250#issuecomment-508425057

**Comment by carestad** [comment]
Ah, of course. That would make sense though. But I always quit Tinker with `CTRL+C` so this never triggered when I tested it.

Tested it now and it seems to work when quitting with `exit` or by running `\Sentry\Laravel\Integration::flushEvents();` after `Log::channel('sentry')->critical('Foo')`.

I'll just close this then.
