### ISSUE TITLE
Decomposition of querystring goes wrong in some cases

### ISSUE THREAD

**Issue by edwardcaret** [getsentry/sentry-laravel#313]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [* ] Other: Manual install of Sentry 9.1.2

## Description

Someone tried to do an sql injection attack, and due to incorrect input validation triggered an Exception.
The issue in Sentry shows all data correct, except where the querystring is parsed to provide a pretty output. The querystring seems to be split on semicolon to seperate parameters. However the semicolon is not used as a seperator in our case (PHP+Laravel).
After reading up on the issue, I see it is not a very clear case on what should be done with supporting semicolon or ampersand.
However as the display of the parameters in the issue screen in this case gives a scewed view of what was passed onto the code, I think this deservers some attention, and perhaps some a parameter to align the data in the issue screen with what the backend actually does with it.

## Steps to Reproduce

1. The attacker made this request:
    GET /api/establishments/filter?product=RDPWIugK'));select%20pg_sleep(3);%20--%20 HTTP/1.1
2. In our case this value was not validated/sanitized to be an integer, and the resulting query had the following:
      product_id = "RDPWIugK'));select%20pg_sleep(3);%20--%20"  
    Of course the database complained, and triggered an Exception which is logged to Sentry
3. Now view the item in Sentry. The querystring is decomposed into:
     Query String
        --                                 
        product                   RDPWIugK'))
        select pg_sleep(3)         

    Given semicolon as a seperator this would be correct. However PHP/Laravel splits on Ampersand, so this is not correct and gives a wrong representation of the data.

![image](https://user-images.githubusercontent.com/6883977/70700191-9ced7280-1cca-11ea-85ef-220544d6fdce.png)

### What you expected to happen

The decomposition of the querystring should have been:
   Query String
     product       RDPWIugK'));select%20pg_sleep(3);%20--%20

### Possible Solution

I would propose adding a configuration parameter which seperator(s) to apply for splitting the querystring.

Even though semicolon seems to be unsupported or dropped by many frameworks and tools, it looks like it is specified in standard to be an aceptable seperator.
So Sentry should support it, as well as ampersand. Using both at the same time is what Sentry seems to do here, is not desirable.

**Comment by untitaker** [comment]
@edwardcaret I am very certain that the Sentry server does not decompose on `;`, at least not on Sentry.io (Sentry 10 beta). I don't think Sentry 9 does either.

It would be interesting to see what the SDK sends. I believe you can do this in PHP using `before_send`: https://docs.sentry.io/error-reporting/configuration/filtering/?platform=php (just put an `echo` or logging statement inside the function).

**Comment by stayallive** [comment]
I think you are mixing up 2 things... the request you mentioned that was made:

```
curl 'http://sentry-laravel-test.develop/login?product=RDPWIugK%27));select%20pg_sleep(3);%20--%20'
```

However in your screenshot I'm seeing `filter-product[]` (not `product`) so I think you are looking in Sentry at a totally different request that the same attacker might have made. It's very possible the attacker used some automated script and tried hundreds of variations and query params.

![image](https://user-images.githubusercontent.com/1090754/70868500-c08e1280-1f81-11ea-8d26-e13981a18ed9.png)

As you can see from my testing it works as expected in the example you provided. We also use the Symfony HTTP component to extract the query params and other request details and since Laravel uses those too I find it hard to believe they're different from each other :) (context: https://github.com/getsentry/sentry-php/blob/ffcd2f488d585d2a4cb54498e7038c15059e053b/src/Integration/RequestIntegration.php#L113-L115)

**Comment by stayallive** [comment]
@edwardcaret did you happen to find out the cause / fixed it?

I am still wondering if this might be a mixup or really a bug somewhere we should investigate. Please let me know so we can try and fix it if needed 😄

**Comment by stayallive** [comment]
Closing this issue because it has been a long time since there was any activity, if there is still a problem please open a new issue.
