### ISSUE TITLE
Although event is created, I can't reach the event.

### ISSUE THREAD

**Issue by EmirCanSANCAR** [getsentry/sentry-laravel#319]
sentry works on some of my laravel projects but not on some. I couldn't understand the reason, although I checked all the files and dependencies in the composer, I couldn't find the error. how can I solve this problem?

```
PS C:\Projects\my-project> php artisan sentry:test
[sentry] Client DSN discovered!
[sentry] Generating test event
[sentry] Sending test event
[sentry] Event sent with ID: 2b873abff4fd49c190f3c11890c983cb
PS C:\Projects\my-project>
```

![image](https://user-images.githubusercontent.com/16269350/72258974-70f24380-3620-11ea-9c3e-39527329d7ca.png)

**Comment by stayallive** [comment]
Hi @EmirCanSANCAR sorry for the troubles, I think since you are on Windows this might be a configuration issues on your PHP side.

See: https://github.com/getsentry/sentry-laravel/issues/281#issuecomment-538976993

As explained there our error reporting for failed events because the transport failed is not very good yet and thus these errors might make it look like it sent it correctly but it actually didn't (we're working on it!).

Let me know if the linked comment solved the issues for you!

**Comment by EmirCanSANCAR** [comment]
Hi @stayallive, Unfortunately, this did not solve my problem. 

Yes I use windows but I have this problem on my linux server.the problem is only in some projects. I can't understand the difference between the two projects. Is there a way to understand this? all configurations are almost identical.

**Comment by EmirCanSANCAR** [comment]
I'm using sentry.io as host. I ran it on a different personal windows computer and on my linux server and it worked. but I can't use sentry in the project on my own windows computer. but I guess that doesn't really matter. ultimately running on the server.

I'm closing the issue for now. but if this issue is important to you, we can continue to talk here for trouble detection.

**Comment by stayallive** [comment]
So it only doesn't work on your personal _Windows_ computer (might be causes by: https://github.com/getsentry/sentry-laravel/issues/281#issuecomment-538976993)?

I am ofcourse happy it works where it matters but I would like to find out if your machine has the issue mentioned before (the incorrectly configured CA in PHP: https://github.com/getsentry/sentry-laravel/issues/281#issuecomment-538976993) or it's something else.

You mentioned before some projects did and some didn't work correctly, is that all on your PC or was that about projects working on other Windows machines and the Linux servers but not on your personal rig?

**Comment by EmirCanSANCAR** [comment]
All projects use the same php settings on the same pc.
My php.ini openssl settings.

```
[openssl]
; The location of a Certificate Authority (CA) file on the local filesystem
; to use when verifying the identity of SSL/TLS peers. Most users should
; not specify a value for this directive as PHP will attempt to use the
; OS-managed cert stores in its absence. If specified, this value may still
; be overridden on a per-stream basis via the "cafile" SSL stream context
; option.
;openssl.cafile=
```

**Comment by stayallive** [comment]
Jep that explains it why it's not working.

See this SO answer: https://stackoverflow.com/questions/39687720/ssl-not-work-in-php5-6-on-windows/39812970#39812970

Step 1 in that answer should solve your problems.
