### ISSUE TITLE
1.6.0 Missing event handler:queueJobExceptionOccurredhandler 

### ISSUE THREAD

**Issue by carlosrgzm** [getsentry/sentry-laravel#323]
Hi, just after updating to version 1.6.0, as soon as I send a Notification in my Laravel application, it raises this error:

"Missing event handler:queueJobExceptionOccurredhandler "

If I set the version to 1.5.0 is working fine. 
Does anyone have the same issue?

Thanks.

**Comment by besanek** [comment]
Yes, I already created pull request #322

**Comment by stayallive** [comment]
1.6.1 will be released shortly to address this, thanks to @besanek!

**Comment by SohrabZ** [comment]
We are having the same issue on our production servers, thanks to Sentry. You guys are supposed to catch and help troubleshoot errors not generate them. Here is a video of what happened today to our entire engineering department: https://www.youtube.com/watch?v=QiZNSzWIaLo

**Comment by bert-w** [comment]
@SohrabZ cry, you decided to deploy `composer update` or w/e on your production server without test driving a critical component like a queue worker. No open source package is free of bugs.

**Comment by SohrabZ** [comment]
Yes, this was due to a couple of human errors on our team, and we reverted as soon as we figured out the issue. I'm not here to blame anyone 😉.

**Comment by anooshr** [comment]
> @SohrabZ cry, you decided to deploy `composer update` or w/e on your production server without test driving a critical component like a queue worker. No open source package is free of bugs.

Sentry is a commercial software business.

**Comment by stayallive** [comment]
Hi all, I'm really sorry this slipped through the cracks. `1.6.1` was just released which fixes this + added tests to prevent this happening in the future.

I hope everyone can accept my deepest apology. Technically Sentry did let you know something broke still but you never expect nor want it to be _by_ Sentry.
