### ISSUE TITLE
Error on php 7.4

### ISSUE THREAD

**Issue by vincentkedison** [getsentry/sentry-laravel#325]
I upgraded my php version to 7.4 and I am running an application built with Laravel 5.6 using "sentry/sentry-laravel": "^0.11.0".
When I run php artisan in the command line I got this error:

In Client.php line 1551:
`Undefined variable: version`

I try to following the answer in this stackoverflow and it's work.
https://stackoverflow.com/questions/59155247/where-to-find-this-client-php-laravel

**Comment by stayallive** [comment]
Hi @vincentkedison,

`0.11.x` uses the "old" PHP SDK client that is no longer supported.

Are you able to upgrade to `sentry/sentry-laravel:^1.6`?

> https://docs.sentry.io/platforms/php/laravel/#laravel-5x--6x

**Comment by stayallive** [comment]
Closing this issue because it is quite old and it has been a long time since there was any activity, if there is still a problem please open a new issue.
