### ISSUE TITLE
Cannot Optimize or Cache Configurations for Laravel when using before_send Hook in sentry.php Config file 

### ISSUE THREAD

**Issue by andrewalexanderbalogh** [getsentry/sentry-laravel#326]
Documentation on setting up the various initialization options for Senty with PHP are noted at  
~ https://docs.sentry.io/error-reporting/configuration/?platform=php

Specific documentation to setting up the initialization options for Sentry with Laravel are noted at  
~ https://docs.sentry.io/platforms/php/laravel/#configuration

Documentaion on use of the `before_send` Hook, initialization option is noted at   
~ https://docs.sentry.io/error-reporting/configuration/filtering/?platform=php

I am Developing my Laravel-App using Laravel 6.x
~ https://laravel.com/docs/6.x

I am using sentry/sentry-laravel version 1.6.1

My `/config/sentry.php` file is as below;
```php
<?php
use Sentry\Event;

return [

    'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),

    // capture release as git sha
    'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),

    'breadcrumbs' => [
        // Capture Laravel logs in breadcrumbs
        'logs' => true,

        // Capture SQL queries in breadcrumbs
        'sql_queries' => true,

        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => true,

        // Capture queue job information in breadcrumbs
        'queue_info' => true,
    ],


    // Laravel does not like Closure Definitions in the /config files...
    'before_send' => function (Sentry\Event $event): ?\Sentry\Event {
        if (
            !env('APP_DEBUG') &&
            (env('APP_ENV') == 'production' || env('APP_ENV') == 'staging')
        ){
            return $event;
        }
        else {
            return NULL;
        }
    },
];

```

The problem I'm having is whenever I try to either **_Optimize_** my Application or **_Cache_** its **_Configuration_** files  
~ as noted at https://laravel.com/docs/6.x/deployment#autoloader-optimization
```
php artisan config:cache
 
php artisan optimize
```

Running either command will result in an exception being thrown of
_"Your configuration files are not serializable."_

The cause of this is my use of a _Closure_ for the  `before_send` Hook in the `config/sentry.php` file. 
This is as noted at the following links; 
~ https://laracasts.com/discuss/channels/laravel/configcache-your-configuration-files-are-not-serializable
~ see https://stackoverflow.com/questions/52065513/your-configuration-files-are-not-serializable

**Comment by andrewalexanderbalogh** [comment]
Previously I had used sentry/sentry-laravel version 0.8.0  
 ~ https://github.com/getsentry/sentry-laravel/tree/0.8.0

That exposed a `setSendCallback` method from the `"sentry/sentry": ">=1.7.0"` dependancy 
~ `/vendor/sentry/sentry/lib/Raven/Client.php`  

Which would set the `before_send` Hook,
and which I was able to use within my ` app/Exceptions/Handler.php` file more or less as follows;

```php
public function report(Exception $exception)
{
    $sentry = app('sentry');
    $sentry->setSendCallback(function($data){
        return env('APP_ENV') == 'production' || env('APP_ENV') == 'staging';
    });

    $sentry->captureException($exception);
    parent::report($exception);
}

Is there not a similar method available anymore?

**Comment by stayallive** [comment]
There is :) You can use any callable parameter in `before_send`.

So you can do the following:

Create a `App\Exceptions\Sentry.php` (or whatever place/name you'd like):

```php
<?php

namespace App\Exceptions;

use Sentry\Event;

class Sentry
{
    public static function beforeSend(Event $event): ?Event
    {
        return $event;
    }
}
```

And use it like this in you `config/sentry.php`:

```php
<?php

return [
    'before_send' => [App\Exceptions\Sentry::class, 'beforeSend'],
];
```

I've left out other options, you should still include those 😉

**Comment by andrewalexanderbalogh** [comment]
Thanks, this now allows me to use the Sentry initialization Hooks without affecting the artisan serialization actions :star:

**Comment by stayallive** [comment]
Perfect! If there is anything else we can help you with let us know 👍

**Comment by afiqiqmal** [comment]
I believe this is not working anymore in L10. Any workaround? 

Facing this issue

```
The option "before_send" with value array is expected to be of type "callable", but is of type "array"
```

sentry.php
```
'before_send' => [\App\Resolvers\Sentry\BeforeSendResolver::class, 'beforeSend'],
```


```php
class BeforeSendResolver
{
    public function beforeSend(\Sentry\Event $event, ?\Sentry\EventHint $hint): ?\Sentry\Event
    {
        $event->setUser(new \Sentry\UserDataBag(
            auth()->id(),
            auth()->user()->email ?? null,
            request()->ip(),
        ));

        return $event;
    }
}

```

**Comment by stayallive** [comment]
Please read the docs again, you need a _static_ method!
