### ISSUE TITLE
Please add Laravel 7 support

### ISSUE THREAD

**Issue by Dalamar** [getsentry/sentry-laravel#332]

**Comment by stayallive** [comment]
@Dalamar what am I missing? We released Laravel 7 support 8 days ago (at the time of this comment).

https://github.com/getsentry/sentry-laravel/releases/tag/1.7.0

Maybe you have your dependency set to a lower version still?

**Comment by Dalamar** [comment]
Terribly sorry!
My bad. 
I checked the compatibility at packagist.org in illuminate/support section and apparently I was confused by the line break after ^6.0 as I din't notice ^7.0 in next line :)

**Comment by stayallive** [comment]
Ahh no problem, you gave me a quick scare there 😉 

If you do run into an issue please do open up a new issue!
