### ISSUE TITLE
Events are not being reported to the dashboard

### ISSUE THREAD

**Issue by iSWORD** [getsentry/sentry-laravel#336]
I'm unable to capture any exceptions. `php artisan sentry:test` works fine and sends the event to Sentry but when I run the line below in tinker or in the project's code, I get the event ID but it's not reported on the Sentry dashboard:
```
>>> app('sentry')->captureException(new Exception('This is a test exception sent from tinker.'))
=> "0fdb27d7f3b74d82ac6e8f3b952b4d6b"
```
The project is at https://sentry.io/organizations/34ml/issues/?project=4721951

This is affecting several other projects:
- https://sentry.io/organizations/34ml/issues/?project=1788656
- https://sentry.io/organizations/34ml/issues/?project=1788649
- https://sentry.io/organizations/34ml/issues/?project=1788661
- https://sentry.io/organizations/34ml/issues/?project=1788650

## Environment

- PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
- sentry/sentry-laravel: 1.7.0
- sentry/sentry: 2.3.2
- laravel/framework: v6.14.0

I can reproduce this on both my local dev machine running macOS Catalina 10.15.2 and the production environment running Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-1007-aws x86_64) and PHP 7.4.3 (cli) (built: Feb 23 2020 07:24:28) ( NTS ).

Please let me know if there's anything else I can provide to help fix the issue.

Thank you,

**Comment by stayallive** [comment]
It is "correct" that doing that using Tinker is not working. Sentry only sends events after the PHP process ends or after the CLI process exits (the way tinker exits does not seem to flush the queue unfortunately).

You can force it by running:

```
app('sentry')->captureException(
    new Exception('This is a test exception sent from tinker.')
);

\Sentry\Laravel\Integration::flushEvents();
```

This should force the queue to empty and should sent your event.

We know this might be unexpected (when using Tinker) and we want to change this behaviour in the future, but this might be the issue or are you also not receiving any uncaught exceptions throughout your application?

Also, since you commented on #328, are you using a proxy and thus the `http_proxy` option?

**Comment by iSWORD** [comment]
@stayallive Thank you so much Alex for your quick and helpful responses! I really appreciate that :)

Running flushEvents does indeed fix the problem in Tinker! I need to figure out what's happening on production now. I'll get back to you once I gather more details.

Thank you again!

**Comment by iSWORD** [comment]
To answer your question

> are you using a proxy and thus the http_proxy option?
I'm not using a proxy, no. I commented there because I thought it was a similar case. Sorry about the confusion.

**Comment by stayallive** [comment]
Much appreciated. Happy to help, let me know if there is anything I can do to assist. 

It might be helpful to see if you missed anything from the setup guide (like changes to the exception handler, see: https://docs.sentry.io/platforms/php/laravel/#laravel-5x--6x) or making sure the exception handler is not set to not report the errors you are expecting or your app is using die/exit in the code path anywhere that might cut the execution short. Or are you using the log channel?

Also a common one, make sure you cleared/updated the config cache if you are using that. And if you are not using that, you can run `php artisan config:clear` to be sure that’s not messing anything up. Although the config cache should also affect the Tinker session. 

And no problem, just making sure the proxy is not the problem.

**Comment by iSWORD** [comment]
Not sure what happened but at least for the project I'm currently working on it started to function properly again! I did realize that since I'm using Nova I had to create another exception handler for Nova to catch Nova exceptions, but other projects do not use Nova and never reported any issues since we migrated from an on-premise setup 😅

Will reopen if I bump into the same issue with other projects.

Thanks a lot for your time, Alex! Be safe.

**Comment by stayallive** [comment]
Great to hear, good to know about Nova, we might need to clarify that in the docs / build this in the integration, will take a look later into that.

Let me know if you have more info for us to take a look 👍

**Comment by iSWORD** [comment]
Yeah absolutely, here's what needs to be done:

1. Create a handler class at `app/Exceptions/NovaExceptionHandler.php`:

```php
<?php

namespace App\Exceptions;

use Laravel\Nova\Exceptions\NovaExceptionHandler as Handler;

class NovaExceptionHandler extends Handler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];
    
    /**
     * Report or log an exception.
     *
     * @param  \Exception  $e
     * @return mixed
     *
     * @throws \Exception
     */
    public function report(\Exception $e)
    {
        if (app()->bound('sentry') && $this->shouldReport($e)) {
            app('sentry')->captureException($e);
        }

        return parent::report($e);
    }
}
```

2. Override the `registerExceptionHandler` method in the `app/Providers/NovaServiceProvider.php` file:
```php
use App\Exceptions\NovaExceptionHandler;
use Illuminate\Contracts\Debug\ExceptionHandler;
...

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    ...
    /**
     * Register Nova's custom exception handler.
     *
     * @return void
     */
    protected function registerExceptionHandler()
    {
        $this->app->bind(ExceptionHandler::class, NovaExceptionHandler::class);
    }
}
```
