### ISSUE TITLE
Breadcrumbs not reset during queue worker executions

### ISSUE THREAD

**Issue by mfn** [getsentry/sentry-laravel#338]
I did catch some exceptions from a Laravel worker => note that workers are _long running_ processes.

Using:
- Laravel 7.2.2
- sentry-laravel 1.7.0
- PHP 7.4.4

Turns out when I looked at the Breadcrumbs, I saw an ever expanding accumulation of all exceptions occurring on the worker so far _and_ the new one.

Example from an exception which happened at 16:37:15
![image](https://user-images.githubusercontent.com/87493/77635098-53abf080-6f52-11ea-9986-dbb55db1bf62.png)

And then some hours later, on the next event of the same issue this existing ones all reappear:
![image](https://user-images.githubusercontent.com/87493/77635273-98d02280-6f52-11ea-9525-1d5afdd4add9.png)

- From a users perspective: confusing
- From a technical perspective: potential memory leak?

Note: I'm not interested in disabling breadcrumbs, great feature :+1:

**Comment by stayallive** [comment]
Hmm, interesting these _should_ be cleared so this is definitely a bug and needs some looking after, thanks for reporting this!

**Comment by mfn** [comment]
Ah ok I see e.g.  `\Sentry\Laravel\EventHandler::afterQueuedJob`

When I saw this:
```php
    protected static $queueEventHandlerMap = [
        'Illuminate\Queue\Events\JobProcessing' => 'queueJobProcessing', // Since Laravel 5.2
        'Illuminate\Queue\Events\JobProcessed' => 'queueJobProcessed', // Since Laravel 5.2
        'Illuminate\Queue\Events\JobExceptionOccurred' => 'queueJobExceptionOccurred', // Since Laravel 5.2
        'Illuminate\Queue\Events\WorkerStopping' => 'queueWorkerStopping', // Since Laravel 5.2
    ];
```
It occurred to me _I too_ use these events, like this:
```php
    protected function initializeQueueEvents(): void
    {
        Queue::before(function (JobProcessing $event) {
            $job = $event->job;
            $queueName = $job->getQueue();
            $logger = $this->getLoggerForQueue($queueName);
            $logger->info(\get_class($event), $this->getJobDetails($queueName, $job));
        });

        Queue::after(function (JobProcessed $event) {
            $job = $event->job;
            $queueName = $job->getQueue();
            $logger = $this->getLoggerForQueue($queueName);
            $logger->info(\get_class($event), $this->getJobDetails($queueName, $job));
        });

        Queue::exceptionOccurred(function (JobExceptionOccurred $event) {
            $job = $event->job;
            $queueName = $job->getQueue();
            $logger = $this->getLoggerForQueue($queueName);
            $details = $this->getJobDetails($queueName, $job);
            $details['exception'] = $event->exception;
            $logger->error(\get_class($event), $details);

            $this->reportOtherwiseIgnoredException($event->exception);
        });

        Queue::failing(function (JobFailed $event) {
            $job = $event->job;
            $queueName = $job->getQueue();
            $logger = $this->getLoggerForQueue($queueName);
            $details = $this->getJobDetails($queueName, $job);
            $details['exception'] = $event->exception;
            $logger->error(\get_class($event), $details);
        });
    }
```
(quote some extensive logging here to keep an eye on things from multiple angles)

**Comment by stayallive** [comment]
@mfn that could actually cause problems in this case since you are using the same events and the cleanup events from Sentry might fire first... are you using log channels and or pushing breadcrumbs yourself, could that be happening?

**Comment by mfn** [comment]
I just tested, the slack event gets called. I'm not doing custom breadcrumb stuff.

However today I also opened https://github.com/DieSocialisten/Swat.io-Issues/issues/1979 and this observation I made here applies to these strange behaviour jobs, so maybe _there_ is something related.

I'll keep diffing.

**Comment by mfn** [comment]
There's nothing on my end by which I can reproduce it so I'm going to close it for now, thanks for your insights!

**Comment by stayallive** [comment]
Hmm thats unfortunate, if you do run into it again, please re-open / open up a new issue so we can fix the issue / track it down!
