### ISSUE TITLE
Install Sentry on Lumen

### ISSUE THREAD

**Issue by medbak** [getsentry/sentry-laravel#339]
I tried to install sentry on lumen 5.6 
I follow the officiel documentation for lumen : https://docs.sentry.io/platforms/php/laravel/

There is an issue in the doc, for the section Lumen 5.x & 6.x : 
# Sentry must be registered before routes are included
`require __DIR__ . '/../app/Http/routes.php';`
It must be : 
`require __DIR__ . '/../routes/web.php';`

When I tried to execute this command : 
`php artisan sentry:test` I got this message :
In web.php line 14: Undefined variable: router

How can I fix this issue ? 
Thanks,

**Comment by stayallive** [comment]
Did you only add the following line in you `bootstrap/app.php`?

```php
$app->register('Sentry\Laravel\ServiceProvider');
```

In that case I think you have an error in your `web.php` file on line 14 as the error states, this looks unrelated to Sentry or it's installation.

The documentation is a bit outdated it looks like, but still valid. I'll see if we can clarify that the line might be different now.

**Comment by medbak** [comment]
Thanks for your reply.

In bootstrap/app.php, I added 
```
$app->register('Sentry\Laravel\ServiceProvider');
require __DIR__ . '/../app/Http/routes.php';
```
But there is an issue in the path, so my current bootstrap/app.php is like :+1: 
```
$app->register('Sentry\Laravel\ServiceProvider');
require __DIR__.'/../routes/web.php';
```
I use Lumen 5.6, and when i  want to test this command : 
`php artisan sentry:test`

I got the error with route

**Comment by stayallive** [comment]
You must _only_ add the line below:

```php
$app->register('Sentry\Laravel\ServiceProvider');
```

The `require __DIR__...` should already be in your `app/bootstrap.php` at the end.

So remove the `require` you added and you should be good 👍

**Comment by medbak** [comment]
It works, thanks a lot :+1: .

**Comment by stayallive** [comment]
Good to hear, thanks for the update!
