### ISSUE TITLE
Class 'Composer\InstalledVersions' not found at runtime

### ISSUE THREAD

**Issue by saeedtrb** [getsentry/sentry-laravel#347]
I added your package to my lumen project, but I got below error at runtime.
`Class 'Composer\InstalledVersions' not found`
I think this error will occur where the composer is not installed.
I'm using  `composer.phar`  instead of installing composer.

lumen : 7.x
php : 7.2
pretty-package-versions : 1.4

**Comment by stayallive** [comment]
It look like you already posted this question here: https://github.com/Jean85/pretty-package-versions/issues/18#issuecomment-626728592.

I'm closing this in favor of that one so we can track it in 1 issue instead of trying to poor effort in multiple issues 👍
