### ISSUE TITLE
Sentry blocks laravel queue if no access (network restrictions) to sentry host

### ISSUE THREAD

**Issue by Divere** [getsentry/sentry-laravel#348]
Is it ok with connect timeout when reporting error from queue job?

**Comment by stayallive** [comment]
I am not sure what exactly you are asking. If you have network restrictions in place so Sentry cannot be reached you should always disable Sentry or lift the network restrictions.

That said, we do currently have better timeouts in place and waiting for a release: https://github.com/getsentry/sentry-php/pull/979, so this might be improved once that PR is released.

**Comment by Divere** [comment]
@stayallive i'm not asking :) it's a fact that currently sentry blocks queue if sentry network is unavailable. So waiting for release of this PR, thx.

**Comment by stayallive** [comment]
Ah. OK.

Well [2.4.0](https://github.com/getsentry/sentry-php/releases/tag/2.4.0) was just released with that change included, so running `composer update` should pull that.

If that does not fixes it for you feel free to re-open with some more information.
