### ISSUE TITLE
sentryID is null

### ISSUE THREAD

**Issue by Zabanya** [getsentry/sentry-laravel#35]
``` php
dd($this->sentryID);
return response()->view('errors.500', [
'sentryID' => $this->sentryID,
'exception' => $exception,
], 500);
```

Laravel 5.3, dd sentryID in render function always null.
do i need 'use Sentry'?

**Comment by stayallive** [comment]
Did you also copy over the [report function](https://github.com/getsentry/sentry-laravel/blob/master/examples/laravel-5.2/app/Exceptions/Handler.php#L28-L42) and add the [SentryServiceProvider](https://github.com/getsentry/sentry-laravel#laravel-5x) to you providers array in `config/app.php`? And the last question, if the events are also not showing in Sentry you should double check your DSN is correct and set in your .env file.

**Comment by Zabanya** [comment]
it was the $dontReport, i remove everything there and it worked :)
