### ISSUE TITLE
Option to disable delaySendingUntilShutdown in HttpTransport

### ISSUE THREAD

**Issue by mendicm** [getsentry/sentry-laravel#353]
It would be great to have a config option to disable delaySendingUntilShutdown in HttpTransport because in some scenarios is most reliable to get rid of all this "async" black magic in PHP or just let the developer decide.

**Comment by uniring** [comment]
Sounds like it'll miss some notifications, we're talking about PHP you know ;)

**Comment by stayallive** [comment]
We are already in the process of fasing that out, see: https://github.com/getsentry/sentry-php/blob/c4359c244b903212d8e2e23755c1087c5f362ff2/src/Transport/HttpTransport.php#L84-L86.

You can use the client builder decorator to register your own transport or set that flag if you need it today.

> https://docs.sentry.io/platforms/php/laravel/#decorating-the-client-builder
> https://docs.sentry.io/platforms/php/#transport
