### ISSUE TITLE
Crash when logging null message

### ISSUE THREAD

**Issue by cweiske** [getsentry/sentry-laravel#356]
Our code does a `Log::info(null)`, which is perfectly fine in Laravel 5.5 (`Illuminate\Log\Write::info` does not enforce `$message` to be a string).

sentry-laravel in `EventHandler::messageLoggedHandler` then tries to call `addLogBreadcrumb`, which fails because that one requires the parameter to be a string.

> Type error: Argument 2 passed to Sentry\Laravel\EventHandler::addLogBreadcrumb() must be of the type string, null given, called in vendor/sentry/sentry-laravel/src/Sentry/Laravel/EventHandler.php on line 295

----

This is with sentry/sentry-laravel v1.7.1

**Comment by cweiske** [comment]
This has been fixed by #345 already.

**Comment by stayallive** [comment]
No problem, for future readers, make sure you are on version `1.8.0` or above.
