### ISSUE TITLE
Issue running in production only on Laravel 4

### ISSUE THREAD

**Issue by samdking** [getsentry/sentry-laravel#36]
When I load in the service provider only on the production environment, by creating the following environment-specific config file in app/config/production/app.php:

```php
<?php

return [

	'providers' => [
		'Sentry\SentryLaravel\SentryLaravelServiceProvider',
	],

	'aliases' => [
		'Sentry' => 'Sentry\SentryLaravel\SentryFacade',
	],

];
```

Sentry breaks for logged in users at this point on line 85 in the service provider:

```php
                if ($app['auth']->check()) {
                    $user = $app['auth']->user();
                    $client->user_context(array(
                        'id' => $user->getAuthIdentifier(),
                    ));
                }
```

This is due to `SentryLaravelServiceProvider`'s boot method running first (by virtue of it being at the top of the list of service providers). Here is a stack trace received in public/error_log:

```
PHP Fatal error:  Call to a member function connection() on null in /path/to/app/bootstrap/compiled.php on line 7453
PHP Stack trace:
PHP   1. {main}() /path/to/app/public/index.php:0
PHP   2. Illuminate\Foundation\Application->run() /path/to/app/public/index.php:49
PHP   3. Stack\StackedHttpKernel->handle() /path/to/app/bootstrap/compiled.php:657
PHP   4. Illuminate\Cookie\Guard->handle() /path/to/app/bootstrap/compiled.php:11040
PHP   5. Illuminate\Cookie\Queue->handle() /path/to/app/bootstrap/compiled.php:8375
PHP   6. Illuminate\Session\Middleware->handle() /path/to/app/bootstrap/compiled.php:8428
PHP   7. Barryvdh\Debugbar\Middleware\Stack->handle() /path/to/app/bootstrap/compiled.php:7821
PHP   8. Illuminate\Foundation\Application->handle() /path/to/app/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
PHP   9. Illuminate\Foundation\Application->boot() /path/to/app/bootstrap/compiled.php:695
PHP  10. array_walk() /path/to/app/bootstrap/compiled.php:634
PHP  11. Illuminate\Foundation\Application->Illuminate\Foundation\{closure}() /path/to/app/bootstrap/compiled.php:634
PHP  12. Sentry\SentryLaravel\SentryLaravelServiceProvider->boot() /path/to/app/bootstrap/compiled.php:633
PHP  13. Sentry\SentryLaravel\SentryLaravelServiceProvider->bindEvents() /path/to/app/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php:38
PHP  14. Illuminate\Container\Container->offsetGet() /path/to/app/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php:51
PHP  15. Illuminate\Foundation\Application->make() /path/to/app/bootstrap/compiled.php:353
PHP  16. Illuminate\Container\Container->make() /path/to/app/bootstrap/compiled.php:583
PHP  17. Illuminate\Container\Container->build() /path/to/app/bootstrap/compiled.php:205
PHP  18. Sentry\SentryLaravel\SentryLaravelServiceProvider->Sentry\SentryLaravel\{closure}() /path/to/app/bootstrap/compiled.php:233
PHP  19. Illuminate\Auth\AuthManager->check() /path/to/app/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php:85
PHP  20. Illuminate\Support\Manager->__call() /path/to/app/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php:85
PHP  21. call_user_func_array:{/path/to/app/bootstrap/compiled.php:8296}() /path/to/app/bootstrap/compiled.php:8296
PHP  22. Illuminate\Auth\Guard->check() /path/to/app/bootstrap/compiled.php:8296
PHP  23. Illuminate\Auth\Guard->user() /path/to/app/vendor/laravel/framework/src/Illuminate/Auth/Guard.php:105
PHP  24. Illuminate\Auth\EloquentUserProvider->retrieveById() /path/to/app/vendor/laravel/framework/src/Illuminate/Auth/Guard.php:144
PHP  25. Illuminate\Database\Eloquent\Model->newQuery() /path/to/app/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:42
PHP  26. Illuminate\Database\Eloquent\Model->newQueryWithoutScopes() /path/to/app/bootstrap/compiled.php:6987
PHP  27. Illuminate\Database\Eloquent\Model->newBaseQueryBuilder() /path/to/app/bootstrap/compiled.php:6997
PHP  28. Illuminate\Database\Eloquent\Model->getConnection() /path/to/app/bootstrap/compiled.php:7020
PHP  29. Illuminate\Database\Eloquent\Model::resolveConnection() /path/to/app/bootstrap/compiled.php:7440
```

The service provider seemingly assumes the `DatabaseServiceProvider` as an example, has already been booted, which is not the case when `SentryLaravelServiceProvider` is run first. Is this an issue with the package?

Alternatively, is there a more appropriate way to make Sentry only operate in the production environment, that doesn't involve a production-only config file approach?

**Comment by dcramer** [comment]
The best way to do production only would be to log Sentry in all environments but only set DSN in production. This ensures you are running nearly the same code in dev and prod but disables reporting in dev.

**Comment by samdking** [comment]
@dcramer Thanks for your reply. I've just noticed the config file which is published in the L5 version references an env variable:

```php
return array(
    'dsn' => env('SENTRY_DSN'),
    ..
);
```

I'd be happy to submit a pull request to add this functionality (using the core `getenv` function) to the L4 config file if you think this would make this approach clearer.

**Comment by samdking** [comment]
(Assuming you meant Laravel 4 here) The notion of environment variables did exist in Laravel 4 (https://laravel.com/docs/4.2/configuration#protecting-sensitive-configuration), but doesn't appear to be the preferred method of defining environment configuration.

I would say however that the DSN comes under the bracket of "sensitive configuration", and is certainly environment specific, and therefore better suits being stored in a git-ignored .env.X.php file, rather than in a committed config file.

**Comment by Caffe1neAdd1ct** [comment]
I would +1 the should be stored in .env.x.php git ignored files as this helps with per environment configuration of legacy laravel 4 applications.

However watch out for using plain `getenv()` for boolean/null/int values in Laravel 4, Laravel 5 has an `env()` function in `helpers.php` which translates strings provided by the php ENV variables back into their appropriate types. 

A string `getenv()` of false for `breadcrumbs.sql_bindings` or `user_context` may evaluate to true accidentally enabling the feature. Also if getenv() fails it will return false which is handled better by the laravel helper function from memory.

For Laravel 4 I pulled out the env() function and put it into a polyfill composer library (https://github.com/zVPS/laravel-4-env-polyfill) which can be useful for setting the dsn & app configs in a Laravel 5 compatible way:

```
<?php
return [
    'dsn' => env('SERVICES_SENTRY_DSN', ''),
    // capture release as git sha
    'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),
    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => env('SERVICES_SENTRY_SQL_BINDINGS', true),
    // Capture default user context
    'user_context' => env('SERVICES_SENTRY_USER_CONTEXT', true),
];
```

.env.local.php
```
    'SERVICES_SENTRY_DSN' => 'http://secure:thingy@localhost:6700/2',
    'SERVICES_SENTRY_SQL_BINDINGS' => 'true',
    'SERVICES_SENTRY_USER_CONTEXT' => 'true',
```

Hope this helps any peoples still on Laravel 4

**Comment by stayallive** [comment]
^ above is really good advice for people still running 4.x and who have not solved this issue another way. However we would be soon dropping 4.x support (the 0.8.x versions will keep working on L4) while moving forward with 5.x support so we are not going to address this in the package ourselfs.
