### ISSUE TITLE
Including additional info alongside Exception to capture

### ISSUE THREAD

**Issue by amcsi** [getsentry/sentry-laravel#361]
I'm trying to include additonal information for an exception I want to explicitly capture.

I'm currently doing this:

```php
                    $sentry->captureEvent([
                        'exception' => $exception,
                        'context' => [
                            'validationErrors' => $exception->errors(),
                        ],
                    ]);
```

My exception is showing up in Sentry, but not the errors array that I'm trying to attach.

I know that I could use `configureScope()` to configure the scope and set context there, but I feel like it's inappropriate here; scope is generally for data that belongs to the entire request; but the data I want to log is for this one Sentry log entry only.
Also I could to something like this:

```php
                $sentry->configureScope(function (Scope $scope) use ($exception) {
                    $scope->setContext('validationErrors', $exception->errors());
                });
                
                $sentry->captureException($exception);

                $sentry->configureScope(function (Scope $scope) {
                    $scope->removeContext('validationErrors');
                });
```

But I'm hoping for a less messy way to do it.

**Comment by stayallive** [comment]
Hi @amcsi,

Good question, I don't think adding context to an event works like that, but you could do something like this:

```php
use function Sentry\withScope;
use function Sentry\captureException;

withScope(function (Scope $scope) use ($exception) {
    $scope->setContext('validationErrors', $exception->errors());

    captureException($exception);
});
```

You can of course also use:

```php
$sentry = app('sentry');

$sentry->withScope(function (Scope $scope) use ($exception, $sentry) {
    $scope->setContext('validationErrors', $exception->errors());

    $sentry->captureException($exception);
});
```

The `withScope` will actually remove anything you've done inside the closure (in regards to the scope) after the closure has been executed.

**Comment by amcsi** [comment]
@stayallive I was able to get it to work with the code I showed you.

But I had no idea there was this `withScope()` function that cleans itself up at the end of the callback. The code is way cleaner with that. Thanks a lot!

**Comment by amcsi** [comment]
It does keep the default user context I get with `send_default_pii => true,` though, right? I haven't actually gotten a chance to try this out yet

**Comment by stayallive** [comment]
Yes. The `withScope` copies the current scope and allows you to update it inside the closure and then removes that copied scope reverting any changes you made inside the closure (when you have the time check the code of `withScope` to see how it works exactly), but anything set outside the closure will persist and be unaffected like the user data.
