### ISSUE TITLE
Laravel 5.3 / Php 7.1.33 | Bug with symfony/polyfill-php80

### ISSUE THREAD

**Issue by acgfbr** [getsentry/sentry-laravel#362]
Hello guys, at the company I work in we had a problem today that consists of the following:

The sentry / sentry-laravel package has a dependency called sentry / sdk.

The sentry / sdk package has a dependency called sentry / sentry.

The sentry / sentry package has a dependency called php-http / client-common.

The http / client-common package has a dependency called symfony / polyfill-php80.

The bug occurs in the http / client-common package.

The dependency on symfony / polyfill-php80 made a code break because it overrides the str_contains laravel helper function, see the print below:

(the polyfill bootstrap comes before the laravel bootstrap and crash)

https://laravel.com/docs/5.3/helpers#method-str-contains

![image](https://user-images.githubusercontent.com/8755427/86414751-4ada6180-bc9b-11ea-996b-c687fc2471b7.png)

![image](https://user-images.githubusercontent.com/8755427/86414510-7a3c9e80-bc9a-11ea-9a44-a5d902f53359.png)

![image](https://user-images.githubusercontent.com/8755427/86413824-a0f9d580-bc98-11ea-9cd0-832a03059a90.png)

I basically downgraded sentry / sentry-laravel to version 0.11.0, however this is a very outdated version, is this dependency on http / client-common really necessary?

Thank you.

**Comment by SOSTheBlack** [comment]
Today I had to force the old version, I had this same problem.

This would solve the problem and I could go back to using the most current version

🤜🏾🤛🏾

**Comment by stayallive** [comment]
Yes this dependency is really needed (it's used for actually sending errors to Sentry), however we did not expect it to include a polyfill and break the Laravel `str_contains` of course.

There is an fix you can apply in your own composer to force a lower version of `php-http/client-common` which does not include the polyfill.

You can run: `composer require "php-http/client-common:2.1.*"`

Or add this manually to your `require` section of the `composer.json`:

```
	"php-http/client-common": "2.1.*"
```

Please do try to remove that version lock in the future when it might no longer be needed.

---

In future Laravel versions the global helper functions are removed so this will no longer be a problem. See the upgrade guide not for Laravel 6: https://laravel.com/docs/6.x/upgrade#helpers. So this should only be an issue on Laravel < 6 or if you re-add the helpers by requiring `laravel/helpers`.

**Comment by acgfbr** [comment]
Hi bro, dont work downgrade:
- Installing sentry/sentry-laravel (1.5.0)
 - Installing php-http/client-common (2.1.0):
- Installing symfony/polyfill-php80 (v1.17.1)

**Comment by stayallive** [comment]
You can check with `composer why symfony/polyfill-php80` to see if some other package also includes it.

Otherwise there is a way to prevent installing the polyfill package but that could have unintended side effects so use at your own risk:

```json
    "replace": {
       "symfony/polyfill-php80": "*"
    }
```
