### ISSUE TITLE
Add `ValidationException` errors as context

### ISSUE THREAD

**Issue by andrey-helldar** [getsentry/sentry-laravel#363]
When a validator error is thrown, the "data" and "rules" keys are sent to Sentry.
Seeing the data, I do not understand why the validator worked despite the fact that if the same data is run locally, then there are no errors.

Therefore, I suggest adding more messages with validator errors (`$validator>errors()->all()`).

![image](https://user-images.githubusercontent.com/10347617/87418859-26f01780-c5db-11ea-8cbb-295dfe3444f6.png)

**Comment by misbah-urrehman** [comment]
You can add the Validation errors manually using the sentry context in the Handler file (app/Exceptions/Handler.php)

`public function report(Exception $exception)
    {
        if (method_exists($exception, 'errors')) {
            $errors = $exception->errors();
            \Sentry\withScope(function (\Sentry\State\Scope $scope) use ($errors) {
                $scope->setContext('Validation Errors', [
                    'errors' => $errors
                ]);
                \Sentry\captureMessage('Validation Errors');
            });
        }

        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }

        parent::report($exception);
    }`

![image](https://user-images.githubusercontent.com/46999000/141481890-635b0367-c890-4206-a5e6-7a2c03af6724.png)

**Comment by andrey-helldar** [comment]
I made such an opportunity a long time ago by expanding the standard service.

As an addition, it also transfers the version of the code obtained from git tags. If the tag is missing, it takes the hash of the commit.

https://github.com/TheDragonCode/sentriable-laravel
