### ISSUE TITLE
Add Laravel version to tags

### ISSUE THREAD

**Issue by andrey-helldar** [getsentry/sentry-laravel#365]
In our project, the application is deployed to several different services with automatic updates.

Therefore, I suggest adding the output of the Laravel version to the tags:

![image](https://user-images.githubusercontent.com/10347617/87673762-b46b6d00-c77d-11ea-9b96-731f3296fc24.png)

```
$scope->setTag('app.version', app()->version());
```

**Comment by stayallive** [comment]
Hi @andrey-helldar, I don't think that should be something that is advisable to do.

You can do this yourself in your project or use the optional [ModulesIntegration](https://github.com/getsentry/sentry-php/blob/f2b11fe0526b422cefb454a0a271c05740d1b709/src/Integration/ModulesIntegration.php) which would list all installed composer packages and their versions.

For most people I would suggest having a `composer.lock` and tie that to your release process so you know which Laravel version you are running for your release version (which you can set in `config/sentry.php`).

**Comment by andrey-helldar** [comment]
Hi @stayallive, I connected the integration module for displaying versions of installed packages, but Sentry does not allow filtering events by them (or I did not find how to do this). Therefore, I suggested adding the version of the application itself to tags.

As for the name "laravel.version" instead of "app.version", this is a moot point. After all, the package "sentry / sentry-laravel" is installed only on Laravel / Lumen and I think it is unnecessary to add this word again.

In addition, I did not manage to add tags through integrations.

**Doesn't work:**
![image](https://user-images.githubusercontent.com/10347617/88033193-b5b6e400-cb47-11ea-871f-ac9e59d491b0.png)

**Working:**
![image](https://user-images.githubusercontent.com/10347617/88033219-c1a2a600-cb47-11ea-9ced-08ff33d70f9b.png)

**Comment by stayallive** [comment]
Ah, I'm sorry I did not realise you wanted to search for this and that you can't do that inside Sentry.

About setting the tags, you are almost doing it correctly, you are doing:

```php
SentrySdk::getCurrentHub()->withScope(function (Scope $scope) { ... });
```

However that is wrong, `withScope` will discard any changes made to the scope after the closure finished running, you should use `configureScope`.

You want:

```php
SentrySdk::getCurrentHub()->configureScope(function (Scope $scope) { ... });

// or

if (app()->bound('sentry')) {
	app('sentry')->configureScope(function (Scope $scope) { ... });
}
```

See the docs outlining this: https://docs.sentry.io/platforms/php/#tagging-events

**Comment by andrey-helldar** [comment]
I understood which version of the application you are talking about. I agree with you that it is correct to name "laravel.version".

About tags. Now, to add tags, I created a class in which I define them, and I transfer errors to Sentry through it:

![image](https://user-images.githubusercontent.com/10347617/88036374-2233e200-cb4c-11ea-8703-9c8eacfbe769.png)
![image](https://user-images.githubusercontent.com/10347617/88036384-26f89600-cb4c-11ea-9f5c-bb74135a5584.png)
![image](https://user-images.githubusercontent.com/10347617/88036405-2e1fa400-cb4c-11ea-833b-52fd7033f70a.png)

In this case, all tags are successfully attached.

But if I set tags in the integration, then they are not attached to the request.

![image](https://user-images.githubusercontent.com/10347617/88036130-ccf7d080-cb4b-11ea-8524-4746f5130ca3.png)
![image](https://user-images.githubusercontent.com/10347617/88036517-55767100-cb4c-11ea-900c-4797316881a4.png)

**Comment by andrey-helldar** [comment]
But:

![image](https://user-images.githubusercontent.com/10347617/88037237-4fcd5b00-cb4d-11ea-99cc-2d52b708546b.png)
![image](https://user-images.githubusercontent.com/10347617/88037273-5956c300-cb4d-11ea-9a28-8b2e71067363.png)

**Comment by andrey-helldar** [comment]
I found a solution - the provider created a service and showed all the necessary data in it.

![image](https://user-images.githubusercontent.com/10347617/88040056-0a129180-cb51-11ea-9e2c-3f0bb2c7dca4.png)
![image](https://user-images.githubusercontent.com/10347617/88040090-14349000-cb51-11ea-8bea-96fa4bd18acd.png)

👍
