### ISSUE TITLE
No config file is created with command on Laravel 7

### ISSUE THREAD

**Issue by 0xSheff** [getsentry/sentry-laravel#367]
Hello, when I use command
php artisan vendor:publish --provider="Sentry\SentryLaravel\SentryLaravelServiceProvider"

I got error
Unable to locate publishable resources.
Publishing complete.

I'm using Laravel 7.25.0 
sentry/sentry-laravel is installed, v.1.8.0

**Comment by stayallive** [comment]
Try: `php artisan vendor:publish --provider="Sentry\Laravel\ServiceProvider"`.

I think you are reading the old docs, the correct ones are here: https://docs.sentry.io/platforms/php/laravel/.

**Comment by 0xSheff** [comment]
Thank you, it works
