### ISSUE TITLE
Sentry exceptions are not showing when php artisan sentry:test success

### ISSUE THREAD

**Issue by InvokerMaster** [getsentry/sentry-laravel#369]
![image](https://user-images.githubusercontent.com/31196185/90579172-2ecf4880-e193-11ea-9410-5cbc2ee4ef93.png)

I have checked the api calling part for getting the response from Sentry server, but it is showing 200 and it seems correct.
But it's not showing on Sentry dashboard.
Can anybody check this and tell me if this is the problem of SDK or the Server configuration?
I am using OnPremise Sentry on my server and this is using LAN for the log.
Thank you

**Comment by stayallive** [comment]
Hi @InvokerMaster, it's really hard for me to debug this, you've done a good chunk of it! It looks like an event is generated correctly and accepted by your Sentry server but it's not showing on your dashboard.

This can have any number of reasons but my first thing to check would be if your Sentry instance is processing events, because if you get a 200 OK response I would suggest Sentry accepted the event but is not processing it to be available on your dashboard and say the SDK is doing it's job.

**Comment by InvokerMaster** [comment]
I see. So this would be the problem of misconfiguration on the Sentry dashboard or the serverside code?

**Comment by stayallive** [comment]
I cannot tell you for sure, but it does look like it. Possibly the workers aren't running. Events are put on a queue by the Sentry server and if the processing queue is not running they will never show up in the dashboard.

Bit of a cop out, but the SDK works on sentry.io so I want to say it's your Sentry instance which is causing issues, but again I cannot be sure.

**Comment by stayallive** [comment]
Hey @InvokerMaster I see you closed it so I assume it's resolved, if you've found the issue it would be nice to let us know what it was in the end, other people googling could learn from it!

**Comment by Smmw** [comment]
@InvokerMaster 
I met the same problem on the self-hosted sentry, 
Run this command locally:
![image](https://user-images.githubusercontent.com/3632980/108128848-41aae180-7112-11eb-9c22-d484bbd898f8.png)
But on the dashboard, the event did not show up.

For production: 
I can see the issue in the `release` tab:
![image](https://user-images.githubusercontent.com/3632980/108129004-70c15300-7112-11eb-882f-9fe966bc9273.png)

When I click issue, there is nothing.

The sentry was working before, and it stopped a week ago.

Could you please let me know how you fixed the problem?

Thanks!

Laravel: 5.7.29
sentry/sentry-laravel: 0.10.1

**Comment by stayallive** [comment]
@Smmw please try out the latest version which is `2.3.1` and if that doesn't work please open up a new issue so we can investigate for your specific case.

**Comment by Smmw** [comment]
@stayallive That was the docker issue in the server, the problem has been solved, thanks!

**Comment by sekroots** [comment]
Hello. Could you share more information about wat was the issue? I am facing the same problem here.
Sentry shows exceptions from laravel/php artisan like this:
- [PDOException /artisan in ?]
- [Exception /artisan in ?] 
thanks

**Comment by alexgilbertDG** [comment]
@Smmw Can you explain what was your fix for this issue ? I got a similar situation.
