### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-laravel#371]
Laravel 8 support for the Sentry Laravel integration will be released on the day (currently planned for 8 september 2020) that Laravel 8 is released.

No need to create PR's or issues for this, it is on the radar and we will make sure Laravel 8 support will be there on release day 💪

**Comment by stayallive** [comment]
Unfortunately Laravel 8 requires Guzzle 7 which the PHP SDK is not yet ready for.

You will need to modify your `composer.json` to include these requirements and replacements for now:

```
{
    "require": {
        "sentry/sentry-laravel": "^1.9",
        "sentry/sentry": "^2.4",
        "http-interop/http-factory-guzzle": "^1.0",
        "php-http/curl-client": "^2.0",
        "guzzlehttp/guzzle": "^7.0"
    },
    "replace": {
        "sentry/sdk": "*"
    }
}
```

**Comment by stayallive** [comment]
@everyone (that doesn't work here unfortunately so I hope everyone subscribed)

We've just released an [update](https://github.com/getsentry/sentry-php-sdk/pull/7) to our underlying `sentry/sdk` package to no longer depend on Guzzle (any version). So the Sentry PHP SDK and also Sentry Laravel can be installed alongside Guzzle 6 or 7 without issues now.

The long and the short is: you can remove changes made to your composer.json and you should only have to require `"sentry/sentry-laravel": "^1.9"` to use Sentry in Laravel 🥳

**Comment by asman03** [comment]
i have problem with this when installing sentry in laravel 8,

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sentry/sentry-laravel 2.x-dev is an alias of sentry/sentry-laravel dev-master and thus requires it to be installed too.
    - sentry/sentry-laravel[dev-master, 2.7.0] require sentry/sdk ^3.1 -> satisfiable by sentry/sdk[3.1.0].
    - sentry/sdk 3.1.0 requires http-interop/http-factory-guzzle ^1.0 -> satisfiable by http-interop/http-factory-guzzle[1.0.0].
    - http-interop/http-factory-guzzle 1.0.0 requires guzzlehttp/psr7 ^1.4.2 -> found guzzlehttp/psr7[1.4.2, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires sentry/sentry-laravel ^2.7 -> satisfiable by sentry/sentry-laravel[2.7.0, 2.x-dev (alias of dev-master)].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


can you help me? thank you

**Comment by stayallive** [comment]
@asman03 check out this comment and try that: https://github.com/getsentry/sentry-laravel/issues/500#issuecomment-872251486.

**Comment by sbellver** [comment]
@asman03 same here :'(
