### ISSUE TITLE
[Beta] Sentry\UserDataBag::setId() must be of the type string or null, int given

### ISSUE THREAD

**Issue by rocramer** [getsentry/sentry-laravel#372]
I'm using the `performance/beta` branch to use the new sentry performance feature. Worked like a charm. Since a few days I am getting the following error message:

`Argument 1 passed to Sentry\UserDataBag::setId() must be of the type string or null, int given, called in /var/www/html/vendor/sentry/sentry/src/UserDataBag.php on line 83 `

When disabling `send_default_pii` to false everything works.

**Comment by stayallive** [comment]
This is only when using the APM branch, which runs on an unstable version of the PHP SDK which has an oversight in the design (ID's must be strings) or in the Laravel integration (not making sure an ID is a string). We're fixing it either way but I wanted to let you know were on it and for people reading here this _does not_ affect the stable released versions.

Thanks for reporting this, when fixed i'll update the issue 👍

**Comment by stayallive** [comment]
@rocramer a fix (getsentry/sentry-php#1078) was just merged, so in theory after a `composer update` this should be fixed 👍

**Comment by rocramer** [comment]
Great, thanks!
