### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by deva7mad** [getsentry/sentry-laravel#375]
I followed all the instructions in the [setup guide](https://docs.sentry.io/platforms/php/guides/laravel/)

**Environment details:**
- PHP version: 7.4.9
- Laravel version: ^7.0

**When try to install sentry version 1.8 i got the following exception:**

```
Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].
    - sentry/sentry-laravel 1.8.0 requires sentry/sdk ^2.1 -> satisfiable by sentry/sdk[2.1.0].
    - sentry/sentry-laravel 1.x-dev requires sentry/sdk ^2.1 -> satisfiable by sentry/sdk[2.1.0].
    - Conclusion: don't install sentry/sdk 2.1.0
    - Installation request for sentry/sentry-laravel ^1.8 -> satisfiable by sentry/sentry-laravel[1.8.0, 1.x-dev].
```

**I used version 1.7 and try to publish config file like the docs says. I got**

```
php artisan vendor:publish --provider="Sentry\Laravel\ServiceProvider"

Unable to locate publishable resources.
Publishing complete.
```

**Comment by stayallive** [comment]
Sentry (Laravel) is currently not compatible with Guzzle 7 out of the box.

See here for updates and or workarounds: getsentry/sentry-php#1059

If you couldn't install 1.8 you should also not be able to install 1.7 I believe, not a 100% on that but that might be the cause why you cant publish the config file.

**Comment by stayallive** [comment]
We've just fixed the issue with Guzzle 7 too, so everything should work as expected.

Please re-open / open a new issue if the issue persists.
