### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by Swop** [getsentry/sentry-laravel#376]
@stayallive @HazAT Any plan to support Laravel 8?

The release date is today, and you have a lock on dependencies for laravel <= 7

Thanks!

**Comment by mfn** [comment]
https://github.com/getsentry/sentry-laravel/releases/tag/1.9.0 🤔

**Comment by stayallive** [comment]
Yeah. Was released yesterday as 1.9.0 🤘

**Comment by Swop** [comment]
Sorry, my bad didn't see that. Thanks!
