### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by jimping** [getsentry/sentry-laravel#377]
Problem 1
    - Installation request for sentry/sentry-laravel ^1.8 -> satisfiable by sentry/sentry-laravel[1.8.0, 1.9.0, 1.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].

**Comment by stayallive** [comment]
Sentry is not (yet) compatible with Guzzle 7 see: https://github.com/getsentry/sentry-php/issues/1059#issuecomment-668115006. 

Guzzle 7 is not a Laravel 8 requirement but if you can't use Guzzle 6 a workaround can be found in the comments if the issue linked above.
