### ISSUE TITLE
Can't install on Laravel 8

### ISSUE THREAD

**Issue by koushik355** [getsentry/sentry-laravel#380]
Hi, I can't install it on Laravel 8. Please update. Because of this, I can't update my entire project. 
Steps to reproduce --

1. install a brand new laravel 8 project
2. try installing sentry/laravel

![image](https://user-images.githubusercontent.com/66407490/93020383-5ed70380-f5fa-11ea-8e42-b868ce104687.png)

Please fix this ASAP. Thank you.

**Comment by nklasio** [comment]
see #371 
works fine with the mentioned workaround

**Comment by stayallive** [comment]
Working hard on it without any special instructions but for now see: https://github.com/getsentry/sentry-laravel/issues/371#issuecomment-689084918.
