### ISSUE TITLE
Laravel 8.6 - The option "traces_sample_rate" does not exist.

### ISSUE THREAD

**Issue by robmellett** [getsentry/sentry-laravel#389]
Hey guys,

This new tracing ability looks great!

We've hit a roadblock on unit tests though. When one of our controllers throws an exception our unit tests dump 

```
   Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException 

  The option "traces_sample_rate" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enable_compression", "environment", "error_types", "excluded_exceptions", "http_proxy", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "project_root", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags".
```

Within `config/sentry.php` I've tried to disable the the 'traces_sample_rate' using the values `0` and `null`, but the error remains.

The only way to get the tests working again is by disabling the key 'traces_sample_rate' entirely.

It would be great to disable this feature during tests.

```
Laravel: 8.6
sentry/sentry-laravel: 2.0
```

**Comment by stayallive** [comment]
You should disable Sentry entirely by setting the DSN to `null` when testing or in your local environment. But thats another discussion :)

The only conclusion I can make with this information is that somehow the `sentry/sentry` package (which is the base PHP SDK) is not version 3.0. However, that should be impossible when using `sentry/sentry-laravel` 2.0. Can you double check this?

The error is that the SDK doesn't know the `traces_sample_rate` option which means the SDK doesn't have tracing support and that is why I'm coming to this conclusion.

**Comment by robmellett** [comment]
Hey @stayallive,

Thank you very much for the reply.  We managed to resolve it by copying the line from the updated `config/sentry.php`

```
'traces_sample_rate' => \floatval(env('SENTRY_TRACES_SAMPLE_RATE', 0.0))
```

I owe you a beer internet friend :)

**Comment by stayallive** [comment]
I'm still a bit puzzled why not having that would result in the error you got... 😕 

But as long as the problem is solved I'm glad (something, something computers and such) 👍
