### ISSUE TITLE
Call to undefined method Sentry\Laravel\Tracing\ViewEngineDecorator::startLivewireRendering() 

### ISSUE THREAD

**Issue by ziming** [getsentry/sentry-laravel#394]
I'm using Livewire 1 if it helps.

Downgrading sentry to 2.0 from 2.0.1 works.

**Comment by stayallive** [comment]
> Downgrading sentry to 2.0 from 2.0.1 works.

This sounds like an upgrade... :) Downgrading to 1.9 you mean?

It definitely helps to know you are using Livewire (although the error gave it away a bit), I'd have to look into it but I assume there are some clashes between our tracing setup and Livewire.

I'd advise you to stay on 1.9.x until we resolve it! Thanks for reporting!

**Comment by ziming** [comment]
I downgrade it to 2.0, not 1.9

**Comment by stayallive** [comment]
2.0 has the broken code so that puzzles me... however I found and fixed the issue and that should be released in the next bugfix release: #395.

Feel free to test it out by changing your `composer.json` to include:

```json
"sentry/sentry-laravel": "dev-dev-feature/actually-decorate-the-view-engine@dev"
```

Don't forget to change this back to the "normal" versions after testing and after this is released:

```json
"sentry/sentry-laravel": "^2.0"
```

**Comment by lukerenfrew** [comment]
Just experienced this issue and got it working by implementing the exact code in the PR. Came here to see if I could submit a pull request and saw this.

Checked out the branch and it solves the issue  👍 

Thanks for your work on this

**Comment by stayallive** [comment]
[`2.1.0`](https://github.com/getsentry/sentry-laravel/releases/tag/2.1.0) was just released which should fix this, thank you all for your reports and testing!
