### ISSUE TITLE
Unable to pull event_id / Ident from a thrown exception

### ISSUE THREAD

**Issue by luaduck** [getsentry/sentry-laravel#4]
Say I've got a custom 500 view that, right now, shows an event ID (generated by laravel-exceptions in this case) that's passed in from the generator. I could just do something like this:

```php
$event_id = app('sentry')->getIdent(app('sentry')->captureException($e));
```
to capture the event_id from the captured exception, but if I do that in `Exceptions\Handler::report()` then I can't access it when my view later gets called by the parent's render() routine.

A possible fix would be having something along the lines of `Sentry::getLastEventId()` as per [clowdy/laravel-raven](https://github.com/clowdy/laravel-raven)'s identically named function (which I can just call from my custom view).

Any ideas?

**Comment by dcramer** [comment]
I think we simply need to add the hook to the ``sentry-php`` core, and then it'd be expoed via app('sentry') easily enough.
