### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by nssmart** [getsentry/sentry-laravel#404]
Index page of a project (readme) contains links for Laravel integration. Haven't check the others, but the Lumen one is broken (https://docs.sentry.io/platforms/php/guides/laravel/lumen/)

**Comment by stayallive** [comment]
Ahh something is not redirecting properly, thanks for letting me know, I've fixed the links!

**Comment by nssmart** [comment]
Thanks

**Comment by stayallive** [comment]
Also thank you for making this issue with number #404, very fitting 😉
