### ISSUE TITLE
How to get a better trace through the application

### ISSUE THREAD

**Issue by websmurf** [getsentry/sentry-laravel#407]
Small question, I recently started experimenting with the trace option in Sentry. I notice the `app.handle` part is pretty large and not further split up:

![image](https://user-images.githubusercontent.com/4027236/97604357-ab8d6700-1a0d-11eb-8b41-13eaa45f3f3a.png)

In what was can we create more detail in the app.handle part?

**Comment by stayallive** [comment]
Good question, `app.handle` is the full application and can (and probably should) have more detail. 

For example if you app renders views or executes queries they will show up as a child of the `app.handle` but out of the box those are the only 2 implemented. 

You can also add your own `span`s to the transaction created to measure things you'd like to measure. 


When you want to measure something happening you can see how we implemented the view tracing for inspiration: https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php#L38

For a measurement you already know the start and end time of you can see how we record queries: https://github.com/getsentry/sentry-laravel/blob/daace27170cb851564dc9552b0dfeed903872697/src/Sentry/Laravel/Tracing/EventHandler.php#L147

Possibly this generic docs will help with some context: https://docs.sentry.io/platforms/php/performance/#manual-instrumentation

Let me know of that helps and/or if you have more questions.

**Comment by websmurf** [comment]
Oki, makes sense. We use the event dispatcher quite intensively; will see if I can hook into that somehow :-)

**Comment by websmurf** [comment]
![image](https://user-images.githubusercontent.com/4027236/97886295-b5bea680-1d28-11eb-832b-a218ace373d5.png)

That's more like it :-)
Thanks for the input!

**Comment by websmurf** [comment]
If anyone is interested, we use laravel-doctrine in stead of Eloquent, this logger will make the queries visible in the performance timeline:

```php
<?php
/**
 * Bandhosting klanten systeem
 *
 * @copyright Bandhosting.nl
 * @author    Adam van Dongen
 */

declare(strict_types=1);

namespace App\Loggers\Doctrine;

use Doctrine\DBAL\Logging\SQLLogger;
use Doctrine\ORM\Configuration;
use Doctrine\ORM\EntityManagerInterface;
use LaravelDoctrine\ORM\Loggers\Logger;
use Sentry\SentrySdk;
use Sentry\State\HubInterface;
use Sentry\Tracing\Span;
use Sentry\Tracing\SpanContext;

/**
 * Class SentryLogger
 *
 * @package Doctrine
 */
class SentryLogger implements SQLLogger, Logger
{
    private ?Span $span = null;
    private HubInterface $hub;

    /**
     * {@inheritDoc}
     */
    public function register(EntityManagerInterface $em, Configuration $configuration): void
    {
        $this->hub = SentrySdk::getCurrentHub();
        $configuration->setSQLLogger($this);
    }

    /**
     * {@inheritDoc}
     */
    public function startQuery($sql, ?array $params = null, ?array $types = null): void
    {
        $parentSpan = $this->hub->getSpan();

        if ($parentSpan === null) {
            return;
        }

        $context = new SpanContext();
        $context->setOp('doctrine.query');
        $context->setDescription($sql);

        $this->span = $parentSpan->startChild($context);

        $scope = $this->hub->pushScope();
        $scope->setSpan($this->span);
    }

    /**
     * {@inheritDoc}
     */
    public function stopQuery(): void
    {
        if ($this->span === null) {
            return;
        }

        $this->span->finish();
        $this->hub->popScope();
    }
}
```

Configure it in your .env file:
```
DOCTRINE_LOGGER=App\Loggers\Doctrine\SentryLogger
```

**Comment by stayallive** [comment]
Looking good, and thank you for sharing the Doctrine logger, probably useful for someone 💪

**Comment by laurentvd** [comment]
Thanks for sharing @websmurf!

**Comment by laurentvd** [comment]
If you set the operation to `db.sql.query`, Sentry recognizes it as a query and shows it in the "most time consuming queries" panel etc. To do so, change `$context->setOp('doctrine.query');` into `$context->setOp('db.sql.query');`.
