### ISSUE TITLE
There are no commands defined in the "sentry" namespace.

### ISSUE THREAD

**Issue by abdullbasitmemon** [getsentry/sentry-laravel#412]
When I am running command on sever `php artisan sentry:test` it is showing error There are no commands defined in the "sentry" namespace.

Laravel version 8
PHP v7.4
AWS-EC2

**Comment by stayallive** [comment]
This would mean that either `sentry/sentry-laravel` is not installed or you have autodiscovering of packages disabled.

Can you check:
- You have `sentry/sentry-laravel` listed as a dependency in your `composer.json`
- By running `composer update` the package is installed and your `composer.lock` is up-to-date
- You can see `vendor/sentry/sentry-laravel` folder in your app

If that all is good, can you share your `composer.json`?

**Comment by abdullbasitmemon** [comment]
I can not run `composer update` command on server, I am facing memory_limit issue. I have installed sentry on my local, it is working fine on local then I uploaded vendor folder and all dependent file like config/sentry.php but still I am facing this issue. May be I am missing something.

Here is my `composer.json`

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.5",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "sentry/sentry-laravel": "^2.1",
        "sendgrid/sendgrid": "~7",
        "yajra/laravel-datatables-oracle": "~9.0"
    },
    "require-dev": {
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

**Comment by stayallive** [comment]
Yes I think you are missing the updated files in the `bootstrap` folder.

But there is an easy fix for that, run: `php artisan package:discover`.

If you are facing memory issues with Composer on your server upload the `composer.lock` file generated locally and run `composer install`, this will install the exact versions and will require significantly less memory and will also run the `post-autoload-dump` scripts from the `composer.json` correctly liek the `package:discover` artisan command.

**Comment by abdullbasitmemon** [comment]
Thanks for your support it is fixed now. 👍 :)
