### ISSUE TITLE
Tracing does not work on Laravel 5.4

### ISSUE THREAD

**Issue by luisgrases** [getsentry/sentry-laravel#423]
Followed the instructions to setup sentry on Laravel from https://docs.sentry.io/platforms/php/guides/laravel/configuration/other-versions/laravel5-6/.

After I finished the setup, I interact with my local environment but not seeing any transactions being logged into the "Performance" tab on sentry.

- I do see the exceptions being reported and showing on sentry tho.
- The `php artisan sentry:test --transaction` seems to work fine, the transaction is logged in sentry.
- `traces_sample_rate` is set to 1.0

Any ideas?

Package versions:
```
"php": "7.3.24",
"laravel/framework": "5.4.36",
"sentry/sentry-laravel": "2.20",
```

**Comment by stayallive** [comment]
Yes I think I know what is going on here, you need to add another service provider manually.

```diff
 'providers' => array(
     // ...
     Sentry\Laravel\ServiceProvider::class,
+    Sentry\Laravel\Tracing\ServiceProvider::class,
 ),
```

Let me know if that works, tracing has not yet been tested on `5.4`.

**Comment by luisgrases** [comment]
that did not work, getting the following error:
```
(1/1) FatalThrowableError
Type error: Argument 1 passed to Sentry\Laravel\Tracing\ServiceProvider::wrapViewEngine() must be an instance of Illuminate\Contracts\View\Engine, instance of Illuminate\View\Engines\CompilerEngine given, called in /opt/foresight/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ServiceProvider.php on line 50
```

**Comment by stayallive** [comment]
Jep, it does activate now but it is not compatible with Laravel 5.4 yet unfortunately.

I'll leave this open to track this request.

**Comment by muhammad-zakir** [comment]
> > that did not work, getting the following error:
> > ```
> > (1/1) FatalThrowableError
> > Type error: Argument 1 passed to Sentry\Laravel\Tracing\ServiceProvider::wrapViewEngine() must be an instance of Illuminate\Contracts\View\Engine, instance of Illuminate\View\Engines\CompilerEngine given, called in /opt/foresight/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ServiceProvider.php on line 50
> > ```
> 
> I got the same error and solved it by disabling views tracing: tracing.views = false in config/sentry.php
> So after adding Sentry\Laravel\Tracing\ServiceProvider::class to the app.php and disabling views tracing - it works fine for me and I can see new transactions in the Sentry dashboard

How do you exactly disable the views tracing? I've tried putting it this way within the config/sentry.php:
```
'tracing' => [
    'views' => false
]
```

But I've got this error instead:
```
The option "tracing" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enable_compression", "environment", "error_types", "http_proxy", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags", "traces_sample_rate", "traces_sampler".
```

**Comment by stayallive** [comment]
That should definitely work, which version of the Laravel integration are you using?

**Comment by muhammad-zakir** [comment]
> That should definitely work, which version of the Laravel integration are you using?

I'm currently using version `2.3.1`

**Comment by stayallive** [comment]
Try upgrading to at least 2.5.0 where that option was introduced.

**Comment by muhammad-zakir** [comment]
> Try upgrading to at least 2.5.0 where that option was introduced.

That solved it. Thank you so much for the help!
