### ISSUE TITLE
Release tracking for commits.

### ISSUE THREAD

**Issue by Traqza** [getsentry/sentry-laravel#426]
Having issues with release tracking

https://stackoverflow.com/questions/65066899/release-tracking-an-error-doesnt-associate-to-a-recent-release

I have added tag to the middleware for sentry and laravel.

 $scope->setTag('release', trim(exec('git ' . base_path('.git-ftp.log') . ' log --pretty="%h" -n1 HEAD')) ? : 'No Valid Tag?' ); but it wont associate a tag, even with a static typed value matching to a old commit hash that sentry sees in the `releases` menu

See https://docs.sentry.io/platforms/php/guides/laravel/enriching-events/scopes/

I believe theres an issue with the SDK.

I have tested and confirmed that I can verify the commit hash are both current, and matching

Please Message me on Sentry Discord under user Levi Z

**Comment by stayallive** [comment]
That is because it's not a tag you need to set.

Try setting `release` in [`config/sentry.php`](https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php#L8) instead.

**Comment by Traqza** [comment]
> 
> 
> That is because it's not a tag you need to set.
> 
> Try setting `release` in [`config/sentry.php`](https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php#L8) instead.

I did that, and still nothing.

**Comment by stayallive** [comment]
You can make sure by using `php artisan tinker` and executing `config('sentry.release')` to see if that value is actually there (and correct), if it's not you might have config caching enabled (try clearing with `php artisan config:clear`) or trying to set it as a plain string to see if that helps.

**Comment by Traqza** [comment]
> 
> 
> You can make sure by using `php artisan tinker` and executing `config('sentry.release')` to see if that value is actually there (and correct), if it's not you might have config caching enabled (try clearing with `php artisan config:clear`) or trying to set it as a plain string to see if that helps.

Same result. I validated that its the commit hash from the repo, on sentry, and as a text file that a FTP file upload for pipelines leaves in my production directory called .git-ftp.log. All are the same hashes.

Cache is good as well.

**Comment by stayallive** [comment]
Okay, okay, this is getting trickier 😄 

I have one other thing you can check, when you trigger your test error, you can go to the issue interface on sentry.io and view the received JSON:

![image](https://user-images.githubusercontent.com/1090754/101137467-2b12e500-360f-11eb-93cf-7ae0bc2d7985.png)

In this JSON file there should be a key called `release`, can you double check that also doesn't contain the correct value?

**Comment by Traqza** [comment]
My commit hash from Bitbucket is - 3bfc58925269d0f8c5bafdcff5d1b2016c9a8299
My commit hash from Pipeline FTP upload to staging server for the latest commit is - 3bfc58925269d0f8c5bafdcff5d1b2016c9a8299
My commit hash from Sentry "Releases" showing the last commit to my repository - 3bfc58925269d0f8c5bafdcff5d1b2016c9a8299
My Tags from Sentry for the submitted code breaking change (error)
![image](https://user-images.githubusercontent.com/17535556/101270883-678b3180-3732-11eb-8e59-436bc7183c85.png)
My JSON for the error 
![image](https://user-images.githubusercontent.com/17535556/101270892-7e318880-3732-11eb-8da1-52b6cb1d1a58.png)
My sentry config file
![image](https://user-images.githubusercontent.com/17535556/101270899-8e496800-3732-11eb-8ed2-289ba066f36f.png)
My SentryUserContext middleware
![image](https://user-images.githubusercontent.com/17535556/101270903-9acdc080-3732-11eb-97d4-16acaf960e1d.png)

**Comment by Traqza** [comment]
Even if I manually key a 'release' into the config file of sentry, I get the same result. I have also tried associating the release that's on the production server via the SentryUserContext middleware as you can see above, and still same result. Nothing shows releases.

**Comment by Traqza** [comment]
I am happy to do a screenshare with you to go over everything so you can visually see it.

**Comment by Traqza** [comment]
Lastly, for what its worth here is my composer.json

![image](https://user-images.githubusercontent.com/17535556/101271175-61e31b00-3735-11eb-8197-81d1938c0497.png)

**Comment by Traqza** [comment]
I have also tried

```
<?php

return [

    'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),

    // capture release as git sha
    'release' => trim(preg_replace("/\s\s+/",'',file_get_contents('.git-ftp.log'))) ? : 'Default-Release-Hash',

    'breadcrumbs' => [
        // Capture Laravel logs in breadcrumbs
        'logs' => true,

        // Capture SQL queries in breadcrumbs
        'sql_queries' => true,

        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => true,

        // Capture queue job information in breadcrumbs
        'queue_info' => true,
    ],

];
```

I have validated that ```trim(preg_replace("/\s\s+/",'',file_get_contents('.git-ftp.log')))``` Will display the hash id from the .git-ftp.log via tinker, however when I attempt to echo the result from the config, i return a null. 

If I add a string text default to it, I get null.

If I add just a string text without the trim(...) and do 'sentry-release-test' I return a null.

![image](https://user-images.githubusercontent.com/17535556/101304812-ff9e1f00-37f5-11eb-8cbf-34974599b550.png)

**Comment by Traqza** [comment]
So i've tracked it back to Sentry/src/Client.php - Line 231 for ```$event->setRelease($this->options->getRelease());``` If I change the object to a static text, I will get the release to post to Sentry. It appears its not being set correctly.

If I set this line to ```$event->setRelease(trim(preg_replace("/\s\s+/",'',file_get_contents('.git-ftp.log'))));``` I will get the correct release information associated to my last commit, and in Sentry.

![image](https://user-images.githubusercontent.com/17535556/101312197-fe75ed80-3807-11eb-891a-c92aabae7fd9.png)

**Comment by Traqza** [comment]
Alright, it appears that Releases tab on Sentry is now showing an issue related to the comment now. However the only way I can get this to trigger is by editing the source code for Sentry Laravel inside the Vendor directory. This isnt ideal, but its working? 

![image](https://user-images.githubusercontent.com/17535556/101313061-33833f80-380a-11eb-952a-527cc3d26546.png)

**Comment by stayallive** [comment]
What exactly did you need to edit in the source code to make it work?

**Comment by stayallive** [comment]
I want to make sure it going right because I'm using in multiple apps the release tracking and don't see any issue. Did you try setting the release hardcoded in your config file?

```php
<?php

return [

    'release' => 'your-release-sha',

];
```

This passes the option directly to the sentry-php SDK so unless you are doing something to not use the Sentry client as initialised by this package the `$this->options->getRelease()` should hold the value as set in your config file.

**Comment by stayallive** [comment]
Also you need to restart `php artisan tinker` after you modified your `config/sentry.php` otherwise the value will never be shown! And if after a restart of tinker is still not shown, make sure to run `php artisan config:clear` before starting tinker.

**Comment by stayallive** [comment]
This code might also not work as you'd expect depending on where that `.git-ftp.log` file is, if it's in the root of you application you might need to do this instead (and also think just a trim is enough):

```php
trim(file_get_contents(base_path('.git-ftp.log'))) ?: 'Default-Release-Hash',
```

**Comment by Traqza** [comment]
> 
> 
> I want to make sure it going right because I'm using in multiple apps the release tracking and don't see any issue. Did you try setting the release hardcoded in your config file?
> 
> ```
> <?php
> 
> return [
> 
>     'release' => 'your-release-sha',
> 
> ];
> ```
> 
> This passes the option directly to the sentry-php SDK so unless you are doing something to not use the Sentry client as initialised by this package the `$this->options->getRelease()` should hold the value as set in your config file.

Yes

**Comment by Traqza** [comment]
> 
> 
> Also you need to restart `php artisan tinker` after you modified your `config/sentry.php` otherwise the value will never be shown! And if after a restart of tinker is still not shown, make sure to run `php artisan config:clear` before starting tinker.

Tried, no avail.

**Comment by Traqza** [comment]
> 
> 
> This code might also not work as you'd expect depending on where that `.git-ftp.log` file is, if it's in the root of you application you might need to do this instead (and also think just a trim is enough):
> 
> ```
> trim(file_get_contents(base_path('.git-ftp.log'))) ?: 'Default-Release-Hash',
> ```

Does not work. Returns null, with or without static text. Cleared config, and cache as well.

**Comment by Traqza** [comment]
The only way ive been able to get it to work is with editing `$event->setRelease($this->options->getRelease());`

**Comment by stayallive** [comment]
Can you tell me the version of the `sentry/sentry` package you are running (you can check with `composer info sentry/sentry`, should be something like: `versions : * 3.1.1`)? 

I'm seeing from your screenshot you are running version `2.2.0` of the Laravel package which is good.

Setting `$event->setRelease($this->options->getRelease());` is the weird part to mee because that tells me `config('sentry.release')` was set with he correct value... otherwise that would never end up in `$this->options->getRelease()` which is what puzzles me so I hope to setup a test project with the versions you are running so I hopefully find the same problem you are facing!

**Comment by Traqza** [comment]
I updated to the latest, and now getting things passing correctly. Not sure why it was giving me grief. Thanks for the help. You can close this out.
