### ISSUE TITLE
Using proxy when submitting exceptions via PHP

### ISSUE THREAD

**Issue by OwenMelbz** [getsentry/sentry-laravel#43]
Hi guys, recently we started to migrate all our exception handling over to Sentry.

However we've got a cluster of servers which have restricted internet connection, so the only way they can contact the internet is via a proxy.

E.g. when we use `curl` on the project we have a set up similar to

```php
        $proxy = '147.128.9.224:8080';

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_PROXY, $proxy);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        try {
            $file_contents = curl_exec($ch);
        }
        catch(Exception $e){
            $file_contents = false;
        }

        curl_close($ch);
```

So we just pass in the proxy to the curl request - how can we apply this same logic to the Sentry/Raven handler within laravel and within the standard php package?

Thanks

**Comment by stayallive** [comment]
I _believe_ (but untested) you can add this in your `sentry.php` configuration file to make this work.

```php
'config' => [
    'http_proxy' => $proxy,
]
```

The config key in the sentry config should be passed to the Sentry PHP SDK and `http_proxy` is the config key you would pass to the PHP SDK to set the `CURLOPT_PROXY` on the curl handler.

**Comment by OwenMelbz** [comment]
Ah lovely thanks for the confirmation, I actually resorted to digging through the code and noticed the `http_proxy` param and took a stab in the dark!

**Comment by roboticsexpert** [comment]
you should pass http_proxy in root of sentry not in config key and every thing works like charm
