### ISSUE TITLE
  The option "traces_sample_rate" does not exist

### ISSUE THREAD

**Issue by jonhassall** [getsentry/sentry-laravel#434]
When using the 'traces_sample_rate' option in config/sentry.php I get:

Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException 

The option "traces_sample_rate" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enable_compression", "environment", "error_types", "excluded_exceptions", "http_proxy", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "project_root", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags".

**Comment by stayallive** [comment]
Well the error is pretty self-explanatory, in the version you are using that option does not exist.

Which version of the Laravel SDK are you using? 

If you are below version 2 that will be the issue and you will have to upgrade first before you can make use if the `traces_sample_rate` option 👍

**Comment by jonhassall** [comment]
I'm using "sentry/sentry-laravel": "^2.0" in composer.json
and it shows "name": "sentry/sdk", version": "2.2.0" in composer.lock
So I'm confused why the traces_sample_rate option isn't present

**Comment by stayallive** [comment]
Can you try and make sure you are on version `^2.3.0` of the `sentry/sentry-laravel` package, I think you might be installing the beta SDK like what is happening here: #396.

**Comment by jonhassall** [comment]
I rebuilt composer.lock and it worked. I suspect an old version locked to an older version.

Thank you so much for your help.

**Comment by hthanhbmt** [comment]
I got the same error. In my case, I want to upgrade sentry package from 1.0.1 to 1.9.x 
I solved this error by remove the old config/sentry.php and publish Sentry ServiceProvider again.
`php artisan vendor:publish --provider="Sentry\Laravel\ServiceProvider"`
