### ISSUE TITLE
PHP Artisan no longer works

### ISSUE THREAD

**Issue by christophstockinger** [getsentry/sentry-laravel#436]
I installed the Sentry Laravel package in my Laravel 8 application following the installation instructions.

However, after the successful installation, the PHP Artisan CLI no longer works. So the command `php artisan sentry:publish` cannot be executed either.

If I uninstall the package, then I can execute PHP Artisan CLI commands!

Does anyone have the same problems or know what the problem is or how to solve it?

**Comment by stayallive** [comment]
Hi @christophstockinger, for future readers it would be awesome if you could tell us what went wrong and how you ended up fixing it 👍
