### ISSUE TITLE
Generated route name not correctly detected when using prefixes

### ISSUE THREAD

**Issue by wfeller** [getsentry/sentry-laravel#440]
It should be `Str::contains(...)` instead of `Str::startsWith(...)` in https://github.com/getsentry/sentry-laravel/blob/c5af38e42f5cd513731613a64a2c6bc8039892a0/src/Sentry/Laravel/Integration.php#L138

Otherwise, you get routes like "prefix.generated::aiusdha" in Sentry.

**Comment by stayallive** [comment]
That is interesting, I did not realize that happened, I'll gladly accept a PR fixing it 😉
