### ISSUE TITLE
Sentry not picking up queue exceptions.

### ISSUE THREAD

**Issue by Kyon147** [getsentry/sentry-laravel#443]
Hi all,

I've been using Sentry for a little bit (moving from bugsnag) and I still have both running and noticed that Sentry is not sending any errors happening in queues/jobs.

I've looked around and I do have in exceptions, so from what I can tell they should be getting reported as they are being reported in Bugsnag.

        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }

Did the queues ever get sorted and work now as they should or am I missing something?

Thanks!

How do you use Sentry:
Self Hosted

Which SDK and version?
Sentry 20.11.14468076

**Comment by stayallive** [comment]
Which Laravel SDK version are you using?

Do you know what kind of exceptions are not reported from your queues? 

Also are you 100% sure they are not not reported because of the `shouldReport` guard we default too, I'm not a 100% sure Bugsnag does the same so that might be the difference (like `ModelNotFoundException` is excluded because of the `shouldReport` check)?

**Comment by tony5Dim** [comment]
There's a tip that isn't in Laravel doc:
$shouldReport represents all the exceptions minus the ones presents in the $dontReport array **AND THE ONES IN THE $internalDontReport**
$internalDontReport is in the parent (Illuminate\Foundation\Exceptions\Handler) and is like this:
```
protected $internalDontReport = [
        AuthenticationException::class,
        AuthorizationException::class,
        HttpException::class,
        HttpResponseException::class,
        ModelNotFoundException::class,
        SuspiciousOperationException::class,
        TokenMismatchException::class,
        ValidationException::class,
    ];
```
So, if you want to log some of these exceptions you have to override $internalDontReport in your Handler.php.

**Comment by stayallive** [comment]
We have the following as the setup:

```php
public function report(Throwable $exception)
{
    if ($this->shouldReport($exception) && app()->bound('sentry')) {
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

If you want to report absolutely everything (including 404's and handled validation errors) you can change it to:

```diff
public function report(Throwable $exception)
{
-   if ($this->shouldReport($exception) && app()->bound('sentry')) {
+   if (app()->bound('sentry')) {
        app('sentry')->captureException($exception);
    }

    parent::report($exception);
}
```

Hope that helps, if there is still something we need to investigate please re-open the issue 👍
