### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-laravel#447]
Hey, we (Sentry) are in the process of migrating all of our repos away from Travis. This issue will be used by @getsentry/productivity to track overall progress across the organization, but please let us know here if there's anything we should be aware of. Thanks!

**Comment by stayallive** [comment]
Ah great this was already on my list.

Are you doing a first PR or shall I draft up a GH workflow to get this going?

**Comment by billyvg** [comment]
@stayallive We won't be able to get to this for a few weeks, so if you could draft one up that'd be great. Thanks!
