### ISSUE TITLE
Normalized route names when using Lumen

### ISSUE THREAD

**Issue by giggsey** [getsentry/sentry-laravel#449]
Hi,

When using Tracing in Lumen, it's unable to get the Route Name.

$request->route() returns an array instead of a Route object. This could be used instead to get the same information as full Laravel.

**Comment by stayallive** [comment]
I'm happy to accept a PR fixing this if you are up for it, the initial performance release was and is focussed on Laravel at the moment 👍

**Comment by mnbp1371** [comment]
Hello, I need to run sentry captureException in queue . do you Have any tutorial?

**Comment by stayallive** [comment]
@mnbp1371 no we do not, but running it in the queue is the same as not in the queue, works anywhere in your project. 

But please open up a new issue with what you want to do and what is not working so we can try to help you out. 

But this is not the issue, or at least I don't think it's related to your question.

**Comment by migralito** [comment]
@stayallive cloud you please give me an overview of the steps to follow for merging the PR? so I can make myself with an expectation whether this is ready to merge or not, and the time it will take for this to make to the following release.
Thank you

**Comment by stayallive** [comment]
@migralito I needed some time to check this out.

Unfortunately I am able to break it with a route like: `{type}/user` when called with the URL: `user/user`, it results in `{type}/{type}`.

I know this is maybe a stretch but I'm sure there are some better examples to think of where this could happen.

I was also missing the route name and action that I've added back. But I'm not 100% sure about the above issue yet.
