### ISSUE TITLE
traces_sample_rate still required with traces_sampler

### ISSUE THREAD

**Issue by zatorck** [getsentry/sentry-laravel#453]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Laravel

### Steps to Reproduce

1. Delete `traces_sample_rate` while having `traces_sampler` 

### Expected Result

Application should work. It's confusing, because I was wondering final trace sample rate is `traces_sample_rate` x `traces_sampler` or something similar. After many tests I investigated that even if  `traces_sampler` is only necessary option in config you still need `traces_sample_rate` to send traces.

### Actual Result

After adding `traces_sampler`, `traces_sample_rate` shouldn't be necessary

**Comment by stayallive** [comment]
Annnnd I'm moving it back because this does seem like a Laravel bug since the SDK handles this properly, sorry for the confusion 😄

**Comment by stayallive** [comment]
@zatorck can you please show what you have set in your config?

After testing with this I get tracing events to show up just fine!

```php
return [
	'dsn' => env('SENTRY_LARAVEL_DSN'),

    'traces_sampler' => function (Sentry\Tracing\SamplingContext $context) {
        return 1.0;
    },
];
```

It would also help to know the versions of Laravel/Lumen and the Sentry SDK you are running.

**Comment by zatorck** [comment]
Hey @stayallive. 

Super thanks for fast answer. Sentry and their team is awesome. 

Unfortunately I was too fast making this thread. After more testing I just realized that yesterday I made it in wrong way. So sorry for bothering You. 

Hope it's ok.

Thanks

**Comment by stayallive** [comment]
Hi @zatorck, no worries it happens!
