### ISSUE TITLE
Sending error logs and exceptions to sentry

### ISSUE THREAD

**Issue by korridor** [getsentry/sentry-laravel#455]
This is the seperate issue for this comment: https://github.com/getsentry/sentry-laravel/issues/159#issuecomment-786581046

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?

 - sentry-laravel 2.3.1
 - Laravel 8.29.0

### Steps to Reproduce

**logging.php**
```php
'stack_staging' => [
    'driver' => 'stack',
    'channels' => ['daily', 'sentry'],
    'ignore_exceptions' => false,
],
```

**Handler.php**

```php
if ($this->shouldReport($exception) && app()->bound('sentry')) {
    app('sentry')->captureException($exception);
}
```

### Expected Result

I would like to send `Log::error('...')` messages to sentry and I would also like to use `app('sentry')->captureException($exception)`to capture exceptions.
I have no problem with only using the Monolog driver, I just want to know if and why `captureException()` is better?

### Actual Result

Exceptions are reported twice in sentry.

**Comment by stayallive** [comment]
I want to quickly add some comments on how I would see this working.

Currently you enabled the logging driver like this (for example):

```php
'sentry' => [
    'driver' => 'sentry',
    'level' => 'info',
],
```

I think a nice addition would be to have the `ignore_exceptions` option added so you can set it up like:

```php
'sentry' => [
    'driver' => 'sentry',
    'level' => 'info',
	'ignore_exceptions' => true,
],
```

This would allow you to still capture log messages but ignores exceptions (because you capture them in the exception handler for example).

**Comment by korridor** [comment]
@stayallive That would be perfect! The `ignore_exceptions` currently only works with the stack driver right?

**Comment by stayallive** [comment]
Yes so we would have to implement that option ourselves to make it work, but that should not be too hard (famous last words).

**Comment by stayallive** [comment]
So I have misunderstood the option name unfortunately...

> When set to true, the handlers are wrapped in Monolog’s WhatFailureGroupHandler handler. Their wrapper/special handlers documentation describes this handler as follows:
>
> > This handler extends the GroupHandler ignoring exceptions raised by each child handler. This allows you to ignore issues where a remote tcp connection may have died, but you do not want your entire application to crash and may wish to continue to log to other handlers.

That is unfortunate but I think it's best we think of another config key to use to prevent confusion.

Would something like `report_exceptions` (defaulting to `true`) be as descriptive you can set to `false` to disable reporting of exceptions for that log channel?

**Comment by korridor** [comment]
@stayallive Sounds good to me.

**Comment by stayallive** [comment]
Sorry it took a bit... but while tackling some other log channel issues I _finally_ got around to this 😉 

Check it out: #482. Should be released in a few days 👍

**Comment by korridor** [comment]
Thanks a lot! :)
