### ISSUE TITLE
Performance monitoring for jobs in queue

### ISSUE THREAD

**Issue by luke83** [getsentry/sentry-laravel#456]
Hi there,
first of all, thanks for all you great work!

I correctly receive on sentry all errors and performance tracking info for "normal" web requests in my laravel apps. 

Is there a way to have performance monitoring tracking for jobs that run on queue via database adapter?

Should be nice to have them reported with the job name as transaction key, the same we have for standard request with route name as transaction key. It should respect sample trace ratio configured, of course.. 

If it is already implemented is there some doc to read to configure it?

**Comment by stayallive** [comment]
No. At the moment only web requests have performance profiling.

In the future there will also be monitoring for background jobs 👍

**Comment by stayallive** [comment]
#478 is in the works to add support for this, if you are interested, willing and able please test it out!

**Comment by luke83** [comment]
> #478 is in the works to add support for this, if you are interested, willing and able please check/test it out!

Thanks! I will check/test is ASAP! 🚀
