### ISSUE TITLE
Sentry events not working, GuzzleHttp\Promise\RejectionException

### ISSUE THREAD

**Issue by Jamesking56** [getsentry/sentry-laravel#459]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry/sentry-laravel 2.3.1 on Laravel 8 and PHP 8

### Steps to Reproduce

1. Set DSN and App\Exception\Handler following documentation
2. Create a route that causes an exception
2. Cause the exception

### Expected Result

Exception is logged in Sentry

### Actual Result

Exception doesn't reach Sentry, debugging turns up a `GuzzleHttp\Promise\RejectionException` is happening when trying to send the exception. I have no idea how to troubleshoot further.

**Comment by stayallive** [comment]
Hey there, let's figure this out 👍 

So my first question, it sounds like you are testing locally? Are you on Windows?

The easiest way to see what is going on is placing a `dd($exception)` on this line (file should be in `vendor/sentry/sentry-php/src/Transport/HttpTransport.php):

https://github.com/getsentry/sentry-php/blob/f35ffc85a383c22f82098a82ba283a73c0267fa0/src/Transport/HttpTransport.php#L111-L118

If not occurring local but on a production or staging machine we can add a logger so we can write what is going on there to the Laravel log for example.

**Comment by Jamesking56** [comment]
I've managed to work it out - turns out my Sentry account hit its limit, therefore Sentry was returning 429 Too Many Requests.

No bugs here!
