### ISSUE TITLE
Laravel 5.4 compatibility

### ISSUE THREAD

**Issue by KKSzymanowski** [getsentry/sentry-laravel#46]
Laravel 5.4 will probably be released this or next month and there is a compatibility issue which will have to be addressed.

There has been some changes to `Illuminate\Events\Dispatcher`, eg. in [this](https://github.com/laravel/framework/commit/dbbfc62beff1625b0d45bbf39650d047555cf4fa) commit. It no longer exposes the `firing()` method used in `SentryLaravelEventHandler`. From what I understand it is used to retrieve the name of the current event and direct the control flow accordingly. 
In 5.4, when an *wildcard event listener* has been registered, the listener method will be called with two arguments:
- Event name
- Event payload

That said, following changes will be required in `SentryLaravelEventHandler::onWildcardEvent`.
1. Add previously mentioned arguments:
```php
public function onWildcardEvent($eventName, $payload)
```
2. Instead of `$args = func_get_args();` we can use the second argument which is the event payload. Eg.
```php
$route = $args[0]->route;
```
will have to be replaced with
```php
$route = $payload[0]->route;
```

While we're on the subject of the `onWildcardEvent` method it feels a bit messy for me. I refactored it [here](https://gist.github.com/KKSzymanowski/1c7965015e30c19e010fa3972db9b091), tell me what do you think.

Also, event names have changed. Eg. Laravel no longer raises `illuminate.log` event, instead an instance of `Illuminate\Log\Events\MessageLogged` is sent. You can see more in [this commit](https://github.com/laravel/framework/commit/57c82d095c356a0fe0f9381536afec768cdcc072). I reflected these changes in the Gist.

For now it's all I have discovered in this subject. Tell me if you're interested in a Pull Request regarding these changes.

**Comment by stayallive** [comment]
It does not look like the handler in the Gist is backwards compatible with 5.3 and lower, is that also possible to implement somehow or would we need a different handler for <=5.3 and >=5.4?

**Comment by KKSzymanowski** [comment]
Yes, it isn't compatible. I asuggest creating a separate branch for 5.4 support. I've seen couple of packages approach similar problems this way.

**Comment by KKSzymanowski** [comment]
Although I just had an idea. If we create bespoke handlers for each event it should work on whole 5.*, because only wildcard API changed that much. I'm not sure though, I will check it later today.
