### ISSUE TITLE
"Puli Factory is not available" Exception after installing sentry-laravel

### ISSUE THREAD

**Issue by david02871** [getsentry/sentry-laravel#463]
Since installing `sentry/sentry-laravel` I get a `PuliUnavailableException` 'Puli Factory is not available' and no Exceptions are appearing in Sentry.

I am running Laravel 8 on php 7.3 in Docker.

`sentry/sentry-laravel` installed using the instructions at https://docs.sentry.io/platforms/php/guides/laravel/

`php artisan sentry:test --transaction` is successful and appears in Sentry.

I installed the following as suggested by other posts and ran `composer update`.
guzzlehttp/psr7
php-http/curl-client
php-http/message

Composer setup:
```
"require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "guzzlehttp/psr7": "^1.7",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "maatwebsite/excel": "^3.1",
        "php-http/curl-client": "^2.2",
        "php-http/message": "^1.11",
        "sentry/sentry-laravel": "^2.4",
        "spatie/laravel-permission": "^4.0"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
```

Is there a port I need to open up?
From docker compose file:

```
        ports:
            - 80:80
            - 8080:8080
            - 9000:9000
```

**Comment by stayallive** [comment]
Hey @david02871 I was just about trying to dig in, did you end up finding the issue and/or solve it?
