### ISSUE TITLE
Sentry is not installed by composer in Laravel 6

### ISSUE THREAD

**Issue by alexv96** [getsentry/sentry-laravel#464]
I installed it on Friday in a project with Laravel 7 and everything worked perfectly, today I tried to install it in another project with Laravel 6 but it doesn't let me install it and that happens only when I run composer.

![image](https://user-images.githubusercontent.com/33232796/111230099-caa82200-85c5-11eb-95f9-5cb79f28ae0e.png)

**Comment by stayallive** [comment]
Hi @alexv96, you can try running this:

```bash
composer require sentry/sentry-laravel --update-with-dependencies
```

It seems like `guzzlehttp/promises` is locked in your `composer.lock` to a lower version than required by us, running the above allows composer to update that package if needed.

Let me know if that fixes it, if not it would be helpful if you could share your `composer.json` so we can investigate!

**Comment by alexv96** [comment]
Hi 

Now it works, it forced me to update the libraries I had installed, thank you very much :D
