### ISSUE TITLE
Changes from #419 are not compatible with projects that change the BaseServiceProvider::$abstract

### ISSUE THREAD

**Issue by KarlCastle** [getsentry/sentry-laravel#466]
### Environment

How do you use Sentry?
sentry.io but this bug occurs with or without a DSN set

Which SDK and version?
PHP and 3.1.5 (whatever `composer require "sentry/sentry-laravel 2.3.1"` delivers)

### Steps to Reproduce

1. composer require sentry/sentry-laravel (2.4.1)
2. add sentry/sentry-laravel to do-not-discover in composer.json
3. create a replacement ServiceProvider that extends BaseServiceProvider and sets BaseServiceProvider::$abstract to something other than 'sentry'

### Expected Result

Middleware stack processes without throwing.

### Actual Result

SetRequestIpMiddleware (added in #419 ) throws because `app('sentry')` is not an instance of `HubInterface`.

**Comment by stayallive** [comment]
2.4.2 was just released with the fix let me know if everything works as expected! 👍
