### ISSUE TITLE
Override SENTRY_ENVIRONMENT in runtime doesn't seem to be working

### ISSUE THREAD

**Issue by jo5ke** [getsentry/sentry-laravel#469]
### Environment
LEMP (php 7.2)
"sentry/sentry-laravel": "^1.8"
"laravel/framework": "^7.0"

### Steps to Reproduce

I've got a multi-tenant app that has a custom DatabaseServiceProvider (it's added in config/app.php providers array) called in which I'm overriding configs like app name, database connection, etc. I managed to get everything working, only the sentry environment seems not to be overridden there

Sentry config is published in config/sentry.php and I tried to override the config like:

`\Config::set('sentry.environment', 'XY_tenant_production');`

But I'm still getting the 'production' as a result (which is a default value in .env).

I even tried to override the app environment like:

`\Config::set('app.env', 'XY_tenant_production');`

But same results again... I tried both console and HTTP kernel error reporting.

Seems like Sentry is bootstrapping before my custom ServiceProvider or it's strictly reading values from .env.

**Comment by stayallive** [comment]
No, you are correct this doesn't work. Config values are not dynamic in any way shape or form and the are read on bootup of the framework and are useless after :)

You are by the way using an older version of the Laravel integration, consider upgrading but I think the example should still mostly work.

If you want to change the environment dynamically you could do the following:

```php
// Not strictly needed, but good practice
if (app()->bound('sentry')) {
    /** @var \Sentry\State\HubInterface $sentry */
    $sentry = app()->make('sentry');
    
    $sentry->getClient()->getOptions()->setEnvironment('XY_tenant_production');
}
```

But, if you are using this to indicate a tenant context I would add a tag and not change the environment personally, something to consider:

```php
// Not strictly needed, but good practice
if (app()->bound('sentry')) {
    /** @var \Sentry\State\HubInterface $sentry */
    $sentry = app()->make('sentry');
    
    $sentry->configureScope(function (\Sentry\State\Scope $scope) {
        $scope->setTag('tenant', 'XY');
    });
}
```

**Comment by jo5ke** [comment]
This seems to be working like a charm!

Thank you very much for your help, as also for your recommendation about using tags, I didn't think of that at all.
