### ISSUE TITLE
Memory leak in long running process due to repeated booted callback registration

### ISSUE THREAD

**Issue by filakhtov** [getsentry/sentry-laravel#472]
### Environment
Using  Sentry SaaS

Which SDK and version?
sentry/sentry-laravel: 2.4.2
sentry/sdk: 3.1.0
sentry/sentry: 3.2.0

### Steps to Reproduce
Running Laravel with `sentry-laravel` in long-running web worker processes such as PSR-7 based web server or Swoole.

### Expected Result
The system is stable and does not continuously increase its memory usage.

### Actual Result
After a couple of thousands requests workers start to hit the `memory_limit` of 128M.

### Identified source of problem
After about a week of debugging and narrowing it down we have identified that the issue comes from [this block of code](https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/Tracing/Middleware.php#L103-L116), i.e. on every request the middleware would register a new booted callback until eventually exhaust all available memory.

Object tree dump after pushing 6000+ requests using `ab` (Apache Bench) tool:
```
(object) Illuminate\Foundation\Application
  basePath => (scalar) <REDACTED>
  hasBeenBootstrapped => (scalar) 1
  booted => (scalar) 1
  bootingCallbacks => (array) 1
    0 => (closure)
  bootedCallbacks => (array) 6538
    0 => (closure)
    1 => (closure)
    2 => (closure)
    3 => (closure)
    4 => (closure)
    ...
    6533 => (closure)
    6534 => (closure)
    6535 => (closure)
    6536 => (closure)
    6537 => (closure)
  terminatingCallbacks => (array) 0
  serviceProviders => (array) 39
    0 => (object) Illuminate\Events\EventServiceProvider
      app => (object) *currentApp
      bootingCallbacks => (array) 0
      bootedCallbacks => (array) 0
    ...
```

**Comment by stayallive** [comment]
Interesting, this library was not tested with Swoole, but there is probably an easy fix.

Would you be up to PR this?

**Comment by filakhtov** [comment]
Hey @stayallive, thanks for a quick look! Doesn't have to be Swoole specifically - any long running web process will surface this problem if it reuses instances across different requests, e.g. RoadRunner which uses PSR-7.

I am more than happy to PR this, but would like to know what your guidance here will be. I can simply introduce a private property on the middleware, something like boolean flag `isBootedCallbackRegistered` and check/set as needed. This is the most naive implementation of course and I am not sure if that's acceptable. What are your thoughts?

**Comment by stayallive** [comment]
No I know it's not specific persé, was just an example.

I'm thinking about it and "just" registering it once would not work...

The main issue is `$fallbackTime` we use in the callback which is the time `startTransaction` is called in the middleware.

We also have `request()` but we can solve that by resolving the request from the container inside the callback.

So looking at this we need to check if we already registered the callback and maybe also have a property to have that `$fallbackTime` set in. The callback and `$fallbackTime` property could possibly even be static to prevent issues with multiple instances of the middleware causing issues although the middleware is registered as singleton at the moment (which I'm not even sure why we would do that or need that).

**Comment by filakhtov** [comment]
Hey @stayallive thanks a lot for this information. I have spent a bit of time testing/figuring out how everything works together and I would actually question the reason behind using the `booted()` callback in the first place. Because we are calling `booted()` from within the Middleware the app is already booted, and Laravel immediately fires off this callback through [this codepath](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Application.php#L941-L943).

I have used `debug_backtrace()` inside of the callback to see where it is invoked and every time it is actually from within that `isBooted()` condition, like so:
```
/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:955
/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942
/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php:125
/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php:43
/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
```

With this in mind, I feel like we can just inline this anonymous function body into the `startTransaction()` method itself. Also, I am not sure what purpose the fallback time serves here, because `LARAVEL_START` constant is always defined by the Laravel autoloader.

What do you think about all the above?

Alternatively, I can move `booted()` registration into the service provider (which is fired earlier than this middleware) and have `microtime()` fallback done there too. I can even register a Sentry-specific "fallback time" as a container entry that can be reused then by the callback AND middleware alike as a starting point of the request.

**Comment by stayallive** [comment]
Yep, this is probably true, I'm not a 100% why we did it that way, probably because we wanted to extract it to our event listener class instead of keeping it in the middleware.

But I think you are right that we can remove the complete callback and inline it.

`LARAVEL_START` is not always defined especially if you are using an older version of Laravel or started with an older version and did not keep `index.php` up-to-date. This is just a safeguard and I see no issues in keeping it.

I would not use the container to use as a global storage for fallback times, but it looks like we also don't need it with the inlining.
