### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by drawmyattention** [getsentry/sentry-laravel#48]
In Laravel 5.4, the ```firing()``` method in the event ```Dispatcher``` has been [removed](https://github.com/laravel/framework/commit/dbbfc62beff1625b0d45bbf39650d047555cf4fa). This means that this package is no longer compatible with the latest version.

It looks as though the current ```SentryLaravelEventHandler``` is really only listening to the following events:

- ```Illuminate\Routing\Events\RouteMatched```
- ```router.matched```
- ```Illuminate\Database\Events\QueryExecuted```
- ```illuminate.query```
- ```illuminate.log```

So I propose that the package actually is refactored a little, to have a dedicated event listener for each of these events (to remove the long list of nested conditionals).

**Comment by dcramer** [comment]
@drawmyattention we just landed some changes in master last week which should add compatibility for 5.4. Could you try upgrading and see if it resolves your issues? 

https://github.com/getsentry/sentry-laravel/commit/6d7b85363adf0f8e046991efa3b5725564baa8c3

**Comment by michaelcullum** [comment]
Please could you tag a release with this ASAP to prevent requiring people to change their requirement to `dev-master@dev` to upgrade to laravel 5.4

**Comment by stayallive** [comment]
@michaelcullum `0.6.0` works fine on 5.4 over here... are you still on `0.5.x` because that version does not work indeed :)
