### ISSUE TITLE
Unable to serialize Configs due to Integrations

### ISSUE THREAD

**Issue by byteasc** [getsentry/sentry-laravel#481]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
PHP / Laravel 

---

After upgrading to the most recent SDK for Laravel, we realized our configs are no longer caching to being unable to Serialize. I see that there was an error related to this with `beforeSend` in the the past but nothing recent otherwise.

The documentation shows setting up the integrations via a Sentry\init() call but we do not do that with Laravel since it is auto loaded, etc. 

We define the integration in our config as such: 
```
    'integrations' => [
        new \Sentry\Integration\IgnoreErrorsIntegration([
            'ignore_exceptions' => ['NoLogException']
        ])
    ]
```

This appears to be consistent with what the documentation has, but due to it being in the config, it causes us to be unable to cache the config in laravel. It provides the specific error - 

`Call to undefined method Sentry\Integration\IgnoreErrorsIntegration::__set_state()`

I assume we're missing something somewhere, but this was never an issue prior to moving to the newer SDK which restructured some of this.

**Comment by stayallive** [comment]
Hey @byteasc, this has always be a problem, and is more of a Laravel problem really 😄 

But luckily there is an easy-ish solution.

Register the integration in the container like this in for example the `register` method of your `AppServiceProvider`:

```php
        $this->app->bind(\Sentry\Integration\IgnoreErrorsIntegration::class, function () {
            return \Sentry\Integration\IgnoreErrorsIntegration([
                'ignore_exceptions' => ['NoLogException'],
            ]);
        });
```

And modify your `config/sentry.php` to:

```php
    'integrations' => [
        \Sentry\Integration\IgnoreErrorsIntegration::class,
    ]
```

This works because we resolve "string" integrations from the Laravel container, this allows the string class name to be properly config cached by Laravel (because it cannot cache class instances) and allows you to still use it.

Little more work but should work 👍

**Comment by byteasc** [comment]
@stayallive 

Thank you! I figured there was a good way to handle it, but hadn't seen it come up lately even with searching history here :) 

It may be worth noting this in yalls documentation around Integrations! 

I appreciate it. I will get this change implemented today in our codebase

**Comment by stayallive** [comment]
Yeah you are absolutely correct, I shall try to add it to the docs!

Let me know if it ends up not working somehow 👍

**Comment by byteasc** [comment]
It seems to be working great! The only change I had to add a "new" 
`return \Sentry\Integration\IgnoreErrorsIntegration([`
here ->
`return new \Sentry\Integration\IgnoreErrorsIntegration([`

**Comment by stayallive** [comment]
🤦 yep, copy pasted that too quick 😉 

Updated the snippet for future readers, thanks!
