### ISSUE TITLE
[Support] How to get started with performance monitoring?

### ISSUE THREAD

**Issue by canvural** [getsentry/sentry-laravel#485]
**Versions used**
`sentry/sentry-laravel`: 2.4.2
`laravel/framework`: 8.38.0

---

Hi,

I added `'traces_sample_rate' => 1.0` to my `config/sentry.php` file. Deployed my app, then made some API requests.

Later when I check the Performance tab on Sentry dashboard I don't see anything.

Do I need to make some extra configuration to enable this? Or it's only enabled for errors/exceptions? (Though I tried also that)

**Comment by stayallive** [comment]
If you only have `traces_sample_rate` set to `1.0` and no `traces_sampler` it should work.

There are some things to check possibly:

- If your plan has performance quota left if you are on sentry.io
- If you checked to fast, performance takes a second to find it's way to the interface
- If you are using frontend browser tracing too and the `sentry-trace` is sent to the backend (if that is the case the frontend decides if the backend should be traced)

**Comment by canvural** [comment]
Ok, I found the problem.

I disabled the auto-discovery for the package. And I'm registering it depending on the environment. But didn't know performance monitoring has a separate service provider. Now I also register the tracing provider, and it works :+1: 

Sorry for the trouble.

**Comment by stayallive** [comment]
Ah. Yeah, no worries I forgot about that too, glad it's working! 👍
