### ISSUE TITLE
Laravel log context param not displayed on issue page

### ISSUE THREAD

**Issue by snakedin** [getsentry/sentry-laravel#488]
Hi! I'm using laravel-sentry via log channel. I offten use laravel log `context` param to log some additional data, for example:

```
Log::notice('Provider could not determine the country for ip', [
	'ip' => $ip,
	'provider' => $providerClass
]);
```

But after upgrading from `2.4.2` to version `2.5.3` these parameters are no longer displayed on sentry issue page neither in message text nor in breadcrumbs log metadata. 

I found a way to display them using `extra` param:

```
Log::notice('Provider could not determine the country for ip', [
	'extra' => [ 
		'ip' => $ip,
		'provider' => $providerClass
	],
]);
```

But this approach affects other log channels (filelog, telescope) and does not seem very convenient. Is it possible to return previous behaviour somehow?

**Comment by stayallive** [comment]
Hi, you mention upgrading to version 5. Version 5 of what exactly? The Sentry SDK for PHP is on version 3 and the Laravel SDK on version 2 😬

**Comment by snakedin** [comment]
I'm sorry, I mean `sentry-laravel` version `^2.5`

And also I need to mention that I use laravel 7 on php 7.2

**Comment by stayallive** [comment]
No worries, I thought you were maybe using another package, but 2.5 makes better sense 😄  

Interesting I have checked out the changes, compared to `^2.4`, but I don't see anything that would make this stop working. In fact I did notice that what you described never worked in the first place.

This works, but without the `extra` key it should not work (in any version):

```php
Log::notice('Provider could not determine the country for ip', [
	'extra' => [ 
		'ip' => $ip,
		'provider' => $providerClass
	],
]);
```

What version were you coming from and does reverting to that version work?

**Comment by stayallive** [comment]
As I type this I read your comment a bit better, you said the information was in the message itself?

It never displayed nicely in a little table like the user data, all that extra data was just in the message?

We made some changes to make log messages show the message and not the fully rendered message with timestamps and all for example, I'm thinking that is what's happening here...

This is the PR with the changes: #482.

**Comment by snakedin** [comment]
Yes, on `2.4.2` with this code there were two places where I could check my context params (not nicely but still): message text and breadcrumbs list:

![sentry](https://user-images.githubusercontent.com/16794174/118538248-9cc29380-b756-11eb-979e-82f00132a003.png)

So my question is, is there a way in `2.5.3` to send a context without wrapping array to `extra` (cause it will affect other log channels in stack)?

Or the only way without `extra` wrapping is to use a custom monolog formatter for message itself?

**Comment by stayallive** [comment]
Ahh, yes with 2.5 the formatter is the only option.

However, I feel we should fix this... I think we can consider this a bug.

It was not intended to remove that data but when cleaning up the formatted message to just show the message part the extra data also got lost. We can do better here to have the data show up nicely.

**Comment by stayallive** [comment]
If you can you can try out #489 which should fix the issue by changing your `composer.json` (temporarily):

```diff
-   "sentry/sentry-laravel": "^2.5"
+   "sentry/sentry-laravel": "dev-add-logger-context-as-extra-context#9ea5cb420aa7caba00d3b508ea95b4bb02ae86bc"
```

You can (and should) change this back to `^2.5` once this PR is merged and released 😄

**Comment by snakedin** [comment]
Yes, it's works perfectly now! Thank you

**Comment by leigeber** [comment]
Hey @stayallive, any general ETA on the fix being pushed? Want to determine if we should deploy the patched release or hold off. Thanks.

**Comment by stayallive** [comment]
I'm planning on a release somewhere this week. So should be soon.

**Comment by stayallive** [comment]
[`2.6.0`](https://github.com/getsentry/sentry-laravel/releases/tag/2.6.0) was just released which includes the fix.
