### ISSUE TITLE
Report Lazy Loading Violations

### ISSUE THREAD

**Issue by NiclasvanEyk** [getsentry/sentry-laravel#494]
Recently Laravel got support [for disabling lazy loading](https://laravel.com/docs/8.x/eloquent-relationships#preventing-lazy-loading) and thereyby a first party solution for detecting N+1 query issues.

By adding a new config option (e.g. `sentry.report_lazy_loading_violations`), Sentry could optionally report these.

Pseudocode:
```php
// Somewhere in Sentry/ServiceProvider.php

if (config('sentry.report_lazy_loading_violations') {
    Model::preventLazyLoading(true);
    Model::handleLazyLoadingViolationUsing(function($model, $key) {
        report(new \Illuminate\Database\LazyLoadingViolationException($model, $key));
    });
}
```

Would something like this be of any interest for you if somebody would send a PR?

**Comment by stayallive** [comment]
Hmm, I'm not sure... the code is so easy it might be better for us to provide some guide on how to do it and nog try and do this ourselfs based on some config which also doesn't work in all Laravel versions which adds complexity to the feature in the first place and unless we sound alarms if we couldn't enable the feature also silent errors.

However we have the concept of integrations you can enable by yourself and which we can supply in the SDK code just not enable by default, this might be a good fit for this.

For you, as the user, it would look something like this in `config/sentry.php`:

```php
<?php

return [
	// ... other SDK config

	'integrations' => [
		// ... optionally any other integrations
		\Sentry\Laravel\Integrations\LazyLoadingViolationIntegration::class,
	],
];
```

A bit more involved than a simple config key but also a bit more involved for the user to enable.
