### ISSUE TITLE
Disable Sentry on the fly?

### ISSUE THREAD

**Issue by Braunson** [getsentry/sentry-laravel#497]
A project I'm working on has an issue in production running out of memory, but more to my feature request, is there a decent way to disable Sentry logging on the fly just before executing a certain set of code?

**Comment by stayallive** [comment]
Okay I can't help you with he first statement, but I can try to answer your question :)

There is no `on` and `off` toggle for the error tracking and it also depends on what errors you want to stop tracking.

But there are a few methods:

- You've [added some code](https://docs.sentry.io/platforms/php/guides/laravel/) to your `App/Exceptions/Handler.php`, you can add some code that prevents calling `captureException` when you are executing that certain set of code
- There is the [`before_send`](https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#before-send) callback you can add (either on the fly or have active all the time), returning `null` from there will never transmit anything to the Sentry server

In both situations the error reporting is still active but might do what you want to.

If not, give me some more info on what exactly you are trying achieve here.

**Comment by Braunson** [comment]
I thought about catching the exception but it's a general thrown PHP exception class so there's no filtering that exception.

I'm trying to figure out what's going on. The error log I have shows Sentry running out of memory compressing the request data to then send to Sentry here's the top of the stack:

```
E_ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 131072 bytes)
in gzcompress called at /app/vendor/sentry/sentry/src/HttpClient/Plugin/GzipEncoderPlugin.php (53)
```

As I'm not sure of the exact error that's being thrown and cannot recreate it locally (this error is on Production), I was looking to disable Sentry from logging just before executing the code for the page that is referenced as being called from in New Relic. I don't necessarily want to disable it across the site but specific to the section...

**Comment by stayallive** [comment]
It's possible the request being sent to Sentry is too large, possibly because of breadcrumbs especially if many queries are executed and/or the queries have large bindings.

You can try to disable some or all of them to limit the amount of data tracked and needing to be transmitted to Sentry causing the memory issues: https://github.com/getsentry/sentry-laravel/blob/acfbddf7286a78d31336b7b38eecdc2743859f34/config/sentry.php#L13-L28.

**Comment by Braunson** [comment]
Thanks @stayallive will try this out.
