### ISSUE TITLE
Queues?

### ISSUE THREAD

**Issue by pulkitjalan** [getsentry/sentry-laravel#5]
Would you be open to a PR that adds support for queues similar to my sentry package: https://github.com/twineis/raven-php or is that something you would like to keep out of the official package?

**Comment by dcramer** [comment]
@pulkitjalan absolutely. I saw your package when I was creating this, but my goal at the time was the simplest solution we could get.

**Comment by pulkitjalan** [comment]
Great, fair enough, Glad to see official support for Laravel and Lumen :)

Ill submit a PR soon.

**Comment by timbroder** [comment]
Did queues make it in? Or is this now part of #90?
