### ISSUE TITLE
Laravel 5.4 problem with jwt, and ide_helper

### ISSUE THREAD

**Issue by isaackearl** [getsentry/sentry-laravel#50]
I upgraded to laravel 5.4 and now when I use my generator for the ide_helper I get this message each time:

sentry.breadcrumbs error=Auth guard driver [api] is not defined.

This is a longshot here in case someone else has run into this with the new release of 5.4... and can point me in the right direction.  I'm opening issues on the ide_helper generator for Laravel as well and the JWTAuth package since I can't be sure which package is causing the issue.

Thanks

**Comment by dcramer** [comment]
This is what happens when a breadcrumb fails to capture. The error message unfortunately is fairly meaningless to me, and ideally we'd also capture a stacktrace where possible (but we dont yet today).

**Comment by isaackearl** [comment]
I found the bit of code that output the error and realized what the issue is..

```
 // bind user context if available
            try {
                if ($app['auth']->check()) {
                    $user = $app['auth']->user();
                    $client->user_context(array(
                        'id' => $user->getAuthIdentifier(),
                    ));
                }
            } catch (\Exception $e) {
                error_log(sprintf('sentry.breadcrumbs error=%s', $e->getMessage()));
            }
```

What I realized is that the current JWT package extends JWTGuard in the Boot method and therefore the 'api' guard driver is not guaranteed to be defined when Sentry loads up...

In order to fix this I'll have to put a pull request in for the JWT package to move the registering of their custom JWTGaurd into the Register method instead of the boot method so it is available to be used by other packages.

For a temporary fix I just put the SentryLaravelServiceProvider BELOW the LaravelServiceProvider that JWT Auth uses in the app.php (config file)... 

```
Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
Sentry\SentryLaravel\SentryLaravelServiceProvider::class,
```

When I do this then the custom Gaurd is created before Sentry tries to load it.
