### ISSUE TITLE
Unable to install laravel package, composer conflicts

### ISSUE THREAD

**Issue by lewis-smith** [getsentry/sentry-laravel#500]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) (altho so far I am not as far as actually using it)

Which SDK and version?
Sentry Laravel ^2.7

### Steps to Reproduce

1. `> composer require sentry/sentry-laravel --with-all-dependencies`

### Expected Result

Package installs

### Actual Result

```
 composer require sentry/sentry-laravel --with-all-dependencies
Using version ^2.7 for sentry/sentry-laravel
./composer.json has been updated
Running composer update sentry/sentry-laravel --with-all-dependencies
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework 6.*, found laravel/framework[v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - laravel/tinker is locked to version v1.0.10 and an update of this package was not requested.
    - laravel/tinker v1.0.10 requires illuminate/console ~5.1|^6.0 -> found illuminate/console[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

This all seems to be core stuff, so I'm not sure why it wouldn't work, but I don't have much experience with diagnosing composer conflicts.

I've attached my composer.json & .lock files.

[composer-files.zip](https://github.com/getsentry/sentry-laravel/files/6748073/composer-files.zip)

**Comment by stayallive** [comment]
Honestly, I have no clue why this is happening...!

But adding `"sentry/sentry-laravel": "^2.7",` manually to your `require` section and running `composer update` afterwards works like a charm with your `composer.json` (after removing your private package).

**Comment by lewis-smith** [comment]
yep, that worked, thank you!

**Comment by bastinald** [comment]
This still does not work.
