### ISSUE TITLE
Backslash escape issue when filtering on sentry.io by transaction name

### ISSUE THREAD

**Issue by tsterker** [getsentry/sentry-laravel#503]
ℹ️  **DISCLAIMER:** I'm currently can't judge if this problem can be solved on the library side or if it's solely a problem of how `sentry.io` constructs transaction filters. Please let me know if should address this problem somewhere else.

⌛  **TL;DR:** Job Transactions show up in sentry.io **Performance** overview, but no events show up in the detail view. It seems to be related to the **backslashes in the job name used for the transaction name** and how sentry.io filters events on transaction name. See the **Investigation** section below for details.

### Environment

- Using Sentry SaaS (sentry.io) 
- SDK: `sentry.php.laravel` version `2.7.0`

### Steps to Reproduce

1. Use `traces_sample_rate=1.0`
2. Use `queue_job_transactions=true` 
3. Trigger Laravel Queue Job (currently `sync` driver)
4. Go to **Performance** view on sentry.io
5. Find Job's transaction  
  > ![image](https://user-images.githubusercontent.com/1156230/124391182-ae083500-dcef-11eb-8cd5-5a846fdfb816.png)
6. Click on transaction name to see **Transaction Summary**  and ensure no filters are active
7. ❌ **No events show**

### Expected Result

Expected to see the recent event(s) of my triggered Laravel Queue Job.

### Actual Result

No transaction events are shown.

> ![image](https://user-images.githubusercontent.com/1156230/124391261-0c351800-dcf0-11eb-9e06-771bc9bb7c30.png)

### Investigation

I had the feeling that the events might actually end up in sentry.io but are not properly associated with the transaction, so this is what I did:

#### Finding the event by ID
- I grabbed `eventId` of the transaction (manually calling `finish()` on the transaction)
- I pasted the eventId into the url:  
   ```
   https://sentry.io/organizations/<ORG>/performance/laravel-sandbox:<EVENT ID>
   ```
- And voila, the event showed up.

#### Finding the event via sentry.io **Discover**

Knowing that the events end up in sentry.io, I wanted to see if I could have manually discovered them:

- Filter transaction events in the **Discover** view & open the transaction group of interest  
  > ![image](https://user-images.githubusercontent.com/1156230/124391688-2243d800-dcf2-11eb-8151-d8acbb4d26ff.png)
- ❌  See **no events**  and notice the **escaped backslashes**  
  > ![image](https://user-images.githubusercontent.com/1156230/124391778-777fe980-dcf2-11eb-8e34-edcc9f026495.png)
- ❗ **Don't escape the backspaces and see all the events**  
  > ![image](https://user-images.githubusercontent.com/1156230/124391842-bc0b8500-dcf2-11eb-8811-fba85b29b335.png)

**Comment by stayallive** [comment]
Hey @tsterker, I think you are right and there is an issue. I have a slightly outdated self-hosted instance and sent events to that instance and sentry.io and something is definitely not working on the sentry.io version.

I am trying to find out who / where best to report this since I don't think this is an SDK thing, and if it is I need someone to explain what needs to be changed so Sentry server understands it properly.

Working on it!

**Comment by HazAT** [comment]
@tsterker This should have been fixed as of now. Please try to use it and report back in case it doesn't work. Cheers.
