### ISSUE TITLE
SamplingContext::getTransactionContext()->getName() always returns <unlabeled transaction>

### ISSUE THREAD

**Issue by justinhartman** [getsentry/sentry-laravel#506]
#### How do you use Sentry?

- sentry.io

#### Which SDK and version?

```console
$ php artisan --version
Laravel Framework 8.50.0
$ composer show |grep sentry
sentry/sdk                            3.1.0              This is a metapackage shipping sentry/sentry with a recommended HTTP client.
sentry/sentry                         3.3.1              A PHP SDK for Sentry (http://sentry.io)
sentry/sentry-laravel                 2.7.0              Laravel SDK for Sentry (https://sentry.io)
```

### Steps to Reproduce

I've been using Sentry in my production app for many months without issue however I now also use [Laravel Telescope](https://laravel.com/docs/8.x/telescope) and the requests sent via Telescope are quickly using up all my credits on sentry.io. I found the [Sampling to filter transaction events documentation](https://docs.sentry.io/platforms/php/guides/laravel/configuration/filtering/#using-sampling-to-filter-transaction-events) and found [this example in your Laravel performance docs](https://docs.sentry.io/platforms/php/guides/laravel/performance/) and tried to implement it as follows:

```php
return [
    'dsn' => env('SENTRY_LARAVEL_DSN', env('SENTRY_DSN')),

    // Filter transaction events and define sample rate prior submitting to Sentry.
    'traces_sampler' => static function (\Sentry\Tracing\SamplingContext $context): float {
    
        if (str_contains($context->getTransactionContext()->getName(), 'Telescope')) {
            // Discard transactions that have 'Telescope' in their name.
            return 0.0;
        }

        // Sample rate for all other transactions.
        return 1.0;
    },
];
```

### Expected Result

Well I would expect `$context->getTransactionContext()->getName()` to return the name of the transaction so that the method's `str_contains` can match the Telescope. The screenshots below show the trace in sentry.io

#### Laravel\Telescope\Http\Controllers\RequestsController@index as a transaction name

![Screenshot 2021-07-21 at 02 56 39](https://user-images.githubusercontent.com/717118/126413716-3c777f62-dd52-4ef3-bfcf-ce8447d32be5.png)

#### telescope as a transaction name

I realise this one may not match as my `str_contains` is looking for `Telescope` and this is lowercase but irrespective, that's not my issue. This is purely to demonstrate that the transactions are named and coming through to sentry.io.

![Screenshot 2021-07-21 at 02 53 40](https://user-images.githubusercontent.com/717118/126413587-e899246d-764f-4f68-9abc-75a4e1efc79f.png)

### Actual Result

The `$context->getTransactionContext()->getName()` should be returning the transaction names but no matter what this only ever returns `<unlabeled transaction>`.

I decided to set some `Log` points in the method to see if it would trigger. This is an example of an `info` log if it matches, and an `error` log if it doesn't.

```php
'traces_sampler' => static function (\Sentry\Tracing\SamplingContext $context): float {
    if (str_contains($context->getTransactionContext()->getName(), 'Telescope')) {
        // Log an info message if this matches.
        \Illuminate\Support\Facades\Log::log('info', $context->getTransactionContext()->getName());
        return 0.0;
    }

    // Log an error message if this doesn't match.
    \Illuminate\Support\Facades\Log::log('error', $context->getTransactionContext()->getName());
    return 1.0;
},
```

The result in the log file and in Sentry is:

```log
[2021-07-21 00:48:43] local.ERROR: <unlabeled transaction>
```

`Log::log('info')` is never hit as it can never match the string.

When I log into sentry.io I can see that Telescope requests are still being logged and the `return 1.0;` type is being set for this (and all other requests) because `return 0.0;` type is never triggered.

I came across [a ticket in this repo and found this comment](https://github.com/getsentry/sentry-laravel/issues/453#issuecomment-779057458) which suggests my method and code is sound and that there is some other reason why the `getName()` property is not returning.

**Comment by stayallive** [comment]
The problem here is that the trace is started before Laravel resolves the route and thus the transaction name is set at the end of the request because when the transaction is started we do not have enough information to construct the transaction name yet. But the traces sampler callback is called at the start of a transaction which is why it's always unlabeled there. 

You can inspect the request using the request facade or helper from inside the traces sampler callback to test if `telescope` is part of the request url which is probably the best way to filter these requests out. 

Let me know of that works out!

**Comment by justinhartman** [comment]
@stayallive thanks for this. In the end this is what I did to filter out the telescope requests.

```php
// Use the Request facade.
use Illuminate\Support\Facades\Request;

// Filter events before sending to Sentry.
'traces_sampler' => static function (\Sentry\Tracing\SamplingContext $context): float {
    // Check for telescope requests and discard them.
    if (str_contains(Request::url(), 'telescope')) {
        return 0.0;
    }

    // Sample rate for all other requests.
    return 1.0;
}
```

**Comment by justinhartman** [comment]
Nope, I spoke too soon. While this works in a local environment, when you move this to production and try to `artisan config:cache` you get the following error.

```log
Error: Call to undefined method Closure::__set_state()
  File "/bootstrap/cache/config.php", line 711, in require
  File "/artisan", line 37
    new Symfony\Component\Console\Output\ConsoleOutput
...
(11 additional frame(s) were not displayed)

LogicException: Your configuration files are not serializable.
  File "/artisan", line 37
    new Symfony\Component\Console\Output\ConsoleOutput
...
(10 additional frame(s) were not displayed)
```

It's because Laravel doesn't allow closures in configs by design so this solution isn't going to work.

I tried to create a helper class like follows:

```php
namespace App\Helpers;

use Illuminate\Support\Facades\Request;

class SentryFilterUrl
{
    /**
     * Check the URL and set the traces_sampler float.
     *
     * @return float
     */
    public function filter(): float
    {
        if (Str::contains(Request::url(), 'telescope')) {
            return 0.0;
        }

        return 1.0;
    }
}
```

And then in `./config/sentry.php`:

```php
'traces_sampler' => [SentryFilterUrl::class, 'filter'],
```

But this returns some other issue whose error now escapes me. Something about a null or closure but receiving an array. I've given up trying to be honest. I'll just have less than ideal reporting due to hitting limits. This affects performance and not exceptions so at least I'm getting those still.

**Comment by stayallive** [comment]
Yes I wanted to warn you for that bit was too late 😅

You have the right idea for the fix. But try making the filter method static, that should work. 

This error is indeed because the Laravel config cache cannot serialize closures. But a callable works just fine like you did.

**Comment by justinhartman** [comment]
So reckon change the filter method to static and it would work? I'll give it a bash.

**Comment by stayallive** [comment]
Yep, that should do it 👌

**Comment by justinhartman** [comment]
Yes, I can confirm, this worked perfectly! Thank you so VERY much!

**Comment by stayallive** [comment]
Cool, and no worries 👌
