### ISSUE TITLE
Error "Please check if your DSN is set properly" when sending a test event on a self-hosted sentry instance

### ISSUE THREAD

**Issue by iraklisg** [getsentry/sentry-laravel#510]
### Environment
self-hosted/on-premise (21.7.0)
Docker version (20.10.8)
Docker Compose (1.29.2)
sentry/sentry-laravel (2.8.0)
Laravel Framework (8.46.0)

### Steps to Reproduce
I have followed the instructions in order to setup the self-hosted sentry instance, i.e
 - download the latest release of the onpremise repository,
 - run `./install.sh` inside this directory
 - run `docker-compose up -d`

The sentry server run successfully.

Then I created a new project and followed the instructions to install the Laravel SDK, i.e
- run `composer require sentry/sentry-laravel`
- Add Sentry reporting to `App/Exceptions/Handler.php`
- Run php artisan sentry:publish --dsn=https://<MY_KEY>@localhost:9000/2

### Expected Result

I was expecting to be able to successfully send the test event
[Sentry] DSN discovered!
[Sentry] Generating test Event
[Sentry] Sending test Event
SUCCESS

### Actual Result
[Sentry] DSN discovered!
[Sentry] Generating test Event
[Sentry] Sending test Event
[Sentry] There was an error sending the test event.
[Sentry] Please check if your DSN is set properly in your config or `.env` as `SENTRY_LARAVEL_DSN`.

The dsn is properly set and properly read by `config/logging.php` I have tried to set the `$SENTRY_BIND` env variable equal to `localhost:9000` but with no success.

Could you please advise?

**Comment by stayallive** [comment]
> Run php artisan sentry:publish --dsn=https://<MY_KEY>@localhost:9000/2

Have you tried running that without `https` but with `http`?

**Comment by iraklisg** [comment]
Yes I have tried with `http://` and I am getting the same results

**Comment by stayallive** [comment]
Good call confirming a sentry.io DSN does work, that rules out any misconfigured other things.

Okay you can add this piece of code to the `register` method of your `AppServiceProvider` to enable some logging:

```php
$this->app->extend(\Sentry\ClientBuilderInterface::class, function (\Sentry\ClientBuilderInterface $builder) {
    $builder->setLogger(new class extends \Psr\Log\AbstractLogger {
        public function log($level, $message, array $context = [])
        {
            error_log("[sentry-laravel] {$level}: {$message} | " . json_encode($context));
        }
    });

    return $builder;
});
```

Alternatively you can put a breakpoint in the [`HttpTransport`](https://github.com/getsentry/sentry-php/blob/bfab90c7ef921221b52b75b5108201e87f0f4661/src/Transport/HttpTransport.php#L112-L117) class to see what error is being thrown, that class should be here: `vendor/sentry/sentry/src/Transport/HttpTransport.php`.

This error might give you a clue about what is happening and why the even is not being sent.

**Comment by BARNZ** [comment]
Thanks for this, was having a similar issue today all of a sudden and wondering why test events were not sending. After adding in the above additional logging I'm seeing the following in my logs:

[sentry-laravel] error: Failed to send the event to Sentry. Reason: "SSL peer certificate or SSH remote key was not OK for "https://o575831.ingest.sentry.io/api/XXX/store/".". | {"exception":{},"event":{}}

**Comment by stayallive** [comment]
This has probably to do with the recent expiration of the Let's Encrypt root (ingest endpoints use a Let's Encrypt cert). 

Some older hosts need a little help fixing it. Try updating you Linux server packages to see if that helps. There is a lot of info on the internet how to fix it for your specific Linux distro and version you are running.

**Comment by BARNZ** [comment]
Thanks for the reply and for pointing me in the right direction. This was just for my local environment and turns out I simply needed to download an install the latest `cacert.pem` from https://curl.se/docs/caextract.html

Test events are now sending again!

**Comment by stayallive** [comment]
I think we got the problem solved here, if there is still an issue feel free to re-open or open a new issue!
