### ISSUE TITLE
Sentry not logging issues on Laravel Vapor / AWS

### ISSUE THREAD

**Issue by sebastiaanluca** [getsentry/sentry-laravel#511]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
sentry/sentry 3.3.2               
sentry/sentry-laravel 2.8.0

Laravel Vapor
Laravel 7

### Steps to Reproduce

1. Followed the guide to configure Sentry as a log channel
2. Set the default log channel to `stack`
3. Have the `stock` log channel configured to log to `single` and `sentry`
4. Have a dedicated endpoint to call that throws a simple `RuntimeException`

### Expected Result

It logs the exception.

### Actual Result

It doesn't log the exception, only creates a performance tab entry.

I have no idea what's going on, but when I do not specifically define a `LOG_CHANNEL` env variable (and it falls back to `sentry` or `stack`), it will never log an error to the issues page in Sentry. The weird thing is, it _will_ create a performance event for it, but won't treat it as a failed response 👀

Performance entry for a failed response without an issue associated:

![Screen Shot 2021-08-25 at 00 10 27](https://user-images.githubusercontent.com/711940/130696797-a753da82-ab41-4b58-bda0-6f870d8a3c14.jpg)

How it should look:

![Screen Shot 2021-08-25 at 00 15 59](https://user-images.githubusercontent.com/711940/130697333-a22a9b6f-4f8c-46a2-ac79-e23362d1f2a9.jpg)

**Comment by sebastiaanluca** [comment]
It's possible this issue occurs because Vapor sets `LOG_CHANNEL=stderr` when you don't define a channel yourself, sending everything to CloudWatch instead. The fallback isn't used either.

**Comment by stayallive** [comment]
Are you setting the `LOG_CHANNEL` in your Vapor env vars yourself too or not? Bit unclear from the issue but important because the default log channel you define in your config is overridden by Vapor to make sure the log output works for CloudWatch so if you don't set it Vapor will do it for you. 

Why are you using log channels and not using the recommended setup in the exception handler: https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel5-6/#install?

**Comment by stayallive** [comment]
So yeah you figured it out while I was writing my reply 😅

But if you want to be sure do not use the log channels way of setting up error logging if you only care for exceptions.

**Comment by sebastiaanluca** [comment]
> Are you setting the LOG_CHANNEL in your Vapor env vars yourself too or not?

I didn't, so yeah, that was the whole issue 😅  It's not mentioned anywhere in their documentation or elsewhere though. And assumed it would use the fallback defined in the config file.

> But if you want to be sure do not use the log channels way of setting up error logging if you only care for exceptions.

Just find a log channel easier to set up (wish it was the default in the guides too). No need to override a method, you just define a a new log entry. Plus it allows you to send debug traces and info messages to Sentry.

Thanks for the fast reply btw. If I hadn't stumbled upon the solution, your reply would've saved me a lot of time!

**Comment by stayallive** [comment]
No worries. Glad you figured it out 👍

Good tip if you encounter something strange in Vapor is to go to the Lambda in the AWS console and see the env vars it's setting since it overrides a few things that you might not expect like this one 😅
