### ISSUE TITLE
Support for Release Health Tracking and Sessions

### ISSUE THREAD

**Issue by ThaDaVos** [getsentry/sentry-laravel#518]
Currently we've setup a Laravel app in Sentry but are unable to configure everything, for example this button keeps showing:
![image](https://user-images.githubusercontent.com/5251028/139019705-f81013f0-b3d4-4341-9c5a-dc68a7e0631e.png)

So I dug into the documentation and noticed, there is no way to configure this for PHP/Laravel.

Will this ever be implemented? Also, the mobile app isn't useful due this as it doesn't show anything because we have no session data.

**Comment by illambo** [comment]
Hello, I'm also interested in the topic,
from docs [Server-Mode/Request-Mode Sessions](https://docs.sentry.io/product/releases/health/?_ga=2.214694677.341112745.1638174277-2032850126.1637850752#request-mode-sessions) seems possible for some sdk (but not for php), why? Thanks

**Comment by ThaDaVos** [comment]
I've already set it up on the front-end - but our Laravel App keeps showing that button and when you click it, there's nothing to be found

**Comment by illambo** [comment]
In my case laravel application it only provides api so it doesn't have a frontend.

**Comment by stayallive** [comment]
I don't think Laravel will ever support release health because it doesn't make much sense for a language like PHP where a session is only as long as the request. I'll have to look into how we get that message out of the UI, but I wouldn't worry too much about it. I will update here if we either remove it from the UI or if somehow we figure out how to support it for PHP 👍

**Comment by ThaDaVos** [comment]
Session is per request - that's not true
One has a session during their use of the application - so why not use the session system of Laravel? It's across multiple requests and most of the time stored or in file, or in redis, or in database - so one can say it's persistent enough for tracking

**Comment by ThaDaVos** [comment]
Or do we have a miscommunication about the meaning of the word `session`?

**Comment by pyr0hu** [comment]
I think in this context the work `session` means a given user's view or use session. PHP's session definition is surely something else and for that @stayallive 's statement that `Session is per request` stands it's ground. You can't really properly track a user story / app usage session with PHP.

You should use JS front-end integration for that. You have to wait a bit to properly show up on the UI though.

So in Sentry's case, IMO it'd be better if the Crash Free Sessions would require using the JS front-end integration for PHP applications.

For tracking API's Crash Free rates as in @illambo 's case, you can use the failure rate as a metric. Maybe later as a separate package, API requests can start a Sentry session and terminate it if the HTTP request got sent. But I'd just use failure rate for that tbh.
