### ISSUE TITLE
issue with laravel 5.4

### ISSUE THREAD

**Issue by roboticsexpert** [getsentry/sentry-laravel#52]
in laravel 5.4 , event fire function renamed to dispatch  ...

If you are manually implementing the Illuminate\Contracts\Events\Dispatcher interface in your application or package, you should rename the fire method to dispatch.

in project we get this :

PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Events\Dispatcher::firing() in /Users/roboticsexpert/Sites/UpperTime/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelEventHandler.php:29

**Comment by dcramer** [comment]
@roboticsexpert are you using the current release of this library? We pushed out an update that added support for 5.4

**Comment by roboticsexpert** [comment]
yes ... but in package dependency you should add that .0.5 version just support laravel 5.3 ...

**Comment by dcramer** [comment]
@roboticsexpert we dont update previous versions, and we didnt know 5.4 was going to break 0.5.0

**Comment by roboticsexpert** [comment]
Overall, Thank you for your quick response. @dcramer
