### ISSUE TITLE
No performance tracing when `allow_url_fopen` is `Off`

### ISSUE THREAD

**Issue by luke83** [getsentry/sentry-laravel#520]
### Environment

Sentry SaaS (sentry.io)

php: 8.0.12
sentry-php: 3.3.0
sentry-laravel: 2.9.0

### Steps to Reproduce

1. Set `allow_url_fopen = Off` in php.ini
2. Set to 1.0 `traces_sample_rate` config parameter
3. navigate in any page of laravel application

### Expected Result

A performance entry registered in sentry project (sentry.io)

### Actual Result

No entry registered. **BUT** setting `allow_url_fopen` to `On` the entry will be registered 🤦‍♂️

### Proposed solution

I think the problem is this line:

https://github.com/getsentry/sentry-laravel/blob/e95bac54959ef608d407944bf284d0d28e97d79e/src/Sentry/Laravel/Tracing/BacktraceHelper.php#L83

I've done a simple test excluding that line and even with `allow_url_fopen = Off` the entry is registered, so the proposed solution is to use curl or anything not affected by `allow_url_fopen` instead of `file_get_contents`.

### Security issue
Please note that `allow_url_fopen = Off` is a requirement for security concerns.

**Comment by luke83** [comment]
Yeah, you let me think about it, maybe my deduction is wrong about the implications, but I can confirm tracing is ok skipping that line of code or turning On `allow_url_open` 🤔

If you have any (different) solution I can test it and give you feedback 😎

**Comment by luke83** [comment]
I think I point my finger on the good guy, I didn't test yet but I read allowed_url_fopen to On is a Guzzle requirement, maybe is this the root cause.. in that case is there any workaround to bypass this requirement for sentry (maybe a custom http implementation for guzzle) 'cause allowed_url_fopen to Off is a security concern to keep always into account.

**Comment by stayallive** [comment]
That is certainly a possibility, see: https://docs.sentry.io/platforms/php/configuration/transports/#httptransport. We are using Httplug and you should be able to choose any adapters supported by them.

To get to the `ClientBuilder` in Laravel, I think some snippets of that went missing in the docs but this should be it:

There is also another way, you can extend the `ClientBuilder` using the Laravel container.

```php
use Sentry\ClientBuilderInterface;

$this->app->extend(ClientBuilderInterface::class, function (ClientBuilderInterface $clientBuilder) {
    $clientBuilder->setTransportFactory($transportFactory);
    
    return $clientBuilder;
});
```

You should place this code in the `register` method of one of one of your own service providers.

Let me know if you get stuck!
