### ISSUE TITLE
Sentry publish command generate a SSL error

### ISSUE THREAD

**Issue by ItsJustMiaouss** [getsentry/sentry-laravel#525]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
- Laravel 8
- PHP 7.4.19
- Sentry SDK (2.10.1)
- Laragon

### Steps to Reproduce

1. Install Sentry SDK with composer
2. Run `php artisan sentry:publish --dsn=xxxxxx`
3. Sentry ask to Enable Performance Monitoring (yes)
4. Sentry ask to send a test event (yes)

### Expected Result

Sentry SDK should send a test event

### Actual Result

```
There was an error sending the event.
SDK: Failed to send the event to Sentry. Reason: "SSL peer certificate or SSH remote key was not OK for "https://oxxxxxx.ingest.sentry.io/api/xxxxxx/store/".".
Please check the error message from the SDK above for further hints about what went wrong.
```
With an image:

![image](https://user-images.githubusercontent.com/59478524/142052186-cc6a7dcb-8990-43d5-bde6-f93709c0cffa.png)

**Comment by stayallive** [comment]
The problem might be related to the Let's Encrypt root certificate that expired and your machine not having an up-to-date enough OpenSSL version or still having the expired root in your certificate authority store.

For more information you can check out this forum post from Let's Encrypt that contains helpful links on how to resolve this for your environment: https://community.letsencrypt.org/t/production-chain-changes/150739/4.

**Comment by ItsJustMiaouss** [comment]
Thank you, @stayallive, it works now!

I have updated my certificate from https://curl.se/docs/caextract.html.
Replacing the DSN with ``sentry.io`` also worked.
