### ISSUE TITLE
Make traces_sampler serializable / support the array with class + function

### ISSUE THREAD

**Issue by tvbeek** [getsentry/sentry-laravel#527]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry/sdk            3.1.0
sentry/sentry         3.3.4
sentry/sentry-laravel 2.10.2

### Steps to Reproduce

1. Add an array with class and function name to the tracer_sampler key. Example from the [documentation](https://docs.sentry.io/platforms/php/guides/laravel/performance/#sample-specific-transactions): `'traces_sampler' => array('App\Helpers\General\TracesSampler', 'sample')`
2. Open any page or run an artisan command
3. Receive the error: `The option "traces_sampler" with value array is expected to be of type "null" or "callable", but is of type "array". `

### Expected Result

I suspected that it would work and give the option to change the options for specific requests.

### Actual Result

Got the error: The option "traces_sampler" with value array is expected to be of type "null" or "callable", but is of type "array". 

Part of the stacktrace:
![image](https://user-images.githubusercontent.com/2026498/142989235-a17cfbbe-2861-4b27-b865-e272a530cd00.png)

Sidenote I understand that it is possible with the use of a closure in the config file. But that result in that the config can't be cached (with php artisan config:cache ) That is one of the recommended steps from the [documentation](https://laravel.com/docs/8.x/deployment#optimizing-configuration-loading) for deployment.

**Comment by stayallive** [comment]
This should already work just fine and in fact is being added to the docs as a alternative for closures because of config caching so I'm puzzled why it's not working for you. 

Does the class exists in your project? And is the method on the class static?

**Comment by tvbeek** [comment]
@stayallive Thanks for the fast feedback, I forgot to make the method static and did misunderstood the error. It works now 😄
