### ISSUE TITLE
default_integrations in tracing doesn't work

### ISSUE THREAD

**Issue by eugeniykurasov** [getsentry/sentry-laravel#528]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-laravel: 2.10.2

### Steps to Reproduce

1. Generate config for laravel `php artisan sentry:publish --dsn=your_dns`
2. Enable `tracing` and set `default_integrations` into false.

### Expected Result

Default integrations will not call.

### Actual Result

Default integrations are called.

**Comment by stayallive** [comment]
Can you share what you want to disable exactly? 

The tracing integrations or the Sentry SDK default integrations?

Keep in mind that in de config you need to set it nested int the `tracing` config for it to take effect and also you might need to clear your config cache `php artisan config:clear` for it to take effect:

```php
<?php

return [
	// ... other settings

	'tracing' => [
		'default_integrations' => false,
	],
]
```

**Comment by eugeniykurasov** [comment]
I want remove body response from tracing.

So I try to redefine integrations without `RequestIntegration`

```<?php

return [
	// ... other settings

	'tracing' => [
		'default_integrations' => false,
                'integrations' => [
                    new \Sentry\Integration\ExceptionListenerIntegration(),
                    new \Sentry\Integration\ErrorListenerIntegration(),
                    new \Sentry\Integration\FatalErrorListenerIntegration(),
                    new \Sentry\Integration\TransactionIntegration(),
                    new \Sentry\Integration\FrameContextifierIntegration(),
                    new \Sentry\Integration\EnvironmentIntegration(),
                ],
        ],
]
```

https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/ServiceProvider.php#L181 - always return true.

**Comment by stayallive** [comment]
You are trying to disable the wrong integrations :)

We have tracing specific integrations and base SDK integrations.

You want to disable the base SDK integrations.

Move your options 1 level lower:

```php
return [
	// ... other settings

	'default_integrations' => false,
	'integrations' => [
	    new \Sentry\Integration\ExceptionListenerIntegration(),
	    new \Sentry\Integration\ErrorListenerIntegration(),
	    new \Sentry\Integration\FatalErrorListenerIntegration(),
	    new \Sentry\Integration\TransactionIntegration(),
	    new \Sentry\Integration\FrameContextifierIntegration(),
	    new \Sentry\Integration\EnvironmentIntegration(),
     ],
];
```

The above won't work when you are using Laravel config caching so you can also do it like:

```php
```php
return [
	// ... other settings

	'default_integrations' => false,
	'integrations' => [
	    \Sentry\Integration\ExceptionListenerIntegration::class,
	    \Sentry\Integration\ErrorListenerIntegration::class,
	    \Sentry\Integration\FatalErrorListenerIntegration::class,
	    \Sentry\Integration\TransactionIntegration::class,
	    \Sentry\Integration\FrameContextifierIntegration::class,
	    \Sentry\Integration\EnvironmentIntegration::class,
     ],
];
```
```

**Comment by eugeniykurasov** [comment]
Thanks. It works now.
