### ISSUE TITLE
Support Scheduled Task Tracing (Performance Monitoring)

### ISSUE THREAD

**Issue by zlanich** [getsentry/sentry-laravel#529]
Currently, there is support for tracing HTTP requests (ie. controller requests), and the breadcrumbs, etc within, as well as queued jobs, but there is no support for tracing "Scheduled Tasks" -- ie. I have several tasks that run nightly, some of which take minutes, and I need to keep an eye on them. Is there a plan to support these as well, and set the transaction name as the command name or name provided using the ->name() method?

The config implies there is support for tracing commands, so technically, if all these were commands, it seems it would trace them, but calls like this are not traced:

```php
$schedule->call(function () {
    (new CachePrimer())->primeIfStale();
})
    ->name('cache-primer') // This could be the transaction name, or default of something
    ->everyMinute();
```

This would be hugely helpful! Thanks!

**Comment by cleptric** [comment]
We're tracking this in https://github.com/getsentry/sentry-laravel/issues/628
