### ISSUE TITLE
Sentry doesn't receive events in production, but works fine in local

### ISSUE THREAD

**Issue by sahilbajaj23** [getsentry/sentry-laravel#530]
Doing a `php artisan sentry:test` on the server produces the following output:

```
[Sentry] DSN discovered!
[Sentry] Generating test Event
[Sentry] Sending test Event
[Sentry] There was an error sending the test event.
[Sentry] Please check if your DSN is set properly in your config or `.env` as `SENTRY_LARAVEL_DSN`.
```

The DSN is properly setup, and the same DNS works in local: so that's not the issue.

Edited the AppServiceProvider as suggested here - https://github.com/getsentry/sentry-laravel/issues/510 - and now the output includes an additional line:

```
[Sentry] DSN discovered!
[Sentry] Generating test Event
[sentry-laravel] error: Failed to send the event to Sentry. Reason: "Peer certificate cannot be authenticated with given CA certificates for "https://xxxxx.ingest.sentry.io/api/xxxxx/store/".". | {"exception":{},"event":{}}
[Sentry] Sending test Event
[Sentry] There was an error sending the test event.
[Sentry] Please check if your DSN is set properly in your config or `.env` as `SENTRY_LARAVEL_DSN`.
```

**Comment by stayallive** [comment]
The problem might be related to the Let's Encrypt root certificate that expired and your machine not having an up-to-date enough OpenSSL version or still having the expired root in your certificate authority store.

For more information you can check out this forum post from Let's Encrypt that contains helpful links on how to resolve this for your environment: https://community.letsencrypt.org/t/production-chain-changes/150739/4.

For testing this you can try replacing `o123456.ingest.sentry.io` in your DSN with just `sentry.io` (without changing anything else) and testing again, if it succeeds your PHP installation is unable to correctly validate Let's Encrypt certificates. Please always try to use the ingest version if possible and only use the plain sentry.io version for testing!

If the change to the sentry.io DSN is also not the solution make sure there is not a corporate firewall blocking access to the DSN domain.

**Comment by sahilbajaj23** [comment]
Thanks for the prompt response, @stayallive - you were right about the issue being an old version of OpenSSL.

I am using AWS Elastic Beanstalk, so updating the platform (which presumably also updated/patched OpenSSL) worked.

Thanks!

**Comment by stayallive** [comment]
Good to hear 💪
