### ISSUE TITLE
Sync span operation names

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-laravel#532]
Update all relevant span operation names to match the docs here
https://develop.sentry.dev/sdk/performance/span-operations/

This is necessary for users to use some of the newer Performance dashboard features like slow db and http ops.

![image](https://user-images.githubusercontent.com/6536764/148569851-13368be3-9461-4276-b61b-5bf456bbe66e.png)

cc: @stayallive

**Comment by yinx** [comment]
We are currently running into this issue. Is this something that we can set in our project or is this only possible through the SDK?
If so I'm open to trying my hand at this and see if I can make a PR. I'm just not sure what the actual change would need to be. What span operations are these slow https ops and slow db ops based on? Is there any documentation that I can follow?

**Comment by stayallive** [comment]
@sl0thentr0py, currently we use `view.render` but am I reading correctly we should use `render.view` to be in spec? Or maybe even `laravel.view` considering it's the framework rendering?

**Comment by stayallive** [comment]
@yinx I have started a PR but have a few things I want to double check before releasing but you can try it out by making the following changes in your `composer.json` and running `composer update` afterwards:

```diff
-   "sentry/sentry-laravel": "^2.10",
+   "sentry/sentry-laravel": "dev-fix-span-names@dev",
```

I'll get this released as soon as we have all the names correct :)

**Comment by yinx** [comment]
@stayallive Awesome thanks! I'll have a look.

**Comment by sl0thentr0py** [comment]
cc: @AbhiPrasad for the framework/render thing, I'm not entirely sure what we want.

The two things we need for the performance dashboards to work right now are
* all database spans get prefixed with `db.*`, so something like `db.sql.query` is fine, only the prefix is important
* all http client requests get marked as `http.client`, again mainly the prefix is important

Note that we should _not_ immediately change *transaction* names since that might break some users' saved queries. This is mainly for span op names which we don't currently allow to filter.

**Comment by stayallive** [comment]
@sl0thentr0py makes sense, I've updated the `db.sql.query` but just to be 100% sure `http.client` is for the server requests? We currently have `http.server` but that is backwards I guess? It makes sense in my head to use `http.server` since it's a server side request but I'm probably coming from a wrong angle :)

**Comment by sl0thentr0py** [comment]
if the server makes another http request internally that's `http.client`, the whole framework request-response cycle is `http.server` but that's usually the top-level transaction so changing that is breaking.

**Comment by stayallive** [comment]
A okay, makes sense, we do have that thought at the moment (`http.server`) so I'm confused why that is not working in the dashboard, the sql query was "wrong" indeed.

![image](https://user-images.githubusercontent.com/1090754/148964575-adbb552c-66e5-449c-a0df-830afbf59a61.png)

**Comment by sl0thentr0py** [comment]
the screenshot is from generic

**Comment by sl0thentr0py** [comment]
@yinx the internal query as far as I remember is 75th percentile

**Comment by AbhiPrasad** [comment]
@stayallive sorry for the delay, I think using `larvel.view` should be fine, we can always re-evaluate later on.

**Comment by stayallive** [comment]
@AbhiPrasad hehe, that was just release today 👍 Had the same thought 😄 Thanks!
