### ISSUE TITLE
"Maximum execution time of 30 seconds exceeded" not logged

### ISSUE THREAD

**Issue by futzlarson** [getsentry/sentry-laravel#538]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry/sentry-laravel 2.10.2

### Steps to Reproduce

In `laravel.log`:

```
[2022-01-28 18:40:35] production.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/production/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:66)
[stacktrace]
#0 {main}
"} 
```

### Expected Result

I thought this would be logged to Sentry and provide the normal details needed to debug, like:
- Stack trace or at least the calling file/line
- Url this occurred at

I'm not calling `RecursiveDirectoryIterator` directly so I have no idea what is calling it. The nginx log around that timestamp didn't reveal anything either. And no scheduled jobs would be running at that time.

### Actual Result

Nothing logged to Sentry. Not sure how to track it down from here. Or is this just not catchable?

**Comment by stayallive** [comment]
Hey @futzlarson, there are a few things at play here.

We should have catched that error in Sentry, this is of course worth figuring out if something is wrong (or configured wrong) for that to happen.

How have you setup Sentry and what PHP & Laravel version are you using?

The backtrace being... small is not something we are going to fix since what Laravel is putting in the logs is the same info Sentry is getting... so we would have a little more context about what you app was doing (url request etc.) but probably not more stack frames since PHP is not giving us those it looks like.

**Comment by futzlarson** [comment]
Yep, been using Sentry for years.

PHP: PHP 7.3.30-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug 26 2021 15:55:41) ( NTS )
Laravel: 8.76.1

The url request alone would be enough; I could figure it out from there.

**Comment by stayallive** [comment]
How have you setup Sentry in Laravel? Like the [installation guide](https://docs.sentry.io/platforms/php/guides/laravel/) or with log channels?

**Comment by futzlarson** [comment]
I followed the installation guide using composer. Except it's the `report()` function in `ExceptionHandler.php` rather than `register()`. Perhaps a relic of initially starting with Laravel 5.8? Here is the function:

```
    public function report(Throwable $exception)
    {
        // Sentry.
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            $sentry = app('sentry');

            // Set user if one exists.
            if (auth()->check()) {
                $sentry->configureScope(function (Scope $scope): void {
                    $user = auth()->user();

                    $scope->setUser([
                        'id' => $user->id,
                        'email' => $user->email,
                        'name' => $user->name,
                        'plan' => $user->plan,
                    ]);
                });
            }

            // Capture.
            $sentry->captureException($exception);
        }

        parent::report($exception);
    }
```

**Comment by futzlarson** [comment]
I have some new info. I added my own logging into `ExceptionHandler.php` and got this:

```
Array
(
    [error] => none: Maximum execution time of 30 seconds exceeded
    [url] => https://app.auxbus.com/signup
    [previous] => https://app.auxbus.com
    [method] => GET
    [info] => Array
        (
            [ip] => 185.93.3.92
            [user_agent] => Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)
            [os] => 
            [browser] => PingdomBot 1.4
            [desktop] => 1
        )
)
```

And this is what I learned:

1. The url, which strangely is a very basic signup page.
2. It's coming from a monitoring bot. At least this time.

Why exactly it's triggering this `RecursiveDirectoryIterator` timeout is for me to find out, but I'm wondering why I had to add my own logging to catch the url and user agent?

**Comment by futzlarson** [comment]
Any update?

**Comment by stayallive** [comment]
I do not know why the Maximum execution time is not catched, it definitely should but I have a hard time reproducing it in my environment which makes it extremely hard to track down what is happening unfortunately... if you have some way of recreating it that would help tracking down why it's not catched.

Just to make doubly sure, can you also share your `config/sentry.php` to make sure nothing is disabled / ignored in there?

**Comment by futzlarson** [comment]
Can't you do `sleep(31)` to verify? Here's `config/sentry.php`:

```
<?php

return [
    'dsn' => env('SENTRY_LARAVEL_DSN'),

    // capture release as git sha
    'release' => release(),

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => true,
];
```

**Comment by stayallive** [comment]
Yes, that was my first instinct... however...

![image](https://user-images.githubusercontent.com/1090754/156363679-22cb847b-b510-4edc-b6ea-71f9f64bba0c.png)

So this "works on my machine" ™ which is not helping you of course... so that's why I am having trouble figuring out what is happening.

**Comment by futzlarson** [comment]
Interesting. Well, it hasn't come up since initially reporting, so how about we close it for now and I'll reopen if it occurs again? Appreciate your efforts.
