### ISSUE TITLE
User (pii) is not identified with sanctum

### ISSUE THREAD

**Issue by ankurk91** [getsentry/sentry-laravel#539]
### Environment

* I am Sentry SaaS (sentry.io) 
* Laravel 8.x (latest as of now) with php 8.1

Which SDK and version?
* latest  - 2.11.0

### Steps to Reproduce

1. Install sentry-laravel, and set DSN and set `send_default_pii` to true
1. Install and configure [sanctum](https://laravel.com/docs/8.x/sanctum) and try to access some REST api endpoints gaurded with `auth:sanctum`.
2. Throw a Test exception from controller
3. Let sentry capture the exception
4. Open sentry dashboard and Notice that sentry could not pick the logged-in user  id.

### Expected Result

Sentry can detect authenticated user from `web` guard, but not from `sanctum`.

Sanctum recently added a `TokenAuthenticated` event which sentry-laravel can listen and can set context.
https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/EventHandler.php#L55

### Actual Result
Sentry should detect user id and report it

**Comment by stayallive** [comment]
Hmm, I'm guessing sanctum doesn't fire the `Illuminate\Auth\Events\Authenticated`. Too bad.

But we can for sure start listening for `TokenAuthenticated` and implement similar functionality.

Thanks for pointing this out!

**Comment by ankurk91** [comment]
Must be labelled as in-progress

**Comment by stayallive** [comment]
Fixed by #542.
