### ISSUE TITLE
Sentry log channel ignores report method on a handled exception

### ISSUE THREAD

**Issue by adiachenko** [getsentry/sentry-laravel#541]
### Environment

**How do you use Sentry?**
Sentry SaaS (sentry.io)

**Which SDK and version?**
Laravel 8.0 `sentry/sentry-laravel:2.11.0`

### Steps to Reproduce

1. Configure Sentry in Laravel Log channels by following [this guide](https://docs.sentry.io/platforms/php/guides/laravel/usage/#log-channels)
2. Create an exception with a report method that returns false as shown in the snippet below (documented [here](https://laravel.com/docs/8.x/errors#renderable-exceptions)).
3. Throw this exception somewhere.

```php
public function report()
{
    return false;
}
```

### Expected Result

Exception is NOT reported to Sentry.

### Actual Result

Exception is reported to Sentry. You have to explicitly add an exception to the exception handler's `$dontReport` array if you want to ignore it.

**Comment by cleptric** [comment]
As we hook into Laravel's reporting system, returning false has the desired effect and is not considered a bug imo.
