### ISSUE TITLE
Shorter way to add extra data to Sentry message

### ISSUE THREAD

**Issue by drmax24** [getsentry/sentry-laravel#545]
Hi guys. Can you suggest how to write the following into one line:    

```php
$eh = new \Sentry\EventHint();
$eh->extra = ['data' => ['a', 'b', 'bla-bla' => 1]];
\Sentry\captureMessage('egisz_callback', Severity::info(), $eh);
```

Older versions of this library allowed to pass an array argument for extra. Can you please help to figure out a shorter notation?

**Comment by stayallive** [comment]
A `EventHint` can be created from an array, this might be a little shorter?

```php
\Sentry\captureMessage(
    'egisz_callback',
    \Sentry\Severity::info(),
    \Sentry\EventHint::fromArray([
        'extra' => ['data' => ['a', 'b', 'bla-bla' => 1]],
    ])
);
```

You can also include a helper in your project to make it even shorter:

```php
function sentry_message(string $message, ?array $extra = null, ?\Sentry\Severity $severity = null): void
{
    \Sentry\captureMessage(
        $message,
        $severity ?? \Sentry\Severity::info(),
        \Sentry\EventHint::fromArray([
            'extra' => $extra,
        ])
    );
}
```

and use it like:

```php
sentry_message('egisz_callback', ['data' => ['a', 'b', 'bla-bla' => 1]]);
```

Hope that helps!

**Comment by lukascocula** [comment]
> A `EventHint` can be created from an array, this might be a little shorter?
> 
> ```
> \Sentry\captureMessage(
>     'egisz_callback',
>     \Sentry\Severity::info(),
>     \Sentry\EventHint::fromArray([
>         'extra' => ['data' => ['a', 'b', 'bla-bla' => 1]],
>     ])
> );
> ```
> 
> You can also include a helper in your project to make it even shorter:
> 
> ```
> function sentry_message(string $message, ?array $extra = null, ?\Sentry\Severity $severity = null): void
> {
>     \Sentry\captureMessage(
>         $message,
>         $severity ?? \Sentry\Severity::info(),
>         \Sentry\EventHint::fromArray([
>             'extra' => $extra,
>         ])
>     );
> }
> ```
> 
> and use it like:
> 
> ```
> sentry_message('egisz_callback', ['data' => ['a', 'b', 'bla-bla' => 1]]);
> ```
> 
> Hope that helps!

Hi, I implemented my code same way, but I am not able to see any extra data in Sentry web interface. I am not sure if implementation is correct or I need to make some additional setup to allow extra data or something? Many thanks

**Comment by stayallive** [comment]
Yes I am sorry, I misunderstood our own code 🤦 

This will work (tested it myself this time):

```php
function sentry_message(string $message, ?array $extra = null, ?\Sentry\Severity $severity = null): void
{
    \Sentry\withScope(function (\Sentry\State\Scope $scope) use ($message, $extra, $severity) {
        $scope->setExtras($extra);

        \Sentry\captureMessage($message, $severity ?? \Sentry\Severity::info());
    });
}
```

Sorry for the confusion!
