### ISSUE TITLE
Span trace for Laravel HTTP Client Requests

### ISSUE THREAD

**Issue by atymic** [getsentry/sentry-laravel#547]
Hey!

Would be awesome to add support for tracing http requests made via the laravel HTTP client. Should be fairly easy as events are fired.

https://laravel.com/docs/9.x/http-client#events

**Comment by stayallive** [comment]
It seems you've done some research on it and calling it "fairly easy", want to take a stab at creating a PR?

**Comment by atymic** [comment]
Sure can do :)
Will PR shortly.

**Comment by cleptric** [comment]
Done in #585 and to be released in v3.0.0
