### ISSUE TITLE
Composer Require Error with Laravel 9.x and PHP 8.1

### ISSUE THREAD

**Issue by niyazialpay** [getsentry/sentry-laravel#549]
### Environment

Laravel 9.x (latest as of now) with php 8.1

Which SDK and version?
latest - 2.11.0

### Steps to Reproduce

I run below command
composer require sentry/sentry-laravel

### Actual Result

sh-4.2$ composer require sentry/sentry-laravel
Using version ^2.11 for sentry/sentry-laravel
./composer.json has been updated
Running composer update sentry/sentry-laravel
Loading composer repositories with package information
Updating dependencies
Lock file operations: 18 installs, 0 updates, 0 removals
  - Locking clue/stream-filter (v1.6.0)
  - Locking http-interop/http-factory-guzzle (1.2.0)
  - Locking jean85/pretty-package-versions (2.0.5)
  - Locking nyholm/psr7 (1.5.0)
  - Locking php-http/client-common (2.5.0)
  - Locking php-http/discovery (1.14.1)
  - Locking php-http/httplug (2.3.0)
  - Locking php-http/message (1.13.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking php-http/promise (1.1.0)
  - Locking sentry/sdk (3.1.1)
  - Locking sentry/sentry (3.3.7)
  - Locking sentry/sentry-laravel (2.11.1)
  - Locking symfony/http-client (v6.0.3)
  - Locking symfony/http-client-contracts (v3.0.0)
  - Locking symfony/options-resolver (v6.0.3)
  - Locking symfony/polyfill-uuid (v1.24.0)
  - Locking symfony/psr-http-message-bridge (v2.1.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 18 installs, 0 updates, 0 removals
  - Installing http-interop/http-factory-guzzle (1.2.0): Extracting archive
  - Installing jean85/pretty-package-versions (2.0.5): Extracting archive
  - Installing symfony/options-resolver (v6.0.3): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing clue/stream-filter (v1.6.0): Extracting archive
  - Installing php-http/message (1.13.0): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing php-http/httplug (2.3.0): Extracting archive
  - Installing php-http/client-common (2.5.0): Extracting archive
  - Installing php-http/discovery (1.14.1): Extracting archive
  - Installing symfony/psr-http-message-bridge (v2.1.2): Extracting archive
  - Installing symfony/polyfill-uuid (v1.24.0): Extracting archive
  - Installing nyholm/psr7 (1.5.0): Extracting archive
  - Installing symfony/http-client-contracts (v3.0.0): Extracting archive
  - Installing symfony/http-client (v6.0.3): Extracting archive
  - Installing sentry/sentry (3.3.7): Extracting archive
  - Installing sentry/sdk (3.1.1)
  - Installing sentry/sentry-laravel (2.11.1): Extracting archive
6 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\OptionsResolver\Exception\InvalidOptionsException 

  The option "environment" with value true is expected to be of type "null" or "string", but is of type "bool".

  at vendor/symfony/options-resolver/OptionsResolver.php:1029
    1025▕                 if (\is_array($value) && $allowedContainsArrayType) {
    1026▕                     throw new InvalidOptionsException(sprintf('The option "%s" with value %s is expected to be of type "%s", but one of the elements is of type "%s".', $this->formatOptions([$option]), $fmtActualValue, $fmtAllowedTypes, $fmtProvidedTypes));
    1027▕                 }
    1028▕
  ➜ 1029▕                 throw new InvalidOptionsException(sprintf('The option "%s" with value %s is expected to be of type "%s", but is of type "%s".', $this->formatOptions([$option]), $fmtActualValue, $fmtAllowedTypes, $fmtProvidedTypes));
    1030▕             }
    1031▕         }
    1032▕
    1033▕         // Validate the value of the resolved option

      +23 vendor frames 
  24  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
sh-4.2$

**Comment by stayallive** [comment]
Reading the error, what do you have configured for the `environment` in your `config/sentry.php` and/or what is the value of `APP_ENVIRONMENT` in your `.env`?

**Comment by niyazialpay** [comment]
I was creating config/sentry.php file after composer installation. I created config/sentry.php file before installation and solved, thank you
