### ISSUE TITLE
Target class [hash] does not exist. When trying to install

### ISSUE THREAD

**Issue by humunuk** [getsentry/sentry-laravel#556]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
composer require sentry/sentry-laravel
Laravel v7.30.6
PHP 7.4.27

### Steps to Reproduce

Just in command line: composer require sentry/sentry-laravel

### Expected Result

Sentry installed successfully

### Actual Result

```
Illuminate\Foundation\ComposerScripts::postAutoloadDump
@php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [hash] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
    807| 
    808|         try {
    809|             $reflector = new ReflectionClass($concrete);
    810|         } catch (ReflectionException $e) {
    811|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812|         }
    813| 
    814|         // If the type is not instantiable, the developer is attempting to resolve
    815|         // an abstract type such as an Interface or Abstract Class and there is

      34 vendor frames 
  35  app/Console/Kernel.php:186
      Illuminate\Foundation\Console\Kernel::bootstrap()

      1 vendor frames 
  37  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by stayallive** [comment]
If you run `composer install` or `composer update` before you run the `composer require`, same problem because we are not resolving `hash` from the container so this error is interesting.

Did you do any other modifications to the framework like removing authentication or something?

**Comment by humunuk** [comment]
Can you help me point to where I could start debuging? 

The app is really really old (starting from Laravel 4.2) and been in continous developement since 2014, so there might be places where upgrading from 4->5->6->7 we have done something differently.

We are using authentication the Laravel way I think, haven't removed anything.

If I check my config/app.php then in alises I do have: 'Hash'           => 'Illuminate\Support\Facades\Hash',

**Comment by stayallive** [comment]
If you run `composer install` or `composer update` before you run the `composer require` does the same problem occur?

You can also try to run `php artisan package:discover -vvv` to see a little more output or check the Laravel log file to see maybe a bigger stacktrace so we can pinpoint better where it's exactly coming from.

**Comment by humunuk** [comment]
I update my comment about running install or update before require.

artisan package:discover -vvv doesnt show more log trace, so I am thinking could it be that the problem occurs before even app is instantiated?

**Comment by humunuk** [comment]
Can you please not close this issue? It's past my worktime already, will continue working with it tomorrow.

It's just that when I install another package (f.e spatie/laravel-permission, fruitcake/laravel-cors), the problem doesn't occur.

If I install separately (sentry/sentry and sentry/sdk), the problem doesn't occur.

It's only when i require sentry/sentry-laravel the problem comes.

**Comment by humunuk** [comment]
Ah yeah sorry :)

No problem does not occur when I just run composer install or composer update.

I thought you said "first run those 2 commands and then require command", my bad

**Comment by humunuk** [comment]
Hey I found the problem.

We have created custom logger for our logging.

In our custom LoggerCreator class we have this code:

``
    public static function getLogFormat()
    {
        if (Auth::check()) {
            $userData = Auth::id();
        } else {
            $userData = 'null';
        }

        $ip = array_key_exists('REMOTE_ADDR', $_SERVER) ? $_SERVER['REMOTE_ADDR'] : '';
        $uuid = array_key_exists('X-Req-Id', $_REQUEST) ? $_REQUEST['X-Req-Id'] : '';
        $userData .= ':' . $ip . ':' . $uuid . ':';

        return "[%datetime%] %channel%.%level_name%: $userData %message% %context% %extra%\n";
    }
```

Now keep in mind all this works perfectly if not trying to install sentry-laravel package.

The line if(Auth::check) is the line that causes the [hash] problem and it causes the problem only with sentry-laravel package,

Can you help with trying to solve why this is?

**Comment by humunuk** [comment]
I have understood that sentry/sentry-laravel package gets installed, but then when i try to start app (f.e. php artisan tinker) it shows the problem I have described in OP

**Comment by humunuk** [comment]
Narrowed down problem a bit further, the problem arises when Sentry tries to extend log manager:

```
        if (($logManager = $this->app->make('log')) instanceof LogManager) {
            $logManager->extend('sentry', function ($app, array $config) {
                return (new LogChannel($app))($config);
            });
        }
```

Line: `$logManager->extend`

**Comment by stayallive** [comment]
Hi @humunuk, I'm sorry for the delay and appreciate all the digging you have been doing!

I'm going to try to reproduce and if possible fix!

Can you share a bit more how you register the custom `LoggerCreator`? I can't seem to find much info on that on what you might have done and the `getLogFormat()` method doesn't seem to be one that is overriden since I can't find that method name in the Laravel sources.

**Comment by humunuk** [comment]
Sure, it's quite old code base and things could have changed by now.

Also I want to say that no need to be sorry, at this point things could be that this is a feature of Laravel that you might not be able to solve.

In Laravel config/logging.php we use this:

```
'default' => env('LOG_CHANNEL', 'custom'),

'channels' => [
        'custom' => [
            'driver' => 'custom',
            'via' => LoggerCreator::class,
        ],
      ]
```

and then in `.env` file `LOG_CHANNEL=custom`

This is whole LoggerCreator class:

```
class LoggerCreator
{
	
	public function __invoke($config)
    {
        return self::createLogger(php_sapi_name());
    }

    public static function getLogFormat()
    {
        if (Auth::check()) {
            $userData = Auth::id();
        } else {
            $userData = 'null';
        }
        $ip = array_key_exists('REMOTE_ADDR', $_SERVER) ? $_SERVER['REMOTE_ADDR'] : '';
        $uuid = array_key_exists('X-Req-Id', $_REQUEST) ? $_REQUEST['X-Req-Id'] : '';
        $userData .= ':' . $ip . ':' . $uuid . ':';

        return "[%datetime%] %channel%.%level_name%: $userData %message% %context% %extra%\n";
    }

    /**
     * @param null|string $logFileName
     * @param null        $storagePath where to store the log - defaults to Laravel storage and logs
     * @return StreamHandler
     * @throws \Exception
     */
    public static function createHandlerAndSetFormatter($logFileName = null, $storagePath = null)
    {
        if ($logFileName == config('app.env')) {
            $baseName = php_sapi_name();
        } else {
            $baseName = $logFileName;
        }

        $logLevel = Monolog::toMonologLevel(config('app.log_level'));

        if(is_null($storagePath)){
            $storagePath = storage_path();
        }
        $path = $storagePath.'/logs/'.$baseName.'.log';

        if (config('app.log') == 'single') {
            $handler = new StreamHandler($path, $logLevel);
        } else {
            $maxFiles = config('app.log_max_files');
            $handler = new RotatingFileHandler($path, $maxFiles, $logLevel);
        }

        $formatter = self::getFormatter();
        $handler->setFormatter($formatter);

        return $handler;
    }

    /**
     * @return LineFormatter
     */
    private static function getFormatter()
    {
        $format = self::getLogFormat();
        return new LineFormatter($format, $dateFormat = null, $allowLineBreaks = true, $ignoreEmptyContextAndExtra = true);
    }

    /**
     * @param string $channel
     * @return Monolog
     */
    public static function createLogger($channel)
    {
        $handler = self::createHandlerAndSetFormatter($channel);
        $logger = new Monolog($channel, [$handler]);

        return $logger;
    }
}
``

**Comment by stayallive** [comment]
This does seem like a highly specific thing, even though we are triggering it a bit early this doesn't seem like it would or should work honestly since the log format is calling the `Auth::id()` probably way before any actual code has run. 

There doesn't seem to be a way for us to register the custom logger without triggering your custom code. I could provide some change to the service provider allowing you to disable the logger registration, but if another package ever registers it's own logger you are going to back at square 1 :)

**Comment by stayallive** [comment]
I have been trying to trigger the issue with the `LoggerCreator` class and setting it as the default logger on Laravel 7.30.6 and PHP 7.4.30 but I think I'm missing a piece because I am unable to reproduce it so far with your instructions.

```
 ❯ php74 artisan tinker --execute 'echo config("logging.default")'
custom
 ❯ php74 artisan tinker --execute 'echo config("logging.channels.custom.via")'
App\LoggerCreator
 ❯ composer74 require sentry/sentry-laravel
Using version 2.x-dev for sentry/sentry-laravel
./composer.json has been updated
Running composer update sentry/sentry-laravel
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: sentry/sentry-laravel
Package manifest generated successfully.
84 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
