### ISSUE TITLE
Commits for Release not showing

### ISSUE THREAD

**Issue by JonPurvis** [getsentry/sentry-laravel#559]
### Environment

How do you use Sentry?
Self Hosted

Which SDK and version?
sentry/sentry-laravel
Laravel 8
PHP 7.4

This is more of a question than a bug, although it could be a bug, who knows!

I have releases tracking for one of our projects, I can see that the latest release went out about 20 minutes ago, which is about right. If I click into the release though, I just get the below when I try and view the commit data for the release

![image](https://user-images.githubusercontent.com/7534029/174691632-6efea520-29fa-46d2-8989-d243320b9687.png)

In `config/sentry.php` for the `release` key, I have:

```
'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),
```

Am I missing something from this in order to also send Sentry the commit information it needs? I've had a look through documentation for this package but couldn't find anything! 

Cheers! 🍻

**Comment by stayallive** [comment]
In this screenshot I cannot tell if the `release` is actually working.

However, that has nothing to do with the commits being attributed to a release, so for the sake of your question whatever you set `release` to doesn't really matter.

> https://docs.sentry.io/product/releases/suspect-commits/#enable-suspect-commits

The above documentation outlines what need to be done to attribute commits to a release.

It basically means you need to create the release using `sentry-cli` or the API and tell it what commit (or range of commits) you are deploying.

The `release` in the Laravel config is just to attribute the issue you are sending to Sentry to be shown with the correct release which is used for showing information about when it was first seen and such, but you are using the commit hash here it actually has no meaning, it could be an arbitrary value (like `v1.1.3`) and you could still get commits for that release following the docs linked above.

I feel this became a bit of a messy comment but I hope I helped a bit in the understanding. Feel free to point out where I can expand on the explanation if needed 👍

**Comment by JonPurvis** [comment]
Managed to get commits pulling through nicely, I think this was a slight misunderstanding on my part.

Thanks for the reply though! I'll close this issue off now.

**Comment by stayallive** [comment]
Great to hear! Thanks for the update 👌
