### ISSUE TITLE
Exception in SentryLaravelEventHandler.php with laravel 5.4

### ISSUE THREAD

**Issue by olibar** [getsentry/sentry-laravel#56]
After migrating to  lavarel 5.4 I am getting the following
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Events\Dispatcher::firing() in /Users/olivier/Developer/CellmarkDMS/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelEventHandler.php:29

seems that the firing method is no longer available in  Illuminate\Events\Dispatcher::firing()

Looked in ``laravel-debugbar`` project from which SentryLaravelEventHandler's event handling is inspired and we have the following (inBarryvdh\Debugbar\DataCollector\EventCollector):
      `  // Pre-Laravel 5.4, using 'firing' to get the current event name.`
        `if (method_exists($this->events, 'firing')) {`
          `  $name = $this->events->firing();`
           ` // Get the arguments passed to the event`
          `  $data = func_get_args();`
        `}`

**Comment by dcramer** [comment]
You need to upgrade the SDK

**Comment by olibar** [comment]
Thanks
What is the required SDK version I should put in my composer ?

**Comment by dcramer** [comment]
@olibar just install the latest version (or take a look at the CHANGES file in this repo to see what you need)
