### ISSUE TITLE
SENTRY_ENVIRONMENT is always production in Laravel

### ISSUE THREAD

**Issue by LocalHeroPro** [getsentry/sentry-laravel#560]
### Version

22.5.0.dev0

### Steps to Reproduce

1. Make two environments: STG, PRD.
```
// in STG .env file
APP_ENV=stg
```
```
// in PRD.env file
APP_ENV=prd
```
2. Leave default as is Sentry config file:
```
// When left empty or `null` the Laravel environment will be used
    'environment' => env('SENTRY_ENVIRONMENT'),
```
3. Go to STG, PRD environment and run
```bash
$ php8.1 artisan sentry:test
```
4. Go to Sentry dashboard and filter issues by environment.

### Expected Result

Sentry will resolve environment type from Laravel .env file from APP_ENV.

### Actual Result

Always reporting as production enviroment.
![image](https://user-images.githubusercontent.com/42643563/171058777-5c18adf3-1bbd-46e2-b3e4-d99d0b89db6e.png)

**Comment by chadwhitacre** [comment]
@stayallive Ideas on this one? 🤔

**Comment by jonaswebdev** [comment]
Hi, I'm experiencing the same issue, I fixed the bug temporally putting the line below in .env file ;)


`SENTRY_ENVIRONMENT="${APP_ENV}"`
