### ISSUE TITLE
Raw URLs sent as Transaction

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-laravel#562]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
sentry-laravel 2.12.0

### Steps to Reproduce

Sending transactions

### Expected Result

High quality transactions

### Actual Result

for sentry laravel (2.12.0) we're getting raw URLs and bad transactions. we noticed:
- OPTIONS has raw URLs. probably shouldn't be recorded to begin with
- there's a bunch of transactions reported without http.method
- 404s are missing the http.status, and those also come with raw URLs

**Comment by smeubank** [comment]
for more context, to improve the performance product experience, we are working to improve transaction naming

meaning that in product we don't have a ton of unique transactions because of poor parameterization from different platforms

Meaning the org slug `…/sentry/…` becomes `…/:orgId/… `

1. all web SDKs should now send source: [dev spec](https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations)
2. [DSC spec](https://develop.sentry.dev/sdk/performance/dynamic-sampling-context/#note-on-low-quality-transaction-names) regarding transaction name quality

**Comment by smeubank** [comment]
and sentry-symphony sends URLs for everything

**Comment by smeubank** [comment]
@jan-auer is there some data we can share with @stayallive regarding 

> there's a bunch of transactions reported without http.method

for option we we agreed to exclude similar to other SDKs it is not useful

**Comment by cleptric** [comment]
@stayallive We should take this into consideration for the DS rollout.

**Comment by cleptric** [comment]
Done in https://github.com/getsentry/sentry-laravel/pull/583 and to be released in v3.0.0
