### ISSUE TITLE
Exception sending doesn't work

### ISSUE THREAD

**Issue by yuraplohov** [getsentry/sentry-laravel#563]
I have installed sentry/sentry-laravel and ran all steps from [guide](https://docs.sentry.io/platforms/php/guides/laravel/)

When I run sentry:publish I see a new event on Sentry dashboard, But when I run sentry:test or throw exception in code I don't see new events on the dashboard

Laravel version: 9
sentry/sentry-laravel: 2.13.0
PHP: 8.1

What could be the reason?

**Comment by stayallive** [comment]
What is the event you get on the dashboard when you run `sentry:publish`?

And did you clear your config cache after publishing by running `php artisan config:clear` before running `php artisan sentry:test`?

**Comment by yuraplohov** [comment]
When I run `sentry:publish` I see a question 

> Want to send a test event? (yes/no)

I answer Yes and see a new event _SentryTestTransaction_ on dashdoard

Yes, I ran `php artisan sentry:test` several times

**Comment by stayallive** [comment]
Is `SENTRY_LARAVEL_DSN` added to your `.env` file?

`sentry:publish` runs `sentry:test` but with the DSN on the command line so if it's not working the `SENTRY_LARAVEL_DSN` might not be correctly added to your `.env` or you have your config cached causing the `.env` not being loaded at all.

**Comment by yuraplohov** [comment]
`SENTRY_LARAVEL_DSN` is added to my `.env` file and has the value I specified in the command `sentry:publish`

When I run sentry:test I see that message in console:
```
DSN discovered from Laravel config or `.env` file!
Sending test event...
Test event sent with ID: 057a3dca3b514dbfb686ebccbd03ad63
```

**Comment by stayallive** [comment]
Have you put the event ID in the search in Sentry?

It's the exact same test even as for `sentry:publish` so it might be grouped instead of showing a new event showing up, because this looks all good to me!

**Comment by yuraplohov** [comment]
I tried to put the event ID in the search in Sentry and saw the text `No items found`
The count of transactions also doesn't change after `sentry:test` and exception throwing

**Comment by yuraplohov** [comment]
Thanks for the help!

Maybe that doesn't work becouse I have expired trial

So I changed Sentry acccount and it works.

**Comment by stayallive** [comment]
Oh yeah that will do it. But that means that the sentry:publish test also didn't work recently. Glad you got it figured out!
