### ISSUE TITLE
Create new release with Sentry SDK 3.7

### ISSUE THREAD

**Issue by Radiergummi** [getsentry/sentry-laravel#566]
This isn't a bug per se, but I would like to use the performance tracing features, and Sentry complains my server-side SDK is outdated. I can't update it, however, because the Laravel package limits the SDK version to 3.2 (released in March 2021).

Therefore, I'd like to kindly ask you to release a new version with the current SDK dependency. Thank you 🙏

**Comment by cleptric** [comment]
Looking at the `composer.json`, we require

```
"sentry/sentry": "^3.3",
"sentry/sdk": "^3.1",
```

So you should always get the latest minor version when you run `composer upgrade`.
`sentry/sdk` is our so-called meta-package, which includes an http-clinet, the latest release is `3.2`.
`sentry/sentry` is the SDK without an http-client, the latest release here is version `3.7`.
It's confusing, I know 😄 

What is the output of `composer info` if you run it in your application?

@stayallive Out of curiosity, why do we require both the SDK and meta-package?

**Comment by Radiergummi** [comment]
@stayallive aaah, got it. `sentry/sdk` is a meta package, and shows up as locked to 3.2.0 in composer output, but installs `sentry/sentry@3.7` already... sorry, confusion on my part.
```shell
^_^ Styx backend $ composer why sentry/sdk
sentry/sentry-laravel  2.13.0  requires  sentry/sdk (^3.1)  
^_^ Styx backend $ composer why sentry/sentry
sentry/sdk             3.2.0   requires  sentry/sentry (^3.5)  
sentry/sentry-laravel  2.13.0  requires  sentry/sentry (^3.3) 
```

**Comment by stayallive** [comment]
No worries! Thanks for reporting back 😄
