### ISSUE TITLE
How can I with sentry/sentry-laravel add custom silent message?

### ISSUE THREAD

**Issue by PetroGromovo** [getsentry/sentry-laravel#569]
on  laravel 9 site with sentry/sentry-laravel I want to add custom errors and I do it in common
control method:

    throw new Exception($request->source . ' : ' . $request->message . ' at ' . formatDateTime($request->time));

But I see 500 error in my browser and would like to avopid it.
Are there some silent methods to add log message ?

Are there some methods for add some custom Tags for any message ?
For filtering by this tags in sentry console ?

    "laravel/framework": "^9.26.1",
    "sentry/sentry-laravel": "^2.13"        

        
Thanks in advance!

**Comment by cleptric** [comment]
https://docs.sentry.io/platforms/php/guides/laravel/usage/#capturing-errors

Is this what you were looking for?
