### ISSUE TITLE
Composer error for 0.6.1

### ISSUE THREAD

**Issue by shibby** [getsentry/sentry-laravel#57]
Hello there,

It seems there is a problem with version 0.6.1. Let me explain:

When i follow your installation instructions, i installed sentry-laravel with `composer require sentry/sentry-laravel`. Which installed 0.6.1, latest.

But, unfortunately, sentry-laravel folder seems **empty** and of course, cannot load `SentryLaravelServiceProvider`. Here is screenshot:

![screenshot from 2017-03-06 01-21-52](https://cloud.githubusercontent.com/assets/291643/23592001/ee4f88ec-0202-11e7-8945-1f62f88efdf2.png)

I saw this issue with two different laravel installation.
Then i fixed version to 0.6.0 and folder came up and now i can use.

I don't know, maybe its about my composer and my other dependencies. But this happened with 2 different laravel 5.4 installation on same setup. 

Edit: now i've tried with laravel4.2 and inside a vagrant box, it installed like a charm. So, issue should change. Is there anyone else who get trouble with 5.4 :)

**Comment by dcramer** [comment]
im not sure how this could be our fault -- we dont actually do anything besides git tag it, and composer does the rest. If you can come up with any more details maybe we can help, but it sounds like an issue with composer on your system

**Comment by shibby** [comment]
Fixed with #67
