### ISSUE TITLE
Transactions filtered by traces_sampler still eating up Transactions

### ISSUE THREAD

**Issue by Jebble** [getsentry/sentry-laravel#612]
### Environment

`"php": "^8.1",`
`"laravel/framework": "^9.0",`
`"sentry/sentry-laravel": "^3.0",`

### Steps to Reproduce

1. Add `traces_sampler` to `config/entry.php`
```
'traces_sampler' => [SentryHelper::class, 'filterTransactionUrl'],
```
2. Add a healthcheck to the system

### Expected Result
For the health checks to not show up in Sentry transactions.

### Actual Result
Debugging the `trace_sampler` locally correctly returns a `traces_sample_rate` of `0.0` which should mean do not sample this transaction. However, in production when our health checks run, the transactions are still flooding our Sentry account.

Our health checks run on the `/api/health` endpoint
So in the `trace_sampler` I started by checking the transaction name and when visiting the endpoint, it shows the name as `/api/health`
However in Sentry the transaction name is `healthcheck` so I added that to the list of exclusions, but they still keep showing up as transactions.

**config/sentry.php**
```php
<?php 
return [
    ...
    'traces_sample_rate' => (float) (env('SENTRY_TRACES_SAMPLE_RATE', 0.2)),
    'traces_sampler' => [SentryHelper::class, 'filterTransactionUrl'],
];
```

**SentryHelper.php**
```php
<?php

class SentryHelper
{
    private const EXCLUDED_TRANSACTION_NAMES = [
        '/api/health',
        'healthcheck',
    ];

    public static function filterTransactionUrl(\Sentry\Tracing\SamplingContext $context): float
    {
        if ($context->getParentSampled()) {
            // If parent transaction is sampled, also sample the current transaction.
            return 1.0;
        }

        if (in_array(
            $context->getTransactionContext()->getName(),
            self::EXCLUDED_TRANSACTION_NAMES
        )) {
            // Drop excluded transactions
            return 0.0;
        }

        // Default sample rate for all other transactions (replaces `traces_sample_rate`)
        return config('sentry.traces_sample_rate');
    }
}
```

![transactions](https://user-images.githubusercontent.com/1397260/201653685-d0f1bd3a-b7ff-4490-bef8-11bafce5e566.png)

**Comment by hmazter** [comment]
I dont know if its correct, but i have solved the same thing with the following code:

```php
    private static array $skip_performance_tracing = [
        'health',
        'ping',
    ];

    public static function tracesSampler(SamplingContext $context): float
    {
        if (request()->is(self::$skip_performance_tracing)) {
            // Skip tracing for specified urls
            return 0.0;
        }

        // read rate from config
        return config('sentry.traces_sample_rate');
    }
```

**Comment by stayallive** [comment]
In case of @Jebble you are using: `$context->getTransactionContext()->getName()`. But this name is not yet set when creating the transaction so that will always return `null` and is why it's not working as expected.

What you can do is configure it like @hmazter with using `request()->is(...)` or wait a little bit for getsentry/sentry-php#1424 to become available so you can do this, since the new `before_send_transaction` will run _just_ before it's sent to Sentry and the transaction name will be available there!

**Comment by cleptric** [comment]
@Jebble Can you let us know what the output of `$context->getTransactionContext()->getName()` in your `traceSampler` method is?

Your code should work fine using SDK `>= v3.0.0`, just confirmed with a test app.

**Comment by Jebble** [comment]
> @Jebble Can you let us know what the output of `$context->getTransactionContext()->getName()` in your `traceSampler` method is?

The output of that is `"/api/health"`
However in Sentry these transactions show p specifically as `healthcheck` where all other transactions come through with their "normal" name.
So I contacted Sentry support, they told me to add `healthcheck` to the filtering and given me some new transactions to test with but sadly that didn't change anything.

The sampler I'm calling lives in one of our common packages shared between multiple API's, but I have confirmed on the production environment that the packages are all up to date, the config files are set on the API's correctly and that the sampler is running. But for some reason the `healthcheck` transactions keep coming through.

**Comment by Jebble** [comment]
> @Jebble I do see `healthcheck` transactions from two days ago using `Version: 2.13.0`.

Thanks for that, this made me check a few things.
In production everything is working, as I can see no healthcheck transactions coming through.

However, apparently our QA environments also have these checks enabled and there's a few that haven't had `main` merged in recently, meaning the `traces_sampler` isn't enabled for those environments.

That makes all the sense now and confirms that the sampler is indeed working.
Thanks for your help!
