### ISSUE TITLE
"Cannot cast mixed to float." static analysis error for "traces_sample_rate" config key

### ISSUE THREAD

**Issue by khalyomede** [getsentry/sentry-laravel#623]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

^3.3

### Steps to Reproduce

1. Run phpstan
2. An error occurs

> Cannot cast mixed to float.

### Expected Result

No static analysis errors.

### Actual Result

> Cannot cast mixed to float.

**Comment by stayallive** [comment]
Ahh that makes more sense.

You meant that you changed it to this?:

```php
'traces_sample_rate' => env('SENTRY_TRACES_SAMPLE_RATE') === null ? null : floatval(env('SENTRY_TRACES_SAMPLE_RATE')),
```

**Comment by khalyomede** [comment]
Yes absolutely.
