### ISSUE TITLE
Data truncated in body

### ISSUE THREAD

**Issue by chelout** [getsentry/sentry-laravel#63]
While trying to get information about unauthorized webhook, i got truncated data in body section [http://joxi.ru/GrqgnBRtQ8OY72](http://joxi.ru/GrqgnBRtQ8OY72) Sentry json [http://joxi.ru/DrlVZMdIvJ68M2](http://joxi.ru/DrlVZMdIvJ68M2) has the same issue [http://joxi.ru/l2Z6PYwswaYyl2](http://joxi.ru/l2Z6PYwswaYyl2)

**Comment by ehfeng** [comment]
None of the links point to screenshots. Can you please update?

**Comment by ehfeng** [comment]
For context, I spoke with @chelout separately. His main concern is that Array content is not displayed in the stack locals (strings and integers, for example, are). Is it possible we collect and send these as well?

**Comment by chelout** [comment]
I've updated screenshots links

**Comment by dcramer** [comment]
@chelout could you confirm the version of sentry/sentry you're using?

**Comment by chelout** [comment]
The latest version

**Comment by dcramer** [comment]
I wonder if we have the thresholds incorrect. What I believe is happening is its saying "this is recursing too much, just show the Repr version of this instead", which shouldn't be the case here.

**Comment by bretthoerner** [comment]
Yep, our max recursions are 3 which gets you `data` (1), `leads` (2), and then `update` (3) at which point we check `$_depth < $max_depth` and anything that level or lower gets the short serialization.

Do we just want to bump our default levels here or do we do anything smarter in other SDKs? We don't do anything smart in the Java SDK (which I'm familiar with).

**Comment by dcramer** [comment]
@bretthoerner the original goal was to reflect what the server does, which is semi-dumb, but i think also varies based on the type of data.

**Comment by stayallive** [comment]
As per getsentry/sentry-php#554 this limit was increased in `sentry/sentry` version `1.9.0` which should solve this. Please reopen if it's still an issue with that version of the PHP SDK.
