### ISSUE TITLE
Variable values are not showing in stack trace

### ISSUE THREAD

**Issue by discover59** [getsentry/sentry-laravel#634]
### Environment

sentry-laravel 2.11.1
php 7.4.33
laravel 8.12

### Steps to Reproduce

Long time ago, sentry error detail page showed the variable values on each stack trace.
But with current version, I cannot see values of any variables.

### Expected Result

I can see variable values on error detail page of python projects and I think it will be possible for php projects as well.

### Actual Result

Cannot see variable values at all.

**Comment by cleptric** [comment]
See https://docs.sentry.io/platforms/php/troubleshooting/#missing-variables-in-stack-traces.

Please make sure you have `zend.exception_ignore_args: Off` set.

**Comment by night-fury-web** [comment]
Thanks, @cleptric. Let me try.
