### ISSUE TITLE
[Breadcrumbs] [Logs] add to breadcrumbs only from specific logs channels

### ISSUE THREAD

**Issue by 4n70w4** [getsentry/sentry-laravel#637]
Hi! I use few laravel log channels at the same time for different log management systems.

But if I enable `breadcrumbs.logs` in `sentry.php` config — all logs from all channel will attached to sentry breadcrumbs.

But I don't want to see messages from all channels in breadcrumbs.

I would like to be able to configure which channels names will be sent to breadcrumbs (include/exclude). Or include/exclude by channel driver.

https://github.com/laravel/framework/discussions/45830

**Comment by 4n70w4** [comment]
Or as workaround it would be nice create interface for `Sentry\Laravel\EventHandler` and create instance via DI instead `$handler = new EventHandler($this->app, $userConfig);` in `\Sentry\Laravel\ServiceProvider::bindEvents()`. Then it would be possible to override the behavior of `EventHandler` in my code.

**Comment by cleptric** [comment]
A third option could be using the [`before_breadcrumb`](https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#before-breadcrumb) hook to filter out breadcrumbs you don't want to get sent to Sentry.
Looking at the linked discussion, it might be tricky to get the context of the channel.
