### ISSUE TITLE
Laravel 5.4 class sentry does not exist

### ISSUE THREAD

**Issue by errogaht** [getsentry/sentry-laravel#64]
`Uncaught ReflectionException: Class sentry does not exist in /home/vagrant/code/skobdom/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 719`

im just run artisan config:cache for get this issue

composer.json https://pastebin.com/raw/qycpc314

**Comment by dcramer** [comment]
Going to get a Laravel 5.4 example in the app so we can try and reproduce any issues, but im not sure what the 'sentry' class could possibly be.

**Comment by dcramer** [comment]
This sounds like you didnt follow the documentation. I reproduced this by only installing the package and not actually configuring it.

**Comment by errogaht** [comment]
All configured right. But now i have same error without artisan config:cache
`PHP Fatal error:  Uncaught ReflectionException: Class sentry does not exist in /srv/www/skobdom.dev.brcl.ru/vendor/laravel/framework/src/Illuminate/Container/Container.php:719`
something wrong in pulling your class to Laravel service container.

**Comment by errogaht** [comment]
i get error above when use artisan. for example add `TEST_LOL=space between` to .env file

and then run artisan cache:clear for example, and you got that error.

Im think way you add your provider to Laravel container not poperly work wit artisan... i dont know

**Comment by errogaht** [comment]
im think you can add this to your readme
![https://goo.gl/IE2ZdL](https://goo.gl/IE2ZdL)

thats work for me

**Comment by stayallive** [comment]
You can do this to make it a bit simpeler:

```php
public function report(Exception $e)
{
    if (app()->bound('sentry') && $this->shouldReport($e) {
        app('sentry')->captureException($e);
    }

    parent::report($e);
}
```

Submitted pull request with README changes for this (#67).

**Comment by errogaht** [comment]
thanks, work great

**Comment by phpguru** [comment]
To elaborate for future readers (since I ran into this error a few times too)... if you have an error too early in the startup phase of Laravel (such as including another provider in a class you haven't loaded with composer install yet) then sentry can fail to be found in the app because it's not bound yet. The above code example by @stayallive allows sentry usage to fail silently, or more accurately, fall back to standard error reporting. Very helpful. Thanks!

**Comment by vschoener** [comment]
@phpguru I just got the same issue trying to play with Service Provider..
My case: A provider need another provider for DI.. But It blows me the error as sentry does not exist..
Still didn't figure out why

**Comment by Xpedigo** [comment]
> ```
> public function report(Exception $e)
> {
>     if (app()->bound('sentry') && $this->shouldReport($e)) { //<---- Missing ')'
>         app('sentry')->captureException($e);
>     }
> 
>     parent::report($e);
> }
> ```

**Comment by Xpedigo** [comment]
@stayallive Missing ')'

`public function report(Exception $e)
{
    if (app()->bound('sentry') && $this->shouldReport($e)) {
        app('sentry')->captureException($e);
    }

    parent::report($e);
}`
