### ISSUE TITLE
Adding a string with the key `user` to loging context throws an exception

### ISSUE THREAD

**Issue by przemyslaw-przylucki** [getsentry/sentry-laravel#644]
### Environment

Sentry: 3.1.3
Laravel: 9.43.0

### Steps to Reproduce

1. Use sentry as the logger driver

```
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'sentry'],
            'ignore_exceptions' => false,
        ],
```

2. Send a log

```
logger()->info('user', ['userId' => 5, 'user' => 'abc'])
```

### Expected Result

The log is added without any problems.

If this is expected behaviour, this should be explicitly documented somewhere

### Actual Result

An exception is thrown, b/c `user` is apparently a reserved keyword, and passing it in the log creates an exception

![image](https://user-images.githubusercontent.com/43403182/216598427-802d1912-dbe9-469d-b469-17677cd904d2.png)

**Comment by cleptric** [comment]
Thanks for reporting!

@stayallive WDYT?

- Ignore none arrays here and check that keys in the user context are strings https://github.com/getsentry/sentry-laravel/blob/6af4ae521ac4acd06a1bfc100ae1880b2cef1ba5/src/Sentry/Laravel/SentryHandler.php#LL197C58-L197C58
- Cast to string here https://github.com/getsentry/sentry-php/blob/d6671685ce13fdaf70113c7ba2ad1a2a31373fec/src/UserDataBag.php#L110. But this feels meeh.
