### ISSUE TITLE
Package breaks applications using the HasMiddleware interface

### ISSUE THREAD

**Issue by jason-nabooki** [getsentry/sentry-laravel#662]
### Environment

Laravel v9
Sentry Laravel v3.3

### Steps to Reproduce

1. Install sentry-laravel package
2. Navigate to a route where the controller is using the `HasMiddleware` interface and has at least one middleware defined in the controller `middleware()` method.

### Expected Result

The route should load.

### Actual Result

Exception is thrown.

`Call to undefined method Sentry\Laravel\Tracing\Routing\TracingControllerDispatcherTracing::methodExcludedByOptions()`

### Links
https://github.com/laravel/framework/pull/44516
https://www.amitmerchant.com/resolving-middlewares-statically-from-controllers-in-laravel-9x/

**Comment by jason-nabooki** [comment]
Is there a way to disable tracing to prevent the exception from being thrown? Setting `traces_sample_rate` to `null` or `0.0` does not help.

**Comment by stayallive** [comment]
To answer your question, you can [disable autodiscovery](https://laravel.com/docs/10.x/packages#opting-out-of-package-discovery) for `sentry/sentry-laravel` and manually add `Sentry\Laravel\ServiceProvider::class` to the `config/app.php` `providers` array to do enable error reporting but completely disable the tracing code.

I am investigating how to fix this... stay tuned!

**Comment by stayallive** [comment]
I think this is a Laravel bug, so I've submitted a PR: laravel/framework#46498.

I also have a fix ready to work around this if needed but I feel like this is more of a hack than a good solution so I'd rather see the fix implemented in the Laravel framework instead if possible.

**Comment by stayallive** [comment]
The PR to the Laravel framework has been merged, I'll keep this open for reference a bit until it's released but I would assume this will get released with the next Laravel patch release somewhere next week and then it should be all good.

Thanks for reporting!

**Comment by jason-nabooki** [comment]
Thank you so much for investigating this in detail and submitting the PR into the Laravel Framework. Much appreciated @stayallive
