### ISSUE TITLE
Dependency outdated / pinned - requires php-http/discovery below <1.15

### ISSUE THREAD

**Issue by J-Brk** [getsentry/sentry-laravel#671]
### Environment

Laravel 10 - PHP 8.1.2

### Steps to Reproduce

1. Install for example: `openai-php/laravel` which uses `php-http/discovery@1.15.2`.
2. Try to install sentry `sentry/sentry-laravel`.

### Expected Result

The installation to complete.

### Actual Result

Installation error: "sentry/sentry[3.13.1, ..., 3.16.0] require php-http/discovery ^1.11, <1.15 -> found php-http/discovery[1.11.0, ..., 1.14.3] but the package is fixed to 1.15.2 (lock file version) by a partial update and that version does not match."

### Solution
Please resolve the requirement for versions below < 1.15. php-http/discovery v1.15.1 was released 2023-02-10. 
https://github.com/php-http/discovery/releases

**Comment by stayallive** [comment]
We released 3.17 which fixes the issue: https://github.com/getsentry/sentry-php/releases/tag/3.17.0. Just running a composer update and then requiring `openai-php/laravel` should work now!

Thanks for your patience!
