### ISSUE TITLE
The option "traces_sampler" with value array is expected to be of type "null" or "callable", but is of type "array".

### ISSUE THREAD

**Issue by uintaam** [getsentry/sentry-laravel#674]
### Environment

v3.3.2 on PHP 8.1, Laravel 8

### Steps to Reproduce

1. Use an array binding to define "traces_sampler" in the config.  Something like `[\App\Helpers\SentryFilterUrl::class, 'tracesSampler']`
2. Get error `The option "traces_sampler" with value array is expected to be of type "null" or "callable", but is of type "array".`

### Expected Result

This works in PHP 7.4 so the expected result in php 8.1 is for the function SentryFilterUrl::tracesSampler to be called.

### Actual Result
This appears to fail in PHP 8.1 due to type checking?  We need to be able to define the traces_sampler function this way as putting a callable into a config file breaks Laravel config caching `php artisan config:cache`

**Comment by cleptric** [comment]
You can follow https://docs.sentry.io/platforms/php/guides/laravel/configuration/laravel-options/#closures-and-config-caching to make this work.

**Comment by uintaam** [comment]
Thanks for the help, it needed to be static.
