### ISSUE TITLE
[Cron Monitoring] Crons have their environment incorrectly set to the release hash

### ISSUE THREAD

**Issue by bakerkretzmar** [getsentry/sentry-laravel#683]
### Environment

- `sentry/sentry-laravel` v3.3.2
- Laravel v9.52.5

### Steps to Reproduce

1. Set up a cron monitor and check in manually with HTTP requests (custom implementation, see below).
1. Switch over to the new `->sentryMonitor()` macro.

### Expected Result

Expected my checkins to continue working normally.

### Actual Result

New crons are created in Sentry for all of my checks, identical to the existing ones but with their environment set to the release hash instead of the actual environment:

<img width="2051" alt="image" src="https://user-images.githubusercontent.com/18192441/233086426-eb1e4c13-e3d7-4d9d-9922-3f1576e4382c.png">

The checks that are missed are the ones I was expecting, with their environment set to `production`, and the ones that checked in successfully, with their environment set to `e45f996`, I didn't create and don't want.

### Details

Here's what I was doing before to check in manually:

```php
Event::macro('sentry', function (string $monitorId, int $maxExpectedDuration = 30): Event {
    /** @var \Illuminate\Console\Scheduling\Event $this */
    return $this->before(function () use ($monitorId, $maxExpectedDuration) {
        $response = Http::withToken(config('sentry.dsn'), 'DSN')
            ->post("https://sentry.io/api/0/monitors/{$monitorId}/checkins/", ['status' => 'in_progress']);
        Cache::put($monitorId, $response['id'], now()->addMinutes($maxExpectedDuration));
    })->onSuccess(function () use ($monitorId) {
        if ($checkinId = Cache::pull($monitorId)) {
            Http::withToken(config('sentry.dsn'), 'DSN')
                ->put("https://sentry.io/api/0/monitors/{$monitorId}/checkins/{$checkinId}/", ['status' => 'ok']);
        }
    })->onFailure(function () use ($monitorId) {
        if ($checkinId = Cache::pull($monitorId)) {
            Http::withToken(config('sentry.dsn'), 'DSN')
                ->put("https://sentry.io/api/0/monitors/{$monitorId}/checkins/{$checkinId}/", ['status' => 'error']);
        }
    });
});
```

And I assume these config variables will be helpful (I don't have `SENTRY_ENVIRONMENT` set):

```php
    'release' => env('APP_ENV') !== 'local' ? trim(exec('git --git-dir ' . base_path('.git') . ' rev-parse --short HEAD')) : '',

    'environment' => env('SENTRY_ENVIRONMENT'),
```

I'll gladly take a stab at fixing this myself if I have time in the next couple weeks!

**Comment by stayallive** [comment]
Sorry about that, we've fixed this yesterday: https://github.com/getsentry/sentry-laravel/releases/tag/3.3.3. A composer update should fix that right away!

**Comment by bakerkretzmar** [comment]
Oh fantastic, I totally missed that. Thanks! 🙌🏻
