### ISSUE TITLE
Cannot install on Lumen 10.x 

### ISSUE THREAD

**Issue by szwagros** [getsentry/sentry-laravel#684]
When trying to install sentry on Lumen 10.x (running composer require "sentry/sentry-laravel:^2.14") I get this error:

  Problem 1
    - Root composer.json requires sentry/sentry-laravel ^2.14 -> satisfiable by sentry/sentry-laravel[2.14.0, 2.14.1, 2.14.2].
    - sentry/sentry-laravel[2.14.0, ..., 2.14.2] require illuminate/support 5.0 - 5.8 | ^6.0 | ^7.0 | ^8.0 | ^9.0 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but the package is fixed to v10.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Is Lumen 10 version not supported ?

**Comment by stayallive** [comment]
Hi @szwagros, we indeed did not take Lumen support with us with the Laravel 10 push. We are trying to fix that and have started work on adding it back in, if you are willing you can test it out by installing the lumen branch: #685. If you find any issues be sure to let us know so we can fix that up before we release this!

**Comment by stayallive** [comment]
Hey Tim, much appreciated! Thanks for letting us know 😄

**Comment by szwagros** [comment]
> Hi @szwagros, we indeed did not take Lumen support with us with the Laravel 10 push. We are trying to fix that and have started work on adding it back in, if you are willing you can test it out by installing the lumen branch: #685. If you find any issues be sure to let us know so we can fix that up before we release this!

Hi - sorry for late replay. Yes it installs and works fine (error reporting, adding scope etc.) I did not test perf monitoring etc.

**Comment by stayallive** [comment]
Sorry this was closed a few minuted too early but [`3.4.0`](https://github.com/getsentry/sentry-laravel/releases/tag/3.4.0) was just released and contains Lumen 10.x support!

Thanks all for testing!
