### ISSUE TITLE
Queue jobs traces do not keep context modifications

### ISSUE THREAD

**Issue by slkolesov** [getsentry/sentry-laravel#690]
Hi!

The package is amazing and helps a lot. Thanks a lot for all of the hard work!

### Environment

The problem I see after upgrading to Laravel 10.9.0 & sentry-laravel 3.4.0 is that customs tags and other context modifications are not saved in the traces of jobs. Which was not the case when running sentry-laravel 2.14.2 with Laravel 9.

### Steps to Reproduce

1. Enable tracing in sentry.php config: queue_job_transactions=>true & queue_jobs=>true.
3. Add custom tags inside Job::handle() method with [\Sentry\configureScope](https://docs.sentry.io/platforms/php/enriching-events/tags/)
4. Dispatch the job - no matter sync/async.

### Expected Result

I expect my custom tags to appear in Sentry in Performance > Transaction Summary > Event Details.

### Actual Result

No custom tags are being recorded.

### The Reason

I suppose this happens because the context is being reset EventHandler::cleanupScopeForTaskWithinLongRunningProcessWhen before the transaction is sent to Sentry.

**Comment by slkolesov** [comment]
Sure, I did. I have `traces_sample_rate = 1.0` and no `traces_sampler` defined. And I do recieve all of the performance transactions events. They just lack all scope modifications I try to do.

**Comment by cleptric** [comment]
Thanks!
