### ISSUE TITLE
Laravel 10, dependencies error: you cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/message-factory

### ISSUE THREAD

**Issue by KulaKrzysztof** [getsentry/sentry-laravel#694]
### Environment

Ubuntu 22.04
Composer 2.5.5
Laravel 10.8.0

### Steps to Reproduce

1. Create new Laravel project
2. Use command: `composer require sentry/sentry-laravel`

### Actual Result

Composer message: ` You cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/message-factory" package is not installed. Try running "composer require Nyholm/psr7".`

I tried install `composer require Nyholm/psr7`, but it not resolved problem.

**Comment by cleptric** [comment]
As a quick fix, please run `composer require php-http/message-factory` while we work on a release that resolves this issue.

**Comment by cleptric** [comment]
> so please excuse us for requiring an abandoned packed for the time being 🙂

**Comment by smudger** [comment]
Hi, is there any update on this? We're keen to remove the abandoned package as soon as possible :)

**Comment by cleptric** [comment]
No update, we can not remove this dependency without breaking old versions of the Symfony HTTP client. See https://github.com/getsentry/sentry-php/issues/1541#issuecomment-1568068745

In the end, while it’s an annoying prompt, this package contains only some interfaces so it’s not a huge problem imo.
