### ISSUE TITLE
Cron monitoring without DSN set results in error

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-laravel#696]
### Discussed in https://github.com/getsentry/sentry-laravel/discussions/695

<div type='discussions-op-text'>

<sup>Originally posted by **lloricode** May 20, 2023</sup>
I have a scheduled command

```php

        $schedule->command(SomeCommand::class)
            ->sentryMonitor('point-of-sale-cron-monitoring')
```

When I try to run ` php artisan schedule:list` on my local, it's working fine, but when `SENTRY_LARAVEL_DSN=` in .env is not set it will throw an exception:

```
Method Illuminate\Console\Scheduling\Event::sentryMonitor does not exist.
```

I hope this allow to just ignore when there is no setup for sentry</div>

**Comment by cleptric** [comment]
Fixed in [3.4.1](https://github.com/getsentry/sentry-laravel/releases/tag/3.4.1)
