### ISSUE TITLE
Custom tags missing in some contexts 

### ISSUE THREAD

**Issue by Sandeep-Singh-Spartan** [getsentry/sentry-laravel#699]
### Steps to Reproduce

I'm trying to use the Sentry package in a laravel application. but I am facing some inconsistency in the custom tags some time they appear in the sentry dashboard sometimes not.  I am attaching the code snippet .

```php
  if (app()->bound('sentry') && $this->shouldReport($e)) {
            app('sentry')->configureScope(function (\Sentry\State\Scope $scope) use ($e): void {
                $scope->setTag('tracking_code', $this->trackingCode);

                if (auth()->check()) {
                    $scope->setUser($this->getUser());
                    $scope->setTag('user_details', json_encode($this->getUser()));
                }
                app('sentry')->captureException($e);
            });
        }
```

### Expected Result

I am attaching the sentry Dashboard’s screenshot
<img width="842" alt="Screenshot 2023-05-24 at 12 00 13 AM" src="https://github.com/getsentry/sentry-docs/assets/128671203/e79531cc-0b6b-4ad0-ab3c-6ed675ee6e18">
 where I am getting the custom tag 

### Actual Result

some time I am getting the custom tag in sentry dashboard
<img width="844" alt="Screenshot 2023-05-24 at 12 00 28 AM" src="https://github.com/getsentry/sentry-docs/assets/128671203/3d0e9357-8f48-4c04-b089-309e20e51979">

**Comment by cleptric** [comment]
It looks like you did create these events using Postman. Did all requests contain some sort of authentication, either a valid session cookie or something else you're using to authenticate against your application? I'm seeing that one request contains a user id, the other the IP (127.0.0.1) instead.

**Comment by Sandeep-Singh-Spartan** [comment]
Yes, all requests are containing some sort of authentication.  I am setting the custom tag  **$scope->setUser($this->getUser());** **$scope->setTag('user_details', json_encode($this->getUser()));**  **$scope->setTag('tracking_code', $this->trackingCode);**sometimes it contains the user id and sometimes the IP(127.0.01). That inconsistency I am facing

**Comment by Sandeep-Singh-Spartan** [comment]
yes, I don’t want to report some time of exception so, I am restricting. for this shouldReport() is used. I am facing inconsistencies in the custom tag.  Exception sometimes the sentry is showing the custom tag sometime not.

**Comment by stayallive** [comment]
That doesn't answer my questions. I want to know if in your two screenshots you are showing us the exact same exceptions captures by Sentry, as in the exact same error in the exact same place or that they are different errors in different parts of your code?

**Comment by Sandeep-Singh-Spartan** [comment]
@stayallive same exception, same place but inconsistency in sentry.

**Comment by cleptric** [comment]
Please let us know which version of our SDK you're using (sentry/sentry-laravel & sentry/sentry) and your PHP version. Do you use something like Octane as well?

**Comment by Sandeep-Singh-Spartan** [comment]
@cleptric I am using these versions "sentry/sentry-laravel": "^2.12.0", "PHP": ">=8.1" "laravel/framework": "^8.0" . I am not using any specific library or framework like Octane,

**Comment by cleptric** [comment]
Please upgrade to the latest major version of the SDK (v3.4.0) and let us know if your issue persists. Breaking changes were minimal, so this should not require many changes, if any on your side.

**Comment by Sandeep-Singh-Spartan** [comment]
Hi @cleptric I upgrade to the latest version of the SDK (v3.4.0). still, the issue is persisting.

**Comment by stayallive** [comment]
Did you also happen to configure Sentry as log channel in your: `config/logging.php`?
