### ISSUE TITLE
Add getPublicDSN function

### ISSUE THREAD

**Issue by hubertnnn** [getsentry/sentry-laravel#71]
This would make it easier to create Raven dialog, by just adding something like

```
@unless(empty($sentryID))
<script src="https://cdn.ravenjs.com/3.3.0/raven.min.js"></script>
<script>
    Raven.showReportDialog({
        eventId: '{{ $sentryID }}',
        dsn: '{{ Sentry::getPublicDSN() }}'
    });
</script>
@endunless
```

**Comment by stayallive** [comment]
This is [already done](https://github.com/getsentry/sentry-laravel/blob/3427048a284883a9b85db8a0cd3a8412100236f0/examples/laravel-5.4/resources/views/errors/500.blade.php#L49) in the examples, or did you mean the package should append this to error views automatically?

**Comment by hubertnnn** [comment]
What I meant was to have a function that will convert the private DSN that is already available in config/.env to a public one, so you don't have to provide both (or write your own converting function), since hardcoding urls in views is considered a bad design.

**Comment by stayallive** [comment]
Ah I understand, totally looked over that ;) I like the idea!

----

In the meantime you can add a public dsn to the `config/sentry.php` file.

```diff
<?php
return array(
-   'dsn' => '',
+   'dsn' => env('SENTRY_DSN', ''),
+   'public_dsn' => env('SENTRY_PUBLIC_DSN', ''),

    // capture release as git sha
    // 'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => true,

    // Capture default user context
    'user_context' => true,
);
```

And use it like:

```diff
@unless(empty($sentryID))
<script src="https://cdn.ravenjs.com/3.3.0/raven.min.js"></script>
<script>
    Raven.showReportDialog({
        eventId: '{{ $sentryID }}',
-       dsn: '{{ Sentry::getPublicDSN() }}'
+       dsn: '{{ config('sentry.public_dsn') }}'
    });
</script>
@endunless
```

Although something like this is probably how you are doing it already.

**Comment by stayallive** [comment]
Sorry for the lack of response, I have created an issue for this in getsentry/sentry-php#593 because I still think this is a great idea.

Will track the implementation there and close this issue since it's not Laravel specific.

Thanks for the great idea!
