### ISSUE TITLE
Bug missed_checkin in 3.6.0

### ISSUE THREAD

**Issue by wit3** [getsentry/sentry-laravel#722]
### Environment

Laravel v10.14.1
Php v8.2.7
Sentry sdk 3.6.0

### Steps to Reproduce

Exception in Sentry Dashboard after update from 3.5.1 to 3.6.0

### Expected Result

What you thought would happen.

### Actual Result
All my scheduled task ( job/command and third party commands)
are gettings this error 
`
Failure reason | missed_checkin
`
![image](https://github.com/getsentry/sentry-laravel/assets/5450259/81b5e41c-19c0-45ff-b59d-02b4a7a3c0f6)

**Comment by cleptric** [comment]
Could you share an example of one of your scheduled tasks that caused a missed check-in?

**Comment by wit3** [comment]
> Could you share an example of one of your scheduled tasks that caused a missed check-in?

```php

  $schedule->job(\App\Actions\InvoiceDocument\CheckDocumentNeedToChangeStatusToProfiled::makeJob())
            ->environments(['production'])
            ->withoutOverlapping()
            ->evenInMaintenanceMode()
            ->everyTenMinutes()
            ->emailOutputOnFailure('salvatore.scalzi@billoo.it')
            ->sentryMonitor(monitorSlug:'check-document-need-to-change-status-to-profiled')
            ->monitorName('check-document-need-to-change-status-to-profiled');

        $schedule->command(\Spatie\Health\Commands\ScheduleCheckHeartbeatCommand::class)
            ->environments(['production', 'staging'])
            ->withoutOverlapping()
            ->evenInMaintenanceMode()
            ->everyMinute()
            ->sentryMonitor(monitorSlug:'schedule-check-heartbeat')
            ->monitorName('schedule-check-heartbeat-command');
            
         $schedule
            ->job(\App\Actions\Workflows\DocumentBatch::makeUniqueJob(ServiceEnum::EE, 10, null))
            ->environments(['production'])
            ->everyFiveMinutes()
            ->withoutOverlapping()
            ->evenInMaintenanceMode()
            ->sentryMonitor(monitorSlug:'document-batch-ee')
            ->emailOutputOnFailure('salvatore.scalzi@billoo.it')
            ->monitorName('start-workflow-ee');    

```

**Comment by cleptric** [comment]
Thanks. I assume you did create the monitors in the UI. How is `schedule-check-heartbeat` configured there, for example?

**Comment by wit3** [comment]
nope, my monitors is created by laravel sentry sdk after i upgrade from 3.5.1 to 3.6.0

here is my list, all of this is created automatically.

![image](https://github.com/getsentry/sentry-laravel/assets/5450259/ce0241f0-8fd1-41aa-9e82-ebb5fdd9b0d0)

**Comment by wit3** [comment]
maybe the error its caused because i remove the method from my schedueld task and didn't delete the record in the UI?

**Comment by cleptric** [comment]
Yes, this can indeed cause the issue you're seeing. We currently have no mechanism in the SDK that can delete a monitor. So you can either pause or delete them. This then would not create any new "missed check-in" errors.
