### ISSUE TITLE
Send span origin

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-laravel#729]
Trace origin indicates what created a trace or a span. Not all traces and spans contain enough information to tell whether the user or what precisely in the SDK created it. Origin solves this problem. Origin can be sent with the [trace context](https://develop.sentry.dev/sdk/event-payloads/contexts/#trace-context) or [spans](https://develop.sentry.dev/sdk/event-payloads/span/). The SDKs must set this value automatically. Users are not expected to set it manually. For more information, visit the [develop docs](https://develop.sentry.dev/sdk/performance/trace-origin/).

As the origin for trace context and spans is optional, every SDK can decide whether to start sending the origin for everything or just selected transactions and spans. This issue is important for internal data analysis to understand the quality of our traces.

**Comment by cleptric** [comment]
Closed via #939
