### ISSUE TITLE
Custom sampler class boots before middleware to continue trace

### ISSUE THREAD

**Issue by Rezrazi** [getsentry/sentry-laravel#733]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.6.1

### Steps to reproduce

1. Create a new sampler class
```php
<?php

namespace App\Exceptions;

use Sentry\Tracing\SamplingContext;

class SentrySampler
{
    public static function tracesSampler(SamplingContext $context): float
    {
        dd('inside the sampler');

        $name = $context->getTransactionContext()?->getName();

        if ($context->getParentSampled()) {
            // If the parent transaction (for example a JavaScript front-end)
            // is sampled, also sample the current transaction
            return 1.0;
        }

        // Default sample rate for all other transactions (replaces `traces_sample_rate`)
        return 0.1;
    }
}
```

2. Create a middleware to continue trace
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

use function Sentry\continueTrace;

class SentryTraceMiddleware
{
    public function handle(Request $request, Closure $next)
    {
        dd('inside the middleware');
        
        $sentryTraceHeader = $request->header('sentry-trace');
        $baggageHeader = $request->header('baggage');

        if (filled($sentryTraceHeader) && filled($baggageHeader)) {
            continueTrace($sentryTraceHeader, $baggageHeader);
        }

        return $next($request);
    }
}
```

3. Add the middleware, set as first in prio list

```php
// Kernel.php

    protected $middleware = [
        SentryTraceMiddleware::class,
        // \App\Http\Middleware\TrustHosts::class,
        TrustProxies::class,
        HandleCors::class,
        //...
    ];

    protected $middlewarePriority = [
        SentryTraceMiddleware::class,
        //...
    ];
 ```

### Expected result

see "inside the middleware"

### Actual result

sees "inside the sampler"

trace is never continued, and `$context->getParentSampled()` is always false

**Comment by stayallive** [comment]
Why are you defining your own middleware, we already define and register a [middleware](https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/Tracing/Middleware.php) which is why the sampler is called first because our middleware calls it.

Can you share a `sentry-trace` and `baggage` header so we can double check?

**Comment by Rezrazi** [comment]
Oh I must've misunderstood the documentation.
Thanks for the heads-up I'll try again with the default setup.

The reason I tried using a custom middleware was due to the fact that sometimes the trace would not contain Laravel's transactions when using in conjecture with a Vue app.

**Comment by stayallive** [comment]
Interesting indeed… if you have some more info if something turns out to be broken let us know!

**Comment by Rezrazi** [comment]
Yep, I'm still getting `$context->getParentSampled()` set to false with a regular setup without my custom middleware, Sentry relative headers are available to Laravel in the incoming request.

So the sampler never sets the 1.0, and the only transactions I see that have events from both Vue and Laravel, are the ones that match both sampling rates. Vue is at 0.5, Laravel is at 0.1, that's a 5% chance 😄 

Any idea what's happening?

**Comment by stayallive** [comment]
Can you share the baggage and sentry-trace header so I can take a look?

**Comment by Rezrazi** [comment]
```json
{
  "baggage": "sentry-environment=qa,sentry-transaction=presets-id,sentry-public_key=e0ff0b96978b41478148faef88531224,sentry-trace_id=504c7e299c4f44b19aab3ebc310ed603,sentry-sample_rate=0.5",
  "sentry-trace": "504c7e299c4f44b19aab3ebc310ed603-b0b4f12dc2b85823-1"
}
```

I'm guessing `sampled` is missing from the baggage, but I'm not sure I understand how sampling works on the Vue SDK. With 0.5, I do see some requests that do not have these headers, and I do see others with the headers present. How come `sampled` is still missing, because if I see the headers, I'm guessing it was sampled no? 

Nuxt app is configured with the following

```js
  Sentry.init({
    enabled: environment !== 'dev',
    app: [vueApp],
    dsn: sentryDSN,
    environment,
    integrations: [
      new BrowserTracing({
        routingInstrumentation: Sentry.vueRouterInstrumentation(nuxtApp.$router),
        tracePropagationTargets: ['localhost', <redacted>],
      }),
    ],
    tracesSampleRate: 0.5,
  });
```

**Comment by stayallive** [comment]
The "sampled" actually comes from the `sentry-trace` header, the last `1` means it's sampled and it correctly registers that the parent is sampled with your values.

You right now still have a `traces_sampler`? Or just `SENTRY_TRACES_SAMPLE_RATE` set to `0.1`?

This is the code that decides when to sample and looking through there just having a sample rate of basically anything should always sample the transaction if the parent is sampled: https://github.com/getsentry/sentry-php/blob/c965f552d7365edd2b81170f749aa300ab0707ec/src/State/Hub.php#L237-L244

When sending a request with the headers you supplied it correctly shows `->getParentSampled()` as `true`.

**Comment by Rezrazi** [comment]
Yeah it makes sense.

I have only a traces_sampler class set up, no env/config value set.
The tracePropagationTargets are correct, and the headers are indeed reaching the Laravel app.
I need to investigate this further to understand how to get reliable results from distributed tracing in my setup.

Thanks for the help 👌

**Comment by cleptric** [comment]
@Rezrazi In your `traces_sampler`, make sure to inherit the sampling decision to not break the trace. See https://docs.sentry.io/platforms/php/guides/laravel/configuration/sampling/#inheritance
