### ISSUE TITLE
Call to undefined method Sentry\SentryLaravel\SentryFacade::captureException()

### ISSUE THREAD

**Issue by davidsoderberg** [getsentry/sentry-laravel#74]
Hi why do I get "Call to undefined method Sentry\SentryLaravel\SentryFacade::captureException()"
on Codeship and server but not local?

**Comment by stayallive** [comment]
You might have a Sentry DSN in your `.env` locally and not on Codeship.

Make sure you check if Sentry is loaded before calling the facade.

```php
if (app()->bound('sentry')) {
    \Sentry::captureException($exception);
}
```

Could this be the cause?

**Comment by davidsoderberg** [comment]
Maybe I have code it like this:
https://github.com/davidsoderberg/MTGSearch/blob/master/app/Exceptions/Handler.php

**Comment by stayallive** [comment]
Fairly certain that is what's going on. Check it out with this PR davidsoderberg/MTGSearch#1

**Comment by davidsoderberg** [comment]
Thanks for your help 😄

**Comment by Pablo-Camara** [comment]
Don't forget to add the service provider!! 
Check: https://cartalyst.com/manual/sentry/2.1#laravel-4

**Comment by stayallive** [comment]
@Pablo-Camara you are on the https://sentry.io/ repository, you are mentioning documentation unrelated to us but related to: https://github.com/cartalyst/sentry.
