### ISSUE TITLE
Limit amount of SQL queries reported

### ISSUE THREAD

**Issue by garygreen** [getsentry/sentry-laravel#75]
It would be nice to limit the amount of SQL queries that are reported - if you are running a cron task which does a lot of queries and it fails, it will report every single query run, that isn't nice. It also causes a big performance hit to log every single query when you are running a big cron task - which is why Laravel turned it off by default and optionally turn it on via `DB::enableQueryLog()`

Something like a config option with a sane value:

```php
'max_queries' => 50
```

**Comment by dcramer** [comment]
We already limit breadcrumbs to 100 entries, and given that its a time ordered list of events, its a bit odd to all of a sudden start losing events and have a timegap.
