### ISSUE TITLE
Http Response empty after sentry trace / breadcrumb

### ISSUE THREAD

**Issue by Andreas-Halemba** [getsentry/sentry-laravel#754]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.7.*

### Steps to reproduce

1. Send a http request with Guzzle Client
2. Access the psr7 response
3. Response is empty

### Expected result

PSR7 response stream is filled with the body of the initial response from the server.

### Actual result

PSR7 response is empty as the sentry tracer reads the stream and does not rewind it.

**Comment by stayallive** [comment]
Thanks for reporting this, could reproduce and created PR to fix, #756.

**Comment by Andreas-Halemba** [comment]
Thanks for the blazing fast fix.
