### ISSUE TITLE
Sentry makes many querys

### ISSUE THREAD

**Issue by jeangarcia2414** [getsentry/sentry-laravel#76]
Hello friends I am using sentry with laravel 4.2 and I see that every time I get to a route all these querys are executed, is there any way to prevent sentry from doing so many querys?

![captura](https://user-images.githubusercontent.com/4573084/27649304-59b86f30-5bff-11e7-97a7-174a841fba72.JPG)
![captura2](https://user-images.githubusercontent.com/4573084/27649307-5cdd7d86-5bff-11e7-9776-6018f1966cfb.JPG)

**Comment by stayallive** [comment]
(This) Sentry is a exception logger and does not do any queries by itself.

Is it possible you are meant to file this issue at [cartalyst/sentry](https://github.com/cartalyst/sentry)?

---- 

If you are at the correct repo you can disable the user context collection what might cause those queries.

```diff
<?php

return array(
    // Capture default user context
-    'user_context' => true,
+    'user_context' => false,
);
```

**Comment by jeangarcia2414** [comment]
Sorry I can not find that property anywhere, 
this is the version I use "cartalyst / sentry": "2.1.3",

**Comment by stayallive** [comment]
You are in the wrong place @jeangarcia2414 :)

Please file your issue over at https://github.com/cartalyst/sentry, this is not the correct Sentry.
