### ISSUE TITLE
`storage` Config not documented

### ISSUE THREAD

**Issue by tonybolzan** [getsentry/sentry-laravel#766]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.7.3

### Steps to reproduce

`storage` Config not documented anyware

### Expected result

A good documentation

### Actual result

Nothing

**Comment by cleptric** [comment]
Will be added in https://github.com/getsentry/sentry-docs/pull/7734

https://sentry-docs-git-laravel-updates.sentry.dev/platforms/php/guides/laravel/performance/instrumentation/automatic-instrumentation/

As this is more of a docs issue, I'm closing this one.
