### ISSUE TITLE
`Tracing\ServiceProvider::class` are mandatory ever if tracing are not wanted

### ISSUE THREAD

**Issue by tonybolzan** [getsentry/sentry-laravel#767]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.7.3

### Steps to reproduce

- Add `Sentry\Laravel\ServiceProvider::class` but not `Sentry\Laravel\Tracing\ServiceProvider::class`
- Don't add config for `tracing` 
- By default `redis_origin` are `true`
- On call `Cache::get('test')` an error occurred
- Because `Sentry/Laravel/Features/CacheIntegration.php` call `$this->resolveEventOrigin()` from trait `ResolvesEventOrigin`  that call `makeBacktraceHelper` and Laravel Container need know how to contruct `Sentry\Laravel\Tracing\BacktraceHelper`, but don't know.
- Causing a error

### Expected result

works without exception

### Actual result

A error
```
Illuminate\Contracts\Container\BindingResolutionException
Target [Sentry\Serializer\RepresentationSerializerInterface] is not instantiable while building [Sentry\Laravel\Tracing\BacktraceHelper].
```

**Comment by stayallive** [comment]
Hi @tonybolzan, that is indeed not very nice that it results in the error.

However, we also don't advertise that this is possible, can you tell us a bit more about why you are registering the service providers manually and are not loading the tracing provider?

**Comment by tonybolzan** [comment]
#### Sorry for the poor context
We've added Sentry to don't discover to avoid loading features we don't use and improve boot time. We already use other Libs like NewRelic for other types of monitoring, and we would like Sentry to be responsible only for Error Reporting.

If you have 2 providers that depend on each other, why not centralize on 1 provider?
Or better yet, make them work independently, as the only impediment is BacktraceHelper.

Setting all configs of tracing to false resolve the problem because it don't try to load BacktraceHelper
```php
return [
    ...
    'tracing' => [
        'queue_job_transactions' => false,
        'queue_jobs' => false,
        'sql_queries' => false,
        'sql_origin' => false,
        'views' => false,
        'livewire' => false,
        'storage' => false,
        'http_client_requests' => false,
        'redis_commands' => false,
        'redis_origin' => false,
        'missing_routes' => false,
        'continue_after_response' => false,
        'default_integrations' => false,
    ],
];
```

**Comment by stayallive** [comment]
No worries, at the moment there is indeed a requirement for the tracing provider to be loaded. Removing the tracing provider also doesn't completely disable the integrations.

However I wanted to check another thing with you, since you mentioned this:

> Because `Sentry/Laravel/Features/CacheIntegration.php` call `$this->resolveEventOrigin()` from trait `ResolvesEventOrigin`  that call `makeBacktraceHelper` and Laravel Container need know how to contruct `Sentry\Laravel\Tracing\BacktraceHelper`, but don't know.

However, that code can only be reached with an active transaction (see https://github.com/getsentry/sentry-laravel/blob/c3d2317297f8b975dc88a097b26eee7c9ec55b79/src/Sentry/Laravel/Features/CacheIntegration.php#L77-L82) so it seems you have an active transaction in your application which should not be possible in the first place... not enterily sure what is happening but without the tracing provider the middleware should not be registered. Are you manually starting transactions?

**Comment by tonybolzan** [comment]
Não, não estou iniciando transações manualmente.

**Comment by stayallive** [comment]
Okay, in any case `3.8.0` should solve the issue for you. Let me know if it persists!
