### ISSUE TITLE
SDK: Failed to send the event to Sentry. Reason: "HTTP/2 stream 1 was reset for "https://o4505868047417344.ingest.sentry.io/api/4505868048793600/envelope/".".

### ISSUE THREAD

**Issue by madelinejones** [getsentry/sentry-laravel#776]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

3.4.1

### Steps to reproduce

1. Followed all of the steps on the [docs](https://docs.sentry.io/platforms/php/guides/laravel/) up to `php artisan sentry:test`, successfully received the test message for my local env
2. Pushed to production (using Laravel Vapor (cli v1.56.0, core v2.31.0)
3. Attempted to `run php artisan sentry:publish --dsn=mydsnhere` and received the error
4. Also tried just manually adding the values to the env and then running `php artisan sentry:test`, but received the same error

### Expected result

Expected to receive the Sentry test message

### Actual result

Error received:
`Sending test event...
There was an error sending the event.
SDK: Failed to send the event to Sentry. Reason: "HTTP/2 stream 1 was reset for "https://o4505868047417344.ingest.sentry.io/api/4505868048793600/envelope/".".
Please check the error message from the SDK above for further hints about what went wrong.`

https://prnt.sc/8ohfCd2C_I7H
https://prnt.sc/w2PPq1Rk0Gwn

**Comment by cleptric** [comment]
Please update the Laravel SDK with `composer update sentry/sentry-laravel -W`. This is a cURL bug we fixed a while ago in the underlying PHP SDK.
