### ISSUE TITLE
The option "profiles_sample_rate" does not exist all of a sudden.

### ISSUE THREAD

**Issue by cAstraea** [getsentry/sentry-laravel#779]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

 "sentry/sentry-laravel": "^3.2"

### Steps to reproduce

run php artisan

currently it's broking the instance and dunno how to fix it. Guess I'll try to remove the package in the meantime. 

### Expected result

no errors

### Actual result

php artisan

   Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException

  The option "profiles_sample_rate" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "before_send_transaction", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enable_compression", "environment", "error_types", "http_connect_timeout", "http_proxy", "http_timeout", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags", "trace_propagation_targets", "traces_sample_rate", "traces_sampler".

  at vendor/symfony/options-resolver/OptionsResolver.php:871
    867▕         if (\count($diff) > 0) {
    868▕             ksort($clone->defined);
    869▕             ksort($diff);
    870▕
  ➜ 871▕             throw new UndefinedOptionsException(sprintf((\count($diff) > 1 ? 'The options "%s" do not exist.' : 'The option "%s" does not exist.').' Defined options are: "%s".', $this->formatOptions(array_keys($diff)), implode('", "', array_keys($clone->defined))));
    872▕         }
    873▕
    874▕         // Override options set by the user
    875▕         foreach ($options as $option => $value) {

      +22 vendor frames
  23  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Sentry\Laravel\ServiceProvider))

      +5 vendor frames
  29  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

![image](https://github.com/getsentry/sentry-laravel/assets/13070662/2412dfe9-2347-4891-84e4-4282faf8962a)

**Comment by cleptric** [comment]
Did you define `profiles_sample_rate` in your `config/sentry.php` file?
The version you're using is likely too old to support profiling, we shipped this in `sentry/sentry` [v3.15.0](https://github.com/getsentry/sentry-php/releases/tag/3.15.0), which is a peer dependency of the Laravel SDK.

You can update the SDK and all its dependencies by running `composer update sentry/sentry-laravel -W`.

**Comment by cleptric** [comment]
I assume your issue was resolved, so I'm closing it.
