### ISSUE TITLE
[Cron Monitoring] DateTimeZone Argument Error

### ISSUE THREAD

**Issue by cyreb7** [getsentry/sentry-laravel#782]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.8.1

### Steps to reproduce

We recently updated from Sentry version 3.3.3 to 3.8.1, and when we did our Cron monitor started throwing errors. We aren't doing anything fancy, but here's our command:
```
$schedule->command(LogScheduledTasksRunning::class)->everyMinute()->sentryMonitor();
```

### Expected result

Using the old version of the SDK had no issue running the `sentryMonitor()` command without issue.

We've found that passing `sentryMonitor(updateMonitorConfig: false)` fixes the issue.

### Actual result

This error is thrown:
```
TypeError 

Sentry\MonitorConfig::__construct(): Argument #4 ($timezone) must be of type ?string, DateTimeZone given, called in /var/www/html/api/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Features/ConsoleIntegration.php on line 97

at vendor/sentry/sentry/src/MonitorConfig.php:29
   25▕      * @var string|null The timezone
   26▕      */
   27▕     private $timezone;
   28▕ 
➜  29▕     public function __construct(
   30▕         MonitorSchedule $schedule,
   31▕         ?int $checkinMargin = null,
   32▕         ?int $maxRuntime = null,
   33▕         ?string $timezone = null

   +25 vendor frames 
26  artisan:35
   Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by cleptric** [comment]
We released [3.8.2](https://github.com/getsentry/sentry-laravel/releases/tag/3.8.2), which fixes this issue.
