### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.

### ISSUE THREAD

**Issue by RealMrHex** [getsentry/sentry-laravel#786]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

latest

### Steps to reproduce

install latest version of sentry laravel client:  `"sentry/sentry-laravel": "^3.8"`
Please update php-http/message-factory dependency to psr/http-factory.

### Expected result

-

### Actual result

-

**Comment by cleptric** [comment]
This is tracked here https://github.com/getsentry/sentry-php/issues/1541
