### ISSUE TITLE
Livewire 3 requests are not identified as Livewire in transansaction

### ISSUE THREAD

**Issue by hmazter** [getsentry/sentry-laravel#787]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.8.2

### Steps to reproduce

1. Use Laravel with Livewire 3 (regular Livewire Components, not Volt)
2. Make livewire component update request, using the default `POST /livewire/update` endpoint
3. See the transaction in Sentry as /livewire/update

### Expected result

I expect to see the component name in the transaction to differentiate between different component updates

### Actual result

I see the default `/livewire/update` as transaction name 
![Screenshot 2023-10-20 at 08 06 14](https://github.com/getsentry/sentry-laravel/assets/805377/e6884d28-5b0b-4b4f-bda8-4b1463601b0e)

I guess this is being addressed in #736

**Comment by stayallive** [comment]
Yes, correct, unfortunately Livewire team has made some drastic changes and no guide on how to migrate our current setup to their new structure. So we didn't complete the work yet to get our integration working for Livewire 3. If you have insights I'd be glad to accept some help on the PR otherwise we will eventually get to it!

**Comment by hmazter** [comment]
Thanks for the answer!
I'm pretty new to Livewire so I don't have any insight (yet) that could help 😄

**Comment by cleptric** [comment]
Did some research today

We can still listen to some events via `LivewireManager::listen`

- `component.booted` -> ???
- `component.boot` -> ???
- `component.dehydrate` -> `dehydrate`
- `component.mount` -> `mount`

There are zero docs, zero upgrade guides nor any meaningful PRs to look at, so this is very tedious.

To check for a livewire request, they now perform `request()->hasHeader('X-Livewire')`.

**Comment by cleptric** [comment]
Support for Livewire 3 was added in [v4.0.0](https://github.com/getsentry/sentry-laravel/releases/tag/4.0.0).

**Comment by hoangtrunga1k55** [comment]
> Support for Livewire 3 was added in [v4.0.0](https://github.com/getsentry/sentry-laravel/releases/tag/4.0.0).

Is support for livewire2?

**Comment by stayallive** [comment]
Yes, both Livewire 2 and 3 are supported.

**Comment by hoangtrunga1k55** [comment]
@stayallive Can you help me?
I have issue with livewire2 and sentry. Each action of livewire, it will make transaction like " livewire?component=pos.pos-transaction". But my url is pos/pos-transaction. How can I group it in transaction pos/pos-transaction and identify each action of livewire (Example: search, goToPage...)

**Comment by cleptric** [comment]
Please open a new issue.
