### ISSUE TITLE
Disable packages sent to sentry

### ISSUE THREAD

**Issue by AidasK** [getsentry/sentry-laravel#788]
### Problem Statement

Would love to disable sending packages information with each error. Looks like waste of resources since these dependencies are very stable and we have more than 50 of packages. Never used this info to debug an error.

<img width="1191" alt="image" src="https://github.com/getsentry/sentry/assets/2088484/4bc2dec9-0b4c-4a4c-a07f-cb6287c0a507">

### Solution Brainstorm

Just add a setting to disable sending this information.

**Comment by cleptric** [comment]
You can disable the package integration as shown here https://docs.sentry.io/platforms/php/guides/laravel/integrations/#custom-integrations

Just replace `\Sentry\Integration\ExceptionListenerIntegration` with `\Sentry\Integration\ModulesIntegration`.
