### ISSUE TITLE
sentry:test command sometimes works sometimes doesn't

### ISSUE THREAD

**Issue by bogdan-kocic** [getsentry/sentry-laravel#817]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.8.2

### Steps to reproduce

I have been using sentry for a long time now without any issues. After upgrading to 3.8 version I started encountering problem where sentry:test command sometimes works sometimes doesn't.

Most of the times it doesn't work, I get following error:
```
DSN discovered from Laravel config or `.env` file!
Sending test event...
There was an error sending the event.
Please check if your DSN is set properly in your `.env` as `SENTRY_LARAVEL_DSN` or in your config file `config/sentry.php`. 
```

I tried generating new sdk client key, but the outcome is same.

### Expected result

`DSN discovered from Laravel config or `.env` file!
Sending test event...
Test event sent with ID: ***`

### Actual result

```
DSN discovered from Laravel config or `.env` file!
Sending test event...
There was an error sending the event.
Please check if your DSN is set properly in your `.env` as `SENTRY_LARAVEL_DSN` or in your config file `config/sentry.php`. 
```

**Comment by stayallive** [comment]
This seems like it might be an networking issue. I would advise you to do two things.

First, upgrade to the latest 4.x release of the SDK (changes are minimal in most cases but do please look over the upgrade guide!)

Seconds, if that doesn't solve the issue you can use the new `logger` option to get some more output that might show where the errors lies, documentation for that here: https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#logger

Let me know if either (or both) of those helps!

**Comment by bogdan-kocic** [comment]
Hello, unfortunately the suggestions didn't help.
This is the whole situation that's happening:
After running **php artisan sentry:publish --dsn=** and accepting test event, the test event passes without errors. For some time after that when I run **php artisan sentry:test** the event is sent without issues. Again after some time it start giving errors but not every time until it gets to stage where it fails every time.

**Comment by stayallive** [comment]
This sounds super strange, is some external tool updating your `.env` file perhaps? 

Or are you using config caching (you can try clearing it with `php artisan config:clear`)?

Unless the config is changing this makes no sense to me 😅

**Comment by apertureless** [comment]
Hey, I've got a similar problem, just that sentry now stopped working.
The error message is also not very helpful

```
 sail artisan sentry:test
DSN discovered from Laravel config or `.env` file!
Sending test event...
There was an error sending the event.
Please check if your DSN is set properly in your `.env` as `SENTRY_LARAVEL_DSN` or in your config file `config/sentry.php`.
```


DSN is properly set. And it is also working. I used the same DSN for testing for the javascript integrations and javascript errors were properly captured.

But any laravel errors / exceptions are not captured. 
I've migrated from 3 -> 4, then it stopped working. 

Have the latest `sentry-laravel` version. 
I have also deleted `config/sentry.php` and re-ran the artisan command.

**Comment by stayallive** [comment]
Same suggestions for you to try: https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#logger. Create a `config/sentry.php` with:

```php
<?php

return [
    'logger' => new \Sentry\Logger\DebugFileLogger(filePath: storage_path('logs/sentry.log')),
];
```

Do not use config caching with this since that doesn't work :)

Anything interesting in the output?

**Comment by LeQuyetTien** [comment]
I have the same problem. This is the result in sentry.log:
![image](https://github.com/getsentry/sentry-laravel/assets/15649247/afe9e196-f1d2-449b-90ac-359570364ea8)

**Comment by cleptric** [comment]
Can you please check if you have `ext-curl` installed and enabled on the CLI when you run the test command? We had another user reach out on Discord, and they ran into https://github.com/getsentry/sentry-php/blob/master/src/HttpClient/HttpClient.php#L43-L45.

**Comment by cleptric** [comment]
Version [4.2.0](https://github.com/getsentry/sentry-laravel/releases/tag/4.2.0) will surface any issues during sending the test event as well as check for the presence of ext cUrl.
