### ISSUE TITLE
Report missing translations

### ISSUE THREAD

**Issue by khalyomede** [getsentry/sentry-laravel#827]
### Problem Statement

I just stumble upon a feature in the [documentation ](https://laravel.com/docs/10.x/localization#handling-missing-translation-strings)of Laravel 10 that allows us to perform any action when the framework encounter a missing translation.

### Solution Brainstorm

To be able to report a missing translation by opt-in for Sentry to catch it:

```php
// app/Providers/AppServiceProvider.php

public function boot(): void
{
    Lang::handleMissingKeysUsing(function (string $key, array $replacements, string $locale) {
        Sentry::reportMissingTranslation($key, $replacements, $locale);
 
        return $key;
    });
}
```

**Comment by cleptric** [comment]
I don't think that many people will be willing to burden the cost for each missing translation. As this then will also be reported for each request, your quota will be depleted in no time.
