### ISSUE TITLE
sentry.breadcrumbs error=Auth guard [] is not defined

### ISSUE THREAD

**Issue by rentalhost** [getsentry/sentry-laravel#83]
This error happen when the `config/auth.php` file doesn't exists. 
In my case, I don't need of this file.

In this case, the auth process should be ignored.

**Edit**: is possible disable it by setting `user_context => false`. Then I don't know if it can be considered a bug.

**Comment by stayallive** [comment]
Since getting the user context needs an guard this is expected behavior, as you mentioned using `user_context => false` in your `config/sentry.php` is the correct way to disable this functionality.

**Comment by Cyrille37** [comment]
Thanks @stayallive,

But the message occurs all the time like in artisan command, where there is no user context.
```
$ ./artisan list
sentry.breadcrumbs error=Authentication user provider [xxx] is not defined.
Laravel Framework 5.4.30

Usage:
  command [options] [arguments]
...
```

**Comment by Cyrille37** [comment]
Ok, #70 solves that ;-)
Thanks again :-)
