### ISSUE TITLE
[Cron Monitoring] Whether to consider adding a switch configuration option for Cron monitoring?

### ISSUE THREAD

**Issue by summerKK** [getsentry/sentry-laravel#836]
### Problem Statement

The scenario goes like this.
If I run in `dev environment`, `php artisan schedule:run`, `Cron` side will generate `CheckIn`, resulting in a lot of `CheckIn`. Can you consider adding a configuration option to avoid `dev environment` to enable this function?

### Solution Brainstorm

sentry.php

```php
[
    'crons' => [
        'monitor_enabled' => env('SENTRY_CRONS_MONITOR_ENABLED', false),
    ],
]
```

src/Sentry/Laravel/Features/ConsoleIntegration.php
```php
public function isApplicable(): bool
{
    return $this->container()->make(Application::class)->runningInConsole() && $this->isCronsFeatureEnabled('monitor_enabled');
}
```

**Comment by summerKK** [comment]
I created a PR 😎
 #837

**Comment by cleptric** [comment]
`before_send_check_in` was added to the PHP SDK in [v4.5.0](https://github.com/getsentry/sentry-php/releases/tag/4.5.0).
