### ISSUE TITLE
Idle timeout reached

### ISSUE THREAD

**Issue by renatoalbsantos** [getsentry/sentry-laravel#851]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

php version 8.3.2

Hello everyone, recently I started receiving this error, does anyone have a solution that could solve it?
<img width="917" alt="Screenshot 2024-02-07 at 09 11 56" src="https://github.com/getsentry/sentry-laravel/assets/88661269/85382ec2-5f15-48dd-8559-099f2c891bbb">

**Comment by cleptric** [comment]
And which SDK version do you use?

**Comment by renatoalbsantos** [comment]
> And which SDK version do you use?
this
<img width="914" alt="Screenshot 2024-02-07 at 09 44 39" src="https://github.com/getsentry/sentry-laravel/assets/88661269/a1691eff-0e5a-40e9-812a-ca8bf97487d0">

**Comment by cleptric** [comment]
You can update the SDK to v4.2.0 to see if this fixes your issue. We now ship our own HTTP client.
