### ISSUE TITLE
Disabling SSL Verify Peer

### ISSUE THREAD

**Issue by Davpyu** [getsentry/sentry-laravel#858]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.2.0

### Steps to reproduce

Hello, i want to ask about how to disable ssl_verify_peer?
1. I tried putting this value on config/sentry.php
```'http_ssl_verify_peer' => false,```
2. and then i add this line on Sentry\Laravel\Console\TestCommand to check if its getting the config. It does giving me the correct config
3. after that i add this on Sentry\Laravel\Console\TestCommand to check if its still showing the same config
4. hmm, thats odd. Why its suddenly change? I decide to check on Sentry\ClientBuilder if its changing on that class. It does not change here, so why its suddenly change on number 3?

### Expected result

http_ssl_verify_peer should be changing when configure on config/sentry.php

### Actual result

For Number 2:
![Screenshot 2024-03-05 143211](https://github.com/getsentry/sentry-laravel/assets/42276243/69342269-907c-4e63-9f92-a278e27c01a3)
For Number 3:
![Screenshot 2024-03-05 143636](https://github.com/getsentry/sentry-laravel/assets/42276243/dad577a1-d8f0-4d50-b207-3e9f7b7e141c)
For Number 4:
![Screenshot 2024-03-05 144212](https://github.com/getsentry/sentry-laravel/assets/42276243/e487e39a-557d-4ac9-aa57-7b53c6bfb307)

**Comment by stayallive** [comment]
The `php artisan sentry:test` uses it's own options and ignores most user-defined options.

See: https://github.com/getsentry/sentry-laravel/blob/2c70e34ee8227559b4710602409f94658f0d989a/src/Sentry/Laravel/Console/TestCommand.php#L92-L97

So this is why the `http_ssl_verify_peer` is not picked up when running `php artisan sentry:test`.

That being said, I think we should not ignore any transport options so I've opened #859 to resolve that oversight and that PR should solve the issue you are seeing.

**Comment by cleptric** [comment]
A fix was released in [4.3.0](https://github.com/getsentry/sentry-laravel/releases/tag/4.3.0).
