### ISSUE TITLE
Improve app paths

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-laravel#86]
I'm not sure how best to approach this, but for example, 'routes' is outside of ``app_path``, and so generating an error there results in a poor user experience. We could use ``base_path`` as the app root, but then it includes vendor, which is also a problem. This possibly needs upstream changes to ``sentry/sentry`` to make this behavior better.

**Comment by dcramer** [comment]
Going to play with something that utilizes ``excluded_app_paths``

**Comment by stayallive** [comment]
Maybe it would also be nice to be able to define multiple included/excluded paths.
