### ISSUE TITLE
Link to Laravel v10 docs broken

### ISSUE THREAD

**Issue by driesvints** [getsentry/sentry-laravel#863]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.6.1

### Steps to reproduce

I wanted to check the Laravel v10 instructions but the link in the readme is broken and only the Laravel v11 instructions are visible.

### Expected result

See the Laravel v10 install guide.

### Actual result

See a page not found: https://docs.sentry.io/platforms/php/guides/other-versions/laravel8-10/

<img width="790" alt="Screenshot 2024-03-12 at 21 44 28" src="https://github.com/getsentry/sentry-laravel/assets/594614/625b8da5-f895-441b-9780-5568b655ee99">

**Comment by cleptric** [comment]
Thanks for the report. Got a PR open that up fixes the issue 🙂
The correct link is https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel8-10/

**Comment by driesvints** [comment]
Thanks!
