### ISSUE TITLE
Does captureUnhandleException still work for Laravel 11

### ISSUE THREAD

**Issue by sts-ryan-holton** [getsentry/sentry-laravel#871]
### Problem Statement

Hi,

I've recently updated to Laravel 11. I notice that your guide for Laravel 11 utilises `Integration::handles()` and not `Integration::captureUnhandledException()`.

Am I still able to use this or must I use `handles`. If so, I need to exclude certain exceptions as per my code, should I utilise `$e` or `$exceptions`.

### Solution Brainstorm

My code

```php
->withExceptions(function (Exceptions $exceptions) {
        $exceptions->reportable(function (Throwable $e) {
            if ($e !== null && is_string($e->getMessage())) {
                if (Str::contains($e->getMessage(), ['has been attempted too many times', 'Deadlock found when trying to get lock'])) {
                    return false;
                }
            }

            Integration::captureUnhandledException($e);
        });
});
```

**Comment by stayallive** [comment]
I'll let you in on a little "secret" 😉 

https://github.com/getsentry/sentry-laravel/blob/67667313292f1040ab003fcc9d74f0ee38e36888/src/Sentry/Laravel/Integration.php#L56-L64

You are totally fine to keep using `Integration::captureUnhandledException` (we do it too), if you upgrade from Laravel 10 there is nothing for you to change if you don't want to. The guide for Laravel 11 is for new installations or people using the new L11 structure. Our L10 docs are also available if you need them: https://docs.sentry.io/platforms/php/guides/laravel/other-versions/laravel8-10/.

I do want to mention that the `before_send` callback is our preferred method of filtering what you do or do not want to send to Sentry: https://docs.sentry.io/platforms/php/guides/laravel/configuration/filtering/#filtering-error-events.
