### ISSUE TITLE
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by fhferreira** [getsentry/sentry-laravel#872]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.1.1

### Steps to reproduce

```
laravel/framework                      v6.20.44               The Laravel Framework.
laravel/horizon                           v3.7.2                 Dashboard and code-driven configuration for Laravel queues.
sentry/sentry-laravel                 4.1.1                  Laravel SDK for Sentry (https://sentry.io)

```

Jobs on HORIZON

### Expected result

Jobs finishes without any issue, and looking at DB no failed_job and the code looks that have worked successful but we received the issues on sentry.

### Actual result

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away (SQL: select * from table_x where id = 123 limit 1)

Here apparently I have the same false positive with laravel-sentry related in the issue below:

https://github.com/laravel/horizon/issues/583#issuecomment-2020910963

**Comment by fhferreira** [comment]
```
carbonphp/carbon-doctrine-types           2.1.0                  Types to use Carbon in Doctrine
doctrine/annotations                      1.13.2                 Docblock Annotations Parser
doctrine/cache                            2.1.1                  PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc,...
doctrine/collections                      1.6.8                  PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                           3.2.0                  PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as ...
doctrine/deprecations                     v0.5.3                 A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selective...
doctrine/event-manager                    1.1.1                  The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                        2.0.8                  PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plu...
doctrine/instantiator                     1.4.0                  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                            1.2.3                  PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/persistence                      2.2.3                  The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.

```

all those packages are used here

**Comment by fhferreira** [comment]
maybe could be the versions of doctrine packages.

**Comment by joeljohn135** [comment]
Try Adjusting your MySQL wait_timeout and max_allowed_packet settings to be more forgiving for long-running jobs or ensure your application keeps the connection alive. Or if you realize that its a sentry problem then exceptions reported by Sentry are not indicative of actual problems in your application, you can configure Sentry to ignore these specific exceptions.

**Comment by stayallive** [comment]
I still think this issue is not triggered by Sentry just captured and reported. 

Thanks @joeljohn135 for chipping in, you hit it right on the nose and if you feel like you can safely ignore it you can check out the options we have for [filtering](https://docs.sentry.io/platforms/php/guides/laravel/configuration/filtering/) and exclude the exception from being reported.

If you still feel like Sentry is somehow causing this I would love to check that out but I need a little more information and a reproduction case, this is a non-standard Laravel setup I have no experience with so a repoduction helps getting to the root of the issue if there is any.

But long story short I don't think it's reasonable that the Sentry SDK causes this issue.

**Comment by fhferreira** [comment]
I've updated horizon configurations with explicit retry_after and updated the package sentry, apparently the erros has gone.

```
sentry/sentry                              4.6.1                  PHP SDK for Sentry (http://sentry.io)
sentry/sentry-laravel                      4.4.0                  Laravel SDK for Sentry (https://sentry.io)

```
