### ISSUE TITLE
Possible bug if transaction is not sampled?

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-laravel#894]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

Sentry PHP 4.7.0

### Steps to reproduce

I might be confused or misunderstanding something, but in looking at Sentry\Laravel\Tracing\Middleware, the transaction is only set on the hub if it was sampled:

```php
        if (!$transaction->getSampled()) {
            return;
        }

        $this->transaction = $transaction;

        SentrySdk::getCurrentHub()->setSpan($this->transaction);
```

However, code in the PHP SDK, such as the getTraceparent(), getW3CTraceparent() and getBaggage() functions, looks at the span on the hub to see if it was sampled.  Therefore, I would have assumed that we want to put a transaction that is not sampled on the hub.

Is the Laravel SDK "doing it wrong" and it should be putting even unsampled transactions on the hub? Or am I just confused and misunderstanding things, which is quite possible :)

### Expected result

I _think_ an unsampled transaction should be on the hub, so that it can be determined that is was not sampled.

### Actual result

The sampling decision, which was actually false, appears to be null.

**Comment by mfb** [comment]
I guess this was done as an optimization? But, to keep the optimization in place, while indicating that the transaction is not sampled, maybe other tracing code could check if both `$parentSpan && $parentSpan->getSampled()` to keep the optimization in place?

**Comment by cleptric** [comment]
Yep, we're fixing this in the core and Laravel Symfony SDKs.
We'll only keep the transaction around though, to keep memory pressure low.

**Comment by mfb** [comment]
Ok so I'm not crazy :p Not sure if core PHP SDK needs to fixed at all, seemed like mainly an issue in Laravel thus I filed the issue here.

**Comment by mfb** [comment]
Actually, looking at core PHP SDK, the GuzzleTracingMiddleware needs some logic fixes:  First of all, it looks like breadcrumb data is only set if there is a span, but I think breadcrumb data should always be set?  And then, don't start span if $span exists but is not sampled.
