### ISSUE TITLE
Sentry delays execution of scheduled commands when offline

### ISSUE THREAD

**Issue by ZacharyDuBois** [getsentry/sentry-laravel#895]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.5.1

### Steps to reproduce

Currently, Sentry is having either ingestion delays or other service issues. All of my cron checks have been marked as failed even though they are working.

1. Create a cron monitor like this (something that would run otherwise fast):
```php
Schedule::command('horizon:snapshot')
    ->everyFiveMinutes()
    ->onOneServer()
    ->withoutOverlapping()
    ->sentryMonitor('horizon_snapshot');
```

2. Run the command without a DSN set. Command completes almost instantly and will move on to the next task immediately.
3. Run again with DSN set while Sentry is having issues. Command runs successfully but delays the next roughly 10s (essentially whatever Sentry has for a timeout).
4. If multiple scheduled tasks are needing to be run, they are all delayed resulting in a backlog.

### Expected result

Since Sentry is only a monitor, it should not impact the rest of the application's operations. If possible, I would think Sentry would either wait for all scheduled commands to complete so a backlog doesn't develop when they have an issue on their end.

### Actual result

Causes a backlog of scheduled commands to run which also can result in two `schedule:run`'s overlapping (thank you Laravel for that `withoutOverlapping()` flag!). Also impacts internal health checks within the Laravel app itself. Like Spatie's health package for monitoring queue/schedule/heartbeat.

**Comment by cleptric** [comment]
Could you let me know the time frame you saw these longer response times?

One way to make your application a bit less reliant on wait times due to the synchronous nature of PHP is using a [self-hosted relay](https://docs.sentry.io/product/relay/getting-started/).
It's a small proxy sever you put somewhere next to your application, which then accepts all events and forwards them to Sentry.

**Comment by cleptric** [comment]
We do set a connection timeout of [2s](https://github.com/getsentry/sentry-php/blob/master/src/Options.php#L39) and a timeout of [5s](https://github.com/getsentry/sentry-php/blob/master/src/Options.php#L33). These values can also be customized in your `config/sentry.php` file, as `http_connect_timeout` and `http_timeout`.

We also recently made some changes to our ingestion time outs server side, but what you are reporting concerns me that these changes do not have the effect we were hoping to see.

**Comment by stayallive** [comment]
I'm wondering if the doubled timeout you are seeing is because for scheduled commands we do a ping at the start of the command and one at the end. Which is why it's double of the expected 5s timeout although 5s might still be on the long side for a timeout.
