### ISSUE TITLE
Ingestion Requests affect API Response Times for Users

### ISSUE THREAD

**Issue by PaulWen** [getsentry/sentry-laravel#897]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.7.0

### Steps to reproduce

Yesterday, we experienced Sentry requests that timed out after 5 seconds as also reported here: https://status.sentry.io/

This affected our services' response times as they increased by 5 seconds.

### Expected result

I would have expected that the Sentry SDK would send the collected data to Sentry AFTER answering the request to ensure that the time required to send the data to Sentry does not affect the users' response times.

### Actual result

Based on our networking logs, the Sentry SDK sends the collected data to Sentry BEFORE sending the response to users.

**Comment by stayallive** [comment]
We use a terminable middleware to sent our less important performance data. However errors are sent immediately which might cause slowdowns if you application is sending errors in a request.

You can mitigate this by deploying Relay in your environment to remove the impact of Sentry latency on your application: https://docs.sentry.io/platforms/php/guides/laravel/performance/#improve-response-time

You can also lower the default timeout: https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#http-timeout
