### ISSUE TITLE
Horizon Support

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-laravel#90]
@taylorotwell suggested we could do this via simple handlers:

https://twitter.com/taylorotwell/status/890209354934341638

This lines up to how we attach in other systems (e.g. Python) so should be straight forward. We'd want to grab tags and alike by default.

**Comment by stayallive** [comment]
We could actually do this without Horizon too.

```Illuminate\Queue\Events\JobFailed```

**Comment by dcramer** [comment]
so it sounds like the Horizon event is based on the illuminate JobFailed, but it extends it with additional metadata (e.g. queue name)

https://github.com/laravel/horizon/blob/master/src/Listeners/MarkJobAsFailed.php

**Comment by stayallive** [comment]
I believe this has been tackled by #153.
