### ISSUE TITLE
`queue.publish` span takes very long without any clear reason

### ISSUE THREAD

**Issue by pataar** [getsentry/sentry-laravel#905]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.5.1

### Steps to reproduce

1. We have a job that spawns multiple jobs
2. The 'spawning' job takes very long, due the cause of the queue.publish span

It's not really sure why. Any idea?

### Expected result

This should be instant.

### Actual result

<img width="1473" alt="image" src="https://github.com/getsentry/sentry-laravel/assets/3403851/2c402dd5-82a6-46d7-a278-5e49e1d0bf02">

**Comment by stayallive** [comment]
What queue driver are you using? It looks like database? But maybe also `sync`?

Can you tell me a little more simplified about your setup (how the jobs are nested)?

**Comment by pataar** [comment]
> What queue driver are you using? It looks like `database`? But maybe also `sync`? Or even `sqs`?
> 
> Can you tell me a little more simplified about your setup (how the jobs are nested)?

Yes, database driver. These are async jobs. These jobs are spawned from a scheduled command, the command iterates over tentants and repeats some business logic in the context of the tentant. Jobs are spawned when certain conditions are met.

**Comment by stayallive** [comment]
Can you show me some code I could add to a new Laravel application that mimics what you are doing? So far I have not been able to figure what is happening or how to reproduce it on our side.

**Comment by pataar** [comment]
/close

Hasn't occurred for a while
