### ISSUE TITLE
`SENTRY_TRACES_SAMPLE_RATE`  has no effect

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-laravel#924]
I noticed the `SENTRY_TRACES_SAMPLE_RATE ` has no effect, because the `couldHavePerformanceTracingEnabled()` method has not been called.[BaseServiceProvider.php](https://github.com/getsentry/sentry-laravel/blob/f987314955bb08d96520c4e02943542540d8f3db/src/Sentry/Laravel/BaseServiceProvider.php#L61-L61)

_Originally posted by @kayw-geek in https://github.com/getsentry/sentry-docs/pull/10644#pullrequestreview-2182454135_

**Comment by stayallive** [comment]
See #892, this is expected. This method has been left as deprecated to not cause a BC.
