### ISSUE TITLE
sentry:publish installs deprecated version of @sentry/browser and variants (v7.4.0)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-laravel#929]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.8.1

### Laravel version

11.16.0

### Steps to reproduce

1. Run `php artisan sentry:publish --dsn=your_dsn`
2. When prompted for, `Do you want to install one of our JavaScript SDKs?", choose `yes`
3. Choose any platform

### Expected result

It should install a reasonably up to date version of sentry-javascript (the current latest version is [8.19.0](https://github.com/getsentry/sentry-javascript/releases/tag/8.19.0)).

(At least, I assume it should, unless there's an intentional reason I may have overlooked.)

### Actual result

It installs 7.4.0, which appears [to be hardcoded](https://github.com/getsentry/sentry-laravel/blob/d8ebad3cc1258c272b471f29e5ec27301dfd5c74/src/Sentry/Laravel/Console/PublishCommand.php#L189) (for any flavor of sentry-javascript, including Vue, Angular, etc.).

**Comment by cleptric** [comment]
The installation step was removed in #930.
For the record, we installed `^7.40.0`, which results into `@sentry/react@7.118.0` being installed at the time of writing.
