### ISSUE TITLE
Causes 500 server errors if using user feedback and having the whole site require Auth middleware

### ISSUE THREAD

**Issue by octoxan** [getsentry/sentry-laravel#93]
I have everything on my site wrapped in this in the web.php routes file...

```
Route::group(['middleware' => 'auth'], function () {

}
```

Adding this...

```
 return response()->view('errors.500', [
		    'sentryID' => $this->sentryID,
	    ], 500);
```

...where the install guide recommends makes the site throw fake 500 server errors whenever a user is logged out. How to fix?

**Comment by dcramer** [comment]
@octoxan can you point out what you're talking about? The guide suggests overriding the error rendering so you can embed the sentryID + user feedback. We dont suggest creating a 500 error when a user is logged out (that I'm aware of).

**Comment by octoxan** [comment]
I'm not trying to create a 500 error when they're logged out.

I have a middleware around all my routes that requires a user to be authenticated, or else it redirects them to /login (the only page without this middleware).

When overriding the error rendering, it actually just shows this error page for every single screen except /login when not logged in.

I thought it was throwing errors, but it appears it was just going to the page.

I fixed it with this...

```
use Auth;

.....

public function render($request, Exception $exception)
    {
    	if (Auth::user()) {
		    return response()->view('errors.500', [
			    'sentryID' => $this->sentryID,
		    ], 500);
	    } else {
		    return parent::render($request, $exception);
	    }
    }

```

**Comment by dcramer** [comment]
I imagine in your case you'd just want to check what the exception is, and if its "Needs Authenticated" you use the default behavior.
