### ISSUE TITLE
Event has no event_id

### ISSUE THREAD

**Issue by vanschelven** [getsentry/sentry-laravel#945]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.8.0

### Laravel version

10.48.22

### Steps to reproduce

Look [here](https://github.com/bugsink/event-samples/blob/main/bugsink/laravel.json) at a generated event (as per the getting-started)

This even contains no `event_id`. However, as per [the docs](https://develop.sentry.dev/sdk/event-payloads/#required-attributes)

> The following attributes are required for all events.
>
> event_id

### Expected result

I expect the official SDK to follow the spec 😄 

### Actual result

It doesn't

**Comment by stayallive** [comment]
Please share a bit more how you obtained this JSON exactly. 

I can assure you we do set a proper event ID 😉

**Comment by vanschelven** [comment]
I just followed [this guide](https://docs.sentry.io/platforms/php/guides/laravel/) which ends with

> php artisan sentry:test


> set a proper event ID, otherwise we would have larger issues [..] It is set on the envelope header though

Indeed, I noticed that; should have mentioned it.

> it is not needed to repeat it in the event item.

Not needed by the Sentry implementation, but needed according to the spec.

Now, whether this is an actual issue depends on whether "sticking to the spec" is a requirement for you 😄 

(Alternatively, we could complain with "team spec")

**Comment by cleptric** [comment]
The SDK exclusively emits events as envelopes, whereas the `event_id` is part of the envelope header. The spec you mentioned is for the store endpoint, something the SDK does no longer use.
As the events are being ingested fine into Sentry, I do not believe there is an issue in the SDK, hence closing.

**Comment by vanschelven** [comment]
Quoting from the spec (first lines)

> Home -> SDK Development -> Event Payloads
> 
> Event Payloads
>
> Events are the fundamental data that clients, often through the use of an SDK, send to the Sentry server.
> 
> Events are packed into envelopes and are sent to the /api/{PROJECT_ID}/envelope/ API endpoint.

I see no indication this is limited to the store endpoint

Anyways, I'll stop fighting windmills I guess
