### ISSUE TITLE
HTTP/2 stream 1 was not closed cleanly

### ISSUE THREAD

**Issue by aagjalpankaj** [getsentry/sentry-laravel#947]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

2.13

### Laravel version

9.52

### Steps to reproduce

I have configured sentry properly but getting below error when I run `php artisan sentry:test`
![Image](https://github.com/user-attachments/assets/31de2aba-b3d7-4b62-a165-0f60e8eaac4e)

### Expected result

test sentry issue in sentry dashboard

### Actual result

There was an error sending the event.
SDK: Failed to send the event to Sentry. Reason: "HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1) for "https://o4504281886162944.ingest.us.sentry.io/api/4508098980020224/store/".".
Please check the error message from the SDK above for further hints about what went wrong.

**Comment by cleptric** [comment]
The SDK version you are using is no longer maintained. Please upgrade to the latest major version, which is [4.9.0](https://github.com/getsentry/sentry-laravel/releases/tag/4.9.0). Should be a straight forward upgrade, see the changelog for [3.x](https://github.com/getsentry/sentry-laravel/blob/3.x/CHANGELOG.md#300) and [4.x](https://github.com/getsentry/sentry-laravel/blob/master/CHANGELOG.md#400).

**Comment by aagjalpankaj** [comment]
Wow! Working after upgrading to v4.9
![Image](https://github.com/user-attachments/assets/11bd95c3-9f6d-44f9-aa7d-ee656a7e9f2b)

Thanks for quick reply :)
